### ISSUE TITLE
Cannot build due to "group id '1519764623' is too big ( > 2097151 ) -> [Help 1]"

### ISSUE THREAD

**Issue by alexec** [naver/pinpoint#1012]
Pinpoint looks really interesting, but I cannot evaluate it due to build failure.

I get the following error when trying to build:
~~~
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single (create-distribution) on project pinpoint-agent: Execution create-distribution of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single failed: group id '1519764623' is too big ( > 2097151 ) -> [Help 1]
~~~

I'm using Maven:
~~~
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/Cellar/maven32/3.2.5/libexec
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
~~~

Debug output:
~~~
[DEBUG] Adding 1 dependency artifacts.
[DEBUG] Adding dependency artifact com.navercorp.pinpoint:pinpoint-plugins:zip:1.5.0-SNAPSHOT.
[DEBUG] Unpacking artifact contents for: com.navercorp.pinpoint:pinpoint-plugins:zip:1.5.0-SNAPSHOT:runtime to: plugin/
[DEBUG] includes:
**/*

[DEBUG] excludes:
none

[DEBUG] Adding archived file-set in: /Users/alex.collins/.m2/repository/com/navercorp/pinpoint/pinpoint-plugins/1.5.0-SNAPSHOT/pinpoint-plugins-1.5.0-SNAPSHOT.zip to archive location: plugin/
[INFO] Building tar: /Users/alex.collins/pinpoint/agent/target/pinpoint-agent-1.5.0-SNAPSHOT.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] pinpoint-agent-distribution ........................ FAILURE [  5.592 s]
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-integration-test-java8 .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.750 s
[INFO] Finished at: 2015-09-26T18:10:18+01:00
[INFO] Final Memory: 25M/81M
[INFO] ------------------------------------------------------------------------Cleaning up unclosed ZipFile for archive /Users/alex.collins/.m2/repository/com/navercorp/pinpoint/pinpoint-plugins/1.5.0-SNAPSHOT/pinpoint-plugins-1.5.0-SNAPSHOT.zip

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single (create-distribution) on project pinpoint-agent: Execution create-distribution of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single failed: group id '1519764623' is too big ( > 2097151 ) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single (create-distribution) on project pinpoint-agent: Execution create-distribution of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single failed: group id '1519764623' is too big ( > 2097151 )
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution create-distribution of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.3:single failed: group id '1519764623' is too big ( > 2097151 )
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: group id '1519764623' is too big ( > 2097151 )
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:623)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:609)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:286)
	at org.codehaus.plexus.archiver.tar.TarArchiver.tarFile(TarArchiver.java:329)
	at org.codehaus.plexus.archiver.tar.TarArchiver.execute(TarArchiver.java:188)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:944)
	at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:436)
	at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
	at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
~~~

**Comment by lioolli** [comment]
Sorry for late answer. It was holiday in Korea till yesterday.

I found this page: https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#tarFileModes
Would you please try adding <tarLongFileMode>posix</tarLongFileMode> to maven assembly plugin configuration in agent/pom.xml?

**Comment by nstopkimsk** [comment]
@alexec Have you solved your problems?

**Comment by minsoo-jun** [comment]
위에 분과 같은 에러 말씀대로 POM.xml를 수정 해서 하니깐 잘되네요
`vi agent/pom.xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <descriptors>
                        <descriptor>src/assembly/distribution.xml</descriptor>
                    </descriptors>
                    <tarLongFileMode>posix</tarLongFileMode>
                    <outputDirectory>${project.build.directory}</outputDirectory>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>create-distribution</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin> 
`
추가 부분 <tarLongFileMode>posix</tarLongFileMode>

**Comment by wnds** [comment]
This should be merged as a PR. Issue still persists in master branch and is fixed by adding posix mode

**Comment by tangximing** [comment]
The error also appears on branch 1.6.x

**Comment by butterflylove** [comment]
在agent模块的pom文件里加
<tarLongFileMode>posix</tarLongFileMode>
