### ISSUE TITLE
quickstart/bin/start-hbase.sh hbase 실행 오류

### ISSUE THREAD

**Issue by myjulyyi** [naver/pinpoint#103]
hbase 실행에서 오류가 발생하고 있습니다.
아래는 로그파일입니다.

확인부탁드립니다. 감사합니다.

<code>
2015. 01. 14. (수) 14:19:53 KST Starting master on conv
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 46565
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 46565
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
2015-01-14 14:19:53,718 INFO org.apache.hadoop.hbase.util.VersionInfo: HBase 0.94.25
2015-01-14 14:19:53,718 INFO org.apache.hadoop.hbase.util.VersionInfo: Subversion git://penates.apache.org/home/jenkins/jenkins-slave/workspace/HBase-0.94.25 -r 7aad0ed8de3dbca78da77fd6c85a1e940cf59ed8
2015-01-14 14:19:53,718 INFO org.apache.hadoop.hbase.util.VersionInfo: Compiled by jenkins on Sat Nov  8 16:02:36 UTC 2014
2015-01-14 14:19:54,121 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
2015-01-14 14:19:54,121 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:host.name=<NA>
2015-01-14 14:19:54,121 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.version=1.7.0_65
2015-01-14 14:19:54,121 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.vendor=Oracle Corporation
2015-01-14 14:19:54,121 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.home=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.65.x86_64/jre
2015-01-14 14:19:54,121 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.class.path=/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../conf:/usr/lib/jvm/java-1.7.0-openjdk.x86_64/lib/tools.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/..:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../hbase-0.94.25-tests.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../hbase-0.94.25.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/activation-1.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/asm-3.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/avro-1.5.3.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/avro-ipc-1.5.3.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-beanutils-1.7.0.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-beanutils-core-1.8.0.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-cli-1.2.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-codec-1.4.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-collections-3.2.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-configuration-1.6.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-digester-1.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-el-1.0.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-httpclient-3.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-io-2.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-lang-2.5.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-logging-1.1.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-math-2.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/commons-net-1.4.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/core-3.1.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/guava-11.0.2.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/hadoop-core-1.0.4.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/hamcrest-core-1.3.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/high-scale-lib-1.1.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/httpclient-4.1.2.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/httpcore-4.1.3.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jackson-core-asl-1.8.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jackson-jaxrs-1.8.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jackson-mapper-asl-1.8.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jackson-xc-1.8.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jamon-runtime-2.3.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jasper-compiler-5.5.23.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jasper-runtime-5.5.23.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jaxb-api-2.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jaxb-impl-2.2.3-1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jersey-core-1.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jersey-json-1.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jersey-server-1.8.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jettison-1.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jetty-6.1.26.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jetty-util-6.1.26.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jruby-complete-1.6.5.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jsp-2.1-6.1.14.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jsp-api-2.1-6.1.14.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/jsr305-1.3.9.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/junit-4.11.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/libthrift-0.8.0.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/log4j-1.2.16.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/metrics-core-2.1.2.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/netty-3.2.4.Final.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/protobuf-java-2.4.0a.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/servlet-api-2.5-6.1.14.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/slf4j-api-1.4.3.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/slf4j-log4j12-1.4.3.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/snappy-java-1.0.3.2.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/stax-api-1.0.1.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/velocity-1.7.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/xmlenc-0.52.jar:/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/zookeeper-3.4.5.jar:
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.library.path=/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../lib/native/Linux-amd64-64
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.io.tmpdir=/tmp
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:java.compiler=<NA>
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:os.name=Linux
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:os.arch=amd64
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:os.version=2.6.32-504.el6.x86_64
2015-01-14 14:19:54,122 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.name=root
2015-01-14 14:19:54,123 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.home=/root
2015-01-14 14:19:54,123 INFO org.apache.zookeeper.server.ZooKeeperServer: Server environment:user.dir=/root/pinpoint/quickstart/hbase/hbase-0.94.25/bin
2015-01-14 14:19:54,148 INFO org.apache.zookeeper.server.ZooKeeperServer: Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../../../data/zookeeper/zookeeper_0/version-2 snapdir /root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../../../data/zookeeper/zookeeper_0/version-2
2015-01-14 14:19:54,191 INFO org.apache.zookeeper.server.NIOServerCnxnFactory: binding to port 0.0.0.0/0.0.0.0:2181
2015-01-14 14:19:54,200 INFO org.apache.zookeeper.server.persistence.FileTxnSnapLog: Snapshotting: 0x0 to /root/pinpoint/quickstart/hbase/hbase-0.94.25/bin/../../../data/zookeeper/zookeeper_0/version-2/snapshot.0
2015-01-14 14:19:54,315 INFO org.apache.zookeeper.server.NIOServerCnxnFactory: Accepted socket connection from /127.0.0.1:60445
2015-01-14 14:19:54,322 INFO org.apache.zookeeper.server.NIOServerCnxn: Processing stat command from /127.0.0.1:60445
2015-01-14 14:19:54,326 INFO org.apache.zookeeper.server.NIOServerCnxn: Stat command output
2015-01-14 14:19:54,327 INFO org.apache.zookeeper.server.NIOServerCnxn: Closed socket connection for client /127.0.0.1:60445 (no session established for client)
2015-01-14 14:19:54,327 INFO org.apache.hadoop.hbase.zookeeper.MiniZooKeeperCluster: Started MiniZK Cluster and connect 1 ZK server on client port: 2181
2015-01-14 14:19:54,433 DEBUG org.apache.hadoop.hbase.master.HMaster: Set serverside HConnection retries=140
2015-01-14 14:19:54,596 ERROR org.apache.hadoop.hbase.master.HMasterCommandLine: Failed to start master
java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMasterconv: 이름 혹은 서비스를 알 수 없습니다
	at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:137)
	at org.apache.hadoop.hbase.LocalHBaseCluster.addMaster(LocalHBaseCluster.java:199)
	at org.apache.hadoop.hbase.LocalHBaseCluster.<init>(LocalHBaseCluster.java:149)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:146)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:104)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:76)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2129)
Caused by: java.net.UnknownHostException: conv: conv: 이름 혹은 서비스를 알 수 없습니다
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at org.apache.hadoop.net.DNS.getDefaultHost(DNS.java:185)
	at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:293)
	at org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster.<init>(HMasterCommandLine.java:221)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:134)
	... 7 more
Caused by: java.net.UnknownHostException: conv: 이름 혹은 서비스를 알 수 없습니다
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	... 15 more
<code>

**Comment by Xylus** [comment]
안녕하세요,
해당 에러는 HBase에서 conv란 호스트로 접속을 시도하는데 해당 호스트에 대한 DNS resolution이 되지 않아 발생한 것 같습니다.

/etc/hosts에 conv에 대한 ip 정보를 추가하여 재실행 부탁드립니다.
