### ISSUE TITLE
Throwing out of Memory Exception when deploying Collector war file in Tomcat

### ISSUE THREAD

**Issue by Janardhan-Babu** [naver/pinpoint#1062]
Getting out of memory exception when deploying collector war file, this i am only observing with 64 bit JDK. Does Collector run  only on 32 bit JDK? 

Catalina.out logs 

INFO: Deploying web application archive /var/lib/tomcat7/webapps/pinpoint-collector-1.1.1.war
10-11 17:50:04 [INFO ](o.s.w.c.ContextLoader              :285) Root WebApplicationContext: initialization started
10-11 17:50:04 [INFO ](o.s.w.c.s.XmlWebApplicationContext :510) Refreshing Root WebApplicationContext: startup date [Sun Oct 11 17:50:04 IST 2015]; root of context hierarchy
10-11 17:50:04 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-collector.xml]
10-11 17:50:05 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-hbase.xml]
10-11 17:50:06 [INFO ](o.s.b.f.c.PropertyPlaceholderConfigurer:172) Loading properties file from class path resource [hbase.properties]
10-11 17:50:06 [INFO ](o.s.b.f.c.PropertyPlaceholderConfigurer:172) Loading properties file from class path resource [pinpoint-collector.properties]
10-11 17:50:06 [INFO ](c.n.p.c.h.PooledHTableFactory      :67) create HConnectionThreadPoolExecutor poolSize:128, workerQueueMaxSize:5120
10-11 17:50:07 [WARN ](o.a.h.u.NativeCodeLoader           :62) Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
10-11 17:50:07 [INFO ](o.a.h.h.z.RecoverableZooKeeper     :121) Process identifier=hconnection-0x4e501e84 connecting to ZooKeeper ensemble=localhost:2181
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:zookeeper.version=3.4.5-cdh5.4.0--1, built on 04/21/2015 19:12 GMT
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:host.name=thinkforward-ProLiant-ML110-G3
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.version=1.7.0_80
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.vendor=Oracle Corporation
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.home=/usr/lib/jvm/java-7-oracle/jre
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.class.path=/usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.io.tmpdir=/tmp/tomcat7-tomcat7-tmp
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:java.compiler=<NA>
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:os.name=Linux
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:os.arch=amd64
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:os.version=3.13.0-24-generic
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:user.name=tomcat7
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:user.home=/usr/share/tomcat7
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :100) Client environment:user.dir=/var/lib/tomcat7
10-11 17:50:07 [INFO ](o.a.z.ZooKeeper                    :438) Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x4e501e840x0, quorum=localhost:2181, baseZNode=/hbase
10-11 17:50:07 [INFO ](o.a.z.ClientCnxn                   :975) Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
10-11 17:50:07 [INFO ](o.a.z.ClientCnxn                   :852) Socket connection established to localhost/127.0.0.1:2181, initiating session
10-11 17:50:08 [INFO ](o.a.z.ClientCnxn                   :1235) Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x15056cf41ac0011, negotiated timeout = 40000
10-11 17:50:08 [INFO ](o.s.b.f.c.PropertiesFactoryBean    :172) Loading properties file from class path resource [pinpoint-collector.properties]
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :185) pinpoint-collector.properties read.
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) collector.tcpListenIp=0.0.0.0
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.tcpListenPort=9994
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) collector.udpStatListenIp=0.0.0.0
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatListenPort=9995
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatWorkerThread=16
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatWorkerQueueSize=512
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatSocketReceiveBufferSize=4194304
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) collector.udpSpanListenIp=0.0.0.0
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanListenPort=9996
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanWorkerThread=32
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanWorkerQueueSize=1024
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanSocketReceiveBufferSize=4194304
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :236) cluster.enable=false
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) cluster.zookeeper.address=
10-11 17:50:08 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) cluster.zookeeper.sessiontimeout=-1
10-11 17:50:09 [INFO ](o.a.h.h.z.RecoverableZooKeeper     :121) Process identifier=hconnection-0x4fbf3744 connecting to ZooKeeper ensemble=localhost:2181
10-11 17:50:09 [INFO ](o.a.z.ZooKeeper                    :438) Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x4fbf37440x0, quorum=localhost:2181, baseZNode=/hbase
10-11 17:50:09 [INFO ](o.a.z.ClientCnxn                   :975) Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
10-11 17:50:09 [INFO ](o.a.z.ClientCnxn                   :852) Socket connection established to localhost/127.0.0.1:2181, initiating session
10-11 17:50:09 [INFO ](o.a.z.ClientCnxn                   :1235) Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x15056cf41ac0012, negotiated timeout = 40000
10-11 17:50:09 [INFO ](c.n.p.c.d.AutoFlusher              :83) Auto flusher initialized.
10-11 17:50:10 [DEBUG](c.n.p.r.c.PinpointSocketFactory    :191) createBootStrap boss:1, worker:1
10-11 17:50:10 [INFO ](c.n.p.c.c.z.ZookeeperClusterService:81) pinpoint-collector cluster disable.
10-11 17:50:10 [DEBUG](c.n.p.r.s.PinpointServerSocket     :413) sendPing
10-11 17:50:10 [DEBUG](c.n.p.r.s.PinpointServerSocket     :446) newPingTimeout
10-11 17:50:10 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :230) Pinpoint-UDP-Span start.
10-11 17:50:10 [WARN ](c.n.p.c.r.u.BaseUDPReceiver        :211) DatagramSocket.setReceiveBufferSize() error. 4194304!=212992
10-11 17:50:11 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :236) UDP Packet reader:2 started.
10-11 17:50:11 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :132) start ioThread localAddress:0.0.0.0/0.0.0.0, IoThread:Pinpoint-UDP-Span-Io(12-0)
10-11 17:50:11 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :230) Pinpoint-UDP-Stat start.
10-11 17:50:11 [WARN ](c.n.p.c.r.u.BaseUDPReceiver        :211) DatagramSocket.setReceiveBufferSize() error. 4194304!=212992
10-11 17:50:11 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :132) start ioThread localAddress:0.0.0.0/0.0.0.0, IoThread:Pinpoint-UDP-Span-Io(12-1)
10-11 17:50:14 [WARN ](o.s.w.c.s.XmlWebApplicationContext :487) Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'udpStatReceiver': Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:553)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1648)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1445)
	at org.apache.catalina.manager.HTMLManagerServlet.upload(HTMLManagerServlet.java:284)
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.navercorp.pinpoint.collector.util.DatagramPacketFactory.create(DatagramPacketFactory.java:30)
	at com.navercorp.pinpoint.collector.util.DatagramPacketFactory.create(DatagramPacketFactory.java:24)
	at com.navercorp.pinpoint.collector.util.ObjectPool.fill(ObjectPool.java:42)
	at com.navercorp.pinpoint.collector.util.ObjectPool.<init>(ObjectPool.java:37)
	at com.navercorp.pinpoint.collector.receiver.udp.AbstractUDPReceiver.afterPropertiesSet(AbstractUDPReceiver.java:121)
	at com.navercorp.pinpoint.collector.receiver.udp.AbstractUDPReceiver.start(AbstractUDPReceiver.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
10-11 17:50:15 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :251) Pinpoint-UDP-Span shutdown.
10-11 17:50:15 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :164) stop ioThread localAddress:0.0.0.0/0.0.0.0:9996, IoThread:Pinpoint-UDP-Span-Io(12-0)
10-11 17:50:15 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :164) stop ioThread localAddress:0.0.0.0/0.0.0.0:9996, IoThread:Pinpoint-UDP-Span-Io(12-1)
10-11 17:50:15 [INFO ](c.n.p.c.r.t.TCPReceiver            :288) Pinpoint-TCP-Server stop
10-11 17:50:15 [INFO ](c.n.p.r.s.PinpointServerSocket     :480) sendServerClosedPacket start
10-11 17:50:15 [INFO ](c.n.p.r.s.PinpointServerSocket     :495) sendServerClosedPacket end
10-11 17:50:15 [INFO ](c.n.p.c.c.z.ZookeeperClusterService:129) pinpoint-collector cluster disable.
10-11 17:50:15 [INFO ](c.n.p.c.d.AutoFlusher              :87) Shutdown auto flusher.
10-11 17:50:15 [INFO ](o.a.h.h.c.ConnectionManager$HConnectionImplementation:1772) Closing zookeeper sessionid=0x15056cf41ac0012
10-11 17:50:15 [INFO ](o.a.z.ZooKeeper                    :684) Session: 0x15056cf41ac0012 closed
10-11 17:50:15 [INFO ](o.a.z.ClientCnxn                   :512) EventThread shut down
10-11 17:50:15 [INFO ](c.n.p.c.h.HbaseTemplate2           :84) HbaseTemplate2.destroy()
10-11 17:50:15 [INFO ](c.n.p.c.h.PooledHTableFactory      :98) PooledHTableFactory.destroy()
10-11 17:50:15 [INFO ](o.a.h.h.c.ConnectionManager$HConnectionImplementation:1772) Closing zookeeper sessionid=0x15056cf41ac0011
10-11 17:50:15 [INFO ](o.a.z.ZooKeeper                    :684) Session: 0x15056cf41ac0011 closed
10-11 17:50:15 [ERROR](o.s.w.c.ContextLoader              :331) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'udpStatReceiver': Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:553)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1648)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1445)
	at org.apache.catalina.manager.HTMLManagerServlet.upload(HTMLManagerServlet.java:284)
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.navercorp.pinpoint.collector.util.DatagramPacketFactory.create(DatagramPacketFactory.java:30)
	at com.navercorp.pinpoint.collector.util.DatagramPacketFactory.create(DatagramPacketFactory.java:24)
	at com.navercorp.pinpoint.collector.util.ObjectPool.fill(ObjectPool.java:42)
	at com.navercorp.pinpoint.collector.util.ObjectPool.<init>(ObjectPool.java:37)
	at com.navercorp.pinpoint.collector.receiver.udp.AbstractUDPReceiver.afterPropertiesSet(AbstractUDPReceiver.java:121)
	at com.navercorp.pinpoint.collector.receiver.udp.AbstractUDPReceiver.start(AbstractUDPReceiver.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
10-11 17:50:15 [INFO ](o.a.z.ClientCnxn                   :512) EventThread shut down
Oct 11, 2015 5:50:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Oct 11, 2015 5:50:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/pinpoint-collector-1.1.1] startup failed due to previous errors
Oct 11, 2015 5:50:15 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/pinpoint-collector-1.1.1] appears to have started a thread named [Pinpoint-SocketFactory-Timer(3-0)] but has failed to stop it. This is very likely to create a memory leak.
Oct 11, 2015 5:50:15 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/pinpoint-collector-1.1.1] appears to have started a thread named [Pinpoint-Client-Boss(4-0)] but has failed to stop it. This is very likely to create a memory leak.
Oct 11, 2015 5:50:15 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/pinpoint-collector-1.1.1] appears to have started a thread named [Pinpoint-Client-Worker(5-0)] but has failed to stop it. This is very likely to create a memory leak.

**Comment by koo-taejin** [comment]
You can choose two ways.

1. increase jvm heap size 
I recommend more than 1gb as heap space. if  you have enough physical memory.

2. change your settings
Changing the pinpoint-collector.properties preferences below may have an effect on memory consumption.
```
collector.udpStatWorkerQueueSize= // you're setting 512
collector.udpSpanWorkerQueueSize=  // you're setting 1024
```
Please reference  quickstart's pinpoint-collector.properties .
It enables you to work in low-specification.

thanks

**Comment by Janardhan-Babu** [comment]
Just wanted to make a note.With 32 bit JDK, the default configs present in pinpoint-collector.properties works fine.But when i use 64bit JDK,need to reduce the above mentioned values to get it running.

Thanks for the help.
