### ISSUE TITLE
hbase shutdown 문의

### ISSUE THREAD

**Issue by imjaebong** [naver/pinpoint#1161]
안녕하세요.
hbase를 동작시켜 놓으면 매일 21시쯤에 Shutdown 되는 현상이 발생하고 있습니다.
동작시킬떄 따로 설정해야 하는 부분이 있나요?
2015-11-05 21:00:16,755 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
2015-11-05 21:00:16,843 ERROR [RS_CLOSE_REGION-localhost:44312-0] regionserver.HRegion: Memstore size is 240
2015-11-05 21:00:16,849 ERROR [RS_CLOSE_REGION-localhost:44312-0] regionserver.HRegion: Memstore size is 561744
2015-11-05 21:00:16,887 ERROR [RS_CLOSE_REGION-localhost:44312-2] regionserver.HRegion: Memstore size is 232
2015-11-05 21:00:16,975 ERROR [RS_CLOSE_REGION-localhost:44312-0] regionserver.HRegion: Memstore size is 6448
2015-11-05 21:00:16,983 ERROR [RS_CLOSE_REGION-localhost:44312-0] regionserver.HRegion: Memstore size is 5152
2015-11-05 21:00:17,018 ERROR [RS_CLOSE_REGION-localhost:44312-2] regionserver.HRegion: Memstore size is 561744
2015-11-05 21:00:17,078 ERROR [RS_CLOSE_REGION-localhost:44312-1] regionserver.HRegion: Memstore size is 561744
2015-11-05 21:00:17,769 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
2015-11-05 21:00:19,772 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
2015-11-05 21:00:23,776 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
2015-11-05 21:00:25,905 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
2015-11-05 21:00:26,908 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
2015-11-05 21:00:28,909 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
2015-11-05 21:00:31,777 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
2015-11-05 21:00:31,777 ERROR [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: ZooKeeper getData failed after 4 attempts
2015-11-05 21:00:31,777 WARN  [M:0;localhost:48368] zookeeper.ZKUtil: master:48368-0x150d50deee70000, quorum=localhost:2181, baseZNode=/hbase Unable to get data of znode /hbase/master
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:359)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:686)
        at org.apache.hadoop.hbase.zookeeper.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:148)
        at org.apache.hadoop.hbase.master.ActiveMasterManager.stop(ActiveMasterManager.java:267)
        at org.apache.hadoop.hbase.master.HMaster.stopServiceThreads(HMaster.java:1030)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:999)
        at org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster.run(HMasterCommandLine.java:281)
        at java.lang.Thread.run(Thread.java:745)
2015-11-05 21:00:31,778 ERROR [M:0;localhost:48368] zookeeper.ZooKeeperWatcher: master:48368-0x150d50deee70000, quorum=localhost:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:359)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:686)
        at org.apache.hadoop.hbase.zookeeper.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:148)
        at org.apache.hadoop.hbase.master.ActiveMasterManager.stop(ActiveMasterManager.java:267)
        at org.apache.hadoop.hbase.master.HMaster.stopServiceThreads(HMaster.java:1030)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:999)
        at org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster.run(HMasterCommandLine.java:281)
        at java.lang.Thread.run(Thread.java:745)
2015-11-05 21:00:31,778 ERROR [M:0;localhost:48368] master.ActiveMasterManager: master:48368-0x150d50deee70000, quorum=localhost:2181, baseZNode=/hbase Error deleting our own master address node
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/master
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:359)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.getData(ZKUtil.java:686)
        at org.apache.hadoop.hbase.zookeeper.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:148)
        at org.apache.hadoop.hbase.master.ActiveMasterManager.stop(ActiveMasterManager.java:267)
        at org.apache.hadoop.hbase.master.HMaster.stopServiceThreads(HMaster.java:1030)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:999)
        at org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster.run(HMasterCommandLine.java:281)
        at java.lang.Thread.run(Thread.java:745)
2015-11-05 21:00:31,780 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,48368,1446683472578
2015-11-05 21:00:32,782 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,48368,1446683472578
2015-11-05 21:00:32,910 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
2015-11-05 21:00:34,784 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,48368,1446683472578
2015-11-05 21:00:38,786 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,48368,1446683472578
2015-11-05 21:00:40,912 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
2015-11-05 21:00:40,912 ERROR [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: ZooKeeper getChildren failed after 4 attempts
2015-11-05 21:00:40,912 WARN  [RS:0;localhost:44312] zookeeper.ZKUtil: regionserver:44312-0x150d50deee70001, quorum=localhost:2181, baseZNode=/hbase Unable to list children of znode /hbase/replication/rs/localhost,44312,1446683473986
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getChildren(RecoverableZooKeeper.java:295)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchForNewChildren(ZKUtil.java:519)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchThem(ZKUtil.java:547)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenBFSAndWatchThem(ZKUtil.java:1527)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursivelyMultiOrSequential(ZKUtil.java:1449)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursively(ZKUtil.java:1331)
        at org.apache.hadoop.hbase.replication.ReplicationQueuesZKImpl.removeAllQueues(ReplicationQueuesZKImpl.java:187)
        at org.apache.hadoop.hbase.replication.regionserver.ReplicationSourceManager.join(ReplicationSourceManager.java:291)
        at org.apache.hadoop.hbase.replication.regionserver.Replication.join(Replication.java:180)
        at org.apache.hadoop.hbase.replication.regionserver.Replication.stopReplicationService(Replication.java:172)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.stopServiceThreads(HRegionServer.java:2035)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:999)
        at java.lang.Thread.run(Thread.java:745)
2015-11-05 21:00:40,912 ERROR [RS:0;localhost:44312] zookeeper.ZooKeeperWatcher: regionserver:44312-0x150d50deee70001, quorum=localhost:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/replication/rs/localhost,44312,1446683473986
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getChildren(RecoverableZooKeeper.java:295)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchForNewChildren(ZKUtil.java:519)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenAndWatchThem(ZKUtil.java:547)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.listChildrenBFSAndWatchThem(ZKUtil.java:1527)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursivelyMultiOrSequential(ZKUtil.java:1449)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNodeRecursively(ZKUtil.java:1331)
        at org.apache.hadoop.hbase.replication.ReplicationQueuesZKImpl.removeAllQueues(ReplicationQueuesZKImpl.java:187)
        at org.apache.hadoop.hbase.replication.regionserver.ReplicationSourceManager.join(ReplicationSourceManager.java:291)
        at org.apache.hadoop.hbase.replication.regionserver.Replication.join(Replication.java:180)
        at org.apache.hadoop.hbase.replication.regionserver.Replication.stopReplicationService(Replication.java:172)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.stopServiceThreads(HRegionServer.java:2035)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:999)
        at java.lang.Thread.run(Thread.java:745)
2015-11-05 21:00:40,915 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,44312,1446683473986
2015-11-05 21:00:41,917 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,44312,1446683473986
2015-11-05 21:00:43,920 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,44312,1446683473986
2015-11-05 21:00:46,788 WARN  [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,48368,1446683472578
2015-11-05 21:00:46,789 ERROR [M:0;localhost:48368] zookeeper.RecoverableZooKeeper: ZooKeeper delete failed after 4 attempts
2015-11-05 21:00:46,789 WARN  [M:0;localhost:48368] regionserver.HRegionServer: Failed deleting my ephemeral node
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,48368,1446683472578
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.delete(RecoverableZooKeeper.java:178)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1287)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1276)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.deleteMyEphemeralNode(HRegionServer.java:1324)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1007)
        at org.apache.hadoop.hbase.master.HMasterCommandLine$LocalHMaster.run(HMasterCommandLine.java:281)
        at java.lang.Thread.run(Thread.java:745)
2015-11-05 21:00:47,921 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,44312,1446683473986
2015-11-05 21:00:55,923 WARN  [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:2181, exception=org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,44312,1446683473986
2015-11-05 21:00:55,923 ERROR [RS:0;localhost:44312] zookeeper.RecoverableZooKeeper: ZooKeeper delete failed after 4 attempts
2015-11-05 21:00:55,923 WARN  [RS:0;localhost:44312] regionserver.HRegionServer: Failed deleting my ephemeral node
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /hbase/rs/localhost,44312,1446683473986
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.delete(RecoverableZooKeeper.java:178)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1287)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.deleteNode(ZKUtil.java:1276)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.deleteMyEphemeralNode(HRegionServer.java:1324)
        at org.apache.hadoop.hbase.regionserver.HRegionServer.run(HRegionServer.java:1007)
        at java.lang.Thread.run(Thread.java:745)
Fri Nov  6 08:57:41 KST 2015 Starting master on localhost.localdomain
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15064
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 8192
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
2015-11-06 08:57:42,951 ERROR [main] master.HMasterCommandLine: Master exiting
java.io.IOException: Unable to create data directory /home/msswas/../data/zookeeper/zookeeper_0/version-2
        at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:85)
        at org.apache.zookeeper.server.ZooKeeperServer.<init>(ZooKeeperServer.java:213)
        at org.apache.hadoop.hbase.zookeeper.MiniZooKeeperCluster.startup(MiniZooKeeperCluster.java:160)
        at org.apache.hadoop.hbase.zookeeper.MiniZooKeeperCluster.startup(MiniZooKeeperCluster.java:129)
        at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:178)
        at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:139)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
        at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2016)

**Comment by koo-taejin** [comment]
저희가 제공하는 기능은 아닙니다. 
내부적으로 원인을 찾아보셔야 할 것 같네요.
