### ISSUE TITLE
Exception occurred from interceptor java.lang.NullPointerException

### ISSUE THREAD

**Issue by dawidmalina** [naver/pinpoint#1258]
```
2015-11-25 20:41:58 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:557) DefaultPinpointClientHandler@4f18837a channelClosed() started.
2015-11-25 20:41:58 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@4f18837a stateTo() completed. Socket state change success(updateWanted:CLOSED_BY_CLIENT ,before:BEING_CLOSE_BY_CLIENT ,current:CLOSED_BY_CLIENT).
2015-11-25 20:41:58 [INFO ](c.n.p.r.c.PinpointClientHandshaker :239) PinpointClientHandshaker@2d02469c handshakeAbort method started.
2015-11-25 20:41:58 [INFO ](c.n.p.r.c.PinpointClientHandshaker :243) PinpointClientHandshaker@2d02469c handshakeStart method failed. beforeState:2
2015-11-25 20:41:58 [WARN ](c.n.p.b.i.InterceptorInvokerHelper :411) Exception occurred from interceptor
java.lang.NullPointerException
	at com.navercorp.pinpoint.bootstrap.interceptor.registry.InterceptorRegistry.getInterceptor(InterceptorRegistry.java:52)
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:106)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:440)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.info(Logger.java:600)
	at com.oberthur.ldz.bsh.BshServer.destroy(BshServer.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:314)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:153)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:239)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:907)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:914)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:884)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)
```

**Comment by Xylus** [comment]
Hi dawidmalina,
Could you tell us how and when `BshServer.destroy` is called?
It looks like Spring is calling it when its context is being closed (perhaps through `@PreDestory`?)

NPE from `InterceptorRegistry.getInterceptor` would be possible if the agent tries to trace something (in this case a `LoggingEvent` instantiation) **after** the application is shutdown and the InterceptorRegistry is unbinded. And this shouldn't happen normally.

**Comment by dawidmalina** [comment]
@Xylus yes it is destroyed through `@PreDestory` with code like this:
```
           try {
                interpreter.eval(destroyScript);
            } catch (EvalError e) {
                log.error("Error evaluating destroy script: " + destroyScript, e);
            }
        }
        interpreter = null;
```

**Comment by Xylus** [comment]
@dawidmalina 
This one should be fixed with 3ebec09, please see #1298

**Comment by dawidmalina** [comment]
It is just docker stop on container.

**Comment by dawidmalina** [comment]
@Xylus I don't see this errors with 1.5.2-SNAPSHOT build
