### ISSUE TITLE
Jetty8 Intreceptor NPE fix 

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#1351]
- incorrected null check

**Comment by dawidmalina** [comment]
Do you think it can be same issue:
```
2015-12-14 16:47:05 [WARN ](c.n.p.p.j.i.Jetty8ServerHandleInterceptor:406) before. Caused:null
java.lang.NullPointerException
        at com.navercorp.pinpoint.plugin.jetty.interceptor.AbstractServerHandleInterceptor.createTrace(AbstractServerHandleInterceptor.java:86)
        at com.navercorp.pinpoint.plugin.jetty.interceptor.AbstractServerHandleInterceptor.before(AbstractServerHandleInterceptor.java:64)
        at org.eclipse.jetty.server.Server.handle(Server.java)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
```

I'm using jetty as a dependency for cxf
```
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http-jetty</artifactId>
            <version>3.0.5</version>
        </dependency>
```

**Comment by koo-taejin** [comment]
Yes. same issue. sorry for the bug.

**Comment by dawidmalina** [comment]
It's ok
