### ISSUE TITLE
윈도우7 환경에서 quickstart/bin/start-web.cmd 실행시 오류가 발생합니다.

### ISSUE THREAD

**Issue by panta21** [naver/pinpoint#1380]
quickstart.web.log 내용입니다.

hbase.client.parallel.scan.enable 이 값이 문제가 있는거 같은데 도움부탁드립니다.

16:11:17 INFO (o.s.w.c.ContextLoader              :285) Root WebApplicationContext: initialization started
16:11:17 INFO (o.s.w.c.s.XmlWebApplicationContext :511) Refreshing Root WebApplicationContext: startup date [Mon Dec 28 16:11:17 KST 2015]; root of context hierarchy
16:11:17 INFO (o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-web.xml]
16:11:17 INFO (o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-hbase.xml]
16:11:17 INFO (o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-datasource.xml]
16:11:17 INFO (o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-dao-config.xml]
16:11:17 INFO (o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-cache.xml]
16:11:17 INFO (o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-websocket.xml]
16:11:17 INFO (.s.b.f.s.DefaultListableBeanFactory:822) Overriding bean definition for bean 'spanMapper': replacing [Generic bean: class [com.navercorp.pinpoint.web.mapper.SpanMapper]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [D:\pinpoint\quickstart\web\target\deploy\WEB-INF\classes\com\navercorp\pinpoint\web\mapper\SpanMapper.class]] with [Generic bean: class [com.navercorp.pinpoint.web.mapper.SpanMapper]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [applicationContext-web.xml]]
16:11:18 INFO (b.f.c.PropertyPlaceholderConfigurer:172) Loading properties file from class path resource [hbase.properties]
16:11:18 INFO (b.f.c.PropertyPlaceholderConfigurer:172) Loading properties file from class path resource [jdbc.properties]
16:11:18 WARN (o.s.w.c.s.XmlWebApplicationContext :487) Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'hbaseTemplate' defined in class path resource [applicationContext-hbase.xml]: Could not resolve placeholder 'hbase.client.parallel.scan.enable' in string value "${hbase.client.parallel.scan.enable}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'hbase.client.parallel.scan.enable' in string value "${hbase.client.parallel.scan.enable}"
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:211)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:222)
	at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:265)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:162)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:607)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'hbase.client.parallel.scan.enable' in string value "${hbase.client.parallel.scan.enable}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer$PlaceholderResolvingStringValueResolver.resolveStringValue(PropertyPlaceholderConfigurer.java:258)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:282)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:204)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:141)
	at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:82)
	at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:208)
	... 18 more
16:11:18 ERROR(o.s.w.c.ContextLoader              :331) Context initialization failed

**Comment by Xylus** [comment]
quickstart에 pinpoint.config 옵션 중 하나가 없어서 그런 것 같습니다. 수정해서 commit 하겠습니다.

**Comment by Xylus** [comment]
bug fix merge 되었습니다. 코드 업데이트 받으시고 재실행 부탁드립니다~
