### ISSUE TITLE
Add support for dubbo

### ISSUE THREAD

**Issue by majinkai** [naver/pinpoint#1416]
Reference [dubbo](http://dubbo.io/User+Guide.htm).

**Comment by nstopkimsk** [comment]
@majinkai Have you developed this plugin?   #1395

**Comment by majinkai** [comment]
Yes, i will PR for this plugin.

**Comment by nstopkimsk** [comment]
merged.

**Comment by VectorHo** [comment]
dubbox 有bug @majinkai 

```logs
2016-12-12 23:01:39 [WARN ](c.n.p.p.c.DefaultTrace             :196) [DefaultTrace] Corrupted call stack found.
com.navercorp.pinpoint.exception.PinpointException: not empty call stack.
	at com.navercorp.pinpoint.profiler.context.DefaultTrace.close(DefaultTrace.java:195)
	at com.navercorp.pinpoint.bootstrap.interceptor.SpanSimpleAroundInterceptor.deleteTrace(SpanSimpleAroundInterceptor.java:106)
	at com.navercorp.pinpoint.bootstrap.interceptor.SpanSimpleAroundInterceptor.after(SpanSimpleAroundInterceptor.java:99)
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:44)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:57)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:70)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy4.getLogs(proxy4.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:288)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:242)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at com.alibaba.dubbo.rpc.protocol.rest.DubboHttpServer$RestHandler.handle(DubboHttpServer.java:86)
	at com.alibaba.dubbo.remoting.http.servlet.DispatcherServlet.service(DispatcherServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:261)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:207)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2016-12-12 23:01:39.330  INFO 1 --- [nio-8088-exec-3] c.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Subscribe: consumer://192.168.42.1/com.alibaba.dubbo.monitor.MonitorService?category=providers,configurators,routers&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=1&timestamp=1481554842772, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.352  INFO 1 --- [nio-8088-exec-3] c.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Notify urls for subscribe url consumer://192.168.42.1/com.alibaba.dubbo.monitor.MonitorService?category=providers,configurators,routers&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=1&timestamp=1481554842772, urls: [dubbo://139.129.20.182:20884/com.alibaba.dubbo.monitor.MonitorService?anyhost=true&application=mysql-monitor&dubbo=2.8.4&generic=false&interface=com.alibaba.dubbo.monitor.MonitorService&interval=60000&methods=lookup,collect&owner=bieber&pid=7&revision=2.8.4&side=provider&timestamp=1480669515075, empty://192.168.42.1/com.alibaba.dubbo.monitor.MonitorService?category=configurators&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=1&timestamp=1481554842772, empty://192.168.42.1/com.alibaba.dubbo.monitor.MonitorService?category=routers&dubbo=2.8.4&interface=com.alibaba.dubbo.monitor.MonitorService&pid=1&timestamp=1481554842772], dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.440  INFO 1 --- [nio-8088-exec-3] c.a.d.remoting.transport.AbstractClient  :  [DUBBO] Successed connect to server /139.129.20.182:20884 from NettyClient 192.168.42.1 using dubbo version 2.8.4, channel is NettyChannel [channel=[id: 0x6dbb8b54, /139.129.20.182:47594 => /139.129.20.182:20884]], dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.440  INFO 1 --- [nio-8088-exec-3] c.a.d.remoting.transport.AbstractClient  :  [DUBBO] Start NettyClient /192.168.42.1 connect to the server /139.129.20.182:20884, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39 [DEBUG](.p.p.ClassFileTransformerDispatcher:109) [transform] classLoader:org.springframework.boot.loader.LaunchedURLClassLoader@248e319b className:com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate
2016-12-12 23:01:39 [DEBUG](c.n.p.p.o.AutoBindingObjectFactory :75 ) Create instance by constructor public com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboConsumerInterceptor(com.navercorp.pinpoint.bootstrap.context.TraceContext,com.navercorp.pinpoint.bootstrap.context.MethodDescriptor), with arguments [com.navercorp.pinpoint.profiler.context.DefaultTraceContext@54e1c68b, {className=com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker, methodName=invoke, parameterTypes=[com.alibaba.dubbo.rpc.Invocation], parameterVariableName=[invocation], parameterDescriptor=(com.alibaba.dubbo.rpc.Invocation invocation), apiDescriptor=com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(com.alibaba.dubbo.rpc.Invocation invocation), lineNumber=215, apiId=124, fullName=com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(com.alibaba.dubbo.rpc.Invocation invocation):215, type=0}]
2016-12-12 23:01:39 [DEBUG](c.n.p.r.c.RequestManager           :107) responsePacket arrived packet:ResponsePacket{requestId=261, payloadLength=6}, objectUniqName:DefaultPinpointClientHandler@77c2494c
2016-12-12 23:01:39 [DEBUG](c.n.p.p.s.TcpDataSender            :178) result success
2016-12-12 23:01:39.479  INFO 1 --- [nio-8088-exec-3] c.f.s.service.extension.LoggingFilter    :  [DUBBO] ↓↓↓↓↓↓ HTTP响应部分 ↓↓↓↓↓↓, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.479  INFO 1 --- [nio-8088-exec-4] c.f.s.service.extension.LoggingFilter    :  [DUBBO] ↓↓↓↓↓↓ HTTP响应部分 ↓↓↓↓↓↓, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.479  INFO 1 --- [nio-8088-exec-4] c.f.s.service.extension.LoggingFilter    :  [DUBBO] The HTTP headers are:
Content-Type: application/json;charset=UTF-8
, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.479  INFO 1 --- [nio-8088-exec-3] c.f.s.service.extension.LoggingFilter    :  [DUBBO] The HTTP headers are:
Content-Type: application/json;charset=UTF-8
, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :96 ) BEFORE org.codehaus.jackson.map.ObjectMapper  args:(null, null, null, null, null)
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :150) AFTER org.codehaus.jackson.map.ObjectMapper  args:(null, null, null, null, null)
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :96 ) BEFORE org.codehaus.jackson.map.ObjectMapper  args:(null, null, null)
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :150) AFTER org.codehaus.jackson.map.ObjectMapper  args:(null, null, null)
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :96 ) BEFORE org.codehaus.jackson.map.ObjectMapper  args:()
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :150) AFTER org.codehaus.jackson.map.ObjectMapper  args:()
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :96 ) BEFORE org.codehaus.jackson.map.ObjectMapper  args:(Utf8Generator, Payload)
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :96 ) BEFORE org.codehaus.jackson.map.ObjectMapper  args:(Utf8Generator, Payload)
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryBefore() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.WriteValueAsStringInterceptor
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryBefore() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.WriteValueAsStringInterceptor
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryAfter() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.WriteValueAsStringInterceptor
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryBefore() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.ReadValueInterceptor
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryAfter() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.ReadValueInterceptor
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryAfter() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.WriteValueAsStringInterceptor
2016-12-12 23:01:39 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryBefore() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(JACKSON_OBJECTMAPPER_SCOPE)[depth=1], executionPoint: BOUNDARY. Skip interceptor class com.navercorp.pinpoint.plugin.jackson.interceptor.ReadValueInterceptor
2016-12-12 23:01:39 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :150) AFTER org.codehaus.jackson.map.ObjectMapper  args:(Utf8Generator, Payload)
2016-12-12 23:01:39.513  INFO 1 --- [nio-8088-exec-3] c.f.s.service.extension.LoggingFilter    :  [DUBBO] The contents of response body is:
{"payload":["ab-security","workflow","ab-system"],"request_id":"6abf994a-cd76-4f73-9f35-e87001c60601"}, dubbo version: 2.8.4, current host: 192.168.42.1
2016-12-12 23:01:39.514  INFO 1 --- [nio-8088-exec-3] c.f.s.service.extension.LoggingFilter    :  [DUBBO]

```

**Comment by VectorHo** [comment]
@majinkai dubbox 中扩展了rest协议，能不能帮忙看看这个怎么fix
