### ISSUE TITLE
quickstart error

### ISSUE THREAD

**Issue by liuhaif** [naver/pinpoint#1551]
hbase: 1.0.3. jdk: 1.8.64bit.  windows 10
First, start hbase, is ok. and then start-collector, report error.
## Hbase error:

2016-02-24 16:48:37,274 INFO  [ProcessThread(sid:0 cport:-1):] server.PrepRequestProcessor: Processed session terminatio
n for sessionid: 0x153121239040008
2016-02-24 16:48:37,368 WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: caught end of stream exc
eption
EndOfStreamException: Unable to read additional data from client sessionid 0x153121239040008, likely client has closed s
ocket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)
## collector error:

 Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tcpDispatchHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.collector.handler.RequestResponseHandler com.navercorp.pinpoint.collector.receiver.TcpDispatchHandler.sqlMetaDataHandler; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlMetaDataHandler' defined in class path resource [applicationContext-collector.xml]: Cannot resolve reference to bean 'hbaseSqlMetaDataCompatibility' while setting bean property 'sqlMetaDataDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseSqlMetaDataCompatibility' defined in class path resource [applicationContext-collector.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataCompatibility]: Constructor threw exception; nested exception is org.springframework.data.hadoop.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:759)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.collector.handler.RequestResponseHandler com.navercorp.pinpoint.collector.receiver.TcpDispatchHandler.sqlMetaDataHandler; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlMetaDataHandler' defined in class path resource [applicationContext-collector.xml]: Cannot resolve reference to bean 'hbaseSqlMetaDataCompatibility' while setting bean property 'sqlMetaDataDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseSqlMetaDataCompatibility' defined in class path resource [applicationContext-collector.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataCompatibility]: Constructor threw exception; nested exception is org.springframework.data.hadoop.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
    ... 22 more
```

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlMetaDataHandler' defined in class path resource [applicationContext-collector.xml]: Cannot resolve reference to bean 'hbaseSqlMetaDataCompatibility' while setting bean property 'sqlMetaDataDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseSqlMetaDataCompatibility' defined in class path resource [applicationContext-collector.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataCompatibility]: Constructor threw exception; nested exception is org.springframework.data.hadoop.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1475)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1220)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
    ... 24 more
```

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseSqlMetaDataCompatibility' defined in class path resource [applicationContext-collector.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataCompatibility]: Constructor threw exception; nested exception is org.springframework.data.hadoop.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1137)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1040)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
    ... 37 more
```

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataCompatibility]: Constructor threw exception; nested exception is org.springframework.data.hadoop.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
    ... 46 more
```

Caused by: org.springframework.data.hadoop.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at com.navercorp.pinpoint.common.hbase.HBaseAdminTemplate.tableExists(HBaseAdminTemplate.java:63)
    at com.navercorp.pinpoint.collector.dao.hbase.HbaseSqlMetaDataCompatibility.<init>(HbaseSqlMetaDataCompatibility.java:48)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
    ... 48 more
```

Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Wed Feb 24 16:48:37 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0

```
    at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.throwEnrichedException(RpcRetryingCallerWithReadReplicas.java:270)
    at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:203)
    at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:57)
    at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
    at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:294)
    at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:269)
    at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:141)
    at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:136)
    at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:886)
    at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:601)
    at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:365)
    at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:310)
    at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:320)
    at com.navercorp.pinpoint.common.hbase.HBaseAdminTemplate.tableExists(HBaseAdminTemplate.java:61)
    ... 54 more
```

Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=77803: row 'SqlMetaData_Ver2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=DESKTOP-083E90G,64757,1456297114822, seqNum=0
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:64)
        ... 3 more
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupConnection(RpcClientImpl.java:404)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:710)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:881)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:850)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1174)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:216)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:300)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:31751)
        at org.apache.hadoop.hbase.client.ScannerCallable.openScanner(ScannerCallable.java:337)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:192)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:62)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:316)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:290)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
        ... 4 more

二月 24, 2016 4:48:37 下午 org.apache.catalina.core.StandardContext startInternal
严重: Error listenerStart
二月 24, 2016 4:48:37 下午 org.apache.catalina.core.StandardContext startInternal
严重: Context [] startup failed due to previous errors
二月 24, 2016 4:48:37 下午 org.apache.catalina.core.ApplicationContext log
信息: Closing Spring root WebApplicationContext
二月 24, 2016 4:48:37 下午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-bio-28082"]

**Comment by guzy** [comment]
你在hbase根目录下执行`bin/hbase shell` ，通过list命令能看到需要的table吗？

**Comment by liuhaif** [comment]
能看到。

 

hbase(main):001:0> list

TABLE                                                                                                                   

AgentEvent                                                                                                              

AgentInfo                                                                                                               

AgentLifeCycle                                                                                                          

AgentStat                                                                                                               

ApiMetaData                                                                                                             

ApplicationIndex                                                                                                        

ApplicationMapStatisticsCallee                                                                                          

ApplicationMapStatisticsCallee_Ver2                                                                                     

ApplicationMapStatisticsCaller                                                                                          

ApplicationMapStatisticsCaller_Ver2                                                                                     

ApplicationMapStatisticsSelf                                                                                            

ApplicationMapStatisticsSelf_Ver2                                                                                       

ApplicationStatistics                                                                                                   

ApplicationTraceIndex                                                                                                   

HostApplicationMap                                                                                                      

HostApplicationMap_Ver2                                                                                                 

SqlMetaData                                                                                                             

SqlMetaData_Ver2                                                                                                        

StringMetaData                                                                                                          

Traces                                                                                                                  

20 row(s) in 1.1770 seconds

 

=> ["AgentEvent", "AgentInfo", "AgentLifeCycle", "AgentStat", "ApiMetaData", "ApplicationIndex", "ApplicationMapStatisticsCallee", "ApplicationMapStatisticsCallee_Ver2", "ApplicationMapStatisticsCaller", "ApplicationMapStatisticsCaller_Ver2", "ApplicationMapStatisticsSelf", "ApplicationMapStatisticsSelf_Ver2", "ApplicationStatistics", "ApplicationTraceIndex", "HostApplicationMap", "HostApplicationMap_Ver2", "SqlMetaData", "SqlMetaData_Ver2", "StringMetaData", "Traces"]

hbase(main):002:0>

 

发件人: gzy [mailto:notifications@github.com] 
发送时间: 2016年2月24日 20:58
收件人: naver/pinpoint <pinpoint@noreply.github.com>
抄送: liuhaif <liuhaif@gmail.com>
主题: Re: [pinpoint] quickstart error (#1551)

 

你在hbase根目录下执行bin/hbase shell ，通过list命令能看到需要的table吗？

**Comment by Xylus** [comment]
Not entirely sure but one thing that you could try is check if the host *DESKTOP-083E90G,64757* can be resolved (from where the collector is running).
Hbase shell working correctly seems weird but it might be worth a try~
