### ISSUE TITLE
when i run the  test case in the IDEA , will throw exceptions as follows

### ISSUE THREAD

**Issue by vwyuheng** [naver/pinpoint#1595]
java.lang.Exception: No tests found matching Method execute(com.navercorp.pinpoint.plugin.google.httpclient.HttpRequestIT) from org.junit.internal.requests.ClassRequest@24367e26

	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by Xylus** [comment]
hi vwyuheng,
Are you running the integration test on a method directly?
If so, our test runner doesn't support running method level tests. Try running the test on class level.
A fix for this is currently being worked on, so please hang tight :)

**Comment by vwyuheng** [comment]
ok,good
