### ISSUE TITLE
how to run integration test?

### ISSUE THREAD

**Issue by hamlet-lee** [naver/pinpoint#1605]
`mvn test` on pinpoint root directory, it seems not running tests in "agent/src/test"

when I run `mvn test`  in "pinpoint/agent" directory, it says
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

when I tried to run a single TestSuite in "pinpoint/agent" directory,
by
```
mvn -Dtest=HttpURLConnectionIT test
```
 it says
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.navercorp.pinpoint.plugin.jdk.http.HttpURLConnectionIT
Working directory: d:\code\pinpoint\agent
Command: [d:\Java\jdk1.6_45\bin\java.exe, -cp, , -javaagent:d:\code\pinpoint\age
nt\target\pinpoint-agent-1.5.2-SNAPSHOT\pinpoint-bootstrap-1.5.2-SNAPSHOT.jar=bo
otClass=com.navercorp.pinpoint.test.PluginTestAgent, -Dpinpoint.agentId=build.te
st.0, -Dpinpoint.applicationName=test, -Dpinpoint.test.id=:child:6, -Dfile.encod
ing=UTF-8, com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest, com.nave
rcorp.pinpoint.plugin.jdk.http.HttpURLConnectionIT, -child=d:\code\pinpoint\agen
t\target\test-classes]
java.lang.NoClassDefFoundError: com/navercorp/pinpoint/test/plugin/ForkedPinpoin
tPluginTest
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.test.plugin.
ForkedPinpointPluginTest
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: com.navercorp.pinpoint.test.plugin.ForkedPinpoint
PluginTest.  Program will exit.
Exception in thread "main"
Working directory: d:\code\pinpoint\agent
Command: [d:\Java\jdk1.7.0_79\bin\java.exe, -cp, , -javaagent:d:\code\pinpoint\a
gent\target\pinpoint-agent-1.5.2-SNAPSHOT\pinpoint-bootstrap-1.5.2-SNAPSHOT.jar=
bootClass=com.navercorp.pinpoint.test.PluginTestAgent, -Dpinpoint.agentId=build.
test.0, -Dpinpoint.applicationName=test, -Dpinpoint.test.id=:child:7, -Dfile.enc
oding=UTF-8, com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest, com.na
vercorp.pinpoint.plugin.jdk.http.HttpURLConnectionIT, -child=d:\code\pinpoint\ag
ent\target\test-classes]
閿欒: 鎵句笉鍒版垨鏃犳硶鍔犺浇涓荤被 com.navercorp.pinpoint.test.plugin.Forked
PinpointPluginTest
Working directory: d:\code\pinpoint\agent
Command: [D:\java\jdk1.8.0_25\bin\java.exe, -cp, , -javaagent:d:\code\pinpoint\a
gent\target\pinpoint-agent-1.5.2-SNAPSHOT\pinpoint-bootstrap-1.5.2-SNAPSHOT.jar=
bootClass=com.navercorp.pinpoint.test.PluginTestAgent, -Dpinpoint.agentId=build.
test.0, -Dpinpoint.applicationName=test, -Dpinpoint.test.id=:child:8, -Dfile.enc
oding=UTF-8, com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest, com.na
vercorp.pinpoint.plugin.jdk.http.HttpURLConnectionIT, -child=d:\code\pinpoint\ag
ent\target\test-classes]
閿欒: 鎵句笉鍒版垨鏃犳硶鍔犺浇涓荤被 com.navercorp.pinpoint.test.plugin.Forked
PinpointPluginTest
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.503 sec - in c
om.navercorp.pinpoint.plugin.jdk.http.HttpURLConnectionIT

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.099 s
[INFO] Finished at: 2016-03-16T09:31:51+08:00
[INFO] Final Memory: 16M/226M
[INFO] ------------------------------------------------------------------------
```

so, how to run the integration tests?

**Comment by lioolli** [comment]
Pinpoint plugin integration tests are executed in integration-test phase.

**Comment by hamlet-lee** [comment]
thanks, `mvn integration-test` is working.
but how can I run a specific Test Case only?

BTW: Wish you guys mention how to run integration test in the document (pinpoint-plugin-sample's doc or somewhere else).

**Comment by nstopkimsk** [comment]
Thanks for your suggestion. 
I added `mvn integration-test` to `Plugin development guide` and `pinpoint-plugin-samples'
