### ISSUE TITLE
NetworkAvailabilityChecker test causes NPE to be thrown in AgentLifeCycleHandler

### ISSUE THREAD

**Issue by jgangemi** [naver/pinpoint#1667]
the handler is looking for the `START_TIMESTAMP` property in the `channelProperties` map, which does not exist when using the test class.

this causes an `NullPointerException` to be thrown b/c a `Long` that is `null` obviously cannot be unboxed into a `long`, which then causes the test to report back the `udp` ports aren't working.

here is the associated stacktrace

```
java.lang.NullPointerException
    at com.navercorp.pinpoint.collector.rpc.handler.AgentLifeCycleHandler.handleLifeCycleEvent(AgentLifeCycleHandler.java:76)
    at com.navercorp.pinpoint.collector.rpc.handler.AgentLifeCycleChangeEventHandler.eventPerformed(AgentLifeCycleChangeEventHandler.java:55)
    at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.executeChangeEventHandler(DefaultPinpointServerState.java:125)
    at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.to(DefaultPinpointServerState.java:114)
    at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.toClosedByPeer(DefaultPinpointServerState.java:84)
    at com.navercorp.pinpoint.rpc.server.DefaultPinpointServer.stop(DefaultPinpointServer.java:140)
    at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.channelDisconnected(PinpointServerAcceptor.java:377)
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:120)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.channelDisconnected(FrameDecoder.java:365)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:361)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by koo-taejin** [comment]
Could you let me know which test case broken.
and the problem still occurs with current master branch?
