### ISSUE TITLE
Quickstart testapp can not connect to collector,but localhost:28080 & localhost:28081 can visit.

### ISSUE THREAD

**Issue by AIIstar** [naver/pinpoint#1680]
Hadoop version:2.7.2
zookeeper version:3.3.6
Hbase version:1.0
Collector and web are running,but when I run the start-testapp.sh,report warn.It seems like the connect was refused on port 29994.
The iptables and SELinux are both stop.
localhost:28080 & localhost:28081 can visit,but in pinpoint-web I can't find test-app.just like the picture in this issues: https://github.com/naver/pinpoint/issues/1601
What's the matter?

quickstart.testapp.log

2016-04-12 16:54:33 [WARN ](c.n.p.r.c.DefaultPinpointClientHandler:462) DefaultPinpointClientHandler@1f0480e1 exceptionCaught() occurred. state:NONE. Caused:拒绝连接: /127.0.0.1:29994
java.net.ConnectException: 拒绝连接: /127.0.0.1:29994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-04-12 16:54:33 [INFO ](c.n.p.r.c.PinpointClientHandshaker :242) PinpointClientHandshaker@5d09958a unexpected state
2016-04-12 16:54:33 [DEBUG](c.n.p.r.c.RequestManager           :164) close()
2016-04-12 16:54:33 [WARN ](c.n.p.r.u.ClientFactoryUtils       :50 ) tcp connect fail. remote:/127.0.0.1:29994 try reconnect, retryCount:0

2016-04-12 16:54:33 [WARN ](c.n.p.r.c.DefaultPinpointClientHandler:462) DefaultPinpointClientHandler@411c6c59 exceptionCaught() occurred. state:NONE. Caused:拒绝连接: /127.0.0.1:29994
java.net.ConnectException: 拒绝连接: /127.0.0.1:29994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-04-12 16:54:33 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@411c6c59 stateTo() started. to:CONNECT_FAILED
2016-04-12 16:54:33 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@411c6c59 stateTo() completed. Socket state change fail(updateWanted:CONNECT_FAILED ,before:NONE ,current:NONE).

**Comment by Xylus** [comment]
Hi Allstar,
Quickstart's [Collector](https://github.com/naver/pinpoint/blob/master/quickstart/collector/src/main/resources/pinpoint-collector.properties) and [TestApp](https://github.com/naver/pinpoint/blob/master/quickstart/conf/pinpoint.config) uses ports `29994, 29995, 29996` for communication.

Could you check if these ports are available?
Thanks!
