### ISSUE TITLE
[fatal error]start-testapp.cmd on win7

### ISSUE THREAD

**Issue by tangyong** [naver/pinpoint#171]
Hi Team,

I met a fatal error while starting testapp on win7 as following:

F:\pinpoint\pinpoint-master\quickstart\bin>start-testapp.cmd
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Caused by: java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:50)
        at java.util.Scanner.<init>(Scanner.java:747)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.parseAgentArgs(PinpointBootStrap.java:132)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:57)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
"---pinpoint-quickstart-testapp initialization start failed---"
"---pinpoint-quickstart-testapp initialization failed. pid=.---"

**Comment by koo-taejin** [comment]
Hi tangyong. 

Please send me e-mail with full log. (log path : quickstart/log/)
If you are using master branch. Then swith to 1.0.4-rc branch. (rc branch more stable than develop branch.)

**Comment by emeroad** [comment]
this issue is here.
182217292e8fc7154b734d971f723006892b4071

**Comment by tangyong** [comment]
@koo-taejin I used master and will switch to 1.0.4-rc to verify the issue. @emeroad sure.

**Comment by tangyong** [comment]
Now, switch into 1.0.4-rc met #175 .

**Comment by tangyong** [comment]
@koo-taejin @emeroad  after switching to 1.0.4-rc, the issue does not happen and agent is running successfully.

So, whether having some regression on current master or not?

**Comment by Xylus** [comment]
The issue should've been resolved with the commit @emeroad mentioned.

Could you try again after updating your master branch?
