### ISSUE TITLE
Get call tree from self defined package

### ISSUE THREAD

**Issue by zhuhewei** [naver/pinpoint#1748]
Hello,i current set the package that need to be monited by Pinpoint in pinpoint.config like this -- profiler.include=com.gome.test.site.service.*

But the call tree can't be monited ,error Message like this 

`2016-05-09 17:19:53 [ERROR](c.n.p.p.ClassFileTransformerDispatcher:126) Transformer:com.navercorp.pinpoint.profiler.instrument.transformer.DebugTransformer threw an exception. cl:java.net.URLClassLoader@36c11c0f ctxCl:java.net.URLClassLoader@36c11c0f agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@6a16f44f Cause:No target is specified. At least one of @Targets, @TargetMethod, @TargetConstructor, @TargetFilter must present. interceptor: com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor
com.navercorp.pinpoint.exception.PinpointException: No target is specified. At least one of @Targets, @TargetMethod, @TargetConstructor, @TargetFilter must present. interceptor: com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor
	at com.navercorp.pinpoint.profiler.instrument.JavassistClass.addInterceptor0(JavassistClass.java:567)
	at com.navercorp.pinpoint.profiler.instrument.JavassistClass.addInterceptor(JavassistClass.java:453)
	at com.navercorp.pinpoint.profiler.instrument.transformer.DebugTransformer.transform(DebugTransformer.java:65)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:249)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:395)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1309)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:622)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:591)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1386)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:434)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:404)
	at org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration.checkServlets(DispatcherServletAutoConfiguration.java:117)
	at org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration.access$000(DispatcherServletAutoConfiguration.java:58)
	at org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration$DefaultDispatcherServletCondition.getMatchOutcome(DispatcherServletAutoConfiguration.java:106)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:45)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:198)
	at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:314)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:243)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:226)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:480)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:424)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:180)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:306)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:239)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:254)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
	at com.gome.test.site.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:408)
	at java.lang.Thread.run(Thread.java:745)`

This is relly confusing,Why i get return information like this "No target is specified",any one get similer error like this ,please let me know ,thank you very much.

**Comment by zhuhewei** [comment]
Finally,it seems the the package i monitor can be get call tree by Pinpoint ,i alreadt get data from collector.

in tomcat log file "catalina.out"
`05-11 09:35:07 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    :54) insert:TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:51, apiInfo:com.gome.test.site.service.SiteService.getXmlListFromSheet(org.apache.poi.ss.usermodel.Sheet sheet), line:42, type:0)
05-11 09:35:07 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    :54) insert:TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:-52, apiInfo:com.gome.test.site.service.SiteService.getXmlPage(java.lang.String xml), line:79, type:0)
05-11 09:35:07 [INFO ](c.n.p.c.h.ApiMetaDataHandler       :51) Received ApiMetaData=TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:52, apiInfo:com.gome.test.site.service.SiteService.getXMLNode(java.lang.String xmlStr, java.lang.String xpathExp), line:175, type:0)
05-11 09:35:07 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    :54) insert:TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:52, apiInfo:com.gome.test.site.service.SiteService.getXMLNode(java.lang.String xmlStr, java.lang.String xpathExp), line:175, type:0)
05-11 09:35:07 [INFO ](c.n.p.c.h.ApiMetaDataHandler       :51) Received ApiMetaData=TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:-56, apiInfo:com.gome.test.site.service.TUrlHelper.getUrlData(java.lang.String longurl), line:37, type:0)
05-11 09:35:07 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    :54) insert:TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:-56, apiInfo:com.gome.test.site.service.TUrlHelper.getUrlData(java.lang.String longurl), line:37, type:0)
05-11 09:35:07 [INFO ](c.n.p.c.h.ApiMetaDataHandler       :51) Received ApiMetaData=TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:-57, apiInfo:com.gome.test.site.service.updateService.run(int minid, int maxid), line:28, type:0)
05-11 09:35:07 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    :54) insert:TApiMetaData(agentId:20160506, agentStartTime:1462930491075, apiId:-57, apiInfo:com.gome.test.site.service.updateService.run(int minid, int maxid), line:28, type:0)
05-11 11:11:54 [INFO ](c.n.p.c.h.ApiMetaDataHandler       :51) Received ApiMetaData=TApiMetaData(agentId:20160506, agentStartTime:1462936300992, apiId:-49, apiInfo:com.gome.test.site.service.SiteService.getXmlPage(java.lang.String xml), line:79, type:0)
05-11 11:11:54 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    :54) insert:TApiMetaData(agentId:20160506, agentStartTime:1462936300992, apiId:-49, apiInfo:com.gome.test.site.service.SiteService.getXmlPage(java.lang.String xml), line:79, type:0)
05-11 11:11:54 [INFO ](c.n.p.c.h.ApiMetaDataHandler       :51) Received ApiMetaData=TApiMetaData(agentId:20160506, agentStartTime:1462936300992, apiId:49, apiInfo:com.gome.test.site.service.SiteService.getXMLNode(java.lang.String xmlStr, java.lang.String xpathExp), line:175, type:0)`

So the data has been returned!
and it's not the problem of Hbase because i have get the Data in hbase in the "ApiMetaData" table

` \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529125678, value=\xB8\x02org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest reques
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xC5 t, org.apache.http.protocol.HttpContext context)\x00\x00\x00Q\x00\x00\x00\x00                                                                                                  
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529125644, value=\xC6\x03org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.HttpHost target, org.apache.http.Htt
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xC6 pRequest request, org.apache.http.client.ResponseHandler responseHandler, org.apache.http.protocol.HttpContext context)\x00\x00\x00\xDA\x00\x00\x00\x00                        
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529125576, value=\x84\x01com.gome.test.site.service.updateService.run(int minid, int maxid)\x00\x00\x00\x1C\x00\x00\x00\x00          
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xC7                                                                                                                                                                                
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529125539, value=\x94\x01com.gome.test.site.service.TUrlHelper.getUrlData(java.lang.String longurl)\x00\x00\x00%\x00\x00\x00\x00     
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xC8                                                                                                                                                                                
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529124235, value=\x98\x02com.gome.test.site.dao.SiteMapDao.updateLockTime(int limitCount, java.lang.String lockTime, java.lang.String
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xC9  minTime, java.lang.String user)\x00\x00\x00"\x00\x00\x00\x00                                                                                                                  
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529124221, value=\xB2\x01com.gome.test.site.dao.SiteMapDao.updateData2(int id, int code, java.lang.String content)\x00\x00\x000\x00\x
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xCA 00\x00\x00                                                                                                                                                                     
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529124208, value=zcom.gome.test.site.dao.SiteMapDao.getListData(int limitCount)\x00\x00\x00\x12\x00\x00\x00\x00                      
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xCB                                                                                                                                                                                
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529124173, value=\x9A\x01com.gome.test.site.service.SiteService.getSheetXmlFromFile(java.io.File file)\x00\x00\x00\xA0\x00\x00\x00\x0
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xCC 0                                                                                                                                                                              
 \x0720160506\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0 column=Api:P_api_signature, timestamp=1462529124155, value=\x92\x01com.gome.test.site.service.SiteService.insertBasicInfo(java.io.File file)\x00\x00\x00\xC3\x00\x00\x00\x00   
 0\x00\x00\x00\x00\x7F\xFF\xFE\xABzx\xCB\x00\xFF\xFF\xFF\xCD`

it's clear that the package monitoring data is in the hbase .

but i still can't get success or fail transaction from Pinpoint web ,there is no Data.

![20160511113111](https://cloud.githubusercontent.com/assets/19264066/15169248/e35f5f52-176b-11e6-92ee-f236bcaba8cb.jpg)

any one seen the same problem like this? please let me know ,thank you very much .

**Comment by zhuhewei** [comment]
The transaction number is zero ,base on the Pinpoint collector log

`05-11 11:48:02 [DEBUG](c.n.p.c.h.AgentStatHandler         :67) Received AgentStats=TAgentStatBatch(agentId:20160506, startTimestamp:1462938089476, agentStats:[TAgentStat(timestamp:1462938455478, collectInterval:5000, gc:TJvmGc(type:PARALLEL, jvmMemoryHeapUsed:1273397232, jvmMemoryHeapMax:1908932608, jvmMemoryNonHeapUsed:84654408, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:5, jvmGcOldTime:4641, jvmGcDetailed:TJvmGcDetailed(jvmGcNewCount:138, jvmGcNewTime:4146, jvmPoolCodeCacheUsed:0.19009272257486978, jvmPoolNewGenUsed:0.5247366215536382, jvmPoolOldGenUsed:0.6548033270643744, jvmPoolSurvivorSpaceUsed:0.007142857142857143, jvmPoolPermGenUsed:0.8732717560558785)), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.20221443711257747), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0]))), TAgentStat(timestamp:1462938460478, collectInterval:5000, gc:TJvmGc(type:PARALLEL, jvmMemoryHeapUsed:1273403984, jvmMemoryHeapMax:1908932608, jvmMemoryNonHeapUsed:84654640, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:5, jvmGcOldTime:4641, jvmGcDetailed:TJvmGcDetailed(jvmGcNewCount:138, jvmGcNewTime:4146, jvmPoolCodeCacheUsed:0.19009272257486978, jvmPoolNewGenUsed:0.524747168988502, jvmPoolOldGenUsed:0.6548033270643744, jvmPoolSurvivorSpaceUsed:0.007142857142857143, jvmPoolPermGenUsed:0.8732744542563834)), cpuLoad:TCpuLoad(jvmCpuLoad:7.80005E-4, systemCpuLoad:0.14277450000000003), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0]))), TAgentStat(timestamp:1462938465478, collectInterval:5000, gc:TJvmGc(type:PARALLEL, jvmMemoryHeapUsed:1273416720, jvmMemoryHeapMax:1908932608, jvmMemoryNonHeapUsed:84654640, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:5, jvmGcOldTime:4641, jvmGcDetailed:TJvmGcDetailed(jvmGcNewCount:138, jvmGcNewTime:4146, jvmPoolCodeCacheUsed:0.19009272257486978, jvmPoolNewGenUsed:0.5247670641499987, jvmPoolOldGenUsed:0.6548033270643744, jvmPoolSurvivorSpaceUsed:0.007142857142857143, jvmPoolPermGenUsed:0.8732744542563834)), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.11235432000000001), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0]))), TAgentStat(timestamp:1462938470477, collectInterval:4999, gc:TJvmGc(type:PARALLEL, jvmMemoryHeapUsed:1273423248, jvmMemoryHeapMax:1908932608, jvmMemoryNonHeapUsed:84654640, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:5, jvmGcOldTime:4641, jvmGcDetailed:TJvmGcDetailed(jvmGcNewCount:138, jvmGcNewTime:4146, jvmPoolCodeCacheUsed:0.19009272257486978, jvmPoolNewGenUsed:0.5247772241790797, jvmPoolOldGenUsed:0.6548033270643744, jvmPoolSurvivorSpaceUsed:0.007142857142857143, jvmPoolPermGenUsed:0.8732744542563834)), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.12387915583116627), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0]))), TAgentStat(timestamp:1462938475477, collectInterval:5000, gc:TJvmGc(type:PARALLEL, jvmMemoryHeapUsed:1273433984, jvmMemoryHeapMax:1908932608, jvmMemoryNonHeapUsed:84654640, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:5, jvmGcOldTime:4641, jvmGcDetailed:TJvmGcDetailed(jvmGcNewCount:138, jvmGcNewTime:4146, jvmPoolCodeCacheUsed:0.19009272257486978, jvmPoolNewGenUsed:0.5247941575608812, jvmPoolOldGenUsed:0.6548033270643744, jvmPoolSurvivorSpaceUsed:0.007142857142857143, jvmPoolPermGenUsed:0.8732744542563834)), cpuLoad:TCpuLoad(jvmCpuLoad:0.0, systemCpuLoad:0.10065424), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0]))), TAgentStat(timestamp:1462938480477, collectInterval:5000, gc:TJvmGc(type:PARALLEL, jvmMemoryHeapUsed:1273438688, jvmMemoryHeapMax:1908932608, jvmMemoryNonHeapUsed:84654640, jvmMemoryNonHeapMax:136314880, jvmGcOldCount:5, jvmGcOldTime:4641, jvmGcDetailed:TJvmGcDetailed(jvmGcNewCount:138, jvmGcNewTime:4146, jvmPoolCodeCacheUsed:0.19009272257486978, jvmPoolNewGenUsed:0.5247981190974355, jvmPoolOldGenUsed:0.6548033270643744, jvmPoolSurvivorSpaceUsed:0.007142857142857143, jvmPoolPermGenUsed:0.8732744542563834)), cpuLoad:TCpuLoad(jvmCpuLoad:7.80005E-4, systemCpuLoad:0.08817414000000001), transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])))])`

this part --transaction:TTransaction(sampledNewCount:0, sampledContinuationCount:0, unsampledNewCount:0, unsampledContinuationCount:0), 

the project runs ,but the transaction keep un added ,it,s zero all the time during my monotoring test.
