### ISSUE TITLE
pinpoint-thrift .................................... FAILURE

### ISSUE THREAD

**Issue by fuchun** [naver/pinpoint#1781]
[INFO] Changes detected - recompiling the module!
[DEBUG] Classpath:
[DEBUG]  /data/pinpoint/thrift/target/classes
[DEBUG]  /root/.m2/repository/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar
[DEBUG]  /root/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
[DEBUG] Source roots:
[DEBUG]  /data/pinpoint/thrift/src/main/java
[DEBUG]  /data/pinpoint/thrift/target/generated-sources/annotations
[DEBUG] Excutable: 
[DEBUG]  /data/jdk1.6.0_24/bin/javac
[DEBUG] Command line options:
[DEBUG] -d /data/pinpoint/thrift/target/classes -classpath /data/pinpoint/thrift/target/classes:/root/.m2/repository/org/apache/thrift/libthrift/0.9.2/libthrift-0.9.2.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar: -sourcepath /data/pinpoint/thrift/src/main/java:/data/pinpoint/thrift/target/generated-sources/annotations: /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/io/PinpointByteArrayOutputStream.java /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/TAnnotation.java /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/TAgentStat.java /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/TActiveTrace.java /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/util/SerializationUtils.java /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/io/ByteArrayOutputStreamTransport
....................................
/dto/command/TCmdActiveThreadCountRes.java /data/pinpoint/thrift/src/main/java/com/navercorp/pinpoint/thrift/dto/command/TCommandTransferResponse.java -s /data/pinpoint/thrift/target/generated-sources/annotations -O -g -deprecation -target 1.6 -source 1.6 -encoding UTF-8
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 81 source files to /data/pinpoint/thrift/target/classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] pinpoint ........................................... SUCCESS [  2.950 s]
[INFO] pinpoint-thrift .................................... FAILURE [  2.248 s]
[INFO] pinpoint-commons ................................... SKIPPED
[INFO] pinpoint-commons-hbase ............................. SKIPPED
[INFO] pinpoint-commons-server ............................ SKIPPED
[INFO] pinpoint-bootstrap-core ............................ SKIPPED
[INFO] pinpoint-bootstrap ................................. SKIPPED
[INFO] pinpoint-rpc ....................................... SKIPPED
[INFO] pinpoint-profiler .................................. SKIPPED
[INFO] pinpoint-profiler-optional ......................... SKIPPED
[INFO] pinpoint-httpclient3-plugin ........................ SKIPPED
[INFO] pinpoint-httpclient4-plugin ........................ SKIPPED
[INFO] pinpoint-ning-asynchttpclient-plugin ............... SKIPPED
[INFO] pinpoint-gson-plugin ............................... SKIPPED
[INFO] pinpoint-cubrid-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-mysql-jdbc-driver-plugin .................. SKIPPED
[INFO] pinpoint-mariadb-jdbc-driver-plugin ................ SKIPPED
[INFO] pinpoint-postgresql-jdbc-driver-plugin ............. SKIPPED
[INFO] pinpoint-jtds-plugin ............................... SKIPPED
[INFO] pinpoint-oracle-jdbc-driver-plugin ................. SKIPPED
[INFO] pinpoint-commons-dbcp-plugin ....................... SKIPPED
[INFO] pinpoint-test ...................................... SKIPPED
[INFO] pinpoint-cassandra-driver-plugin ................... SKIPPED
[INFO] pinpoint-jdk-http-plugin ........................... SKIPPED
[INFO] pinpoint-redis-plugin .............................. SKIPPED
[INFO] pinpoint-tomcat-plugin ............................. SKIPPED
[INFO] pinpoint-json-lib-plugin ........................... SKIPPED
[INFO] pinpoint-jackson-plugin ............................ SKIPPED
[INFO] pinpoint-thrift-plugin ............................. SKIPPED
[INFO] pinpoint-user-plugin ............................... SKIPPED
[INFO] pinpoint-arcus-plugin .............................. SKIPPED
[INFO] pinpoint-google-httpclient-plugin .................. SKIPPED
[INFO] pinpoint-jetty-plugin .............................. SKIPPED
[INFO] pinpoint-spring-plugin ............................. SKIPPED
[INFO] pinpoint-spring-boot-plugin ........................ SKIPPED
[INFO] pinpoint-ibatis-plugin ............................. SKIPPED
[INFO] pinpoint-mybatis-plugin ............................ SKIPPED
[INFO] pinpoint-okhttp-plugin ............................. SKIPPED
[INFO] pinpoint-log4j-plugin .............................. SKIPPED
[INFO] pinpoint-logback-plugin ............................ SKIPPED
[INFO] pinpoint-dubbo-plugin .............................. SKIPPED
[INFO] pinpoint-activemq-client-plugin .................... SKIPPED
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-integration-test-java8 .................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.508 s
[INFO] Finished at: 2016-05-18T17:14:57+08:00
[INFO] Final Memory: 24M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-thrift: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project pinpoint-thrift: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:976)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinpoint-thrift

**Comment by fuchun** [comment]
export JAVA_HOME=/data/jdk1.7.0_67
export JAVA_7_HOME=/data/jdk1.7.0_67
export JAVA_6_HOME=/data/jdk1.6.0_24
export JAVA_8_HOME=/data/jdk1.8.0_91

**Comment by fuchun** [comment]
I found I downloaded wrong jdk1.6
