### ISSUE TITLE
angular.js 에러 문의

### ISSUE THREAD

**Issue by defresh** [naver/pinpoint#1848]
안녕하세요.
1.6.0 버전(master 브랜치)를 clone 받아 설치를 해봤습니다.
가이드에 따라 quickstart 를 진행 했는데요~
web (http://localhost:28080) 접속시 아래와 같이 앵귤러에서 에러가 발생해서요 ㅠ.ㅜ
다시 받아서 재 빌드를 해봐도 동일해서 문의드려 봅니다.

angular-lib.min.js?v=20160615153413:92 Error: [$injector:unpr] http://errors.angularjs.org/1.2.18/$injector/unpr?p0=filterConfigProvider%20%3C-NaNilterConfig
    at Error (native)
    at http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:6:450
    at http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:36:145
    at Object.c [as get] (http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:34:236)
    at http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:36:213
    at c (http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:34:236)
    at d (http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:34:453)
    at Object.instantiate (http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:35:103)
    at http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:67:284
    at link (http://pinpoint/lib/js/angular-lib.min.js?v=20160615153413:959:248)

감사합니다.

**Comment by denzelsN** [comment]
안녕하세요.
build file ( grunt ) 의 설정 잘못으로 발생한 버그입니다.

수정하여 올려두었으니 pull 받으신 후 빌드를 다시 한번 실행해 주세요.

**Comment by defresh** [comment]
@denzelsN  님

풀 받아보니 우선 에러는 발생하지 않았습니다.
그런데 이번엔 우측 창에 로딩 이미지가 사라지지 않고 내용이 노출되지 않네요 ㅠ.ㅜ

다시 클론 받아도 동일해서 문의드립니다.

**Comment by denzelsN** [comment]
@defresh 
안녕하세요.

화면 캡쳐 및 에러 로그가 있다면 같이 올려주실 수 있을까요?

**Comment by defresh** [comment]
![pinpoint](https://cloud.githubusercontent.com/assets/10772108/16182352/f5bfb19a-36df-11e6-8192-666a19a84e97.png)

네 캡쳐입니다~
요상태로 계속 유지됩니다.

**Comment by denzelsN** [comment]
@defresh 
감사합니다.  에러확인하고 수정했습니다.
 pull 받으신 후 빌드를 다시 한번 실행해 주세요.

**Comment by defresh** [comment]
@denzelsN 님

다시 설치 해보니 우선 loading 메세지는 사라졌습니다.
다만 testapp 요청을 날려도 call stack 이 쌓이지 않네요^^;

consumeCpu.pinpoint 같은 uri 실행 시켰을때
testapp 쪽에 호출 로그는 정상적으로 쌓이고 있는데.

![pinpoint1](https://cloud.githubusercontent.com/assets/10772108/16184441/4edd4adc-36f7-11e6-9c43-367b419dd4eb.png)

그리고 web 쪽에 계속 아래와 같은 에러 로그가 발생 합니다.

14:57:33 WARN (.n.p.w.c.ControllerExceptionHandler:50 ) Error:from value must be higher than 0
java.lang.IllegalArgumentException: from value must be higher than 0
        at com.navercorp.pinpoint.web.scatter.ScatterData.<init>(ScatterData.java:53)
        at com.navercorp.pinpoint.web.dao.hbase.HbaseApplicationTraceIndexDao.scanTraceScatterData(HbaseApplicationTraceIndexDao.java:300)
        at com.navercorp.pinpoint.web.service.ScatterChartServiceImpl.selectScatterData(ScatterChartServiceImpl.java:146)
        at com.navercorp.pinpoint.web.controller.ScatterChartController.selectScatterData(ScatterChartController.java:186)
        at com.navercorp.pinpoint.web.controller.ScatterChartController.getScatterData(ScatterChartController.java:165)
        at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:856)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at com.navercorp.pinpoint.web.servlet.NoCacheFilter.doFilter(NoCacheFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)


한번만 더 도움 부탁 드립니다.( _ _)

**Comment by denzelsN** [comment]
@Xylus  확인 부탁드려요~

**Comment by defresh** [comment]
![pinpoint2](https://cloud.githubusercontent.com/assets/10772108/16185471/1e0a2e04-36ff-11e6-96f2-ad8029f1a69c.png)

@denzelsN  님 @Xylus 님

내부 서비스 테스트 환경에 적용해 봤을때
트래픽 넣어보니 Thread chart 에는 값이 적용 되네요.

다만 우측에 request 정보 있는 그래프가 계속 Loading 이라고만 표시 됩니다^^;

**Comment by denzelsN** [comment]
@defresh  
제보 감사합니다. 에러 확인했습니다. 
다른 기능을 수정 하면서 발생한 side-effect 입니다.
곧 수정해서 올리도록 하겠습니다.

**Comment by denzelsN** [comment]
@defresh  
받아서 빌드 다시 해보세요.

**Comment by defresh** [comment]
@denzelsN 님

Loading 문구는 사라졌는데 여전히 데이터는 No Data 라고 나와요^^;
WEB 쪽 에러도 사라졌습니다.

TESTAPP 및 별도 적용한 서비스 동일하네요.

**Comment by denzelsN** [comment]
@defresh 
다시 한번 받아서 빌드해보세요.
혹시 모르니 브라우저 캐시도 지우고 해보시기 바랍니다.

**Comment by defresh** [comment]
@denzelsN 님

감사합니다. 우선 우측에 그래프도 정상적으로 나옵니다^^;

다만 추가로 여러 서비스를 적용 해보니 찾은 문젠데요^^;(다른 이슈로 올려야 할거 같긴하지만..)

A 서비스를 보다가 B서비스로 넘어와서 transactionList 로 들어가면 transactionList/A@TOMCAT 형태로 호출되어서 트랜잭션 리스트가 안보이네요^^;

**Comment by denzelsN** [comment]
@defresh 
넵 ^^; 
url 과 파라미터 처리하는 코드를 좀 수정하면서 여기저기 side-effect가 생기고 있습니다.
아무래도 master branch가 개발 중인 코드가 올라가는 곳이다 보니 에러가 좀... :)
1.5.2 버젼을 받으시면 좀 더 에러없이 테스트가 가능합니다.
