### ISSUE TITLE
Zookeeper does not reconnect when session expired. 

### ISSUE THREAD

**Issue by koo-taejin** [naver/pinpoint#191]
Zookeeper does not reconnect when session expired. 

-------------------------- zookeeper session expired --------------------------
(o.a.z.ClientCnxn) Client session timed out, have not heard from server in 11198ms for sessionid 0x34331c4ac633093, closing socket connection and attempting reconnect
(o.a.z.ClientCnxn) Opening socket connection to server cvzk02.pinpoint.nhnsystem.com/10.114.80.176:2181. Will not attempt to authenticate using SASL (java.lang.SecurityException: 
(o.a.z.ClientCnxn) Socket connection established -, initiating session
(o.a.z.ClientCnxn) EventThread shut down
(o.a.z.ClientCnxn) Unable to reconnect to ZooKeeper service, session 0x34331c4ac633093 has expired, closing socket connection

-------------------------- cluster work failed --------------------------
(c.n.p.c.c.z.ZookeeperLatestJobWorker) Worker execute job(UpdateJob, ChannelContext=com.navercorp.pinpoint.rpc.server.ChannelContext@54ae9d7d, Retry=0/3).
(c.n.p.c.c.z.ZookeeperLatestJobWorker) instance must be connected.
com.navercorp.pinpoint.collector.cluster.zookeeper.exception.ConnectionException: instance must be connected.

**Comment by lioolli** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
문종호(jongho.moon@navercor...) 님은 현재 부재중입니다.</br>
보내신 메일 <[pinpoint] Zookeeper does not reconnect when session expired. (#191)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
문종호(jongho.moon@navercor...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-02-23 00:00 ~ 2015-02-27 23:59 GMT +09:00]<br>리프레시로 2/23 ~ 2/27 동안 자리를 비웁니다.<br>Pinpoint 관련 문의는 dl_labs_p_pinpoint@navercorp.com로 부탁드립니다.
--------------------------------------------

**Comment by god8816** [comment]
2018-07-27 17:19:31 [WARN ](o.a.z.ClientCnxn                   ) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2018-07-27 17:19:31 [WARN ](c.n.p.c.c.z.ZookeeperJobWorker     ) handleUpdate failed. caused:Instance must be connected., jobSize:1
com.navercorp.pinpoint.collector.cluster.zookeeper.exception.ConnectionException: Instance must be connected.
	at com.navercorp.pinpoint.collector.cluster.zookeeper.DefaultZookeeperClient.checkState(DefaultZookeeperClient.java:273)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.DefaultZookeeperClient.exists(DefaultZookeeperClient.java:255)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.handleUpdate(ZookeeperJobWorker.java:341)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.handle(ZookeeperJobWorker.java:323)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.run(ZookeeperJobWorker.java:228)
	at java.lang.Thread.run(Thread.java:745)

pinpoint -version：1.7.3

**Comment by koo-taejin** [comment]
@god8816 
Please create a new issue  with detailed explanation.
