### ISSUE TITLE
AlarmMessageSenderImple.java 도와주세요!!!!

### ISSUE THREAD

**Issue by msbell** [naver/pinpoint#1964]
안녕하세요!!
알람 구현 하다가 막혀서 질문드립니다 ㅠㅠ

~/doc/alarm.md 의 구현 및 설정 방법 보고 기타 부분 빼고 다 차례대로 수행하였는데요..
AlarmMessageSenderImple.java 의 userGroupService 변수에서 nullpointexception 에러가 뜹니다 ㅜㅜ

우선 .../web/alarm/AlarmMessageSenderImple.java 생성 후, 주신 코드를 복붙하였습니다.
그랬더니 
1.
List<String> receivers = userGroupService.selectPhoneNumberOfMember(checker.getUserGroupId());
이 부분에서 getUserGroupId() 에러나서 getuserGroupId() 로 수정했고,
2. 
똑같은 부분에서 userGroupService를 cannot find symbol 에러 뜨길래
UserGroupService userGroupService; 하고 선언해주었는데, 
spring annotation 이용해서 설정을 해주어야하는 것입니까?
뭔가 연결을 시켜줘야 하는 것 같긴 한데.. 메뉴얼에는 그런 말이 없고 
또 무엇보다 Spring을 잘 몰라서 어떻게 해야하는지 막막하네요!!

.war 파일 만들어서 deploy하고 나머지 부분 다 설정하고 log 확인해보았더니,
userGroupService 변수에서 nullpointexception이 뜹니다.

도움을 주세요
로그 파일은 아래와 같이 뜹니다.
NullPointerException 뜨는 변수는 userGroupService 입니다.
어떻게 선언해줘야 하는 것인지 모르겠습니다.
알려주세요.
감사합니다!!

16:30:00 ERROR(o.s.b.c.s.AbstractStep             :222) Encountered an error executing step alarmStep in job alarmJob
java.lang.NullPointerException
	at com.navercorp.pinpoint.web.alarm.AlarmMessageSenderImple.sendSms(AlarmMessageSenderImple.java:44)
	at com.navercorp.pinpoint.web.alarm.AlarmWriter.sendAlarmMessage(AlarmWriter.java:62)
	at com.navercorp.pinpoint.web.alarm.AlarmWriter.write(AlarmWriter.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy45.write(Unknown Source)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)
	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16:30:00 ERROR(o.s.b.c.s.AbstractStep             :222) Encountered an error executing step alarmPartitionStep in job alarmJob
org.springframework.batch.core.JobExecutionException: Partition handler returned an unsuccessful step
	at org.springframework.batch.core.partition.support.PartitionStep.doExecute(PartitionStep.java:111)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:127)
	at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:61)
	at com.navercorp.pinpoint.web.batch.BatchJobLauncher.alarmJob(BatchJobLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by koo-taejin** [comment]
1번 부분은 메소드명에 문제가 있네요 수정하도록 하겠습니다. 
2번은 변수 선언부분에 다음처럼 추가해주시면 될 것 같네요 
```
    @Autowired
    private UserGroupService userGroupService;
```
이부분은 메뉴얼에서 수정하도록 하겠습니다.

**Comment by msbell** [comment]
네 전부 다 해결되었습니다. 빠른 답변 정말 감사드려요!
Pinpoint 정말 좋습니다!!

**Comment by msbell** [comment]
추가로 완료된 source code 공유합니다.
감사합니다.

package com.navercorp.pinpoint.web.alarm;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.navercorp.pinpoint.web.alarm.AlarmMessageSender;
import com.navercorp.pinpoint.web.alarm.checker.AlarmChecker;
import com.navercorp.pinpoint.web.service.UserGroupService;
import com.navercorp.pinpoint.web.dao.UserDao;
import com.navercorp.pinpoint.web.dao.UserGroupDao;
import com.navercorp.pinpoint.web.vo.User;
import com.navercorp.pinpoint.web.vo.UserGroup;
import com.navercorp.pinpoint.web.vo.UserGroupMember;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.util.ArrayList;
import java.util.List;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.HttpClientBuilder;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * @author minwoo.jung
 */

public class AlarmMessageSenderImple implements AlarmMessageSender {

	private final Logger logger = LoggerFactory.getLogger(this.getClass());

	@Autowired
	private UserGroupService userGroupService;
	
	@Override
	public void sendSms(AlarmChecker checker, int sequenceCount) {
		List<String> receivers = userGroupService.selectPhoneNumberOfMember(checker.getuserGroupId());
		if (receivers.size() == 0) return;

		List<String> smsMessageList = checker.getSmsMessage();
		for (String message : smsMessageList) {
			// 로그 저장
			logger.info("send SMS : {}", message);

			// SMS 전송 로직
		}
	}

	@Override
	public void sendEmail(AlarmChecker checker, int sequenceCount) {
		//		List<String> receivers = userGroupService.selectEmailOfMember(checker.getuserGroupId());
		//
		//		if (receivers.size() == 0) return;
		//
		//		for (String message : checker.getEmailMessage()) {
		//			logger.info("send email : {}", message);
		//
		//			//TODO email 전송 로직 구현
		//		}
	}
}

**Comment by koo-taejin** [comment]
네 해결되었다니 다행이네요 :)
