### ISSUE TITLE
Pinpoint Agent not able to communicate with Collector

### ISSUE THREAD

**Issue by sattishv** [naver/pinpoint#1967]
Hi team,

We have a dockerized environment, where the agent and collector are installed on separate containers. When we tried to communicate each other we are experiencing socket connection error eventhough we exposed few ports like 28080-28082 ,9994-9996. Could you please help us on how to proceed further.

Exception:
2016-08-05 17:10:36 [WARN ](c.n.p.r.c.DefaultPinpointClientHandler:462) DefaultPinpointClientHandler@415a7b5d exceptionCaught() occurred. state:CONNECT_FAILED. Caused:Connection refused: /172.17.0.2:9994
java.net.ConnectException: Connection refused: /172.17.0.2:9994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Error Stack:
2016-08-05 17:10:45 [WARN ](c.n.p.r.c.PinpointClientFactory$ConnectEvent:343) try reconnect. connectAddress:/172.17.0.2:9994
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:196) DefaultPinpointClientHandler@443b97f initReconnect() started.
2016-08-05 17:10:45 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@443b97f stateTo() started. to:BEING_CONNECT
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@443b97f stateTo() completed. Socket state change success(updateWanted:BEING_CONNECT ,before:NONE ,current:BEING_CONNECT).
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:203) DefaultPinpointClientHandler@443b97f initReconnect() completed.
2016-08-05 17:10:45 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:144) DefaultPinpointClientHandler@443b97f channelOpen() started. channel:[id: 0x04963dc9]
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:460) DefaultPinpointClientHandler@443b97f exceptionCaught() occurred. state:BEING_CONNECT, caused:Connection refused: /172.17.0.2:9994.
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:556) DefaultPinpointClientHandler@443b97f channelClosed() started.
2016-08-05 17:10:45 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@443b97f stateTo() started. to:CONNECT_FAILED
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@443b97f stateTo() completed. Socket state change success(updateWanted:CONNECT_FAILED ,before:BEING_CONNECT ,current:CONNECT_FAILED).
2016-08-05 17:10:45 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:519) DefaultPinpointClientHandler@443b97f closeResources() started.
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.PinpointClientHandshaker :238) PinpointClientHandshaker@e848c7c handshakeAbort() started.
2016-08-05 17:10:45 [INFO ](c.n.p.r.c.PinpointClientHandshaker :242) PinpointClientHandshaker@e848c7c unexpected state
2016-08-05 17:10:45 [DEBUG](c.n.p.r.c.RequestManager           :164) close()
2016-08-05 17:10:47 [DEBUG](c.n.p.p.s.UdpDataSender            :166) Data sent. size:844, TAgentStatBatch(agentId:kncntusr

**Comment by koo-taejin** [comment]
please show you're pinpoint-collector.properties and configuration of docker port mapping.

**Comment by sattishv** [comment]
Hi,

Thanks for the response. Here is the complete test environment and what we are trying to accomplish
we have 2 docker containers docker 1 and docker 2
Docker 1 has the pinpoint installarion
Docker 2 has the agent hooked to our application

Docker 1 : Pinpoint Installation
we started pinpoint using the below docker run command
docker run -i -t --net=webserv_default -p 28080-28082:28080-28082 -p 9994:9994/udp -p 9995:9995/udp -p 9996:9996/udp --cap-add SYS_PTRACE yous/pinpoint:1.5.2 bash
network settings:
eth0      Link encap:Ethernet  HWaddr 02:42:ac:12:00:02
          inet addr:172.18.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8147 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3253 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:20219566 (19.2 MiB)  TX bytes:338882 (330.9 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:37038 errors:0 dropped:0 overruns:0 frame:0
          TX packets:37038 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:27239068 (25.9 MiB)  TX bytes:27239068 (25.9 MiB)

pinpoint-collector.properties
/pinpoint/quickstart/collector/target/classes/pinpoint-collector.properties

# tcp listen ip
collector.tcpListenIp=0.0.0.0
collector.tcpListenPort=29994

# udp listen ip
collector.udpStatListenIp=0.0.0.0
collector.udpStatListenPort=29995

collector.l4.ip=172.18.0.2

collector.udpStatWorkerThread=16
collector.udpStatWorkerQueueSize=128

collector.udpStatSocketReceiveBufferSize=4194304


# span listen port ---------------------------------------------------------------------
collector.udpSpanListenIp=0.0.0.0
collector.udpSpanListenPort=29996

collector.udpSpanWorkerThread=32
collector.udpSpanWorkerQueueSize=256

collector.udpSpanSocketReceiveBufferSize=4194304

statistics.flushPeriod=1000

cluster.enable=true
cluster.zookeeper.address=localhost
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=
cluster.listen.port=

Docker 2: Agent Installation

Network Settings:
br-6e12787a2f19 Link encap:Ethernet  HWaddr 02:42:C4:E6:97:0C
          inet addr:172.18.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:c4ff:fee6:970c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:12246 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12232 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1033196 (1008.9 KiB)  TX bytes:1924924 (1.8 MiB)

docker0   Link encap:Ethernet  HWaddr 02:42:F2:5D:1E:73
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:f2ff:fe5d:1e73/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:12246 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12232 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1033196 (1008.9 KiB)  TX bytes:1924924 (1.8 MiB)

eth0      Link encap:Ethernet  HWaddr 74:DB:D1:30:E7:59
          inet addr:10.25.103.175  Bcast:10.25.103.255  Mask:255.255.248.0
          inet6 addr: fe80::76db:d1ff:fe30:e759/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4720053 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1563766 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:6906921336 (6.4 GiB)  TX bytes:188394952 (179.6 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:338822 errors:0 dropped:0 overruns:0 frame:0
          TX packets:338822 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:194729892 (185.7 MiB)  TX bytes:194729892 (185.7 MiB)

vethecd9844 Link encap:Ethernet  HWaddr FA:4C:3B:1E:55:F6
          inet6 addr: fe80::f84c:3bff:fe1e:55f6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3321 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8215 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:344054 (335.9 KiB)  TX bytes:20226764 (19.2 MiB)
pinpoint.config:
#
# Pinpoint agent configuration
#

###########################################################
# Collector server                                        #
###########################################################
profiler.collector.ip=172.18.0.2

# placeHolder support "${key}"
profiler.collector.span.ip=${profiler.collector.ip}
profiler.collector.span.port=9996

# placeHolder support "${key}"
profiler.collector.stat.ip=${profiler.collector.ip}
profiler.collector.stat.port=9995

# placeHolder support "${key}"
profiler.collector.tcp.ip=${profiler.collector.ip}
profiler.collector.tcp.port=9994

###########################################################
# Profiler Global Configuration                           #
###########################################################
profiler.enable=true

profiler.interceptorregistry.size=8192
profiler.jvm.collect.interval=1000

# Allow to add detailed collector's metrics
profiler.jvm.collect.detailed.metrics=true

# Allow sampling.
profiler.sampling.enable=true

# 1 out of n transactions will be sampled where n is the rate. (1: 100%)
profiler.sampling.rate=1

# Allow buffering when flushing span to IO.
profiler.io.buffering.enable=true

# How many spans to store if buffering enabled.
profiler.io.buffering.buffersize=20

# Capacity of the SpanDataSender write queue.
profiler.spandatasender.write.queue.size=5120
#profiler.spandatasender.socket.sendbuffersize=1048576
#profiler.spandatasender.socket.timeout=3000
profiler.spandatasender.chunk.size=16384

# Capacity of the StatDataSender write queue.
profiler.statdatasender.write.queue.size=5120
#profiler.statdatasender.socket.sendbuffersize=1048576
#profiler.statdatasender.socket.timeout=3000
profiler.statdatasender.chunk.size=16384

# Interval to retry sending agent info. Unit is milliseconds.
profiler.agentInfo.send.retry.interval=300000

# Allow TCP data command.
profiler.tcpdatasender.command.accept.enable=true

# Trace Agent active thread info.
profiler.pinpoint.activethread=true

## Call Stack
# Set max depth, if -1 is unlimited and min is 2.
profiler.callstack.max.depth=64

# weather or not to propagate exceptions occurred at interceptor
"pinpoint.config" 420L, 14279C

Agent log snippets:
2016-08-11 15:16:04 [WARN ](c.n.p.r.c.PinpointClientFactory$ConnectEvent:343) try reconnect. connectAddress:/172.18.0.2:9994
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:196) DefaultPinpointClientHandler@395050da initReconnect() started.
2016-08-11 15:16:04 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@395050da stateTo() started. to:BEING_CONNECT
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@395050da stateTo() completed. Socket state change success(updateWanted:BEING_CONNECT ,before:NONE ,current:BEING_CONNECT).
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:203) DefaultPinpointClientHandler@395050da initReconnect() completed.
2016-08-11 15:16:04 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:144) DefaultPinpointClientHandler@395050da channelOpen() started. channel:[id: 0x0bc788a2]
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:556) DefaultPinpointClientHandler@395050da channelClosed() started.
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:460) DefaultPinpointClientHandler@395050da exceptionCaught() occurred. state:BEING_CONNECT, caused:Connection refused: /172.18.0.2:9994.
2016-08-11 15:16:04 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@395050da stateTo() started. to:CONNECT_FAILED
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@395050da stateTo() completed. Socket state change success(updateWanted:CONNECT_FAILED ,before:BEING_CONNECT ,current:CONNECT_FAILED).
2016-08-11 15:16:04 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:519) DefaultPinpointClientHandler@395050da closeResources() started.
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.PinpointClientHandshaker :238) PinpointClientHandshaker@6263cbe8 handshakeAbort() started.
2016-08-11 15:16:04 [INFO ](c.n.p.r.c.PinpointClientHandshaker :242) PinpointClientHandshaker@6263cbe8 unexpected state
2016-08-11 15:16:04 [DEBUG](c.n.p.r.c.RequestManager           :164) close()

Please review and let us know if u need any other details to probe

Thanks
Sattish.

**Comment by koo-taejin** [comment]
Collector's port is set as follows.

```
collector.tcpListenPort=29994
collector.udpStatListenPort=29995
collector.udpSpanListenPort=29996
# 29994 ~ 29996
```

but agent try to connect different port (9994 ~ 9996).
If you change this, then will be success.

thanks :)

**Comment by sattishv** [comment]
Hi koo,

Thanks i am able to connect .Appreciate your support

Sattish
