### ISSUE TITLE
JDK logger conflict in JBoss

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#2026]
Pinpoint Agent is not working in Jboss ENV
 - Tested in jboss-eap-6.4,
 - JDK version :  oracle 1.7.0_80
 
```
8월 30, 2016 2:32:27 오후 com.navercorp.pinpoint.bootstrap.PinpointStarter start
정보: pinpoint agent started normally.
WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
8월 30, 2016 2:32:27 오후 org.jboss.msc.service.ServiceContainerImpl <clinit>
INFO: JBoss MSC version 1.1.5.Final-redhat-1
8월 30, 2016 2:32:27 오후 org.jboss.as.server.ApplicationServerService start
INFO: JBAS015899: JBoss EAP 6.4.0.GA (AS 7.5.0.Final-redhat-21) starting
8월 30, 2016 2:32:28 오후 org.jboss.as.controller.AbstractOperationContext executeStep
2016-08-30 14:32:28 [DEBUG](c.n.p.p.DefaultAgent               :308) Agent status is changed. STOPPED
ERROR: JBAS014612: Operation ("parallel-extension-add") failed - address: ([])
2016-08-30 14:32:28 [INFO ](c.n.p.p.DefaultAgent               :450) Stopping pinpoint Agent.
java.lang.RuntimeException: JBAS014670: Failed initializing module org.jboss.as.logging
2016-08-30 14:32:28 [INFO ](c.n.p.p.AgentInfoSender            :103) AgentInfoSender stopped
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:111)
2016-08-30 14:32:28 [INFO ](c.n.p.p.m.AgentStatMonitor         :100) AgentStat monitor stopped
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:702)
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:537)
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:338)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:314)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1144)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:393)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:301)
	at org.jboss.as.server.ServerService.boot(ServerService.java:355)
	at org.jboss.as.server.ServerService.boot(ServerService.java:330)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:263)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: JBAS011592: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:103)
	... 11 more
Caused by: java.lang.IllegalStateException: JBAS011592: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
	at org.jboss.as.logging.LoggingExtension.initialize(LoggingExtension.java:136)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:97)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:139)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:125)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)

8월 30, 2016 2:32:28 오후 org.jboss.as.server.ServerService boot
FATAL: JBAS015957: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
2016-08-30 14:32:28 [DEBUG](c.n.p.p.s.AsyncQueueingExecutor    :110) Loop is stop.
2016-08-30 14:32:28 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    :197) Pinpoint-UdpSpanDataExecutor(16-0) stopped.
2016-08-30 14:32:28 [DEBUG](c.n.p.p.s.AsyncQueueingExecutor    :110) Loop is stop.
2016-08-30 14:32:28 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    :197) Pinpoint-UdpStatDataExecutor(17-0) stopped.
2016-08-30 14:32:28 [DEBUG](c.n.p.p.s.AsyncQueueingExecutor    :110) Loop is stop.
2016-08-30 14:32:28 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    :197) Pinpoint-TcpDataExecutor(15-0) stopped.
```
### workaround 
 https://github.com/suraj-raturi/pinpoint/blob/b4a02b065c9310a7b6bde196252f550a2d300f0f/plugins/jboss/README.md
 Add logger manager configuration in domain.xml
```
  <system-properties>
       <property name="java.util.logging.manager" value="org.jboss.logmanager.LogManager"/>
  </system-properties>
```

**Comment by emeroad** [comment]
Thirdparty lib conflict 

netty 3.6.6
```
[Loaded org.jboss.netty.channel.ChannelFactory from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded java.lang.IllegalStateException from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded com.navercorp.pinpoint.rpc.util.CpuUtils from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/pinpoint-rpc-1.6.0-SNAPSHOT.jar]
[Loaded com.navercorp.pinpoint.rpc.util.LoggerFactorySetup from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/pinpoint-rpc-1.6.0-SNAPSHOT.jar]
[Loaded org.jboss.netty.logging.InternalLoggerFactory from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded org.jboss.netty.logging.Slf4JLoggerFactory from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded org.jboss.netty.logging.InternalLogger from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded org.jboss.netty.logging.JdkLoggerFactory from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded org.jboss.netty.util.internal.StackTraceSimplifier from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded org.jboss.netty.util.DebugUtil from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded org.jboss.netty.util.internal.SystemPropertyUtil from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/netty-3.6.6.Final.jar]
[Loaded java.util.logging.Logger from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Handler from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Level from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Level$KnownLevel from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.concurrent.CopyOnWriteArrayList from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$1 from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.PropertyChangeSupport from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.ChangeListenerMap from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.PropertyChangeSupport$PropertyChangeListenerMap from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
```

guava 19.0
```
[Loaded javassist.ClassPoolTail from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.CtPrimitiveType from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.ClassMap from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.CtClass$1 from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.CtClass$DelayedFileOutputStream from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.ClassClassPath from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.ClassPathList from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded javassist.JarClassPath from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/javassist-3.20.0-GA.jar]
[Loaded com.navercorp.pinpoint.profiler.util.Maps from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/pinpoint-profiler-1.6.0-SNAPSHOT.jar]
[Loaded com.google.common.collect.GenericMapMaker from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMaker from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMaker$NullConcurrentMap from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.ComputingConcurrentHashMap from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMaker$ComputingMapAdapter from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMaker$NullComputingConcurrentMap from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap$Strength from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap$Strength$1 from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap$Strength$2 from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap$Strength$3 from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap$ValueReference from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.base.Preconditions from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded com.google.common.collect.MapMakerInternalMap$ReferenceEntry from file:/C:/project/master/pinpoint-naver/naver-agent/target/pinpoint-naver-agent-1.6.0-SNAPSHOT/lib/guava-19.0.jar]
[Loaded java.util.logging.Logger from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Handler from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Level from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Level$KnownLevel from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$1 from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.PropertyChangeSupport from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.ChangeListenerMap from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
```

**Comment by emeroad** [comment]
We solved JDKLogger problem.

```
[Loaded java.security.PermissionsEnumerator from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded org.jboss.modules.SecurityActions from file:/C:/project/jboss-eap-6.4/jboss-modules.jar]
[Loaded org.jboss.modules.SecurityActions$1 from file:/C:/project/jboss-eap-6.4/jboss-modules.jar]
[Loaded java.util.logging.LogManager from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Level from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.Level$KnownLevel from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$1 from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded org.jboss.logmanager.LogManager from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded java.util.logging.Logger from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded org.jboss.logmanager.Logger from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded org.jboss.logmanager.ConfigurationLocator from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded org.jboss.logmanager.Configurator from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded java.beans.PropertyChangeSupport from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.ChangeListenerMap from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.PropertyChangeSupport$PropertyChangeListenerMap from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.beans.PropertyChangeListener from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$LoggerContext from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$SystemLoggerContext from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$LogNode from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LoggingPermission from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded java.util.logging.LogManager$Cleaner from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded org.jboss.logmanager.LogManager$1 from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded org.jboss.logmanager.Level from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded java.util.logging.LoggingMXBean from C:\Develop\Java\jdk1.7.0_80\jre\lib\rt.jar]
[Loaded org.jboss.logmanager.Protectable from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
[Loaded org.jboss.logmanager.LogContext from jar:file:/C:/project/jboss-eap-6.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.4.Final-redhat-1.jar!/]
```
