### ISSUE TITLE
collecter's thread blocked

### ISSUE THREAD

**Issue by wahaha001** [naver/pinpoint#2102]
pinpoint version:1.5.2

i found many collecter's theads is blocked.

 **thread stack(jvisualvm dump):**

**"Pinpoint-UDP-Stat-Io(20-5)" - Thread t@272
   java.lang.Thread.State: BLOCKED
	at java.net.DatagramSocket.receive(DatagramSocket.java:712)
	- waiting to lock <1f0501a9> (a java.net.DatagramSocket) owned by "Pinpoint-UDP-Stat-Io(20-1)" t@268**
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.read0(UDPReceiver.java:200)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.receive(UDPReceiver.java:138)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.access$300(UDPReceiver.java:47)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$2.run(UDPReceiver.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- locked <1cdf7251> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**"Pinpoint-UDP-Stat-Io(20-4)" - Thread t@271
   java.lang.Thread.State: BLOCKED
	at java.net.DatagramSocket.receive(DatagramSocket.java:712)
	- waiting to lock <1f0501a9> (a java.net.DatagramSocket) owned by "Pinpoint-UDP-Stat-Io(20-1)" t@268**
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.read0(UDPReceiver.java:200)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.receive(UDPReceiver.java:138)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.access$300(UDPReceiver.java:47)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$2.run(UDPReceiver.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- locked <d93b085> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**"Pinpoint-UDP-Stat-Io(20-3)" - Thread t@270
   java.lang.Thread.State: BLOCKED
	at java.net.DatagramSocket.receive(DatagramSocket.java:712)
	- waiting to lock <1f0501a9> (a java.net.DatagramSocket) owned by "Pinpoint-UDP-Stat-Io(20-1)" t@268**
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.read0(UDPReceiver.java:200)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.receive(UDPReceiver.java:138)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.access$300(UDPReceiver.java:47)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$2.run(UDPReceiver.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- locked <771c2b0c> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**"Pinpoint-UDP-Stat-Io(20-2)" - Thread t@269
   java.lang.Thread.State: BLOCKED
	at java.net.DatagramSocket.receive(DatagramSocket.java:712)
	- waiting to lock <1f0501a9> (a java.net.DatagramSocket) owned by "Pinpoint-UDP-Stat-Io(20-1)" t@268**
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.read0(UDPReceiver.java:200)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.receive(UDPReceiver.java:138)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.access$300(UDPReceiver.java:47)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$2.run(UDPReceiver.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- locked <46df04d4> (a java.util.concurrent.ThreadPoolExecutor$Worker)

## except this thread is running, all of the other "Pinpoint-UDP-Stat-Io" thread is blocked!!
_"Pinpoint-UDP-Stat-Io(20-1)" - Thread t@268
   java.lang.Thread.State: RUNNABLE   
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)_
	- locked <7e828346> (a java.net.PlainDatagramSocketImpl)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:145)
	- locked <7e828346> (a java.net.PlainDatagramSocketImpl)
	at java.net.DatagramSocket.receive(DatagramSocket.java:786)
	- locked <57c37dc3> (a java.net.DatagramPacket)
	- locked <1f0501a9> (a java.net.DatagramSocket)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.read0(UDPReceiver.java:200)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.receive(UDPReceiver.java:138)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver.access$300(UDPReceiver.java:47)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$2.run(UDPReceiver.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- locked <6700aa37> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by koo-taejin** [comment]
Hi wahaha001.

The conclusion first, This is normal situation. 

Socket will continue to wait when there is no message(especially 'Pinpoint-UDP-Stat-Io' threads are receiving small messages). 
In this case, other threads  are blocked state.

thanks.

**Comment by wahaha001** [comment]
OK。。。thanks  :)
