### ISSUE TITLE
Failed to get region location org.apache.hadoop.hbase.TableNotFoundException

### ISSUE THREAD

**Issue by amitsanaye** [naver/pinpoint#2115]
I am getting following error in catalina.out

2016-10-04 13:06:21 [ERROR](o.a.h.h.c.AsyncProcess             :405) Failed to get region location
org.apache.hadoop.hbase.TableNotFoundException: Traces
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1404)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1199)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:395)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:344)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:238)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:190)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1495)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1086)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$8.doInTable(HbaseTemplate2.java:353)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.execute(HbaseTemplate2.java:766)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:350)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.asyncPut(HbaseTemplate2.java:400)
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDao.insert(HbaseTraceDao.java:94)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:84)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:121)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:100)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:45)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:207)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by emeroad** [comment]
Please check the HBase table.

**Comment by vserrao** [comment]
hi
 I'm also facing the same error.

**Comment by vserrao** [comment]
i created the table; the error is resolved

**Comment by shettypramith246** [comment]
Which table u created & any methodology followed to resolve the issue
