### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/tomcat/util/ExceptionUtils , how to solve this problem ?

### ISSUE THREAD

**Issue by magicdogs** [naver/pinpoint#2182]
evn: 
jdk1.8
pinpoint-agent:1.5.2
springboot 1.3.2
tomcat 8.0.33

when i had run my project jar file standalone , the server run  normal , no have 'NoClassDefFoundError' found in my log file .

when i had add the pinpoint-agent  to my jar file and run it ,  my server had broken down at a certain time  about  , and i had check log file  .  a lot of  those Error .  i don't know why ?   how to slove it ? thanks a lot .. 

2016-10-20 17:54:13 [DEBUG](c.n.p.p.t.i.StandardHostValveInvokeInterceptor:123) AFTER org.apache.catalina.core.StandardHostValve  args:(Request, Response) Caused:org/apache/tomcat/util/ExceptionUtils
java.lang.NoClassDefFoundError: org/apache/tomcat/util/ExceptionUtils
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
2016-10-20 17:54:13 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :147) Pinpoint-UdpSpanDataExecutor(14-0) is shutdown. discard data:TSpan(agentId:20161099, applicationName:market, agentStartTime:1476952876655, transactionId:00 01 EF CC 81 8A FE 2A C5 01, spanId:-6088734735818452950, startTime:1476957253037, elapsed:5, rpc:/marketing/api/activitys/op_act_thm_33161025/redeem, serviceType:1010,

**Comment by Xylus** [comment]
Hi @magicdogs 
How did you run your SpringBoot application with the pinpoint-agent?

**Comment by magicdogs** [comment]
@Xylus  i had run the command like this :
nohup java -jar -javaagent:/data/pinpoint/pinpoint-agent-1.5.2/pinpoint-bootstrap-1.5.2.jar -Dpinpoint.agentId=20161099 -Dpinpoint.applicationName=market  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/dump market.jar &

market.jar  use Maven buildding  with  springboot plugin
<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
</plugin>

**Comment by Xylus** [comment]
@magicdogs 
Sorry for the late reply,
The command you used should start the spring boot app just fine with the agent attached. Would it be possible for you to post the agent log file?
