### ISSUE TITLE
빌드후 start-collector.sh 실행시 아래와 같이 로그에 에러가 나면서 

### ISSUE THREAD

**Issue by jijoungsoo** [naver/pinpoint#2205]
빌드후 start-collector.sh 실행시 아래와 같이 로그에 에러가 나면서 
 start-collector.sh 가 180초가 지나 fail이 됩니다.

quickstart/bin/start-collector.sh

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spanHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.collector.dao.TraceDao com.navercorp.pinpoint.collector.handler.SpanHandler.traceDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Unknown TraceDao configuration : compatibilityMode
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Xylus** [comment]
@jijoungsoo 
안녕하세요,
quickstart collector 설정이 잘못 되어 있었습니다. `compatibilityMode`는 web 쪽 설정인데 collector 설정에 들어가 있었네요.
해당 이슈 수정해서 master에 merge 되었습니다.
코드 업데이트 하신 후에 빌드/실행 다시 한번 부탁드립니다.
감사합니다.
