### ISSUE TITLE
different classloader

### ISSUE THREAD

**Issue by yorkart** [naver/pinpoint#2230]
run pinpoint web in tomcat  with agent jvm parameter
-javaagent:/data/pinpoint-bootstrap-1.6.0-SNAPSHOT.jar
-Dpinpoint.agentId=31
-Dpinpoint.applicationName=web.local

catch some exceptions :
```
com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@7382f612 Cause:Cannot find suitable constructor for com.navercorp.pinpoint.plugin.mybatis.interceptor.SqlSessionOperationInterceptor
```
```
agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@7382f612 Cause:Cannot find suitable constructor for com.navercorp.pinpoint.plugin.spring.beans.interceptor.CreateBeanInstanceInterceptor
```

use remote debug to this method :
```
public class ProfilerPluginArgumentProvider implements ArgumentProvider {
 public Option get(int index, Class<?> type, Annotation[] annotations) {
        if (type == Trace.class) {
            return Option.withValue(pluginContext.getTraceContext().currentTraceObject());
        } else if (type == TraceContext.class) {
            return Option.withValue(pluginContext.getTraceContext());
        } else if (type == Instrumentor.class) {
            final InstrumentorDelegate delegate = new InstrumentorDelegate(pluginContext);
            return Option.withValue(delegate);
        } else if (type == InterceptorScope.class) {
            Name annotation = TypeUtils.findAnnotation(annotations, Name.class);
            
            if (annotation == null) {
                return Option.empty();
            }
            
            InterceptorScope scope = pluginContext.getInterceptorScope(annotation.value());
            
            if (scope == null) {
                throw new PinpointException("No such Scope: " + annotation.value());
            }
            
            return Option.withValue(scope);
        }
        
        return Option.empty();
    }
}
```
found different classloader
type  classloader is null
TraceContext.class classloader is WebappClassLoader

**Comment by emeroad** [comment]
Hi yorkart.
We need detailed error information.
  - jvm version
  - was version
  - stack trace

**Comment by yorkart** [comment]
jvm 1.8
tomcat 1.8

```
2016-11-07 08:55:30 [DEBUG](c.n.p.p.i.JavassistClassPool       :139) getContextClassPool() className=org.springframework.web.servlet.FrameworkServlet
2016-11-07 08:55:30 [DEBUG](c.n.p.p.u.JavaAssistUtils          :540) 
0  start_pc:0  index:0  name:this  nameIndex:249
1  start_pc:0  index:1  name:request  nameIndex:353
2  start_pc:0  index:2  name:response  nameIndex:355
2016-11-07 08:55:30 [DEBUG](c.n.p.p.i.URLClassLoaderHandler    :81 ) add Jar:file:/data/pinpoint/plugin/pinpoint-spring-plugin-1.6.0-SNAPSHOT.jar
2016-11-07 08:55:30 [DEBUG](c.n.p.p.o.OrderedValueProvider     :70 ) argument miss match index:0, type:interface com.navercorp.pinpoint.bootstrap.context.TraceContext value:SPRING typeCl:Pa
rallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@3232a28a
, valueCl:null
2016-11-07 08:55:30 [DEBUG](c.n.p.p.o.OrderedValueProvider     :70 ) argument miss match index:0, type:interface com.navercorp.pinpoint.bootstrap.context.TraceContext value:SPRING typeCl:Pa
rallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@3232a28a
, valueCl:null
2016-11-07 08:55:30 [ERROR](.p.p.ClassFileTransformerDispatcher:126) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:Par
allelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@3232a28a
 ctxCl:ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@3232a28a
 agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@7382f612 Cause:Cannot find suitable constructor for com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor
com.navercorp.pinpoint.exception.PinpointException: Cannot find suitable constructor for com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor
        at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:68)
        at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:56)
        at com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.getInterceptor(AnnotatedInterceptorFactory.java:101)
        at com.navercorp.pinpoint.profiler.instrument.JavassistMethod.createInterceptor(JavassistMethod.java:281)
        at com.navercorp.pinpoint.profiler.instrument.JavassistMethod.addInterceptor0(JavassistMethod.java:265)
        at com.navercorp.pinpoint.profiler.instrument.JavassistMethod.addInterceptor(JavassistMethod.java:131)
        at com.navercorp.pinpoint.plugin.spring.web.SpringWebMvcPlugin$1.doInTransform(SpringWebMvcPlugin.java:50)
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2241)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:802)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1243)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1108)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2241)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:802)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1243)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1108)
        at org.apache.catalina.util.Introspection.loadClass(Introspection.java:153)
        at org.apache.catalina.startup.WebAnnotationSet.loadApplicationServletAnnotations(WebAnnotationSet.java:129)
        at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:66)
        at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:327)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:774)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:298)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5075)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by yorkart** [comment]
before tomcat bootstrap ```ProfilerPluginArgumentProvider``` work fine .  
after bootstrap , the ```Interceptor``` constructor is failed.

I have a question that has not been verified. tomcat uses the custom classloader to load webapp .
why main method has invoke , the agent still can work.  Is modify the behavior of the tomcat's classloader ?

**Comment by jaehong-kim** [comment]
Please retry to the latest(today) version.

**Comment by ofauchon** [comment]
Hi. could you please confirm us if the problem is fixed in latest version, or not  ?
