### ISSUE TITLE
BUILD Failed - Failed to execute goal on project pinpoint-jboss-plugin:

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2253]
Hi All,

I just downloaded the pinpoint version-1.6.0-RC1 and also installed the following JDK's as per the Build requirement

a)JDK6
b)JDK7
c)JDk8

Apache Maven Version:
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: /Users/z0025g0/Downloads/apache-maven-3.3.9
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

However when i try to build the pinpoint using maven i could succesfully build couple of files, however it fails at the end when tried to build JBOSS Plugin

[INFO] pinpoint-cxf-plugin ................................ SUCCESS [  2.138 s]
[INFO] pinpoint-hystrix-plugin ............................ SUCCESS [  0.790 s]
[INFO] pinpoint-jboss-plugin .............................. FAILURE [ 10.195 s]
[INFO] pinpoint-plugins ................................... SKIPPED
[INFO] pinpoint-bootstrap-core-optional ................... SKIPPED
[INFO] pinpoint-tools ..................................... SKIPPED
[INFO] pinpoint-agent-distribution ........................ SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-profiler-optional-jdk8 .................... SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-thirdparty ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2016-11-14T17:52:15+05:30
[INFO] Final Memory: 113M/1499M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project pinpoint-jboss-plugin: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-jboss-plugin:jar:1.6.0-RC1: Failed to collect dependencies at org.jboss.as:jboss-as-security:jar:7.2.0.Final -> org.jboss.as:jboss-as-clustering-infinispan:jar:7.2.0.Final -> org.jboss.as:jboss-as-ee:jar:7.2.0.Final -> org.jboss.metadata:jboss-metadata-ear:jar:7.0.8.Final -> org.jboss.metadata:jboss-metadata-common:jar:7.0.8.Final -> sun-jaxb:jaxb-api:jar:2.1.4: Failed to read artifact descriptor for sun-jaxb:jaxb-api:jar:2.1.4: Could not transfer artifact sun-jaxb:jaxb-api:pom:2.1.4 from/to cloudera (https://repository.cloudera.com/artifactory/cloudera-repos/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project pinpoint-jboss-plugin: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-jboss-plugin:jar:1.6.0-RC1: Failed to collect dependencies at org.jboss.as:jboss-as-security:jar:7.2.0.Final -> org.jboss.as:jboss-as-clustering-infinispan:jar:7.2.0.Final -> org.jboss.as:jboss-as-ee:jar:7.2.0.Final -> org.jboss.metadata:jboss-metadata-ear:jar:7.0.8.Final -> org.jboss.metadata:jboss-metadata-common:jar:7.0.8.Final -> sun-jaxb:jaxb-api:jar:2.1.4
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-jboss-plugin:jar:1.6.0-RC1: Failed to collect dependencies at org.jboss.as:jboss-as-security:jar:7.2.0.Final -> org.jboss.as:jboss-as-clustering-infinispan:jar:7.2.0.Final -> org.jboss.as:jboss-as-ee:jar:7.2.0.Final -> org.jboss.metadata:jboss-metadata-ear:jar:7.0.8.Final -> org.jboss.metadata:jboss-metadata-common:jar:7.0.8.Final -> sun-jaxb:jaxb-api:jar:2.1.4
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.jboss.as:jboss-as-security:jar:7.2.0.Final -> org.jboss.as:jboss-as-clustering-infinispan:jar:7.2.0.Final -> org.jboss.as:jboss-as-ee:jar:7.2.0.Final -> org.jboss.metadata:jboss-metadata-ear:jar:7.0.8.Final -> org.jboss.metadata:jboss-metadata-common:jar:7.0.8.Final -> sun-jaxb:jaxb-api:jar:2.1.4

Looks like some issue while downloading or it referring to different path while tried to download the JBOSS related files from the source

Could you please help me here on what peice that I am missing here 

Appreciate your quick response on the same 

Error Description:

[ERROR] Failed to execute goal on project pinpoint-jboss-plugin: Could not resolve dependencies for project com.navercorp.pinpoint:pinpoint-jboss-plugin:jar:1.6.0-RC1: Failed to collect dependencies at org.jboss.as:jboss-as-security:jar:7.2.0.Final -> org.jboss.as:jboss-as-clustering-infinispan:jar:7.2.0.Final -> org.jboss.as:jboss-as-ee:jar:7.2.0.Final -> org.jboss.metadata:jboss-metadata-ear:jar:7.0.8.Final -> org.jboss.metadata:jboss-metadata-common:jar:7.0.8.Final -> sun-jaxb:jaxb-api:jar:2.1.4: Failed to read artifact descriptor for sun-jaxb:jaxb-api:jar:2.1.4: Could not transfer artifact sun-jaxb:jaxb-api:pom:2.1.4 from/to cloudera (https://repository.cloudera.com/artifactory/cloudera-repos/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

**Comment by dinesh4747** [comment]
Also i have made the common java home end point as JDK1.7 JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/

Kindly let me know if you require any further information regarding the same

**Comment by Xylus** [comment]
Hi @dinesh4747 
Looks like an issue with ssl certificate.
Could you try changing `https://repository.cloudera.com/artifactory/cloudera-repos/` to `http://repository.cloudera.com/artifactory/cloudera-repos/` and give it a try? (https -> http)

**Comment by dinesh4747** [comment]
Hi Xylus,

Thanks for your valuable guidance i started working for me
