### ISSUE TITLE
collector run error

### ISSUE THREAD

**Issue by xingkaihu** [naver/pinpoint#2276]
11-21 19:16:17 [WARN ](c.n.p.c.h.AgentStatHandler         :61) AgentStat handle error. Caused:Failed 1 action: ConnectException: 1 time, ; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: ConnectException: 1 time, 
11-21 19:16:27 [ERROR](o.a.h.h.c.AsyncProcess             :379) Failed to get region location 
org.apache.hadoop.hbase.ipc.FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:52205
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:695)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:881)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:850)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1174)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:216)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:300)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:31727)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.getRowOrBefore(ProtobufUtil.java:1580)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1294)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1126)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:369)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:320)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:206)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:183)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1482)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1095)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2$8.doInTable(HbaseTemplate2.java:299)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.execute(HbaseTemplate.java:58)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:296)
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseAgentStatDao.insert(HbaseAgentStatDao.java:65)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handleAgentStat(AgentStatHandler.java:59)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handleAgentStatBatch(AgentStatHandler.java:72)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handle(AgentStatHandler.java:49)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:65)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:121)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:100)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:45)
        at com.navercorp.pinpoint.collector.receiver.udp.TimingWrap.run(TimingWrap.java:43)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:183)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
11-21 19:16:27 [WARN ](c.n.p.c.h.AgentStatHandler         :61) AgentStat handle error. Caused:Failed 1 action: FailedServerException: 1 time, ; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 1 action: FailedServerException: 1 time, 
^C

**Comment by Xylus** [comment]
Looks like an hbase error. Please check your hbase setup and connections.
