### ISSUE TITLE
Pinpoint shows a header you provided implies functionality that is not implemented. (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: )

### ISSUE THREAD

**Issue by irocks04** [naver/pinpoint#2298]
#### Description

I see an issue wherein it conflicts with the application and the application images fail to load.
Works absolutely fine when the agent is removed. Thumnails get loaded.
#### Environment

* Pinpoint version: 1.5.2 /1.6
* Java micro service
* Additional details (e.g. how your collector/web is set up):

I am using pinpoint 1.5.2 version for both web and collector and used 1.6 version for web.
The agent was also tried with both 1.5.2 and with 1.6
It shows thumnail not found and in the logs i see the message functionality not implemented. So somewhere its creating a conflict.

**Comment by irocks04** [comment]
![image](https://cloud.githubusercontent.com/assets/20955417/20829556/95460900-b8a2-11e6-84af-9301ecfb17d7.png)

**Comment by irocks04** [comment]
Exception in the log

ERROR [2016-12-02 18:33:23] [d467a985-6587-4475-9fd0-4d76fd0b62cf] r.c.c.i.i.o.ObjectStoreIOps: Exception while getting file object. Error Message: A header you provided implies functionality that is not implemented. (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: ),HTTP Status Code: 501,AWS
Error Code: NotImplemented,Error Type: Service,Request ID:
ERROR [2016-12-02 18:33:23] [d467a985-6587-4475-9fd0-4d76fd0b62cf] r.c.c.r.CabinetResource: api=getFile
com.amazonaws.services.s3.model.AmazonS3Exception: A header you provided implies functionality that is not implemented. (Service: Amazon S3; Status Code: 501; Error Code: NotImplemented; Request ID: )
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1032) ~[aws-java-sdk-core-1.9.0.jar:na]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:687) ~[aws-java-sdk-core-1.9.0.jar:na]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441) ~[aws-java-sdk-core-1.9.0.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292) ~[aws-java-sdk-core-1.9.0.jar:na]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3655) ~[aws-java-sdk-s3-1.9.0.jar:na]
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1132) ~[aws-java-sdk-s3-1.9.0.jar:na]
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1004) ~[aws-java-sdk-s3-1.9.0.jar:na]
        at realdoc.core.cabinet.io.impl.operations.ObjectStoreIOps.getFileInputStream(ObjectStoreIOps.java:71) ~[cabinet.jar:2.12.4]
        at realdoc.core.cabinet.io.impl.operations.VCSIOps.getFileInputStream(VCSIOps.java:27) ~[cabinet.jar:2.12.4]
        at realdoc.core.cabinet.service.CabinetFilesService.getFileInputStream(CabinetFilesService.java:162) ~[cabinet.jar:2.12.4]
        at realdoc.core.cabinet.service.CabinetFilesService$$FastClassBySpringCGLIB$$976e210c.invoke(<generated>) ~[cabinet.jar:2.12.4]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
        at realdoc.core.cabinet.service.CabinetFilesService$$EnhancerBySpringCGLIB$$c73016a0.getFileInputStream(<generated>) ~[cabinet.jar:2.12.4]
        at realdoc.core.cabinet.resources.CabinetResource.getFile(CabinetResource.java:181) ~[cabinet.jar:2.12.4]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.21.jar:na]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.21.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.21.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.21.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.21.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.21.jar:na]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.22.1.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) [jersey-container-servlet-core-2.22.1.jar:na]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) [jersey-container-servlet-core-2.22.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) [jersey-container-servlet-core-2.22.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) [jersey-container-servlet-core-2.22.1.jar:na]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) [jersey-container-servlet-core-2.22.1.jar:na]
        at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [dropwizard-jetty-0.9.3.jar:0.9.3]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365) [jetty-servlets-9.2.17.v20160517.jar:9.2.17.v20160517]
        at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:132) [dropwizard-jetty-0.9.3.jar:0.9.3]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [dropwizard-servlets-0.9.3.jar:0.9.3]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:43) [dropwizard-jersey-0.9.3.jar:0.9.3]
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:38) [dropwizard-jersey-0.9.3.jar:0.9.3]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at realdoc.ghost.GhostFilter.doFilter(GhostFilter.java:70) [realdoc-ghost-2.11.0.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:257) [jetty-servlets-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:220) [jetty-servlets-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [metrics-jetty9-3.1.2.jar:3.1.2]
        at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dropwizard-jetty-0.9.3.jar:0.9.3]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [jetty-io-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.17.v20160517.jar:9.2.17.v20160517]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.17.v20160517.jar:9.2.17.v20160517]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by Xylus** [comment]
Not sure why s3's rejecting your HTTP calls...does s3 block http calls made with unknown http headers? If so, this might be why as pinpoint adds custom headers to propagate trace over RPC.

**Comment by Xylus** [comment]
@irocks04 Could you also paste the response you get when making the call to S3?

**Comment by irocks04** [comment]
Response doesn't say much its just 
"{"code":"INTERNAL_SERVER_ERROR","realdocRequestId":"b4d271ad-7f66-4a83-a9e1-cadc90c38450","message":"Exception occurred while invoking Cabinet service"}".

Cabinet is the one which calls storage and we are using amazon s3 client and amazon sdk. 

Is there a way we can remove the custom headers sent from poinpoint? I'll do that only for this agent and for the rest of the agents set up across different servers it works absolutely fine.

**Comment by Xylus** [comment]
I was going to ask you to disable the plugin for the http client library wrapped by the `AmazonHttpClient` (which I think is Apache HttpClient, but you'll have to check and make sure), but realized there isn't an option to disable it via editing *pinpoint.config*.

You could simply delete `pinpoint-httpclient3-plugin-$VERSION.jar` or `pinpoint-httpclient4-plugin-$VERSION.jar` from *$PINPOINT_AGENT/plugin* directory and give it a go.
Let us know how it works out.

**Comment by irocks04** [comment]
Thank you . this is awesome. worked fine.
