### ISSUE TITLE
May be ClassLoader problem while transforming provider class, please help

### ISSUE THREAD

**Issue by DevotedTangLiu** [naver/pinpoint#2307]
#### Description
I tried to transform provider class, where is the process class of the RPC server. But it doesn't work. I look into agent logs and found errors as follows. Please help, thanks.

#### Environment

* Pinpoint version: 1.6.0-SNAPSHOT

#### Additional Info

```
2016-12-08 15:04:21 [DEBUG](.p.p.ClassFileTransformerDispatcher:109) [transform] classLoader:com.isuwang.dapeng.bootstrap.classloader.ShareClassLoader@7fe8ea47 className:com.isuwang.dapeng.core.SoaBaseProcessor transformer:com.navercorp.pinpoint.profiler.plugin.MatchableC
lassFileTransformerGuardDelegate
2016-12-08 15:04:21 [ERROR](.p.p.ClassFileTransformerDispatcher:126) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:com.isuwang.dapeng.bootstrap.classloader.ShareClassLoader@7fe8ea47 ctxCl:com.isuwang.d
apeng.bootstrap.classloader.AppClassLoader@68c9d179 agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@816f27d Cause:null
java.lang.NullPointerException
        at com.isuwang.dapeng.pinpoint.plugin.DapengPinpintPlugin$2.doInTransform(DapengPinpintPlugin.java:63)
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.isuwang.dapeng.bootstrap.classloader.AppClassLoader.loadClass(AppClassLoader.java:23)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springframework.core.type.StandardAnnotationMetadata.hasAnnotatedMethods(StandardAnnotationMetadata.java:135)
        at org.springframework.context.annotation.ConfigurationClassUtils.isLiteConfigurationCandidate(ConfigurationClassUtils.java:175)
        at org.springframework.context.annotation.ConfigurationClassUtils.checkConfigurationClassCandidate(ConfigurationClassUtils.java:114)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:282)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.isuwang.dapeng.container.spring.SpringContainer.start(SpringContainer.java:68)
        at com.isuwang.dapeng.container.ContainerStartup$$Lambda$14/2109798150.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.isuwang.dapeng.container.ContainerStartup.startup(ContainerStartup.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.isuwang.dapeng.bootstrap.Bootstrap.startup(Bootstrap.java:71)
        at com.isuwang.dapeng.bootstrap.Bootstrap.main(Bootstrap.java:46)
```

FYI, AppClassLoader work like this:
```
public class AppClassLoader extends URLClassLoader {

    public AppClassLoader(URL[] urls) {
        super(urls, ClassLoader.getSystemClassLoader());
    }

    @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {

        if (name.startsWith("com.isuwang.dapeng.core") || name.startsWith("com.isuwang.org.apache.thrift") || name.startsWith("com.isuwang.dapeng.transaction.api"))
            return ClassLoaderManager.shareClassLoader.loadClass(name);
        return super.loadClass(name, resolve);
    }
}
```

TransformCallBack as follows:
```
transformTemplate.transform("com.isuwang.dapeng.core.SoaBaseProcessor", new TransformCallback() {
            @Override
            public byte[] doInTransform(Instrumentor instrumentor, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws InstrumentException {
                InstrumentClass target = instrumentor.getInstrumentClass(loader, className, classfileBuffer);

                target.getDeclaredMethod("process", "com.isuwang.org.apache.thrift.protocol.TProtocol", "com.isuwang.org.apache.thrift.TProtocol").addInterceptor("com.isuwang.dapeng.pinpoint.plugin.interceptor.DapengProviderInterceptor");

                return target.toBytecode();
            }
        });
```
line 63 is: 
```
                target.getDeclaredMethod("process", "com.isuwang.org.apache.thrift.protocol.TProtocol", "com.isuwang.org.apache.thrift.TProtocol").addInterceptor("com.isuwang.dapeng.pinpoint.plugin.interceptor.DapengProviderInterceptor");

```
Thank you again, please reply.

**Comment by DevotedTangLiu** [comment]
Hand on, i find out that i made an stupid mistake. I did not write the class name correctlly!!!!!!!

**Comment by DevotedTangLiu** [comment]
Yet a stupid mistake made, 
"com.isuwang.org.apache.thrift.protocol.TProtocol"  but not "com.isuwang.org.apache.thrift.TProtocol"

**Comment by DevotedTangLiu** [comment]
Thank you anyway
