### ISSUE TITLE
Service started will make HBase down immediately

### ISSUE THREAD

**Issue by linzhiqiang0514** [naver/pinpoint#2325]
#### Description

Update the 1.6.0 version, after the service is started, the program connected HBASE service, down immediately

#### Environment
HBase Version	0.98.4.2.2.0.0-2041-hadoop2, r18e3e58ae6ca5ef5e9c60e3129a1089a8656f91d	HBase version and revision
HBase Compiled	Wed Nov 19 15:10:28 EST 2014, jenkins	When HBase version was compiled and by whom
Hadoop Version	2.6.0.2.2.0.0-2041, r7d56f02902b436d46efba030651a2fbe7c1cf1e9	Hadoop version and revision
Hadoop Compiled	2014-11-19T19:42Z, jenkins	When Hadoop version was compiled and by whom
This is installed by Ambari.

Tomcat : 8.0.36

#### Additional Info

WEBAPP LOG:

Type 1:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionInfoServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.fact
ory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.web.dao.TraceDao com.navercorp.pinpoint.web.service.TransactionInfoServiceImpl.traceDao; nested exception is org.springframewor
k.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemExc
eption: Failed after attempts=36, exceptions:
Fri Dec 09 12:33:33 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68460: row 'Traces,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=crmtmon3.test.com,600
20,1470017421638, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Fri Dec 09 12:33:33 CST 2016, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68460: row 'Traces,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=crmtmon3.test.com,600
20,1470017421638, seqNum=0

        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Xylus** [comment]
Hi @linzhiqiang0514 
Have you created the 2 new hbase tables? 
You have to the following tables if you're upgrading from an existing Pinpoint installation - https://github.com/naver/pinpoint/releases/tag/1.6.0
```
AgentStatV2
TraceV2
```


You can find the relevant hbase scripts [here](https://github.com/naver/pinpoint/blob/master/hbase/scripts/hbase-create.hbase) (non-snappy), or [here](https://github.com/naver/pinpoint/blob/master/hbase/scripts/hbase-create-snappy.hbase) (snappy).
