### ISSUE TITLE
Unable to connect Agent JVM machine to Collector Box 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2352]
Please find below the server log generated in catalina.out file where seems like connection is refused when i tried to connect from agent to collector box via 9994/tcp port

java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:208)
	at org.apache.catalina.startup.Catalina.stopServer(Catalina.java:476)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.startup.Bootstrap.stopServer(Bootstrap.java:408)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:497)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-12-15 05:54:29 [WARN ](c.n.p.r.u.ClientFactoryUtils       ) tcp connect fail. remote:/10.63.68.44:9994 try reconnect, retryCount:0
2016-12-15 05:54:29 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@d62a05c exceptionCaught() occurred. state:NONE. Caused:Connection refused: /10.63.68.44:9994
java.net.ConnectException: Connection refused: /10.63.68.44:9994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-12-15 05:54:29 [WARN ](c.n.p.r.u.ClientFactoryUtils       ) tcp connect fail. remote:/10.63.68.44:9994 try reconnect, retryCount:1
2016-12-15 05:54:29 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@7574cada exceptionCaught() occurred. state:NONE. Caused:Connection refused: /10.63.68.44:9994
java.net.ConnectException: Connection refused: /10.63.68.44:9994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dinesh4747** [comment]
My Application is running on Tomcat-8.5.6

OS - Centos

**Comment by koo-taejin** [comment]
Please review the guidelines for contributing.

**Comment by dinesh4747** [comment]
Hi Koo -

I am not able to see the appropriate information which I am looking for 

Kindly let me know if I am missing something in the configuration or some basic stuff because of which i couldn't connect my Agent Machine to Collector

**Comment by koo-taejin** [comment]
I'm not talking about solving that issue.
We have guideline when you make new issue which reporting a bug or seeking help.
Please makes new issue by filling in [guideline for contributing](https://github.com/naver/pinpoint/blob/master/CONTRIBUTING.md).

**Comment by dinesh4747** [comment]
Agreed Koo - moving forward i will do that

Seems like my issue in configuration of collector properties I got the context from Issue (https://github.com/naver/pinpoint/issues/1967) 

Thanks - 
Dinesh
