### ISSUE TITLE
 Cause:Cannot find suitable constructor for com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor when trying to connect the Agent log file 

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2357]
Hi Pinpoint Team - 

when i tried connecting my tomcat process (Pinpoint agent enabled) to collector server which is sitting on different machine 

I am facing the issue in  Cause:Cannot find suitable constructor for com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor exception in the **pinpoint agent log file**

I could also successfully connect to other collector machine through port 9994 but it throws me the not suitable exception

Please find below the reference snippet of error stack we encountered in agent-pinpoint.log file

2016-12-15 10:08:49 [ERROR](.p.p.ClassFileTransformerDispatcher) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:ParallelWebappClassLoader^M
  context: pinpoint-web-1.6.0^M
  delegate: false^M
----------> Parent Classloader:^M
java.net.URLClassLoader@18a4d52b^M
 ctxCl:ParallelWebappClassLoader^M
  context: pinpoint-web-1.6.0^M
  delegate: false^M
----------> Parent Classloader:^M
java.net.URLClassLoader@18a4d52b^M
 agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@15a8cf03 Cause:Cannot find suitable constructor for com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor
com.navercorp.pinpoint.exception.PinpointException: Cannot find suitable constructor for com.navercorp.pinpoint.bootstrap.interceptor.BasicMethodInterceptor
        at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:68)
        at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:56)
        at com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.getInterceptor(AnnotatedInterceptorFactory.java:101)
        at com.navercorp.pinpoint.profiler.instrument.ASMMethod.createInterceptor(ASMMethod.java:257)
        at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:246)
        at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:115)
        at com.navercorp.pinpoint.plugin.spring.web.SpringWebMvcPlugin$1.doInTransform(SpringWebMvcPlugin.java:50)
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1254)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2268)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1254)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        at org.apache.catalina.util.Introspection.loadClass(Introspection.java:153)
        at org.apache.catalina.startup.WebAnnotationSet.loadApplicationServletAnnotations(WebAnnotationSet.java:129)
        at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:66)
        at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:328)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:778)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)

**Comment by Xylus** [comment]
Hi @dinesh4747 
Did you launch the collector with Pinpoint agent attached?
We don't support this yet (plus it wouldn't really trace anything), so if you did, please do not attach agent to the collector.
(Feel free to attach Pinpoint agent to anything else you'd like to trace including Pinpoint web, just not the collector)
