### ISSUE TITLE
Why does my stat.html page  is blank? 

### ISSUE THREAD

**Issue by adventurer2008** [naver/pinpoint#2387]
#### Description
In my main page, I have multi agents under pinpoint 1.6.0. But in stat.html page, there is blank.Why?
Under pinpoint 1.5.2.  It's normal.

#### Environment

* Pinpoint version:1.6.0
* OS, WAS, affected library, etc: CentOS 6.6
Web Server:Jboss4.0

#### Additional Info

![1](https://cloud.githubusercontent.com/assets/15321530/21413418/22ee363a-c832-11e6-83a8-06e0f071e9af.jpg)

![2](https://cloud.githubusercontent.com/assets/15321530/21413424/27fcd050-c832-11e6-8a21-4282be8415d6.jpg)

**Comment by Xylus** [comment]
Hi @adventurer2008 
Just tried out /stat.html with the latest build and it seemed to work okay.
Is everything else working alright? If so, could you copy the debug log when you invoke /stat.html and post it here so we can take a look?
Thanks

**Comment by adventurer2008** [comment]
Other functions is working ok.
The debug log is as below:

2016-12-26 09:48:46.762 DEBUG [org.apache.coyote.http11.Http11NioProtocol] Socket: [org.apache.tomcat.util.net.NioEndpoint$KeyAttachment@263d9dfd:org.apache.tomcat.util.net.NioChannel@1eff228:java.nio.channels.SocketChannel[connected local=/ XXXXXXXX:11080 remote=/10.100.61.90:17534]], Status in: [OPEN_READ], State out: [OPEN]
2016-12-26 09:48:46.821 DEBUG [org.apache.coyote.http11.InternalNioInputBuffer] Received [GET /components/bootstrap/dist/css/bootstrap.min.css?v=${buildTime} HTTP/1.1
Via: 1.1 ISASRV1
Cookie: _ga=GA1.1.1316832931.1478762909; _gat=1
Referer: http:// XXXXXXXX:11080/stat.html
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Host:  XXXXXXXX:11080
Accept: text/css,*/*;q=0.1
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6
Connection: Keep-Alive

]
2016-12-26 09:48:46.821 DEBUG [org.apache.coyote.http11.Http11NioProcessor] Error parsing HTTP request header
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:283)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
2016-12-26 09:48:46.822 DEBUG [org.apache.coyote.http11.Http11NioProtocol] Socket: [org.apache.tomcat.util.net.NioEndpoint$KeyAttachment@263d9dfd:org.apache.tomcat.util.net.NioChannel@1eff228:java.nio.channels.SocketChannel[connected local=/ XXXXXXXX:11080 remote=/10.100.61.90:17534]], Status in: [OPEN_READ], State out: [CLOSED]
2016-12-26 09:48:46.822 DEBUG [org.apache.tomcat.util.threads.LimitLatch] Counting down[catalina-exec-4] latch=4
2016-12-26 09:48:46.822 DEBUG [org.apache.tomcat.util.threads.LimitLatch] Counting up[http-nio-11080-Acceptor-1] latch=4
2016-12-26 09:48:46.822 DEBUG [org.apache.tomcat.util.threads.LimitLatch] Counting up[http-nio-11080-Acceptor-0] latch=5

**Comment by adventurer2008** [comment]
Hi, I've solve the problem. Acturally  tomcat 8.0.39 from apache website all has the error. it's because the jason data of stat.html cann't meet RFC 7230 and RFC 3986. So I changed other tomcat version and now it's ok.
