### ISSUE TITLE
MalformedURIException

### ISSUE THREAD

**Issue by niyuelin1990** [naver/pinpoint#2431]
log4j:ERROR Could not parse url [file:/D:/pinpoint/pinpoint-agent/lib/log4j.xml].
com.sun.org.apache.xerces.internal.util.URI$MalformedURIException: Path contains invalid character: 安
        at com.sun.org.apache.xerces.internal.util.URI.initializePath(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.URI.initialize(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.URI.<init>(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.URI.<init>(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.expandSystemIdStrictOff1(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.expandSystemId(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator$2.parse(DOMConfigurator.java:767)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:866)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:773)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:62)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:94)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:45)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:34)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:124)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:76)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:71)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:121)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
log4j:WARN No appenders could be found for logger (org.jboss.netty.channel.socket.nio.SelectorUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

when i start  tomcat, it will have this problem, so, how to resolve it?

**Comment by minwoo-jung** [comment]
You should read error message. 
**com.sun.org.apache.xerces.internal.util.URI$MalformedURIException: Path contains invalid character: 安**

**Comment by niyuelin1990** [comment]
I use  the master code,  and run it , none update the code ,but has  this error.   And  i check  "log4j.xml" not has any worry
