### ISSUE TITLE
there are some errors when pinpoint running several weeks

### ISSUE THREAD

**Issue by sun008102** [naver/pinpoint#2435]
# #### Environment
Pinpoint version: 1.5.2
OS: cenos6.7
hadoop : hadoop-2.6.0-cdh5.8.0
hbase:hbase-1.2.0-cdh5.8.0
zookeeper:zookeeper-3.4.5-cdh5.8.0

# #### Question Description
there are some errors when pinpoint running several weeks。
The phenomenon of performance is all tables can't be scan,and error is "ERROR: connection refused ",
then I restart hadoop and hbase ,there are some errors in hbase-master.log and namenode.log.

after this,I restart hadoop and hbase again,then another errors in appearance。

I need help! Thanks very much!

All errors are as follows：

# **(1) hbase-master.log**
# **first restart error logs:** 
EventThread] coordination.SplitLogManagerCoordination: task /hbase/splitWAL/RESCAN0000081539 entered state: DONE hortonworks,60000,1482113386129
2017-01-04 14:25:48,180 WARN  [hortonworks,60000,1482113386129_ChoreService_2] master.CatalogJanitor: Failed scan of catalog table
org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=351, exceptions:
Wed Jan 04 14:25:48 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68123: row '' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hortonworks,16201,1482113386126, seqNum=0

        at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.throwEnrichedException(RpcRetryingCallerWithReadReplicas.java:276)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:207)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
        at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:320)
        at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:295)
        at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:160)
        at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:155)
        at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:867)
        at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:193)
        at org.apache.hadoop.hbase.client.MetaScanner.metaScan(MetaScanner.java:89)
        at org.apache.hadoop.hbase.master.CatalogJanitor.getMergedRegionsAndSplitParents(CatalogJanitor.java:172)
        at org.apache.hadoop.hbase.master.CatalogJanitor.getMergedRegionsAndSplitParents(CatalogJanitor.java:124)
        at org.apache.hadoop.hbase.master.CatalogJanitor.scan(CatalogJanitor.java:225)
        at org.apache.hadoop.hbase.master.CatalogJanitor.chore(CatalogJanitor.java:106)
        at org.apache.hadoop.hbase.ScheduledChore.run(ScheduledChore.java:185)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at org.apache.hadoop.hbase.JitterScheduledThreadPoolExecutorImpl$JitteredRunnableScheduledFuture.run(JitterScheduledThreadPoolExecutorImpl.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68123: row '' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hortonworks,16201,1482113386126, seqNum=0
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
        ... 3 more

# **second restart error logs:**
2017-01-04 15:45:28,089 WARN  [ProcedureExecutor-0] master.SplitLogManager: error while splitting logs in [hdfs://10.4.55.175:8020/hbase/WALs/hortonworks,16201,1482113386126-splitting] installed = 3 but only 0 done
2017-01-04 15:45:28,089 WARN  [ProcedureExecutor-0] procedure.ServerCrashProcedure: Failed serverName=hortonworks,16201,1482113386126, state=SERVER_CRASH_SPLIT_LOGS; retry
java.io.IOException: error or interrupted while splitting logs in [hdfs://10.4.55.175:8020/hbase/WALs/hortonworks,16201,1482113386126-splitting] Task = installed = 3 done = 0 error = 3
        at org.apache.hadoop.hbase.master.SplitLogManager.splitLogDistributed(SplitLogManager.java:291)
        at org.apache.hadoop.hbase.master.MasterFileSystem.splitLog(MasterFileSystem.java:400)
        at org.apache.hadoop.hbase.master.MasterFileSystem.splitLog(MasterFileSystem.java:373)
        at org.apache.hadoop.hbase.master.MasterFileSystem.splitLog(MasterFileSystem.java:295)
        at org.apache.hadoop.hbase.master.procedure.ServerCrashProcedure.splitLogs(ServerCrashProcedure.java:435)
        at org.apache.hadoop.hbase.master.procedure.ServerCrashProcedure.executeFromState(ServerCrashProcedure.java:248)
        at org.apache.hadoop.hbase.master.procedure.ServerCrashProcedure.executeFromState(ServerCrashProcedure.java:73)
        at org.apache.hadoop.hbase.procedure2.StateMachineProcedure.execute(StateMachineProcedure.java:119)
        at org.apache.hadoop.hbase.procedure2.Procedure.doExecute(Procedure.java:498)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execProcedure(ProcedureExecutor.java:1061)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:856)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.execLoop(ProcedureExecutor.java:809)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor.access$400(ProcedureExecutor.java:75)
        at org.apache.hadoop.hbase.procedure2.ProcedureExecutor$2.run(ProcedureExecutor.java:495)
2017-01-04 15:45:28,365 INFO  [ProcedureExecutor-1] master.SplitLogManager: dead splitlog workers [hortonworks,16201,1482113386126]

# **(2) namenode log**
15:42:55,154 INFO org.apache.hadoop.ipc.Server: IPC Server handler 3 on 8020, call org.apache.hadoop.hdfs.protocol.ClientProtocol.addBlock from 10.4.55.175:48732 Call#1560729 Retry#0
java.io.IOException: File /hbase/data/default/SqlMetaData_Ver2/632a19ab4bc3289ddf9aa5c07521be20/.tmp/41ce37069a6546b88112092d8f60e785 could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1610)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3315)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:679)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:214)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:489)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2086)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2082)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2080)
2017-01-03 15:42:55,628 INFO BlockStateChange: BLOCK* addToInvalidates: blk_1073795418_54594 10.4.55.175:50010

**Comment by minwoo-jung** [comment]
Maybe this exception is inside problem in hbase. 
Unfortunately You shold inquire hbase Q&A then asking us.

In my experience, see log message... It seem to not execute replication and split in hbase. 
```
java.io.IOException: error or interrupted while splitting logs 


File /hbase/data/default/SqlMetaData_Ver2/632a19ab4bc3289ddf9aa5c07521be20/.tmp/41ce37069a6546b88112092d8f60e785 could only be replicated to 0 nodes instead of minReplication (=1). There are 1 datanode(s) running and no node(s) are excluded in this operation.
```

**Comment by jacarrichan** [comment]
@sun008102    do you  resolve  this  problem?

**Comment by sayed-moin-ahmed** [comment]
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=80312: row 'AgentInfo,,00000000000000' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=master,16201,1599034044323, seqNum=0
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:169)
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
        ... 3 more
Caused by: java.net.UnknownHostException: master
