### ISSUE TITLE
com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class

### ISSUE THREAD

**Issue by andyspan** [naver/pinpoint#2444]
#### Description
I'm working on developing a sample weblogic plugin for pinpoint，it can work in weblogic 10 but not weblogic 12c.

When reading logs, I can find many classloader / Interceptor errors (see above).

Do you know what is wrong ?

Thanks for your help.

#### Environment

* Pinpoint version:1.6.0
* OS, WAS, affected library, etc:Windows7
* Additional details (e.g. how your collector/web is set up):

#### Additional Info
`
2017-01-05 17:38:29 [WARN ](c.n.p.p.i.PlainClassLoaderHandler  ) Failed to load plugin class com.navercorp.pinpoint.plugin.weblogic.interceptor.ServletStubImplInterceptor with classLoader PolicyClassLoader 'weblogic-launcher' @4d95d2a2 {file:/C:/PROGRA~1/Java/JDK18~1.0_9/lib/tools.jar file:/C:/Oracle/MIDDLE~1/ORACLE~1/wlserver/server/lib/weblogic.jar ... (597 more)}
java.lang.RuntimeException: com.navercorp.pinpoint.plugin.weblogic.interceptor.ServletStubImplInterceptor
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.loadClass(PlainClassLoaderHandler.java:174)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:89)
	at com.navercorp.pinpoint.profiler.instrument.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:63)
	at com.navercorp.pinpoint.profiler.plugin.DefaultProfilerPluginContext.injectClass(DefaultProfilerPluginContext.java:176)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.resolveScopeInfo(ASMMethod.java:197)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:245)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:115)
	at com.navercorp.pinpoint.plugin.weblogic.WeblogicPlugin$1.doInTransform(WeblogicPlugin.java:47)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:839)
	at com.oracle.classloader.PolicyClassLoader.defineClass(PolicyClassLoader.java:515)
	at com.oracle.classloader.PolicyClassLoader.defineClass(PolicyClassLoader.java:495)
	at com.oracle.classloader.SearchPolicy.defineClass(SearchPolicy.java:115)
	at com.oracle.classloader.search.SearchCodeSources.loadClass(SearchCodeSources.java:174)
	at com.oracle.classloader.search.SearchSequence.loadClass(SearchSequence.java:126)
	at com.oracle.classloader.PolicyClassLoader$1.run(PolicyClassLoader.java:259)
	at com.oracle.classloader.PolicyClassLoader$1.run(PolicyClassLoader.java:257)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.oracle.classloader.PolicyClassLoader.loadClass(PolicyClassLoader.java:256)
	at com.oracle.classloader.weblogic.LaunchClassLoader.loadClass(LaunchClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at weblogic.servlet.internal.HttpServer.loadWebApp(HttpServer.java:474)
	at weblogic.servlet.internal.WebAppModule.registerWebApp(WebAppModule.java:1381)
	at weblogic.servlet.internal.WebAppModule.prepare(WebAppModule.java:806)
	at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:295)
	at weblogic.application.internal.ExtensibleModuleWrapper$PrepareStateChange.next(ExtensibleModuleWrapper.java:285)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.ExtensibleModuleWrapper.prepare(ExtensibleModuleWrapper.java:109)
	at weblogic.application.internal.flow.ModuleListenerInvoker.prepare(ModuleListenerInvoker.java:100)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:196)
	at weblogic.application.internal.flow.ModuleStateDriver$1.next(ModuleStateDriver.java:191)
	at weblogic.application.utils.StateMachineDriver$ParallelChange.run(StateMachineDriver.java:83)
	at weblogic.application.utils.StateMachineDriver.nextStateInParallel(StateMachineDriver.java:144)
	at weblogic.application.internal.flow.ModuleStateDriver.parallelPrepare(ModuleStateDriver.java:50)
	at weblogic.application.internal.flow.DeploymentCallbackFlow.prepare(DeploymentCallbackFlow.java:76)
	at weblogic.application.internal.flow.DeploymentCallbackFlow.prepare(DeploymentCallbackFlow.java:56)
	at weblogic.application.internal.BaseDeployment$1.next(BaseDeployment.java:730)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.BaseDeployment.prepare(BaseDeployment.java:242)
	at weblogic.application.internal.SingleModuleDeployment.prepare(SingleModuleDeployment.java:53)
	at weblogic.application.internal.DeploymentStateChecker.prepare(DeploymentStateChecker.java:158)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.prepare(AppContainerInvoker.java:61)
	at weblogic.deploy.internal.targetserver.AppDeployment.prepare(AppDeployment.java:158)
	at weblogic.management.deploy.internal.ConfiguredDeployments.deployPreStandbyInternalApps(ConfiguredDeployments.java:111)
	at weblogic.management.deploy.internal.DeploymentServerService.deployPreStandbyInternalApps(DeploymentServerService.java:209)
	at weblogic.management.deploy.internal.DeploymentPreStandbyServerService.start(DeploymentPreStandbyServerService.java:51)
	at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1262)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:332)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:762)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:643)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:348)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:333)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:54)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:617)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:397)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:346)
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.plugin.weblogic.interceptor.ServletStubImplInterceptor
	at com.oracle.classloader.PolicyClassLoader.loadClass(PolicyClassLoader.java:267)
	at com.oracle.classloader.weblogic.LaunchClassLoader.loadClass(LaunchClassLoader.java:62)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.loadClass(PlainClassLoaderHandler.java:168)
	... 75 more
`

**Comment by andyspan** [comment]
PolicyClassLoader ？Don’t support it？
