### ISSUE TITLE
PP1.6 Context initialization failed

### ISSUE THREAD

**Issue by zhanglc** [naver/pinpoint#2495]
run with hbase 1.2.4 single (no hdfs, within zookeeper) ,logs show the error as follow when start pp-web . 
```
2017-01-17 10:23:42 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adminServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.web.dao.stat.JvmGcDao com.navercorp.pinpoint.web.service.AdminServiceImpl.jvmGcDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jvmGcDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Tue Jan 17 10:23:42 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68349: row 'AgentStat,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=127.0.0.1,40692,1484590971754, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Tue Jan 17 10:23:42 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68349: row 'AgentStat,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=127.0.0.1,40692,1484590971754, seqNum=0

        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
```

**Comment by yangzdpssoft** [comment]
我也是这样

**Comment by yangzdpssoft** [comment]
这个问题解决了吗，求教

**Comment by bishenghua123** [comment]
解决了吗？是什么问题
