### ISSUE TITLE
Collector log throwing the exection- handleStreamRouteCreate failed. command:TCmdActiveThreadCount(), routeResult:NOT_SUPPORTED_REQUEST

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2542]
Hi Pinpoint Team - 

I could able to successfully connect from my Agent running in tomcat to Collector and all the necessary port were being opened 

9994 (tcp), 9995 and 9996 (udp) ports are opened and available public as well

From Agent to Collector sitting on different machine i could able to connect successfully but when i am running some test on the agent (Tomcat JVM Container) i couldn't see the data points in the Pinpoint Web UI

I found the below exception in collector log 

2017-01-27 09:43:09 [INFO ](c.n.p.c.c.r.f.LoggingFilter        :34 ) LoggingFilter doEvent StreamEvent{{remoteAddress=/192.168.100.14:29997,applicationName=GOA,agentId=10.65.72.228_JVM,startTimeStamp=1485509527778streamChannelContext=ServerStreamChannel[Channel:[id: 0xcaa9d64a, /192.168.100.14:42785 => /192.168.100.14:29997], StreamId:976, State:CONNECT_ARRIVED].streamChannelId=976requestObject=TCmdActiveThreadCount()}.
2017-01-27 09:43:09 [WARN ](c.n.p.c.c.ClusterPointRouter       :154) handleStreamRouteCreate failed. command:TCmdActiveThreadCount(), routeResult:NOT_SUPPORTED_REQUEST

**Comment by dinesh4747** [comment]
From the logs it is evident that "handleStreamRouteCreate failed" and the routeResult:NOT_SUPPORTED_REQUEST 

Also please find below the agent log where i am seeing the exception as "java.io.IOException: No route to host"

java.io.IOException: No route to host
        at java.net.PlainDatagramSocketImpl.send(Native Method)
        at java.net.DatagramSocket.send(DatagramSocket.java:693)
        at com.navercorp.pinpoint.profiler.sender.UdpDataSender.sendPacket(UdpDataSender.java:134)
        at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
        at java.lang.Thread.run(Thread.java:745)
2017-01-27 01:39:37 [INFO ](c.n.p.p.s.UdpDataSender            ) packet send error. size:345, TSpanChunk(agentId:10.65.72.228_JVM, applicationName:GOA, agentStartTime:1485334493022, serviceType:1010, tran
