### ISSUE TITLE
hbase java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by TimeStarRipple** [naver/pinpoint#2627]
#### Description

I installed hbase on a computer, it is the host name of the hbase . 
![image](https://cloud.githubusercontent.com/assets/12027412/23116960/52672554-f788-11e6-8c8f-8ef787663b4a.png)

And I installed collector on another computer. It can ping hbase
![image](https://cloud.githubusercontent.com/assets/12027412/23117027/9ed1363c-f788-11e6-833a-41d6f9612225.png)

But there are some errors when it is started. The pinpoint collector can't connected hbase
#### Environment

* Pinpoint version:1.6.0
* OS, WAS, affected library, etc:ubuntu14.04
* Additional details (e.g. how your collector/web is set up):hbase1.2.4

#### Additional Info

The following is the collector of logs
```
2017/2/20 下午3:21:53Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.collector.dao.TraceDao com.navercorp.pinpoint.collector.handler.SpanHandler.traceDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53
2017/2/20 下午3:21:53	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
2017/2/20 下午3:21:53	... 26 more
2017/2/20 下午3:21:53Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1525)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
2017/2/20 下午3:21:53	... 28 more
2017/2/20 下午3:21:53Caused by: com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53
2017/2/20 下午3:21:53	at com.navercorp.pinpoint.common.hbase.HBaseAdminTemplate.tableExists(HBaseAdminTemplate.java:61)
2017/2/20 下午3:21:53	at com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDaoFactory.getObject(HbaseTraceDaoFactory.java:54)
2017/2/20 下午3:21:53	at com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDaoFactory.getObject(HbaseTraceDaoFactory.java:18)
2017/2/20 下午3:21:53	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
2017/2/20 下午3:21:53	... 36 more
2017/2/20 下午3:21:53Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
2017/2/20 下午3:21:53Mon Feb 20 15:21:52 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.throwEnrichedException(RpcRetryingCallerWithReadReplicas.java:276)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:207)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:320)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:295)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:160)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:155)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:867)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:410)
2017/2/20 下午3:21:53	at com.navercorp.pinpoint.common.hbase.HBaseAdminTemplate.tableExists(HBaseAdminTemplate.java:59)
2017/2/20 下午3:21:53	... 39 more
2017/2/20 下午3:21:53Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68679: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase,33098,1487574090526, seqNum=0
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
2017/2/20 下午3:21:53	... 3 more
2017/2/20 下午3:21:53Caused by: java.net.ConnectException: Connection refused
2017/2/20 下午3:21:53	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2017/2/20 下午3:21:53	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
2017/2/20 下午3:21:53	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
2017/2/20 下午3:21:53	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
2017/2/20 下午3:21:53	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupConnection(RpcClientImpl.java:416)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:722)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:906)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:873)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1242)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:226)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:331)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallable.openScanner(ScannerCallable.java:394)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:203)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:64)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:360)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:334)
2017/2/20 下午3:21:53	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
2017/2/20 下午3:21:53	... 4 more
2017/2/20 下午3:21:5320-Feb-2017 15:21:53.167 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
2017/2/20 下午3:21:5520-Feb-2017 15:21:55.890 INFO [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [2,721] milliseconds.
2017/2/20 下午3:21:5520-Feb-2017 15:21:55.892 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
2017/2/20 下午3:21:5520-Feb-2017 15:21:55.929 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
2017/2/20 下午3:21:55 java.lang.Object.wait(Native Method)
2017/2/20 下午3:21:55 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
2017/2/20 下午3:21:55 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
2017/2/20 下午3:21:55 org.apache.hadoop.fs.FileSystem$Statistics$StatisticsDataReferenceCleaner.run(FileSystem.java:3093)
2017/2/20 下午3:21:55 java.lang.Thread.run(Thread.java:745)
2017/2/20 下午3:21:5520-Feb-2017 15:21:55.932 SEVERE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [org.apache.htrace.core.Tracer.ThreadLocalContext] (value [org.apache.htrace.core.Tracer$ThreadLocalContext@248913bd]) and a value of type [org.apache.htrace.core.Tracer.ThreadContext] (value [org.apache.htrace.core.Tracer$ThreadContext@14d65ef8]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
2017/2/20 下午3:21:5620-Feb-2017 15:21:56.534 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/ROOT has finished in 97,092 ms
2017/2/20 下午3:21:5620-Feb-2017 15:21:56.539 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [http-nio-9080]
2017/2/20 下午3:21:5620-Feb-2017 15:21:56.546 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler [ajp-nio-9009]
2017/2/20 下午3:21:5620-Feb-2017 15:21:56.557 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 99071 ms
```

**Comment by emeroad** [comment]
Sorry. Pinpoint team does not provide hbase technical support.

**Comment by TimeStarRipple** [comment]
Ok, Thanks
