### ISSUE TITLE
question about mvn integration-test error

### ISSUE THREAD

**Issue by MengZhi825** [naver/pinpoint#2643]
#### Description

i run mvn integration-test in pinpoint-plugin-sample error.  it  throws NoClassFoundException.

#####testRunFinished
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.206 sec <<< FAILURE! - in com.navercorp.pinpoint.plugin.sample.Sample_08_Interceptor_Annotations_IT
test[:child:-1](com.navercorp.pinpoint.plugin.sample.Sample_08_Interceptor_Annotations_IT)  Time elapsed: 0.005 sec  <<< ERROR!
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/plugin/test/PluginTestVerifierHolder
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1.evaluate(ForkedPinpointPluginTestRunner.java:59)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.runTests(ForkedPinpointPluginTest.java:128)
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.access$000(ForkedPinpointPluginTest.java:36)
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1.call(ForkedPinpointPluginTest.java:64)
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1.call(ForkedPinpointPluginTest.java:60)
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.executeTestCase(ForkedPinpointPluginTest.java:116)
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.main(ForkedPinpointPluginTest.java:69)
Caused by: com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.plugin.test.PluginTestVerifierHolder
        at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1.evaluate(ForkedPinpointPluginTestRunner.java:59)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

#### Environment

this is pom.xml in pinpoint-plugin-sample-agent.
<parent>
        <groupId>com.navercorp.pinpoint</groupId>
        <artifactId>plugin-sample</artifactId>
        <version>1.6.0-SNAPSHOT</version>
    </parent>
<properties>
        <distribution.directory>${project.build.directory}/pinpoint-agent</distribution.directory>
        <pinpoint.version>1.6.0</pinpoint.version>
    </properties>
<dependencies>
        <dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>pinpoint-profiler</artifactId>
            <version>${pinpoint.version}</version>
        </dependency>
        <dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>pinpoint-profiler-optional</artifactId>
            <type>pom</type>
            <version>${pinpoint.version}</version>
        </dependency>

        <dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>pinpoint-plugins</artifactId>
            <version>${pinpoint.version}</version>
            <type>pom</type>
            
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>plugin-sample-plugin</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>

        
        <dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>pinpoint-test</artifactId>
            <version>${pinpoint.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>plugin-sample-target</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

* Pinpoint version: 1.6.0-SNAPSHOT

**Comment by Xylus** [comment]
Hi @feiyangzhi 
Could you try changing the plugin-sample version to 1.6.0 and give it a try?

**Comment by feiyangzhi** [comment]
it still error.  and when i look into pinpoint project source code.  i find com/navercorp/pinpoint/bootstrap/plugin/test/PluginTestVerifierHolder not in project .

**Comment by Xylus** [comment]
Ah yes. it's been moved to pinpoint-test module.
I guess the dependency for plugin-samples should be updated to reflect this.
In the mean time, you could try adding the following dependency to plugin-samples :
```
<dependency>
    <groupId>com.navercorp.pinpoint</groupId>
    <artifactId>pinpoint-test</artifactId>
    <scope>test</scope>
</dependency>
```

**Comment by feiyangzhi** [comment]
Ah, the plugin-samples already has the pinpoint-test dependency.

**Comment by Xylus** [comment]
Oh you're right, the SNAPSHOT version you've got does have the dependency. Scratch out my last comment.

The pinpoint project source code does have `com/navercorp/pinpoint/bootstrap/plugin/test/PluginTestVerifierHolder` under `bootstrap-core`.
I wonder why it's not working.
Have you rebuilt everything after you've changed the plugin-samples version to match the pinpoint version you've built?

**Comment by feiyangzhi** [comment]
aha,  thinks, i follow your tips that change the plugin-samples version to 1.6.0 and then mvn clean install pinpoint project. and then every thing ok. thanks! but i found that i should add pinpoint-profiler-optional dependency type of pom which as follows:

<dependency>
            <groupId>com.navercorp.pinpoint</groupId>
            <artifactId>pinpoint-profiler-optional</artifactId>
            <type>pom</type>
            <version>${pinpoint.version}</version>
        </dependency>

**Comment by MengZhi825** [comment]
i follow your tips that  i change the plugin-samples version to 1.6.0 and then run mvn clean install pinpoint project.  when i run pinpoint-plugin-sample  test , i got the error as follows:
```

2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) pinpoint agentArgs:AGENT_TYPE=PLUGIN_TEST
2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) agentParameter :AGENT_TYPE=PLUGIN_TEST
2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) Agent original-path:D:\OpenSource\pinpoint-plugin-sample\agent\.\target\plugin-sample-agent-1.6.0-SNAPSHOT
2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) Agent canonical-path:D:\OpenSource\pinpoint-plugin-sample\agent\target\plugin-sample-agent-1.6.0-SNAPSHOT
2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) pinpoint-commons not found.
2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) found bootStrapCore. D:\OpenSource\pinpoint-plugin-sample\agent\target\plugin-sample-agent-1.6.0-SNAPSHOT\boot\pinpoint-bootstrap-core-1.6.0.jar
2017-02-24 20:44:38 [INFO ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) bootStrapCoreOptional not found.
2017-02-24 20:44:38 [WARN ](com.navercorp.pinpoint.bootstrap.AgentDirBaseClassPathResolver) pinpoint-commons-x.x.x(-SNAPSHOT).jar not found
2017-02-24 20:44:38 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointBootStrap) Agent Directory Verify fail. skipping agent loading.
*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
2017-02-24 20:44:38 [DEBUG ](com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest) child-runner lib:file:/C:/Users/zhimeng/.m2/repository/com/navercorp/pinpoint/plugin-sample-target/1.6.0-SNAPSHOT/plugin-sample-target-1.6.0-SNAPSHOT.jar
2017-02-24 20:44:38 [DEBUG ](com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest) child-runner lib:file:/D:/OpenSource/pinpoint-plugin-sample/agent/target/test-classes/
2017-02-24 20:44:38 [DEBUG ](com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest) testId::child:-1
#####testRunStarted
#####testStarted#####test[:child:-1](com.navercorp.pinpoint.plugin.sample.Sample_02_Injecting_Custom_Interceptor_IT)
#####testFailure#####test[:child:-1](com.navercorp.pinpoint.plugin.sample.Sample_02_Injecting_Custom_Interceptor_IT)#####java.lang.NoClassDefFoundError#####com/navercorp/pinpoint/bootstrap/plugin/test/PluginTestVerifierHolder#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1,evaluate,ForkedPinpointPluginTestRunner.java,59#####org.junit.runners.ParentRunner,runLeaf,ParentRunner.java,325#####org.junit.runners.BlockJUnit4ClassRunner,runChild,BlockJUnit4ClassRunner.java,78#####org.junit.runners.BlockJUnit4ClassRunner,runChild,BlockJUnit4ClassRunner.java,57#####org.junit.runners.ParentRunner$3,run,ParentRunner.java,290#####org.junit.runners.ParentRunner$1,schedule,ParentRunner.java,71#####org.junit.runners.ParentRunner,runChildren,ParentRunner.java,288#####org.junit.runners.ParentRunner,access$000,ParentRunner.java,58#####org.junit.runners.ParentRunner$2,evaluate,ParentRunner.java,268#####org.junit.runners.ParentRunner,run,ParentRunner.java,363#####org.junit.runner.JUnitCore,run,JUnitCore.java,137#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,runTests,ForkedPinpointPluginTest.java,128#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,access$000,ForkedPinpointPluginTest.java,36#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1,call,ForkedPinpointPluginTest.java,64#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1,call,ForkedPinpointPluginTest.java,60#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,executeTestCase,ForkedPinpointPluginTest.java,116#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,main,ForkedPinpointPluginTest.java,69#####$CAUSE$#####java.lang.ClassNotFoundException#####com.navercorp.pinpoint.bootstrap.plugin.test.PluginTestVerifierHolder#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1,evaluate,ForkedPinpointPluginTestRunner.java,59#####org.junit.runners.ParentRunner,runLeaf,ParentRunner.java,325#####org.junit.runners.BlockJUnit4ClassRunner,runChild,BlockJUnit4ClassRunner.java,78#####org.junit.runners.BlockJUnit4ClassRunner,runChild,BlockJUnit4ClassRunner.java,57#####org.junit.runners.ParentRunner$3,run,ParentRunner.java,290#####org.junit.runners.ParentRunner$1,schedule,ParentRunner.java,71#####org.junit.runners.ParentRunner,runChildren,ParentRunner.java,288#####org.junit.runners.ParentRunner,access$000,ParentRunner.java,58#####org.junit.runners.ParentRunner$2,evaluate,ParentRunner.java,268#####org.junit.runners.ParentRunner,run,ParentRunner.java,363#####org.junit.runner.JUnitCore,run,JUnitCore.java,137#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,runTests,ForkedPinpointPluginTest.java,128#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,access$000,ForkedPinpointPluginTest.java,36#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1,call,ForkedPinpointPluginTest.java,64#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1,call,ForkedPinpointPluginTest.java,60#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,executeTestCase,ForkedPinpointPluginTest.java,116#####com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest,main,ForkedPinpointPluginTest.java,69#####

com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/plugin/test/PluginTestVerifierHolder

	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1.evaluate(ForkedPinpointPluginTestRunner.java:59)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.runTests(ForkedPinpointPluginTest.java:128)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.access$000(ForkedPinpointPluginTest.java:36)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1.call(ForkedPinpointPluginTest.java:64)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1.call(ForkedPinpointPluginTest.java:60)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.executeTestCase(ForkedPinpointPluginTest.java:116)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.main(ForkedPinpointPluginTest.java:69)
Caused by: com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.plugin.test.PluginTestVerifierHolder
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1.evaluate(ForkedPinpointPluginTestRunner.java:59)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.runTests(ForkedPinpointPluginTest.java:128)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.access$000(ForkedPinpointPluginTest.java:36)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1.call(ForkedPinpointPluginTest.java:64)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest$1.call(ForkedPinpointPluginTest.java:60)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTest.executeTestCase(ForkedPinpointPluginTest.java:116)

```

i found it must the reason of not packing releated class into pinpoint-agent  boot/ dir. 
when i modify distribution.xml in pinpoint-sample-agent as follows:
```
 <dependencySet>
        <!--mengzhi825 modified.-->
        <includes>
            <include>com.navercorp.pinpoint:pinpoint-bootstrap-core</include>
            <include>com.navercorp.pinpoint:pinpoint-bootstrap-core-optional</include>
            <include>com.navercorp.pinpoint:pinpoint-commons</include>
        </includes>
        <outputDirectory>boot</outputDirectory>
    </dependencySet>
```

there is no error occur.

**Comment by Xylus** [comment]
Glad you solved it!
Looks like the plugin-samples project needs updating.
Thanks for working out the solution.
