### ISSUE TITLE
Running Hbase and Collector on a different machine wherein failed to connect due to com.navercorp.pinpoint.common.hbase.HbaseSystemException

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#2645]
Please find below configuration as follows

1) Running pinpoint collector on Separate Machine
2) Running Standalone Hbase on separate machine
3) 2181 port is opened up and collector--->Hbase connection established and works properly

However when i refer to the collector log there was some hbasesystem exception due to which Collector is not sending data to Hbase 

Exception trace as follows:

2017-02-24 04:43:24 [INFO ](c.n.p.c.h.PooledHTableFactory      ) create HConnectionThreadPoolExecutor poolSize:64, workerQueueMaxSize:5120
2017-02-24 04:43:24 [WARN ](o.a.h.u.NativeCodeLoader           ) Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-02-24 04:43:25 [INFO ](c.n.p.c.d.h.HbaseTraceDaoFactory   ) TraceDao Compatibility v2
2017-02-24 04:44:14 [WARN ](o.s.w.c.s.XmlWebApplicationContext ) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spanChunkHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.collector.dao.TraceDao com.navercorp.pinpoint.collector.handler.SpanChunkHandler.traceDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Fri Feb 24 04:44:14 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Fri Feb 24 04:44:14 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0

2017-02-24 04:44:14 [INFO ](c.n.p.c.h.HbaseTemplate2           ) HBaseTemplate2.destroy()
2017-02-24 04:44:14 [WARN ](c.n.p.c.h.HbaseTemplate2           ) count -1
2017-02-24 04:44:14 [INFO ](c.n.p.c.h.PooledHTableFactory      ) PooledHTableFactory.destroy()
2017-02-24 04:44:14 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spanChunkHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.navercorp.pinpoint.collector.dao.TraceDao com.navercorp.pinpoint.collector.handler.SpanChunkHandler.traceDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Fri Feb 24 04:44:14 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Fri Feb 24 04:44:14 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0

        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is com.navercorp.pinpoint.common.hbase.HbaseSystemException: Failed after attempts=36, exceptions:
Fri Feb 24 04:44:14 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0
; nested exception is org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Fri Feb 24 04:44:14 CST 2017, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0

Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68356: row 'TraceV2,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost.localdomain,50197,1487662358656, seqNum=0
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
        ... 3 more
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
        at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupConnection(RpcClientImpl.java:416)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:722)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:906)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:873)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1242)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:226)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:331)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
        at org.apache.hadoop.hbase.client.ScannerCallable.openScanner(ScannerCallable.java:394)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:203)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:64)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:360)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:334)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
        ... 4 more

**Comment by dinesh4747** [comment]
From the exception i see that some thing went wrong when table Tracev2  and AgentStatV2 were getting invoked 

However in my Hbase both the tables have been created and working fine

**Comment by dstrimble** [comment]
Is there a solution anywhere for this issue?

**Comment by wangshihui** [comment]
Hi @dinesh4747 
I meet same issue
please check your hbase version,if you use pinpoint 1.6.x ,Hbase ver 1.2.4 is OK,and 1.2.6 may not works fine.
and if use zookeeper inner hbase， hbase  is not in same host the collector deployed  also check   attribute  **cluster.zookeeper.address**  in conf file **pinpoint-collector.properties**,set it's value with the host name or ip addr in which the zookeeper deployed.
this works for me,and you can hava a try

**Comment by alphatan** [comment]
@wangshihui Thanks! You saved my life.
