### ISSUE TITLE
 Cannot find constructor with parameter types: [java.lang.String, int, java.util.Properties, java.lang.String, java.lang.String]

### ISSUE THREAD

**Issue by zvrr** [naver/pinpoint#2646]
pinpoint-agent 1.6
tomcat 8
jdk 1.7

please help.
```
agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@6cb0dffe Cause:com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find constructor with parameter types: [java.lang.String, int, java.util.Properties, java.lang.String, java.lang.String]
com.navercorp.pinpoint.exception.PinpointException: com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find constructor with parameter types: [java.lang.String, int, java.util.Properties, java.lang.String, java.lang.String]
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:72)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2479)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:883)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1303)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1180)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:400)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:187)
        at org.logicalcobwebs.proxool.DefaultConnectionBuilder.buildConnection(DefaultConnectionBuilder.java:39)
        at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:159)
        at org.logicalcobwebs.proxool.ConnectionPool.getConnection(ConnectionPool.java:217)
        at org.logicalcobwebs.proxool.ProxoolDriver.connect(ProxoolDriver.java:89)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:187)
        at com.coola.jutil.sql.DBEngine.getConnectionByProxool(DBEngine.java:793)
        at com.coola.jutil.sql.DBEngine.getConnection(DBEngine.java:688)
        at com.coola.jutil.sql.DBEngine.executeQuery(DBEngine.java:143)
        at com.zhenai.api.APISecretDaoImpl.get(APISecretDaoImpl.java:29)
        at com.zhenai.api.APISecretServiceImpl.getAPISecret(APISecretServiceImpl.java:157)
        at com.zhenai.api.APISecretServiceImpl.<init>(APISecretServiceImpl.java:22)
        at com.coola.core.user.server.UserServiceImpl.<init>(UserServiceImpl.java:44)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)
        at com.zhenai.server.HessianServlet.init(HessianServlet.java:191)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1241)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1154)
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:827)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:78)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1033)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:744)
Caused by: com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find constructor with parameter types: [java.lang.String, int, java.util.Properties, java.lang.String, java.lang.String]
        at com.navercorp.pinpoint.profiler.instrument.ASMClass.addInterceptor0(ASMClass.java:436)
        at com.navercorp.pinpoint.profiler.instrument.ASMClass.addInterceptor0(ASMClass.java:417)
        at com.navercorp.pinpoint.profiler.instrument.ASMClass.addInterceptor(ASMClass.java:313)
        at com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlPlugin$1.doInTransform(MySqlPlugin.java:75)
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
```

**Comment by chenguoxi1985** [comment]
Hi zvrr,

It looks like that pinpoint can not find the function/class to intercept. Maybe it's  caused by incorrect version. Can you check your JAVA_HOME configuration? Pinpoint requires to set Java6/7/8:

Requirements

In order to build Pinpoint, the following requirements must be met:

    JDK 6 installed (jdk1.6.0_45 recommended)
    JDK 7 installed (jdk1.7.0_80 recommended)
    JDK 8 installed
    Maven 3.2.x+ installed
    JAVA_6_HOME environment variable set to JDK 6 home directory.
    JAVA_7_HOME environment variable set to JDK 7 home directory.
    JAVA_8_HOME environment variable set to JDK 8 home directory.
