### ISSUE TITLE
collector error

### ISSUE THREAD

**Issue by kenu** [naver/pinpoint#265]
collector쪽 에러 로그입니다.
```
03-28 12:27:15 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:15 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:15 [WARN ](o.a.h.h.z.RecoverableZooKeeper     :219) Possibly transient ZooKeeper exception: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
03-28 12:27:15 [INFO ](o.a.h.h.u.RetryCounter             :53) Sleeping 8000ms before retry #3...
03-28 12:27:16 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server pinpoint/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:16 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:18 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:18 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:18 [WARN ](o.a.h.h.z.RecoverableZooKeeper     :219) Possibly transient ZooKeeper exception: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/root-region-server
03-28 12:27:18 [INFO ](o.a.h.h.u.RetryCounter             :53) Sleeping 8000ms before retry #3...
03-28 12:27:18 [WARN ](o.a.h.h.z.RecoverableZooKeeper     :219) Possibly transient ZooKeeper exception: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
03-28 12:27:18 [INFO ](o.a.h.h.u.RetryCounter             :53) Sleeping 8000ms before retry #3...
03-28 12:27:19 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server pinpoint/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:19 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:21 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:21 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:21 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server pinpoint/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:21 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:23 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:23 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:23 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server pinpoint/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:23 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:23 [WARN ](o.a.h.h.z.RecoverableZooKeeper     :219) Possibly transient ZooKeeper exception: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
03-28 12:27:23 [ERROR](o.a.h.h.z.RecoverableZooKeeper     :221) ZooKeeper exists failed after 3 retries
03-28 12:27:23 [WARN ](o.a.h.h.z.ZKUtil                   :453) hconnection-0x14c612d0a440013 Unable to set watcher on znode (/hbase)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:172)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:450)
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.checkIfBaseNodeAvailable(ZooKeeperNodeTracker.java:208)
        at org.apache.hadoop.hbase.zookeeper.RootRegionTracker.waitRootRegionLocation(RootRegionTracker.java:77)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:874)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:987)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:885)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:987)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:889)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:846)
        at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:270)
        at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:210)
        at org.apache.hadoop.hbase.client.HTableFactory.createHTableInterface(HTableFactory.java:36)
        at org.apache.hadoop.hbase.client.HTablePool.createHTable(HTablePool.java:265)
        at org.apache.hadoop.hbase.client.HTablePool.findOrCreateTable(HTablePool.java:195)
        at org.apache.hadoop.hbase.client.HTablePool.getTable(HTablePool.java:174)
        at org.apache.hadoop.hbase.client.HTablePool.getTable(HTablePool.java:213)
        at com.navercorp.pinpoint.common.hbase.PooledHTableFactory.createHTableInterface(PooledHTableFactory.java:47)
        at org.springframework.data.hadoop.hbase.HbaseUtils.getHTable(HbaseUtils.java:73)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.getTable(HbaseTemplate.java:75)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.execute(HbaseTemplate.java:54)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:345)
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseAgentStatDao.insert(HbaseAgentStatDao.java:76)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handleAgentStat(AgentStatHandler.java:59)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handleAgentStatBatch(AgentStatHandler.java:72)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handle(AgentStatHandler.java:49)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:64)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPReceiver$DispatchPacket.run(BaseUDPReceiver.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
03-28 12:27:23 [ERROR](o.a.h.h.z.ZooKeeperWatcher         :397) hconnection-0x14c612d0a440013 Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:172)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:450)
        at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.checkIfBaseNodeAvailable(ZooKeeperNodeTracker.java:208)
        at org.apache.hadoop.hbase.zookeeper.RootRegionTracker.waitRootRegionLocation(RootRegionTracker.java:77)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:874)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:987)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:885)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:987)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:889)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:846)
        at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:270)
        at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:210)
        at org.apache.hadoop.hbase.client.HTableFactory.createHTableInterface(HTableFactory.java:36)
        at org.apache.hadoop.hbase.client.HTablePool.createHTable(HTablePool.java:265)
        at org.apache.hadoop.hbase.client.HTablePool.findOrCreateTable(HTablePool.java:195)
        at org.apache.hadoop.hbase.client.HTablePool.getTable(HTablePool.java:174)
        at org.apache.hadoop.hbase.client.HTablePool.getTable(HTablePool.java:213)
        at com.navercorp.pinpoint.common.hbase.PooledHTableFactory.createHTableInterface(PooledHTableFactory.java:47)
        at org.springframework.data.hadoop.hbase.HbaseUtils.getHTable(HbaseUtils.java:73)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.getTable(HbaseTemplate.java:75)
        at org.springframework.data.hadoop.hbase.HbaseTemplate.execute(HbaseTemplate.java:54)
        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.put(HbaseTemplate2.java:345)
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseAgentStatDao.insert(HbaseAgentStatDao.java:76)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handleAgentStat(AgentStatHandler.java:59)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handleAgentStatBatch(AgentStatHandler.java:72)
        at com.navercorp.pinpoint.collector.handler.AgentStatHandler.handle(AgentStatHandler.java:49)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:64)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPReceiver$DispatchPacket.run(BaseUDPReceiver.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
03-28 12:27:23 [INFO ](o.a.h.h.c.HConnectionManager$HConnectionImplementation:1731) This client just lost it's session with ZooKeeper, will automatically reconnect when needed.
03-28 12:27:24 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:24 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
03-28 12:27:25 [INFO ](o.a.z.ClientCnxn                   :966) Opening socket connection to server pinpoint/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
03-28 12:27:25 [WARN ](o.a.z.ClientCnxn                   :1089) Session 0x14c612d0a440013 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
^C
[root@pinpoint pinpoint]# 
```

도움 부탁합니다.

**Comment by minwoo-jung** [comment]
안녕하세요~ 

로그를 봐서는 zookeeper 쪽에서 정상적으로 응답을 못주고 있는것같습니다. 
zookeeper 정상동작을 확인해보는게 좋을것같습니다.

**Comment by minwoo-jung** [comment]
@kenu 
해결 하셨나요?^^
