### ISSUE TITLE
NotFoundInstrumentException : Cannot find method executeQuery with parameter types: [java.lang.String] 

### ISSUE THREAD

**Issue by Anishkp** [naver/pinpoint#2695]
#### Description
Getting the following exception on the pinpoint-agent logs while connecting to pinpoint collector.  Agent version is 1.6.0. In the log folder of the agent the following exception is seen. I can see that all other details about the JVM (like GC, CPU etc) is getting registered in the collector. But it is only application transaction status that is failing and no transactions are getting registered. 

#### Exception details:

2017-03-13 02:57:34 [ERROR](.p.p.ClassFileTransformerDispatcher) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:org.springframework.boot.loader.LaunchedURLClassLoader@644baf4a ctxCl:org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$TcclSafeAggregatedClassLoader@1a23d23c agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@64cee07 Cause:com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find method executeQuery with parameter types: [java.lang.String]
com.navercorp.pinpoint.exception.PinpointException: com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find method executeQuery with parameter types: [java.lang.String]
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:72)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)

#### Environment

* Pinpoint version: 1.6.0
* OS: Linux
* Additional details (e.g. how your collector/web is set up):
Collector and HBase set on the same machine remotely.

**Comment by emeroad** [comment]
It looks like a problem with hibernate classloaer.
 - Could you make a regression test case?
 - What is Hibernate and WAS version?

**Comment by Anishkp** [comment]
@emeroad  - We are not using hibernate. We use JPA.

**Comment by ofauchon** [comment]
Hi. 
Same problem here with :

- Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
- hibernate-jpa-2.1-api-1.0.0.Final.jar
- tomcat 8 

----------> Parent Classloader:
java.net.URLClassLoader@2f94c4db
 agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@30a3107a Cause:com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find method executeQuery with parameter types: [java.lang.String]
com.navercorp.pinpoint.exception.PinpointException: com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find method executeQuery with parameter types: [java.lang.String]
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:72)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
        at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
....
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.postgresql.jdbc4.Jdbc4Connection.createStatement(Jdbc4Connection.java:30)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.createStatement(AbstractJdbc3Connection.java:230)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.createStatement(AbstractJdbc2Connection.java:294)
        at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getTypeInfo(AbstractJdbc2DatabaseMetaData.java:3950)
        at org.hibernate.engine.jdbc.spi.TypeInfo.extractTypeInfo(TypeInfo.java:84)
        at org.hibernate.engine.jdbc.env.internal.ExtractedDatabaseMetaDataImpl$Builder.apply(ExtractedDatabaseMetaDataImpl.java:194)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentImpl.<init>(JdbcEnvironmentImpl.java:209)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:114)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)

**Comment by ofauchon** [comment]
It seems the error disappeared after I rebooted with  postgresql trace off in pinpoint.config. 
But I still have no traces coming on the collector
Same behaviour on both 1.6.0 and 1.6.1 RC

**Comment by Xylus** [comment]
@Anishkp 
If you're using postgresql jdbc driver, please refer to [this](https://github.com/naver/pinpoint/issues/2771#issuecomment-292904788).

**Comment by emeroad** [comment]
Duplicate issue : #2771
