### ISSUE TITLE
How to connect to the database in PinPoint Plugin

### ISSUE THREAD

**Issue by tianhewulei** [naver/pinpoint#2699]
#### Description
**hi , I wrote a logic in the plugin，exp:**

```
public class JDBCHelper { 
    private final String DRIVER = "com.mysql.jdbc.Driver"; 
    private final String USERNAME = "root"; 
    private final String PASSWORD = "123456"; 
    private final String URL = "jdbc:mysql://10.10.50.2:3306/flink_bussines"; 
    private Connection connection;   
    public JDBCHelper()
    {
        try { 
            Class.forName(DRIVER); 
            connection = DriverManager.getConnection(URL,USERNAME,PASSWORD);
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
    }
}
public class CommonPlugin implements ProfilerPlugin, TransformTemplateAware {	
	private TransformTemplate transformTemplate;
	@Override
	public void setup(ProfilerPluginSetupContext context) {
		addApplicationTypeDetector(context);
		addTransformers();
	}	
	private void addTransformers() {
		JDBCHelper jdbcHelper = new JDBCHelper();
        }
}
```

**But Tomcat startup throw this Exception，pinpoint plugin and tomcat  lib directory has mysql driver lib：**

```
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.navercorp.pinpoint.common.plugin.PluginLoaderClassLoader.loadClas
s(PluginLoaderClassLoader.java:45)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at com.navercorp.pinpoint.plugin.util.config.JDBCHelper.<init>(JDBCHelpe
r.java:34)
        at com.navercorp.pinpoint.plugin.core.CommonPlugin.addTransformers(Commo
nPlugin.java:30)
        at com.navercorp.pinpoint.plugin.core.CommonPlugin.setup(CommonPlugin.ja
va:26)
```

**How to connect to the database in PinPoint Plugin?**

#### Environment
* Pinpoint version: 1.6.0

**Comment by tianhewulei** [comment]
I changed jedis, the same problem.  I think this problem is two different classloader，But how to deal with it？

Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/Jedis

**Comment by emeroad** [comment]
The plug-in does not support access to other libs.
