### ISSUE TITLE
I wana Help --com.navercorp.pinpoint.rpc.PinpointSocketException: timeout

### ISSUE THREAD

**Issue by koalton** [naver/pinpoint#2720]
#### Description

I set hbase distributed mode ,and  hbase stores datas in normal file system but not hdfs .and i make sure two RegionServers time is same( error less than 1 second ).Then I run my application ,console show that blow
`2017-03-16 10:46:37 [INFO ](c.n.p.p.s.TcpDataSender            :191) request fail. request:TApiMetaData(agentId:PP20170216-KO, agentStartTime:1489632370139, apiId:-2, apiInfo:com.koalton.processor.ProcessMSG.startMoni(), line:131, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
        at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
        at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:662)
2017-03-16 10:46:37 [INFO ](c.n.p.p.s.TcpDataSender            :191) request fail. request:TApiMetaData(agentId:PP20170216-KO, agentStartTime:1489632370139, apiId:2, apiInfo:com.koalton.processor.ProcessMSG.getMSG(long offset), line:195, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
        at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
        at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:662)
2017-03-16 10:46:37 [INFO ](c.n.p.p.s.TcpDataSender            :191) request fail. request:TApiMetaData(agentId:PP20170216-KO, agentStartTime:1489632370139, apiId:-3, apiInfo:com.koalton.processor.ProcessMSG.doMSG(com.ai.usb.common.consumer.MessageIterator msgIterator), line:203, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
        at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
        at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:662)
2017-03-16 10:46:37 [INFO ](c.n.p.p.s.TcpDataSender            :191) request fail. request:TApiMetaData(agentId:PP20170216-KO, agentStartTime:1489632370139, apiId:3, apiInfo:com.koalton.processor.ProcessMSG.createDone(com.koalton.common.protocol.SendMessageContext context), line:388, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
        at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
        at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at java.lang.Thread.run(Thread.java:662)`

#### Environment

* Pinpoint version: 1.6.0
* OS: CentOS6.5

**Comment by koalton** [comment]
a oh ,it's looks like my hbase config somewhere wrong .. just let me check it ....

**Comment by sww0825521xy** [comment]
any update? I meet the same problem.

**Comment by RoySRose** [comment]
@sww0825521xy 

It looks like any problem with Pinpoint.

Please check out hbase version.
https://naver.github.io/pinpoint/main.html#upgrade-consideration
or consider upgrade
https://naver.github.io/pinpoint/hbaseupgrade.html
