### ISSUE TITLE
A strange problem--

### ISSUE THREAD

**Issue by koalton** [naver/pinpoint#2721]
#### Description

My application is run normal ,but in pp-collector logs -catalina.out,i find blow
`2017-03-13 09:59:22 [WARN ](c.n.p.c.h.SpanHandler              :92 ) Span handle error. Caused:calleeApplicationName must not be null. Span:TSpan(agentId:PP20170216-KO, applicationName:Koalton-KO, agentStartTime:1489370341649, transactionId:00 01 91 C2 8F AB AC 2B 16, spanId:-6520163464253415646, startTime:1489370362600, elapsed:29, serviceType:0, flag:0, spanEventList:[TSpanEvent(sequence:0, startElapsed:0, endElapsed:29, serviceType:2900, annotations:[TAnnotation(key:900, value:<TAnnotationValue stringValue:20170301020728081614>), TAnnotation(key:907, value:<TAnnotationValue stringValue:DB>), TAnnotation(key:905, value:<TAnnotationValue stringValue:100899813527>), TAnnotation(key:903, value:<TAnnotationValue longValue:635469559>), TAnnotation(key:14, value:<TAnnotationValue boolValue:true>)], depth:1, apiId:-4)], applicationServiceType:1000)
java.lang.NullPointerException: calleeApplicationName must not be null
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapStatisticsCallerDao.update(HbaseMapStatisticsCallerDao.java:88)
	at com.navercorp.pinpoint.collector.handler.StatisticsHandler.updateCaller(StatisticsHandler.java:59)
	at com.navercorp.pinpoint.collector.handler.SpanHandler.insertSpanEventStat(SpanHandler.java:183)
	at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:90)
	at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
	at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
	at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:121)
	at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:100)
	at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:45)
	at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:188)
	at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`
I find the source code ,calleeApplicationName is destinatyId.but in my plugin,i have not use it ,how it could be happen ?

#### Environment

* Pinpoint version:1.6.0
* OS:centos6.5

**Comment by Xylus** [comment]
Hi @koalton 
From the log, you seem to be tracing something with `ServiceType` 2900.
As far as I know, Pinpoint currently does not have any plugins using 2900. May I ask if you're using a custom plugin?

**Comment by koalton** [comment]
@Xylus ,hi, u r right. i custom my plugin just for my application ,and in my AroundInterceptor2 implement,i use this servieType like blow

![bbb](https://cloud.githubusercontent.com/assets/22216568/23997785/d0229330-0a8d-11e7-97be-4e7bd3f012f9.jpg)

and ,would you like tell me it will do matter ?

**Comment by Xylus** [comment]
If it's tracing a rpc call to a remote node you'll have to record more properties as well as pass trace info over.
Please take a look at the [plugin development guide](https://github.com/naver/pinpoint/wiki/Pinpoint-Plugin-Developer-Guide) for more details.

**Comment by koalton** [comment]
@Xylus ,thanks .
I think i know how to modify my code . Actually,it is not a rpc call but a normal tracing. thanks for your help ~
