### ISSUE TITLE
exception on agent startup when multiple apps are running on the same host

### ISSUE THREAD

**Issue by sluramod** [naver/pinpoint#2743]
#### Description

I'm getting exceptions when app instrumented with pinpoint agent starts up. 
Failed to bind to: /127.0.0.1:65535

#### Environment

* Pinpoint version:
3.6.0
* OS, WAS, affected library, etc:
CentOS, java version "1.8.0_121"
* Additional details (e.g. how your collector/web is set up):
collector, web, hbase are running on another host(s)
#### Additional Info

Stacktrace:
preLoad error Caused:Failed to bind to: /127.0.0.1:65535org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:65535
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.bind(PinpointServerAcceptor.java:159)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.bind(PinpointServerAcceptor.java:150)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:46)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:34)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:121)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:76)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:71)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:120)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by emeroad** [comment]
It is a preloading log for deadlock prevention.
Perhaps there is no problem with the pinpoint agent.

**Comment by angeloudy** [comment]
Any updates on this one? I am running into the same issue
