### ISSUE TITLE
java.lang.VerifyError Exception

### ISSUE THREAD

**Issue by sluramod** [naver/pinpoint#2745]
#### Description

[WARN ](s.b.i.CreateBeanInstanceInterceptor) Unexpected exception
java.lang.VerifyError
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at com.navercorp.pinpoint.profiler.DynamicTransformService.triggerRetransform(DynamicTransformService.java:86)
        at com.navercorp.pinpoint.profiler.DynamicTransformService.retransform(DynamicTransformService.java:60)
        at com.navercorp.pinpoint.profiler.plugin.DefaultProfilerPluginContext.retransform(DefaultProfilerPluginContext.java:166)
        at com.navercorp.pinpoint.bootstrap.instrument.InstrumentorDelegate.retransform(InstrumentorDelegate.java:69)
        at com.navercorp.pinpoint.plugin.spring.beans.interceptor.AbstractSpringBeanCreationInterceptor.processBean(AbstractSpringBeanCreationInterceptor.java:55)
        at com.navercorp.pinpoint.plugin.spring.beans.interceptor.CreateBeanInstanceInterceptor.after(CreateBeanInstanceInterceptor.java:65)
        at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor1.after(ExceptionHandleAroundInterceptor1.java:44)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1060)
        at com.mycompany.quartz.QuartzSpringBeanJobFactory.createJobInstance(QuartzSpringBeanJobFactory.java:23)
        at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:41)
        at org.quartz.core.JobRunShell.initialize(JobRunShell.java:127)
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:375)
#### Environment

* Pinpoint version:
1.6.0
* OS, WAS, affected library, etc:
CentOS, java version "1.8.0_121"
* Additional details (e.g. how your collector/web is set up):
profiler.spring.beans.1.scope=post-processor

**Comment by emeroad** [comment]
We need information about what class is causing the problem.
Please attach a more detailed log and related code.

**Comment by zejunW** [comment]
maybe you can add -noverify to the JVM arguments
