### ISSUE TITLE
 java.lang.NoClassDefFoundError when pinpoint is running

### ISSUE THREAD

**Issue by mantos730** [naver/pinpoint#2779]
#### Description
Hi, I am a newbie of pinpoint project. 

I try to follow the instruction guide and install pinpoint collector, web and agent on tomcat7.
After setup these components, the pinpoint web runs successfully. However I can't see and select any application in pinpoint web.

I check logs, Here are exceptions I found from tomcat log:
#### exception 1
2017-04-10 06:42:30 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryBefore() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(ThriftServerScope)[depth=0], executionPoint: INTERNAL. Skip interceptor class com.navercorp.pinpoint.plugin.thrift.interceptor.tprotocol.server.TProtocolReadFieldBeginInterceptor
        at com.navercorp.pinpoint.common.util.AnnotationTranscoder.getMappingValue(AnnotationTranscoder.java:56)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.newAnnotationBo(SpanFactory.java:264)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildAnnotationList(SpanFactory.java:237)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.bind(SpanFactory.java:144)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBo(SpanFactory.java:252)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBoList(SpanFactory.java:220)
2017-04-10 06:42:30 [DEBUG](.s.ExceptionHandleScopedInterceptor:298) tryAfter() returns false: interceptorScopeTransaction: InterceptorScopeInvocation(ThriftServerScope)[depth=0], executionPoint: INTERNAL. Skip interceptor class com.navercorp.pinpoint.plugin.thrift.interceptor.tprotocol.server.TProtocolReadFieldBeginInterceptor
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanBo(SpanFactory.java:56)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:82)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:122)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:101)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:51)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:186)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-04-10 06:42:30 [DEBUG](c.n.p.c.h.SpanHandler              :78 ) Received SPAN=TSpan(agentId:5566, applicationName:Tomcat7, agentStartTime:1491806415731, transactionId:00 01 F3 D6 DD B4 B5 2B 90 01, spanId:7719682887466504214, startTime:1491806550400, elapsed:12, rpc:/pinpoint-web-1.6.1-SNAPSHOT/features/configuration/userGroup/pinpointUser.html, serviceType:1010, endPoint:192.168.85.157:8080, remoteAddr:192.168.1.16, flag:0, spanEventList:[TSpanEvent(sequence:0, startElapsed:9, endElapsed:3, serviceType:1011, annotations:[TAnnotation(key:41, value:<TAnnotationValue stringValue:v=1491554484114>)], depth:1, apiId:1)], apiId:2, applicationServiceType:1010)
Exception in thread "Pinpoint-UDP-Span-Worker(41-111)" java.lang.NoClassDefFoundError: com/navercorp/pinpoint/thrift/dto/TAnnotation
        at com.navercorp.pinpoint.common.util.AnnotationTranscoder.getMappingValue(AnnotationTranscoder.java:56)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.newAnnotationBo(SpanFactory.java:264)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildAnnotationList(SpanFactory.java:237)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.bind(SpanFactory.java:144)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBo(SpanFactory.java:252)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBoList(SpanFactory.java:220)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanBo(SpanFactory.java:56)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:82)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:122)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:101)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:51)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:186)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
#### exception 2

2017-04-10 06:42:30 [DEBUG](n.p.p.t.i.RequestRecycleInterceptor:88 ) BEFORE org.apache.catalina.connector.Request org.apache.catalina.connector.Request recycle args:()
Exception in thread "Pinpoint-UDP-Span-Worker(41-119)" java.lang.NoClassDefFoundError: com/navercorp/pinpoint/thrift/dto/TAnnotation
        at com.navercorp.pinpoint.common.util.AnnotationTranscoder.getMappingValue(AnnotationTranscoder.java:56)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.newAnnotationBo(SpanFactory.java:264)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildAnnotationList(SpanFactory.java:237)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.bind(SpanFactory.java:144)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBo(SpanFactory.java:252)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBoList(SpanFactory.java:220)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanBo(SpanFactory.java:56)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:82)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:122)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:101)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:51)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:186)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
#### exception 3

2017-04-10 06:42:31 [DEBUG](c.n.p.c.h.SpanHandler              :78 ) Received SPAN=TSpan(agentId:5566, applicationName:Tomcat7, agentStartTime:1491806415731, transactionId:00 01 F3 D6 DD B4 B5 2B A1 01, spanId:7370444027309735254, startTime:1491806551455, elapsed:1, rpc:/pinpoint-web-1.6.1-SNAPSHOT/favicon.png, serviceType:1010, endPoint:192.168.85.157:8080, remoteAddr:192.168.1.16, flag:0, spanEventList:[TSpanEvent(sequence:0, startElapsed:0, endElapsed:1, serviceType:1011, depth:1, apiId:1)], apiId:2, applicationServiceType:1010)
Exception in thread "Pinpoint-UDP-Span-Worker(41-123)" java.lang.NoClassDefFoundError: com/navercorp/pinpoint/thrift/dto/TAnnotation
        at com.navercorp.pinpoint.common.util.AnnotationTranscoder.getMappingValue(AnnotationTranscoder.java:56)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.newAnnotationBo(SpanFactory.java:264)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildAnnotationList(SpanFactory.java:237)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.bind(SpanFactory.java:144)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBo(SpanFactory.java:252)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanEventBoList(SpanFactory.java:220)
        at com.navercorp.pinpoint.common.server.bo.SpanFactory.buildSpanBo(SpanFactory.java:56)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:82)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:122)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:101)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:51)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:186)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

#### Environment
ubuntu 16.04

#### Additional Info
Hadoop: 2.8.0
hbase 1.0.3

**Comment by Xylus** [comment]
Hi @mantos730 
It looks like you've attached pinpoint agent to your pinpoint collector instance. Pinpoint collectors cannot have pinpoint agents attached to them currently.
Please let me know if this is not the case.

**Comment by mantos730** [comment]
Hi @Xylus,

It works! I run pinpoint agent on another application, and set pinpoint web as root in tomcat, everything works perfectly, Thank you so much.
