### ISSUE TITLE
Jboss EAP 6 Error  ----  Help

### ISSUE THREAD

**Issue by Eilikce** [naver/pinpoint#2807]
#### Description
All the time my pinpoint work well on my Tomcat and Jetty . But now I have a trouble in my pinpoint when I use agent on my new Jboss EAP 6.2 . There is the error Log when I start up the jboss . After jboss started , the ServerMap show a Jboss chart , but I can't find anything on the pinpoint Scatter Chart .

What can I do for this error ?

some of my agent conf:

###########################################################
# application type                                        # 
###########################################################
profiler.applicationservertype=JBOSS

###########################################################
# JBOSS                                                   #
###########################################################
profiler.jboss.enable=true
# Classes for detecting application server type. Comma separated list of fully qualified class names. Wildcard not supported.
profiler.jboss.bootstrap.main=org.jboss.modules.Main
# Check pre-conditions when registering class file transformers mainly due to Tomcat plugin transforming the same class.
# Setting this to true currently adds transformers only if the application was launched via org.jboss.modules.Main.
# Set this to false to bypass this check entirely.
profiler.jboss.conditional.transform=true
# Hide pinpoint headers.
profiler.jboss.hidepinpointheader=true
# URLs to exclude from tracing
profiler.jboss.excludeurl=
# HTTP Request methods to exclude from tracing
#profiler.jboss.excludemethod=
profiler.jboss.tracerequestparam=true

# original IP address header
# https://en.wikipedia.org/wiki/X-Forwarded-For
#profiler.jboss.realipheader=X-Forwarded-For
# nginx real ip header
#profiler.jboss.realipheader=X-Real-IP
# optional parameter, If the header value is ${profiler.jboss.realipemptyvalue}, Ignore header value.
#profiler.jboss.realipemptyvalue=unknown

#### Environment

* Pinpoint version: 1.6.0
* OS, WAS, affected library, etc: Windows 7 64bit
* Additional details (e.g. how your collector/web is set up):

#### Additional Info
2017-04-14 11:20:29 [DEBUG](c.n.p.p.i.PlainClassLoaderHandler  :264) define class:com.navercorp.pinpoint.plugin.jboss.ServletAsyncMethodDescriptor cl:ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
2017-04-14 11:20:29 [WARN ](c.n.p.p.i.PlainClassLoaderHandler  :281) com.navercorp.pinpoint.plugin.jboss.ServletAsyncMethodDescriptor define fail classMetadata:com.navercorp.pinpoint.profiler.instrument.classreading.DefaultSimpleClassMetadata@19b3a92 cl:ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base)) Caused by:null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:271)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:254)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:192)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:132)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:93)
	at com.navercorp.pinpoint.profiler.instrument.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:63)
	at com.navercorp.pinpoint.profiler.plugin.DefaultProfilerPluginContext.injectClass(DefaultProfilerPluginContext.java:176)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.resolveScopeInfo(ASMMethod.java:197)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:245)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:108)
	at com.navercorp.pinpoint.plugin.jboss.JbossPlugin$3.doInTransform(JbossPlugin.java:159)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:345)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:261)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:76)
	at org.jboss.modules.Module.loadModuleClass(Module.java:548)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:189)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	at org.apache.catalina.core.StandardHost.<init>(StandardHost.java:64)
	at org.jboss.as.web.WebVirtualHostService.start(WebVirtualHostService.java:77)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/context/MethodDescriptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	... 41 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.context.MethodDescriptor from [Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	... 45 more
2017-04-14 11:20:29 [WARN ](c.n.p.p.i.PlainClassLoaderHandler  :95 ) Failed to load plugin class com.navercorp.pinpoint.plugin.jboss.interceptor.StandardHostValveInvokeInterceptor with classLoader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
java.lang.RuntimeException: com.navercorp.pinpoint.plugin.jboss.ServletAsyncMethodDescriptor define fail Caused by:null
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.handleDefineClassFail(PlainClassLoaderHandler.java:283)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:275)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:254)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:192)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:132)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:93)
	at com.navercorp.pinpoint.profiler.instrument.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:63)
	at com.navercorp.pinpoint.profiler.plugin.DefaultProfilerPluginContext.injectClass(DefaultProfilerPluginContext.java:176)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.resolveScopeInfo(ASMMethod.java:197)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:245)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:108)
	at com.navercorp.pinpoint.plugin.jboss.JbossPlugin$3.doInTransform(JbossPlugin.java:159)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:345)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:261)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:76)
	at org.jboss.modules.Module.loadModuleClass(Module.java:548)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:189)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	at org.apache.catalina.core.StandardHost.<init>(StandardHost.java:64)
	at org.jboss.as.web.WebVirtualHostService.start(WebVirtualHostService.java:77)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:271)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/context/MethodDescriptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	... 41 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.context.MethodDescriptor from [Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	... 45 more
2017-04-14 11:20:29 [WARN ](.p.i.JarProfilerPluginClassInjector:67 ) Failed to load plugin class com.navercorp.pinpoint.plugin.jboss.interceptor.StandardHostValveInvokeInterceptor with classLoader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.jboss.interceptor.StandardHostValveInvokeInterceptor with classLoader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:96)
	at com.navercorp.pinpoint.profiler.instrument.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:63)
	at com.navercorp.pinpoint.profiler.plugin.DefaultProfilerPluginContext.injectClass(DefaultProfilerPluginContext.java:176)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.resolveScopeInfo(ASMMethod.java:197)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:245)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:108)
	at com.navercorp.pinpoint.plugin.jboss.JbossPlugin$3.doInTransform(JbossPlugin.java:159)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:345)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:261)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:76)
	at org.jboss.modules.Module.loadModuleClass(Module.java:548)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:189)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	at org.apache.catalina.core.StandardHost.<init>(StandardHost.java:64)
	at org.jboss.as.web.WebVirtualHostService.start(WebVirtualHostService.java:77)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.RuntimeException: com.navercorp.pinpoint.plugin.jboss.ServletAsyncMethodDescriptor define fail Caused by:null
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.handleDefineClassFail(PlainClassLoaderHandler.java:283)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:275)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:254)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:192)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:132)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:93)
	... 32 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:271)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/context/MethodDescriptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	... 41 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.context.MethodDescriptor from [Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	... 45 more
2017-04-14 11:20:29 [ERROR](.p.p.ClassFileTransformerDispatcher:126) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base)) ctxCl:ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base)) agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@a352a5 Cause:Failed to load plugin class com.navercorp.pinpoint.plugin.jboss.interceptor.StandardHostValveInvokeInterceptor with classLoader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.jboss.interceptor.StandardHostValveInvokeInterceptor with classLoader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
	at com.navercorp.pinpoint.profiler.instrument.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:68)
	at com.navercorp.pinpoint.profiler.plugin.DefaultProfilerPluginContext.injectClass(DefaultProfilerPluginContext.java:176)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.resolveScopeInfo(ASMMethod.java:197)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:245)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:108)
	at com.navercorp.pinpoint.plugin.jboss.JbossPlugin$3.doInTransform(JbossPlugin.java:159)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:120)
	at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:101)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:345)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:261)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:76)
	at org.jboss.modules.Module.loadModuleClass(Module.java:548)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:189)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	at org.apache.catalina.core.StandardHost.<init>(StandardHost.java:64)
	at org.jboss.as.web.WebVirtualHostService.start(WebVirtualHostService.java:77)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.jboss.interceptor.StandardHostValveInvokeInterceptor with classLoader ModuleClassLoader for Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:96)
	at com.navercorp.pinpoint.profiler.instrument.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:63)
	... 31 more
Caused by: java.lang.RuntimeException: com.navercorp.pinpoint.plugin.jboss.ServletAsyncMethodDescriptor define fail Caused by:null
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.handleDefineClassFail(PlainClassLoaderHandler.java:283)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:275)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:254)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:192)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:132)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:93)
	... 32 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.navercorp.pinpoint.profiler.instrument.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:271)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/context/MethodDescriptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	... 41 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.context.MethodDescriptor from [Module "org.jboss.as.web:main" from local module loader @2f1e75 (finder: local module finder @178b64b (roots: V:\Jboss\jboss-eap-6.2\modules,V:\Jboss\jboss-eap-6.2\modules\system\layers\base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118)
	... 45 more

**Comment by jaehong-kim** [comment]
I guess the same reason as the issue below. #2350
There are two ways to fix it.
* Please use pinpoint-1.6.1.
* In version 1.6.0, modify the following settings(pinpoint.config).
~~~
# Allow bytecode framework (JAVASSIST or ASM)
profiler.instrument.engine=JAVASSIST
~~~

**Comment by Eilikce** [comment]
Hi jaehong-kim,

Thanks for your help , but it didn't work with your idea ...

**Comment by jaehong-kim** [comment]
@Eilikce 
Did you see the following article when applying JBoss ?
* https://github.com/naver/pinpoint/tree/master/plugins/jboss

**Comment by clearBird** [comment]
@jaehong-kim I use pinpoint-1.6.1，but throw not solve the error：

**Comment by jaehong-kim** [comment]
@Eilikce 
It looks like the issue below. #2850 
* Did you add the Java option when you ran it?
~~~
JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,
com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_HOME/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-$JBOSS_LOGMANAGER_VERSION.jar"
JAVA_OPTS="$JAVA_OPTS -javaagent:$PINPOINT_AGENT_HOME/pinpoint-bootstrap-$PINPOINT_VERSION.jar"
JAVA_OPTS="$JAVA_OPTS -Dpinpoint.applicationName=APP-APPLICATION-NAME" 
JAVA_OPTS="$JAVA_OPTS -Dpinpoint.agentId=APP-AGENTID"
~~~
* Show all logs from execution until error occurs.

**Comment by Eilikce** [comment]
It worked ! 
Thanks a lot 
the issue below. #2850
