### ISSUE TITLE
JBoss AS 7.1.1 + 7.2.0 won't start with pinpoint

### ISSUE THREAD

**Issue by mabunixda** [naver/pinpoint#2845]
#### Description
I want to add pinpoint to a jboss application running on jboss. Because i was not able to add pinpoint to the testing system i started using a local docker container by tutum/jboss:as7
`
docker run  -it -v /root/jboss/standalone.conf:/jboss-as-7.1.1.Final/bin/standalone.conf -v /root/assets:/srv/pinpoint -p 8080:8080 -p 9090:9090 tutum/jboss:as7 
`

standalone.conf the following lines were added:
`
if [ "x$JBOSS_MODULES_SYSTEM_PKGS" = "x" ]; then
 JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman,org.jboss.logmanager,com.navercorp.pinpoint.bootstrap,com.navercorp.pinpoint.common,Com.navercorp.pinpoint.exception"
fi

JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_HOME/modules/org/jboss/logmanager/main/jboss-logmanager-1.2.2.GA.jar"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
JAVA_OPTS="$JAVA_OPTS -javaagent:/srv/pinpoint/pinpoint-agent/pinpoint-bootstrap-1.6.1.jar"
JAVA_OPTS="$JAVA_OPTS -Dpinpoint.applicationName=1"
JAVA_OPTS="$JAVA_OPTS -Dpinpoint.agentId=jbossSample"
` 

This configuration results in the following error appearing first in the startup:

`
2017-04-19 12:01:50 [INFO ](n.p.p.c.m.DefaultApplicationContext:96 ) DefaultAgent classLoader:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@21f3aa07
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader.loadClass(PinpointURLClassLoader.java:70)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at java.util.logging.LogManager$1.run(LogManager.java:166)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.<clinit>(LogManager.java:156)
        at java.util.logging.Logger.demandLogger(Logger.java:280)
        at java.util.logging.Logger.getLogger(Logger.java:321)
        at com.google.inject.internal.util.Stopwatch.<clinit>(Stopwatch.java:27)
        at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:61)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:100)
        at com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:125)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:118)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:69)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:76)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:71)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
`

and finally the startup breaks with this error:
`
WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
Exception in thread "main" java.lang.NoClassDefFoundError: org/jboss/logmanager/Level
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:249)
        at org.jboss.modules.Module.run(Module.java:247)
        at org.jboss.modules.Main.main(Main.java:291)
Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Level
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:395)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
        ... 4 more
`

Before these lines appear in the log  the following is in the log files:
`
2017-04-19 12:01:51 [INFO ](c.n.p.p.DefaultAgent               :176) Starting pinpoint Agent.
2017-04-19 12:01:51 [INFO ](c.n.p.p.AgentInfoSender            :200) Sending AgentInfo TAgentInfo(hostname:98e0a418089d, ip:172.17.0.5, ports:, agentId:jbossSample, applicationName:1, serviceType:1040, pid:84, ag
entVersion:1.6.1, vmVersion:1.6.0_45, startTimestamp:1492603309194, jvmInfo:TJvmInfo(version:0, vmVersion:1.6.0_45, gcType:PARALLEL))                                                                               2017-04-19 12:01:51 [INFO ](c.n.p.p.m.DefaultAgentStatMonitor  :84 ) AgentStat monitor started
2017-04-19 12:01:51 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
`

I gonna at the startup log to
[pinpoint.txt](https://github.com/naver/pinpoint/files/934237/pinpoint.txt)

I am not able to find a solution - i already tried different hints by google using -logmanager or other jvm flags without any success 

Thanks

**Comment by mabunixda** [comment]
Found the [solution](https://github.com/naver/pinpoint/issues/972#issuecomment-219488721)

**Comment by mabunixda** [comment]
With Jboss AS 7.2.0 i run into [this bug](https://issues.jboss.org/browse/WFLY-1432). Is there a workaround possible without upgading jboss?

**Comment by emeroad** [comment]
Unfortunately, we have no plans for workaround.
The JDK logger is used by google guava and guice, it is difficult to provide a workaround.

**Comment by mabunixda** [comment]
I was able to fix this by pulling the [wildfly commit](https://github.com/wildfly/wildfly/pull/4576) into the tag 7.2.0.Final and repackage jboss.as.logging
