### ISSUE TITLE
Workaround java level Deadlock when initializing annotation

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#2862]
#### Description
Class.getAnnotation() of JDK 6, 7 can cause java level deallock 

Related issue:
 - https://ecosystem.atlassian.net/browse/AO-283
 - https://bugs.openjdk.java.net/browse/JDK-7171421
 - https://issues.apache.org/jira/browse/HIVE-7409
 - http://stap.sjtu.edu.cn/index.php?title=Jdk7122142

#### Environment
Affects Version/s: 1.0.x, 1.1.x, 1.5.x, 1.6.1-

#### Additional Info
```
[Thread Dump] 
Found one Java-level deadlock:
=============================
"TP-Processor4096":
waiting to lock monitor 0x00007fd0e80094b0 (object 0x0000000761528120, a java.lang.Class),
which is held by "TP-Processor15"
"TP-Processor15":
waiting to lock monitor 0x00007fd0e8009a98 (object 0x000000079e0a1cb0, a org.apache.catalina.loader.WebappClassLoader),
which is held by "TP-Processor3"
"TP-Processor3":
waiting to lock monitor 0x00007fd0e80094b0 (object 0x0000000761528120, a java.lang.Class),
which is held by "TP-Processor15"

Java stack information for the threads listed above:
===================================================

"TP-Processor4096":
at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:63)
- waiting to lock <0x0000000761528120> (a java.lang.Class for sun.reflect.annotation.AnnotationType)
at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:202)
at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
at java.lang.reflect.Method.declaredAnnotations(Method.java:693)
- locked <0x000000079e6c5678> (a java.lang.reflect.Method)
at java.lang.reflect.Method.getAnnotation(Method.java:679)
at com.nhn.lucy.web.interceptor.PropertyInterceptor.intercept(PropertyInterceptor.java:39)
...

"TP-Processor15":
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2436)
at java.lang.Class.getDeclaredMethods(Class.java:1793)
at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:86)
at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:83)
at java.security.AccessController.doPrivileged(Native Method)
at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:82)
at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:66)
- locked <0x0000000761528120> (a java.lang.Class for sun.reflect.annotation.AnnotationType)
at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:202)
at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
at java.lang.Class.initAnnotationsIfNecessary(Class.java:3079)
- locked <0x0000000766800f00> (a java.lang.Class for org.codehaus.jackson.map.introspect.VisibilityChecker$Std)
at java.lang.Class.getAnnotation(Class.java:3038)
at org.codehaus.jackson.map.introspect.VisibilityChecker$Std.<clinit>(VisibilityChecker.java:178)
at org.codehaus.jackson.map.ObjectMapper.<clinit>(ObjectMapper.java:196)
...

"TP-Processor3":
at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:63)
- waiting to lock <0x0000000761528120> (a java.lang.Class for sun.reflect.annotation.AnnotationType)
at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:202)
at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
at java.lang.Class.initAnnotationsIfNecessary(Class.java:3079)
- locked <0x000000076680f8e0> (a java.lang.Class for com.navercorp.pinpoint.plugin.arcus.interceptor.FrontCacheGetFutureConstructInterceptor)
at java.lang.Class.getAnnotation(Class.java:3038)
at com.navercorp.pinpoint.profiler.instrument.JavassistClass.addInterceptor0(JavassistClass.java:478)
at com.navercorp.pinpoint.profiler.instrument.JavassistClass.addInterceptor(JavassistClass.java:394)
at com.navercorp.pinpoint.plugin.arcus.ArcusPlugin$4.doInTransform(ArcusPlugin.java:145)
at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:70)
at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform0(ClassFileTransformerDispatcher.java:119)
at com.navercorp.pinpoint.profiler.ClassFileTransformerDispatcher.transform(ClassFileTransformerDispatcher.java:100)
at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2818)
- locked <0x000000079e0a1cb0> (a org.apache.catalina.loader.WebappClassLoader)
at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1159)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1647)
- locked <0x000000079e0a1cb0> (a org.apache.catalina.loader.WebappClassLoader)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
at net.spy.memcached.plugin.FrontCacheMemcachedClient.asyncGet(FrontCacheMemcachedClient.java:50)
at net.spy.memcached.MemcachedClient.asyncGet(MemcachedClient.java:817)
at net.spy.memcached.ArcusClientPool.asyncGet(ArcusClientPool.java:141)
at com.navercorp.arcus.spring.cache.ArcusCache.get(ArcusCache.java:108)
at org.springframework.cache.interceptor.CacheAspectSupport.inspectCacheables(CacheAspectSupport.java:294)
at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:199)
at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:66)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
...
```

**Comment by emeroad** [comment]
opensource 대상 플러그인 
httpclient3
httpclient4
ning-asynchttpclient
gson
jackson
cubrid-jdbc
mysql-jdbc
mariadb-jdbc
postgresql-jdbc
jtds
dbcp
dbcp2
hikaricp
oracle-jdbc
jdk-http
json-lib
redis
tomcat
thrift
user
arcus
google-httpclient
jetty
spring
spring-boot
ibatis
mybatis
okhttp
log4j
logback
dubbo
cassandra
activemq-client
cxf
hystrix
jboss
vertx
resin

**Comment by lirenzuo** [comment]
all jdk7 version has a problem ??

**Comment by emeroad** [comment]
@lirenzuo  Yes, All JDK 6, 7  has a deadlock bug.
 - JDK-7122142 : (ann) Race condition between isAnnotationPresent and getAnnotations
   http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7122142
   Fixed Versions: 8 (b100)

**Comment by lirenzuo** [comment]
@emeroad  thank you!

**Comment by lirenzuo** [comment]
@emeroad   thank you!

**Comment by emeroad** [comment]
@lirenzuo
I found a backport patch for JDK 6, 7
 - JDK 6 last backport issue
   http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8025620
   Fixed Versions:6u81 (b01) - commercial version
- JDK 7 last backport issue 
   http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8025621
   Fixed Versions:7u80 (b01) - jdk 7 last version

I do not know if the backport has been completely fixed.
JDK 6_45
```java
    public static synchronized AnnotationType getInstance(Class var0) {
        AnnotationType var1 = SharedSecrets.getJavaLangAccess().getAnnotationType(var0);
        if(var1 == null) {
            var1 = new AnnotationType(var0);
        }

        return var1;
    }
````

- JDK 7_80
```java
    // synchronized block is removed.
    public static AnnotationType getInstance(Class<? extends Annotation> var0) {
        JavaLangAccess var1 = SharedSecrets.getJavaLangAccess();
        AnnotationType var2 = var1.getAnnotationType(var0);
        if(var2 == null) {
            var2 = new AnnotationType(var0);
            if(!var1.casAnnotationType(var0, (AnnotationType)null, var2)) {
                var2 = var1.getAnnotationType(var0);

                assert var2 != null;
            }
        }

        return var2;
    }
```

**Comment by lirenzuo** [comment]
@emeroad  3q
