### ISSUE TITLE
Problem with 'unable to create new native thread' and 'DeadlockLoserDataAccessException'

### ISSUE THREAD

**Issue by fei228** [naver/pinpoint#2928]
- 1.6.0 release version

- web UI is well displaying

- deploied with .war file on tomcat7

- memory is quite enough.

- Alarm setting is TOTAL_COUNT, threshold=1

1. unable to create new native thread 

pinpoint-web log

05-12 16:19:00 DEBUG hbase.HbaseMapResponseTimeDao - selectResponseTime applicationName:TyphoneBizRestServer(SPRING_BOOT:1210), Range{from=1494573240317, to=14945

73540317, range=300000}

05-12 16:19:00 DEBUG hbase.HbaseMapResponseTimeDao - scan time:Range{from=2017-05-12 16:13:59 999, to=2017-05-12 16:19:00 000, range s=300}

05-12 16:19:00 ERROR step.AbstractStep - Encountered an error executing step alarmStep in job alarmJob

java.lang.OutOfMemoryError: unable to create new native thread

        at java.lang.Thread.start0(Native Method)

        at java.lang.Thread.start(Thread.java:714)

        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)

        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)

        at com.navercorp.pinpoint.common.hbase.parallel.ParallelResultScanner.<init>(ParallelResultScanner.java:65)

        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.executeParallelDistributedScan(HbaseTemplate2.java:670)

        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.findParallel(HbaseTemplate2.java:623)

        at com.navercorp.pinpoint.web.dao.hbase.HbaseMapResponseTimeDao.selectResponseTime(HbaseMapResponseTimeDao.java:79)

        at com.navercorp.pinpoint.web.alarm.collector.ResponseTimeDataCollector.collect(ResponseTimeDataCollector.java:62)

        at com.navercorp.pinpoint.web.alarm.checker.AlarmChecker.check(AlarmChecker.java:76)

        at com.navercorp.pinpoint.web.alarm.AlarmProcessor.process(AlarmProcessor.java:29)

        at com.navercorp.pinpoint.web.alarm.AlarmProcessor.process(AlarmProcessor.java:26)

        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)

        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)

        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)

        at com.sun.proxy.$Proxy64.process(Unknown Source)

        at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:126)

        at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:293)

        at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:192)

        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)

        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)

        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)

        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)

        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)

        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)

        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)

        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)

        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)

        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)

        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)

        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==>  Preparing: SELECT * FROM alarm_rule WHERE application_id = ?

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> Parameters: LoadBalancer(String)

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - <==      Total: 0

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> BindingLog: SELECT * FROM alarm_rule WHERE application_id = 'LoadBalancer'

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==>  Preparing: SELECT * FROM alarm_rule WHERE application_id = ?

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> Parameters: ProxyRegistrarLodev(String)

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - <==      Total: 0

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> BindingLog: SELECT * FROM alarm_rule WHERE application_id = 'ProxyRegistrarLodev'

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==>  Preparing: SELECT * FROM alarm_rule WHERE application_id = ?

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> Parameters: PushServerB2B(String)

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - <==      Total: 0

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> BindingLog: SELECT * FROM alarm_rule WHERE application_id = 'PushServerB2B'

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==>  Preparing: SELECT * FROM alarm_rule WHERE application_id = ?

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> Parameters: TESTAPP(String)

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - <==      Total: 1

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> BindingLog: SELECT * FROM alarm_rule WHERE application_id = 'TESTAPP'

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==>  Preparing: SELECT * FROM alarm_rule WHERE application_id = ?

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> Parameters: Typh(String)

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - <==      Total: 0

05-12 16:19:00 DEBUG AlarmDao.selectRuleByApplicationId - ==> BindingLog: SELECT * FROM alarm_rule WHERE application_id = 'Typh'

05-12 16:19:00 DEBUG hbase.HbaseMapResponseTimeDao - selectResponseTime applicationName:TESTAPP(TOMCAT:1010), Range{from=1494573240425, to=1494573540425, range=300000}

05-12 16:19:00 DEBUG hbase.HbaseMapResponseTimeDao - scan time:Range{from=2017-05-12 16:13:59 999, to=2017-05-12 16:19:00 000, range s=300}

05-12 16:19:00 ERROR step.AbstractStep - Encountered an error executing step alarmStep in job alarmJob

java.lang.OutOfMemoryError: unable to create new native thread

        at java.lang.Thread.start0(Native Method)

        at java.lang.Thread.start(Thread.java:714)

        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)

        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)

        at com.navercorp.pinpoint.common.hbase.parallel.ParallelResultScanner.<init>(ParallelResultScanner.java:65)

        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.executeParallelDistributedScan(HbaseTemplate2.java:670)

        at com.navercorp.pinpoint.common.hbase.HbaseTemplate2.findParallel(HbaseTemplate2.java:623)

        at com.navercorp.pinpoint.web.dao.hbase.HbaseMapResponseTimeDao.selectResponseTime(HbaseMapResponseTimeDao.java:79)

        at com.navercorp.pinpoint.web.alarm.collector.ResponseTimeDataCollector.collect(ResponseTimeDataCollector.java:62)

        at com.navercorp.pinpoint.web.alarm.checker.AlarmChecker.check(AlarmChecker.java:76)

        at com.navercorp.pinpoint.web.alarm.AlarmProcessor.process(AlarmProcessor.java:29)

        at com.navercorp.pinpoint.web.alarm.AlarmProcessor.process(AlarmProcessor.java:26)

        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)

        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)

        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)

        at com.sun.proxy.$Proxy64.process(Unknown Source)

        at org.springframework.batch.core.step.item.SimpleChunkProcessor.doProcess(SimpleChunkProcessor.java:126)

        at org.springframework.batch.core.step.item.SimpleChunkProcessor.transform(SimpleChunkProcessor.java:293)

        at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:192)

        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)

        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:395)

        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)

        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267)

        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)

        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)

        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)

        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)

        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:253)

        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)

        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)

        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

05-12 16:19:00 ERROR step.AbstractStep - Encountered an error executing step alarmPartitionStep in job alarmJob

org.springframework.batch.core.JobExecutionException: Partition handler returned an unsuccessful step

        at org.springframework.batch.core.partition.support.PartitionStep.doExecute(PartitionStep.java:111)

        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:195)

        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:141)

        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)

        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)

        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:151)

        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:130)

        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:135)

        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:301)

        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:134)

        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)

        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:127)

        at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:61)

        at com.navercorp.pinpoint.web.batch.BatchJobLauncher.alarmJob(BatchJobLauncher.java:32)

        at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)

        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)

        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

05-12 16:19:00 INFO  support.SimpleJobLauncher - Job: [FlowJob: [name=alarmJob]] completed with the following parameters: [{schedule.date=1494573540000}] and the following status: [FAILED]

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2.DeadlockLoserDataAccessException

05-11 23:13:00 ERROR support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INST

ANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.

exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

        at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:63)

        at com.navercorp.pinpoint.web.batch.BatchJobLauncher.alarmJob(BatchJobLauncher.java:32)

        at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)

        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)

        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

Caused by: org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:263)

        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)

        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)

        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)

        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)

        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:975)

        at org.springframework.batch.core.repository.dao.JdbcJobInstanceDao.createJobInstance(JdbcJobInstanceDao.java:105)

        at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:135)

        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)

        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)

        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)

        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

        at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:172)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)

        at com.sun.proxy.$Proxy60.createJobExecution(Unknown Source)

        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:124)

        at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:61)

        ... 14 more

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)

        at com.mysql.jdbc.Util.getInstance(Util.java:386)

        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1064)

        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)

        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)

        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)

        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)

        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)

        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)

        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2444)

        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2362)

        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2347)

        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)

        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)

        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)

        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:916)

        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:909)

        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)

        ... 35 more

Regarding above issue, I found that below jobKeys are same.
Below is on MySQL, 'show engine innodb status' command

------------------------

LATEST DETECTED DEADLOCK

------------------------

2017-05-12 15:44:35 7fa56a51ab00

*** (1) TRANSACTION:

TRANSACTION 670663, ACTIVE 0 sec inserting

mysql tables in use 1, locked 1

LOCK WAIT 4 lock struct(s), heap size 1184, 2 row lock(s), undo log entries 1

MySQL thread id 4551, OS thread handle 0x7fa5675aeb00, query id 1543776 116.122.36.39 admin_pinpoint update

INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (14829, 'alarmJob', '33de12a6eca954aa384656c1de6e8668', 0)

*** (1) WAITING FOR THIS LOCK TO BE GRANTED:

RECORD LOCKS space id 8568 page no 37 n bits 360 index `JOB_INST_UN` of table `pinpoint`.`BATCH_JOB_INSTANCE` trx table locks 2 total table locks 4  trx id 670663 lock_mode X locks gap before rec insert intention waiting lock hold time 0 wait time before grant 0

*** (2) TRANSACTION:

TRANSACTION 670662, ACTIVE 0 sec inserting

mysql tables in use 1, locked 1

4 lock struct(s), heap size 1184, 2 row lock(s), undo log entries 1

MySQL thread id 4582, OS thread handle 0x7fa56a51ab00, query id 1543777 116.122.36.39 admin_pinpoint update

INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (14830, 'alarmJob', '33de12a6eca954aa384656c1de6e8668', 0)

*** (2) HOLDS THE LOCK(S):

RECORD LOCKS space id 8568 page no 37 n bits 360 index `JOB_INST_UN` of table `pinpoint`.`BATCH_JOB_INSTANCE` trx table locks 2 total table locks 4  trx id 670662 lock mode S locks gap before rec lock hold time 0 wait time before grant 0

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:

RECORD LOCKS space id 8568 page no 37 n bits 360 index `JOB_INST_UN` of table `pinpoint`.`BATCH_JOB_INSTANCE` trx table locks 2 total table locks 4  trx id 670662 lock_mode X locks gap before rec insert intention waiting lock hold time 0 wait time before grant 0

*** WE ROLL BACK TRANSACTION (2)

**Comment by fei228** [comment]
This Exception was encountered with AlarmMessageSenderImple.java, ApplicationContext variable.
I deleted ApplicationContext variable, and made it autowired class.

**Comment by liyang1518** [comment]
I have encountered the same problem with you. Can you point out the problem?
