### ISSUE TITLE
 I need help! when use cloudera hbase , it always refused the connection.

### ISSUE THREAD

**Issue by SKingNight** [naver/pinpoint#2937]
hi
  i am using pinpoint with version 1.6.0. At first，the collector , web,and hbase (localhost) was arranged on the same machine, it works well. but when i use cloudera hbase instead of the localhost ,and 
change the hbase.properties:
 hbase.client.host=bigdata1,bigdata2,bigdata4
 hbase.client.port=2181

the when i restart collector, the collector always throws an exception:
2017-05-18 15:38:28 [WARN ](o.a.z.ClientCnxn                   ) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

I have search some solution such as iptables or system-date ,but it not work. i'm not sure whether something errors in collector or in cloudera zookeeper(ex.the cloudera platform works well) .

can you give me some suggestions. thank you

**Comment by bingfengxiyang** [comment]
How do you solve this problem? Can you tell me?

**Comment by bingfengxiyang** [comment]
How do you solve this problem? Can you tell me?

**Comment by SKingNight** [comment]
> How do you solve this problem? Can you tell me?

check prop file, it has zk options, maybe the problem caused by it
