### ISSUE TITLE
many timeout exception at the startup stage of application,any helps?

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#2949]
when the application start, some timeout exception will be thrown, however, it will be ok after some secords, i am sure the collector always listening on the right port. so ,any comment about timeout exception at the startup stage of application?

```
2017-05-23 15:11:52 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :97 ) BEFORE com.fasterxml.jackson.databind.ObjectMapper  args:(null, null, null)
2017-05-23 15:11:52 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :151) AFTER com.fasterxml.jackson.databind.ObjectMapper  args:(null, null, null)
2017-05-23 15:11:52 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :97 ) BEFORE com.fasterxml.jackson.databind.ObjectMapper  args:()
2017-05-23 15:11:52 [DEBUG](c.n.p.b.i.BasicMethodInterceptor   :151) AFTER com.fasterxml.jackson.databind.ObjectMapper  args:()
2017-05-23 15:11:52 [INFO ](c.n.p.p.s.TcpDataSender            :196) request fail. request:TApiMetaData(agentId:sh-test-gateway, agentStartTime:1495523498481, apiId:-68, apiInfo:redis.clients.jedis.Jedis.zadd(java.lang.String key, java.util.Map scoreMembers, redis.clients.jedis.params.sortedset.ZAddParams params), line:1404, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
	at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:745)
[2017-05-23 15:11:53.008][ WARN][shawn-local][gateway][4352][localhost-startStop-1][com.ebao.v4.boot.core][txid=0][spid=0][line=59]:version file can not be read,use default dev-local-ver/2017-05-23 15:11:53
2017-05-23 15:11:53 [INFO ](c.n.p.p.s.TcpDataSender            :196) request fail. request:TApiMetaData(agentId:sh-test-gateway, agentStartTime:1495523498481, apiId:-89, apiInfo:redis.clients.jedis.Jedis.zremrangeByScore(java.lang.String key, double start, double end), line:2275, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
	at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:745)
2017-05-23 15:11:53 [INFO ](c.n.p.p.s.TcpDataSender            :196) request fail. request:TApiMetaData(agentId:sh-test-gateway, agentStartTime:1495523498481, apiId:-91, apiInfo:redis.clients.jedis.Jedis.zinterstore(java.lang.String dstkey, java.lang.String[] sets), line:2390, type:0) Caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
	at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by koo-taejin** [comment]
Hi aximo

It can happen with a lot of resources at the start of the application.
You do not have to worry about failures because they automatically resend metadata.

If you are worried about the log, you can use better server, or avoiding many requests immediately after the start of the application.

thanks .
