### ISSUE TITLE
ClassLoader deadlock still exists in jdk1.6

### ISSUE THREAD

**Issue by zhangzhaoyu** [naver/pinpoint#2957]
Hi, @emeroad @koo-taejin After your commits for issue  #2862, I pulled the newest code of the master branch and  tested it with jdk1.6, today.  I restarted my application dozens of times, the deadlock appeared less than the testing with pinpoint agent 1.6.0 version. The deadlock only took about **ten percent** of the total tests.

It seems your commits  for #2881 issue had an effect. The below is the newest deadlock stack log, It maybe can help you to find out the problem.

[jstack.txt](https://github.com/naver/pinpoint/files/1027845/jstack.txt)

Preloading the needed classes seemed can resolve the problem. Because of the difficulity debug for multi threads program, it is hard for me to find out which classess should be preloaded first.

**Comment by koo-taejin** [comment]
Hi zhangzhaoyu 

I will look into the log and see if I can preload it.

To be more specific, In JDK 1.6 we conclude that can reduce the deadlock, but can not completely solve it.
(I tested monitor exit with Unsafe and tested custom classloaders created by others. )

We have concluded that we solve the problem by preloading the possible deadlocks.

Thank you very much for posting the log every time.

**Comment by koo-taejin** [comment]
Can I get agent's log when deadlock occured 

According to thead dump which you posted. it seems to have already been loaded in the preload section.
So I wonder if an exception occurred or what exception occurred.

thanks.

**Comment by zhangzhaoyu** [comment]
@koo-taejin Hi, I tested it again. It is so difficult to make the bug recur ...。Three different place logs:
1. **console log(stdout)**, I will just give you the last dozens lines where the application was stopped.
```
10:15:51,651 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.zookeeper] to WARN
10:15:51,651 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.I0Itec.zkclient] to WARN
10:15:51,651 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.alibaba.dubbo] to WARN
10:15:51,651 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate.validator] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.core] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.beans.factory] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.context] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.aop] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.jdbc] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.transaction.annotation] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [o.springframework.web.servlet.mvc] to WARN
10:15:51,652 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [runqianReportLogger] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.abchina.pancloud] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.commons.digeste] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.alisoft.xplatform.asf] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.mybatis.spring] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.ibatis] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Connection] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [java.sql.Statement] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.abchina.pancloud.integration] to WARN
10:15:51,653 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf.ehcache] to WARN
10:15:51,654 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.zookeeper] to false
10:15:51,654 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.zookeeper]
10:15:51,655 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
10:15:51,655 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:15:51,655 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [file—debug] to Logger[ROOT]
10:15:51,655 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [file—error] to Logger[ROOT]
10:15:51,655 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ElogCollectorAppender] to Logger[ROOT]
10:15:51,655 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:15:51,656 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@14f79cb - Registering current configuration as safe fallback point

2017-05-26 10:15:52 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spring.beans.name.pattern=null
2017-05-26 10:15:52 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spring.beans.class.pattern=null
2017-05-26 10:15:52 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spring.beans.annotation=null
2017-05-26 10:15:52 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spring.beans.[0-9]+(.scope|.base-packages|.name.pattern|.class.pattern|.annotation)={profiler.spring.beans.1.name.pattern=, profiler.spring.beans.1.class.p
attern=, profiler.spring.beans.1.base-packages=, profiler.spring.beans.1.annotation=org.springframework.stereotype.Controller,org.springframework.stereotype.Service,org.springframework.stereotype.Repository, profiler.spring.beans.1.scope=component-scan}

```
2. **pinpoint agent log dir**  (~/pinpoint-agent-1.7.0/logs/), when the console log was blocked, the pinpoint agent gives the below exception:
```
2017-05-26 10:15:51 [INFO ](.n.p.p.c.p.s.j.MemoryMetricProvider) loaded : HotSpot's Parallel (Old) gc memory metrics
2017-05-26 10:15:51 [INFO ](n.p.p.c.p.s.c.CpuLoadMetricProvider) loaded : CpuLoadMetric for Oracle Java 1.6
2017-05-26 10:15:51 [INFO ](.p.c.p.s.d.DataSourceMetricProvider) loaded : Default DataSourceMetric
2017-05-26 10:15:51 [INFO ](n.p.p.c.m.DefaultApplicationContext) spanDataSender:com.navercorp.pinpoint.profiler.sender.UdpDataSender@1e2c841
2017-05-26 10:15:51 [INFO ](n.p.p.c.m.DefaultApplicationContext) statDataSender:com.navercorp.pinpoint.profiler.sender.UdpDataSender@1c958af
2017-05-26 10:15:51 [INFO ](n.p.p.c.m.DefaultApplicationContext) clientFactory:com.navercorp.pinpoint.rpc.client.DefaultPinpointClientFactory@1dd7736
2017-05-26 10:15:51 [INFO ](n.p.p.c.m.DefaultApplicationContext) client:com.navercorp.pinpoint.rpc.client.DefaultPinpointClient@bd93cd
2017-05-26 10:15:51 [INFO ](n.p.p.c.m.DefaultApplicationContext) tcpDataSender:com.navercorp.pinpoint.profiler.sender.TcpDataSender@3299f6
2017-05-26 10:15:51 [INFO ](n.p.p.c.m.DefaultApplicationContext) agentInformation:AgentInformation{agentId='sjsh_jf_service_88', applicationName='sjsh_dubbo_jf_service', startTime=1495764949414, pid=18235, machineName='zhangzhaoyu', hostIp='fe80:0:0:0:eab1:fcff:fe1d:5a1a%3', serverType=DUBBO_PROVIDER, jvmVersion='1.6.0_45', agentVersion='1.7.0-SNAPSHOT'}
2017-05-26 10:15:51 [INFO ](c.n.p.p.DefaultAgent               ) Starting pinpoint Agent.
2017-05-26 10:15:51 [INFO ](c.n.p.p.m.DefaultAgentStatMonitor  ) AgentStat monitor started
2017-05-26 10:15:51 [INFO ](c.n.p.p.AgentInfoSender            ) Sending AgentInfo TAgentInfo(hostname:zhangzhaoyu, ip:fe80:0:0:0:eab1:fcff:fe1d:5a1a%3, ports:, agentId:sjsh_jf_service_88, applicationName:sjsh_dubbo_jf_service, serviceType:1110, pid:18235, agentVersion:1.7.0-SNAPSHOT, vmVersion:1.6.0_45, startTimestamp:1495764949414, jvmInfo:TJvmInfo(version:0, vmVersion:1.6.0_45, gcType:PARALLEL))
2017-05-26 10:15:56 [INFO ](c.n.p.p.s.TcpDataSender            ) request fail. request:TApiMetaData(agentId:sjsh_jf_service_88, agentStartTime:1495764949414, apiId:2, apiInfo:org.mybatis.spring.SqlSessionTemplate.selectMap(java.lang.String statement, java.lang.Object parameter, java.lang.String mapKey), line:173, type:0) Caused:null
org.jboss.netty.handler.timeout.WriteTimeoutException
	at org.jboss.netty.handler.timeout.WriteTimeoutHandler.<clinit>(WriteTimeoutHandler.java:79)
	at com.navercorp.pinpoint.rpc.client.PinpointClientPipelineFactory.getPipeline(PinpointClientPipelineFactory.java:57)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:206)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientFactory.connect(DefaultPinpointClientFactory.java:219)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientFactory.connect(DefaultPinpointClientFactory.java:215)
	at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:50)
	at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:35)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:78)
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:73)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
2017-05-26 10:24:08 [INFO ](c.n.p.p.DefaultAgent               ) Stopping pinpoint Agent.
2017-05-26 10:24:11 [INFO ](c.n.p.p.AgentInfoSender            ) AgentInfoSender stopped
2017-05-26 10:24:14 [INFO ](c.n.p.p.m.DefaultAgentStatMonitor  ) AgentStat monitor stopped
2017-05-26 10:24:14 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    ) Pinpoint-UdpSpanDataExecutor(15-0) stopped.
2017-05-26 10:24:14 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    ) Pinpoint-UdpStatDataExecutor(16-0) stopped.
2017-05-26 10:24:14 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    ) Pinpoint-TcpDataExecutor(14-0) stopped.
2017-05-26 10:24:14 [INFO ](.n.p.r.c.PinpointClientHandlerState) DefaultPinpointClientHandler@186f3b3 stateTo() completed. Socket state change success(updateWanted:BEING_CLOSE_BY_CLIENT ,before:RUN_DUPLEX ,current:BEING_CLOSE_BY_CLIENT).
2017-05-26 10:24:17 [INFO ](c.n.p.p.s.TcpDataSender            ) request fail. request:TApiMetaData(agentId:sjsh_jf_service_88, agentStartTime:1495764949414, apiId:-3, apiInfo:org.mybatis.spring.SqlSessionTemplate.selectMap(java.lang.String statement, java.lang.Object parameter, java.lang.String mapKey, org.apache.ibatis.session.RowBounds rowBounds), line:180, type:0) Caused:null
java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.channel.SimpleChannelDownstreamHandler.closeRequested(SimpleChannelDownstreamHandler.java:150)
	at org.jboss.netty.channel.SimpleChannelDownstreamHandler.handleDownstream(SimpleChannelDownstreamHandler.java:76)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.channel.SimpleChannelHandler.closeRequested(SimpleChannelHandler.java:334)
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:260)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.close(Channels.java:812)
	at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:205)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientHandler.closeChannel(DefaultPinpointClientHandler.java:511)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientHandler.close(DefaultPinpointClientHandler.java:495)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.close(DefaultPinpointClient.java:216)
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.closeTcpDataSender(DefaultApplicationContext.java:225)
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.close(DefaultApplicationContext.java:215)
	at com.navercorp.pinpoint.profiler.DefaultAgent.stop(DefaultAgent.java:196)
	at com.navercorp.pinpoint.profiler.DefaultAgent.stop(DefaultAgent.java:183)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter$1.run(PinpointStarter.java:173)
	at java.lang.Thread.run(Thread.java:662)

```

3. **jstack thread log**
[jstack.txt](https://github.com/naver/pinpoint/files/1030680/jstack.txt)

I have tried about ten times when the deadlock came out. I hope those can help you.

**Comment by koo-taejin** [comment]
I need a full log of the pinpoint agent log. If possible, please post the log.'

thanks :)

**Comment by zhangzhaoyu** [comment]
Ok, the below is :
1. pinpoint-agent log
[jf-serivce-error.2017-05-26_0.txt](https://github.com/naver/pinpoint/files/1031016/jf-serivce-error.2017-05-26_0.txt)


2. another my application log by slf4j which was storeed in file:
[sjsh_jf_service_88-pinpoint.txt](https://github.com/naver/pinpoint/files/1031017/sjsh_jf_service_88-pinpoint.txt)


**It seems it has something wrong with oracle jdbc.**

**Comment by qingnianban** [comment]
Has the problem been solved?

**Comment by koo-taejin** [comment]
@qingnianban 
We have reduced the deadlock situation a lot compared to the first, but we have not been able to fully resolve it.
It is recommended to use JDK 1.7+ if possible. In this case, ideadlock will not occur.

**Comment by koo-taejin** [comment]
hi @qingnianban 

added function of selecting profiler's parent's classloader.
Through this function, I expect that deadlock will not occur.

TODO : must be set following option
```
# select parent classloader (BOOTSTRAP / EXTENSION / SYSTEM)
profiler.classloader.parent =

# SYSTEM: Same as before so this options can occur deadlock. (default)
# EXTENSION: use extension class loader (recommended)
# BOOTSTRAP: use the bootstrap class loader
```

You can merge link pull request(https://github.com/naver/pinpoint/pull/3676) into your environment or use this branch (https://github.com/koo-taejin/pinpoint/tree/%23prevent_deadlock)
Please test you're environment.

It will not merge to  master branch. cause there is a insufficient.
However, if it is confirmed that there is no problem, I plan to do a little more work on the code.

thanks.
