### ISSUE TITLE
Requested row out of range for row lock on HRegion AgentStatV2

### ISSUE THREAD

**Issue by fchenxi** [naver/pinpoint#3007]
#### Environment

* Pinpoint version:1.6.0
* OS, WAS, affected library, etc: centos 6.5, hadoop-2.6.2,hbase-1.0.1,Zookeeper-3.4.6,jdk1.7.0_67
* Additional details (e.g. how your collector/web is set up):
When the pinpoint-1.6.0 collector and web started, after restart the hbase cluster, then continuous  "Requested row out of range for row lock on HRegion " logs come out.
#### Additional Info

continuous err logs follow:
2017-06-06 15:05:04,814 WARN  [B.defaultRpcServer.handler=2,queue=2,port=16020] regionserver.HRegion: Failed getting lock in batch put, row=\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_
org.apache.hadoop.hbase.regionserver.WrongRegionException: Requested row out of range for row lock on HRegion AgentStatV2,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492655057427.558553b993512cf42409c475572511ec., startKey='=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', getEndKey()='>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', row='\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_'
	at org.apache.hadoop.hbase.regionserver.HRegion.checkRow(HRegion.java:3853)
	at org.apache.hadoop.hbase.regionserver.HRegion.getRowLockInternal(HRegion.java:3884)
	at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2614)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2478)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2432)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2436)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doBatchOp(RSRpcServices.java:642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doNonAtomicRegionMutation(RSRpcServices.java:606)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:1836)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31451)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)
2017-06-06 15:05:04,814 WARN  [B.defaultRpcServer.handler=13,queue=1,port=16020] regionserver.HRegion: Failed getting lock in batch put, row=\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_
org.apache.hadoop.hbase.regionserver.WrongRegionException: Requested row out of range for row lock on HRegion AgentStatV2,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492655057427.558553b993512cf42409c475572511ec., startKey='=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', getEndKey()='>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', row='\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_'
	at org.apache.hadoop.hbase.regionserver.HRegion.checkRow(HRegion.java:3853)
	at org.apache.hadoop.hbase.regionserver.HRegion.getRowLockInternal(HRegion.java:3884)
	at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2614)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2478)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2432)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2436)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doBatchOp(RSRpcServices.java:642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doNonAtomicRegionMutation(RSRpcServices.java:606)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:1836)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31451)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)
2017-06-06 15:05:04,814 WARN  [B.defaultRpcServer.handler=2,queue=2,port=16020] regionserver.HRegion: Failed getting lock in batch put, row=\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_
org.apache.hadoop.hbase.regionserver.WrongRegionException: Requested row out of range for row lock on HRegion AgentStatV2,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492655057427.558553b993512cf42409c475572511ec., startKey='=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', getEndKey()='>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', row='\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_'
	at org.apache.hadoop.hbase.regionserver.HRegion.checkRow(HRegion.java:3853)
	at org.apache.hadoop.hbase.regionserver.HRegion.getRowLockInternal(HRegion.java:3884)
	at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2614)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2478)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2432)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2436)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doBatchOp(RSRpcServices.java:642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doNonAtomicRegionMutation(RSRpcServices.java:606)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:1836)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31451)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)
2017-06-06 15:05:04,814 WARN  [B.defaultRpcServer.handler=13,queue=1,port=16020] regionserver.HRegion: Failed getting lock in batch put, row=\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_
org.apache.hadoop.hbase.regionserver.WrongRegionException: Requested row out of range for row lock on HRegion AgentStatV2,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492655057427.558553b993512cf42409c475572511ec., startKey='=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', getEndKey()='>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', row='\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_'
	at org.apache.hadoop.hbase.regionserver.HRegion.checkRow(HRegion.java:3853)
	at org.apache.hadoop.hbase.regionserver.HRegion.getRowLockInternal(HRegion.java:3884)
	at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2614)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2478)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2432)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2436)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doBatchOp(RSRpcServices.java:642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doNonAtomicRegionMutation(RSRpcServices.java:606)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:1836)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31451)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)
2017-06-06 15:05:04,814 WARN  [B.defaultRpcServer.handler=2,queue=2,port=16020] regionserver.HRegion: Failed getting lock in batch put, row=\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_
org.apache.hadoop.hbase.regionserver.WrongRegionException: Requested row out of range for row lock on HRegion AgentStatV2,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1492655057427.558553b993512cf42409c475572511ec., startKey='=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', getEndKey()='>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', row='\x0E172.17.210.140_3020\x00\x00\x00\x00\x00\x02\x7F\xFF\xFE\xA3\x83\xF59_'
	at org.apache.hadoop.hbase.regionserver.HRegion.checkRow(HRegion.java:3853)
	at org.apache.hadoop.hbase.regionserver.HRegion.getRowLockInternal(HRegion.java:3884)
	at org.apache.hadoop.hbase.regionserver.HRegion.doMiniBatchMutation(HRegion.java:2614)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2478)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2432)
	at org.apache.hadoop.hbase.regionserver.HRegion.batchMutate(HRegion.java:2436)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doBatchOp(RSRpcServices.java:642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.doNonAtomicRegionMutation(RSRpcServices.java:606)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.multi(RSRpcServices.java:1836)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31451)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
	at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
	at java.lang.Thread.run(Thread.java:745)

Thanks for reply!

**Comment by Xylus** [comment]
Hi @fchenxi 
This looks like an error related to hbase.
A quick google search seems to point the issue towards the client not being able to find the right region to insert, and suggestions to try `hbck` and see if any inconsistencies show up.

**Comment by fchenxi** [comment]
Thanks @Xylus suggestions.
Actually i have already try 'hbase hbck -details' to check inconsistencies, it prints ' AgentStatV2 is okay. Number of regions: 64'.
It maybe pinpoint-1.6.0 is incompatible with hbase-1.0.1? or others?

**Comment by Xylus** [comment]
@fchenxi thanks for testing it out.
We haven't really tested 1.6.0 against hbase 1.0.1 (please see the hbase compatibility table under [here](https://github.com/naver/pinpoint#installation)) so that might be it although I'm not entirely sure if that's the issue.

**Comment by fchenxi** [comment]
@Xylus , i tested pinpint-1.6.0 with hbase-1.2.5,hbae-1.2.6 for a week, it`s result is nice.

**Comment by Xylus** [comment]
Awesome, glad to hear it's working well :+1:
