### ISSUE TITLE
pinpoint collector error

### ISSUE THREAD

**Issue by cookooc** [naver/pinpoint#3042]
# **java.lang.NullPointerException**
2017-06-15 14:41:11 [WARN ](.h.AgentLifeCycleChangeEventHandler) AgentLifeCycleChangeEventHandler exceptionCaught(). pinpointServer:DefaultPinpointServer@4035352d(remote:/127.0.0.1:49943, state:UNEXPECTED_CLOSE_BY_CLIENT), code:UNEXPECTED_CLOSE_BY_CLIENT. error: null.
java.lang.NullPointerException
	at com.navercorp.pinpoint.collector.rpc.handler.AgentEventHandler.handleEvent(AgentEventHandler.java:81)
	at com.navercorp.pinpoint.collector.rpc.handler.AgentEventHandler.handleEvent(AgentEventHandler.java:66)
	at com.navercorp.pinpoint.collector.rpc.handler.AgentLifeCycleChangeEventHandler.eventPerformed(AgentLifeCycleChangeEventHandler.java:58)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.executeChangeEventHandler(DefaultPinpointServerState.java:125)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.to(DefaultPinpointServerState.java:114)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.toUnexpectedClosedByPeer(DefaultPinpointServerState.java:94)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServer.stop(DefaultPinpointServer.java:144)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.channelDisconnected(PinpointServerAcceptor.java:377)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:120)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.channelDisconnected(FrameDecoder.java:365)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by Xylus** [comment]
Hi @cookooc 
Thanks for reporting.
Which collector version are you using? and also the agent version that caused the exception.
Thanks

**Comment by cookooc** [comment]
collector version 1.6.1 and agent version 1.6.1
