### ISSUE TITLE
unable to deploy the collector

### ISSUE THREAD

**Issue by vidyasagarguduru** [naver/pinpoint#307]
Got the latest version and built the war files, when trying to deploy the collector war in tomcat-7 getting the below exception. Any Idea how can I fix it. 

Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/common/ServiceType$1
	at com.navercorp.pinpoint.common.ServiceType.<init>(ServiceType.java:67)
	at com.navercorp.pinpoint.common.ServiceType.of(ServiceType.java:46)
	at com.navercorp.pinpoint.common.ServiceType.of(ServiceType.java:42)
	at com.navercorp.pinpoint.common.ServiceType.<clinit>(ServiceType.java:214)
	at com.navercorp.pinpoint.plugin.jdk.http.JdkHttpConstants.<clinit>(JdkHttpConstants.java:26)
	at com.navercorp.pinpoint.plugin.jdk.http.JdkHttpTypeProvider.setup(JdkHttpTypeProvider.java:30)
	at com.navercorp.pinpoint.common.TypeProviderLoader.load(TypeProviderLoader.java:81)
	at com.navercorp.pinpoint.common.TypeProviderLoader.load(TypeProviderLoader.java:63)
	at com.navercorp.pinpoint.common.service.DefaultTypeLoaderService.<init>(DefaultTypeLoaderService.java:63)
	at com.navercorp.pinpoint.common.service.DefaultTypeLoaderService.<init>(DefaultTypeLoaderService.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 62 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.common.ServiceType$1
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 77 more

**Comment by vidyasagarguduru** [comment]
It is happening when spring creating the bean 'typeLoaderService'





Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.navercorp.pinpoint.common.service.DefaultTypeLoaderService]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: com/navercorp/pinpoint/common/ServiceType$1
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1000)
	... 60 more
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/common/ServiceType$1
	at com.navercorp.pinpoint.common.ServiceType.<init>(ServiceType.java:67)
	at com.navercorp.pinpoint.common.ServiceType.of(ServiceType.java:46)
	at com.navercorp.pinpoint.common.ServiceType.of(ServiceType.java:42)
	at com.navercorp.pinpoint.common.ServiceType.<clinit>(ServiceType.java:214)
	at com.navercorp.pinpoint.plugin.jdk.http.JdkHttpConstants.<clinit>(JdkHttpConstants.java:26)
	at com.navercorp.pinpoint.plugin.jdk.http.JdkHttpTypeProvider.setup(JdkHttpTypeProvider.java:30)
	at com.navercorp.pinpoint.common.TypeProviderLoader.load(TypeProviderLoader.java:81)
	at com.navercorp.pinpoint.common.TypeProviderLoader.load(TypeProviderLoader.java:63)
	at com.navercorp.pinpoint.common.service.DefaultTypeLoaderService.<init>(DefaultTypeLoaderService.java:63)
	at com.navercorp.pinpoint.common.service.DefaultTypeLoaderService.<init>(DefaultTypeLoaderService.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 62 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.common.ServiceType$1
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 77 more

**Comment by vidyasagarguduru** [comment]
I am able to solve this issue. 
PinPointCommons did not build properly so that class is missing in the jars. 

Thanks.

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [pinpoint] unable to deploy the collector (#307)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>
--------------------------------------------

**Comment by vidyasagarguduru** [comment]
Sorry, I can not understand it.

**Comment by nstopkimsk** [comment]
@vidyasagarguduru Have you solved this issues?
