### ISSUE TITLE
Corrupted(Invalid Sequence) - Unable to trace DataStax Cassandra Batch Sql statement - CassandraStatementExecuteQueryInterceptor

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3090]
During in one of my transaction I am observing the Corrupted(Invalid Sequence) for couple of my transactions, when looking at the agent logs we had observed the below exception 

2017-06-27 15:07:50 [WARN ](draStatementExecuteQueryInterceptor) com.datastax.driver.core.BatchStatement cannot be cast to java.lang.String
java.lang.ClassCastException: com.datastax.driver.core.BatchStatement cannot be cast to java.lang.String
    at com.navercorp.pinpoint.plugin.cassandra.interceptor.CassandraStatementExecuteQueryInterceptor.before(CassandraStatementExecuteQueryInterceptor.java:102)
    at com.navercorp.pinpoint.bootstrap.interceptor.scope.ExceptionHandleScopedInterceptor.before(ExceptionHandleScopedInterceptor.java:57)
    at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java)
    at com.target.oms.allocation.dao.NodeZonesDao.persist(NodeZonesDao.java:64)
    at com.target.oms.allocation.dao.NodeZonesDao.save(NodeZonesDao.java:53)
    at com.target.oms.allocation.dao.NodeZonesDao.save(NodeZonesDao.java:49)
    at com.target.oms.allocation.dao.NodeZonesDao$$FastClassBySpringCGLIB$$90186cce.invoke(<generated>

From the exception its pretty clear that Pinpoint agent does not trace the Cassandra Datastax api call for Batch Sql statements 

Specific code in CassandraStatementExecuteQueryInterceptor  here where we are observing the issue 

String sql;
            if (args[0] instanceof BoundStatement) {
                sql = ((BoundStatement) args[0]).preparedStatement().getQueryString();
            } else if (args[0] instanceof RegularStatement) {
                sql = ((RegularStatement) args[0]).getQueryString();
            } else {
                // we have string
                sql = (String) args[0];
            }

Kindly let me know If I have misinterpreted anything here

**Comment by Xylus** [comment]
Looks like a bug in the Cassandra datastax plugin.
Thanks for reporting!
