### ISSUE TITLE
pinpoint web start failed

### ISSUE THREAD

**Issue by achiz** [naver/pinpoint#3190]
#### Description

안녕하세요. pinpoint 에 관심이 생겨서 사용중인 어플리케이션 성능테스트를 위해서 
pinpoint 를 설치하였습니다.

quickstart 가이드대로 참고했구요. 환경은 윈도우입니다.

hbase 셋팅 후 quickstart 폴더에있는 실행배치로 순서대로 실행했습니다.

test-app 을 제외한 hbase, collector, web 순서대로 실행했구요.

hbase 셋팅을 제외한 나머지 설정 값들은 건들지 않았습니다.

테스트 버전은 1.7.0 과 1.6.2 stable 버전입니다.

![pinpoint](https://user-images.githubusercontent.com/2038117/28648398-839c05ea-72a8-11e7-8ed5-290ebb4c77c4.PNG)

제가봤을때는 web 을 제외한 나머지는 정상구동되었으나 web 부분만 구동때  아래와 같은 에러가 나옵니다.

web 로그 마지막부분을 보여드리면

`2017-07-26 23:09:06 [WARN ](o.s.w.c.s.XmlWebApplicationContext :550) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationStatController.ApplicationTransactionController' defined in file [H:\Download\pinpoint-master\quickstart\web\target\deploy\WEB-INF\classes\com\navercorp\pinpoint\web\controller\ApplicationStatController$ApplicationTransactionController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.navercorp.pinpoint.web.service.stat.ApplicationTransactionService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2017-07-26 23:09:06 [ERROR](o.s.w.s.DispatcherServlet          :502) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationStatController.ApplicationTransactionController' defined in file [H:\Download\pinpoint-master\quickstart\web\target\deploy\WEB-INF\classes\com\navercorp\pinpoint\web\controller\ApplicationStatController$ApplicationTransactionController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.navercorp.pinpoint.web.service.stat.ApplicationTransactionService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:138)
	at javax.servlet.GenericServlet.init(GenericServlet.java:160)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1280)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1193)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1088)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5176)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5460)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.navercorp.pinpoint.web.service.stat.ApplicationTransactionService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1486)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 31 more
2017-07-26 23:14:05 [DEBUG](c.n.p.r.s.PinpointServerAcceptor   :55 ) ping write success channel:[id: 0xc2f4559d, /192.168.175.1:62247 => /192.168.175.1:9997]
2017-07-26 23:14:05 [DEBUG](c.n.p.r.s.PinpointServerAcceptor   :282) newPingTimeout
2017-07-26 23:14:05 [DEBUG](c.n.p.r.c.PacketDecoder            :96 ) receive pong. [id: 0xc2f4559d, /192.168.175.1:62247 => /192.168.175.1:9997]
2017-07-26 23:14:06 [DEBUG](c.n.p.r.s.DefaultPinpointServer    :424) DefaultPinpointServer@5f6d0c94 handlePingPacket() started. packet:PingPacket{pingId:1(RUN_DUPLEX)}
2017-07-26 23:14:06 [DEBUG](c.n.p.w.c.c.ClusterAcceptor        :102) ping received PingPacket{pingId:1(RUN_DUPLEX)} DefaultPinpointServer@5f6d0c94(remote:/192.168.175.1:62247, state:RUN_DUPLEX) 
2017-07-26 23:14:06 [DEBUG](c.n.p.r.s.DefaultPinpointServer    :55 ) pong write success. channel:[id: 0xc2f4559d, /192.168.175.1:62247 => /192.168.175.1:9997]
`

어떤문제인지 감이 안잡혀서 조언을 구합니다.

#### Environment

* Pinpoint version: stable, 1.7.0-snapshot
* OS, WAS, affected library, etc: windows 10, 
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
@achiz 안녕하세요,
저희 master branch는 개발 branch이기 때문에 빌드가 실패하거나 실행이 되지 않을 수 있습니다.
(위 이슈는 master branch 소스의 문제인 것 같습니다)

테스트 및 운영을 위해서는 가급적 stable한 릴리즈(현재 1.6.2) 사용을 부탁드립니다.

감사합니다.

**Comment by achiz** [comment]
@Xylus 빠른 답변 감사드립니다.

위에 언급하였지만 stable 1.6.2 도 똑같은 문제가 발생하여 문의드렸습니다.

**Comment by Xylus** [comment]
1.6.2에는 위 에러가 발생하는 `ApplicationStatController` 클래스가 없어 이슈가 발생하면 안돼야 합니다.
혹시 1.7.0-SNAPSHOT 빌드 후, 1.6.2 quickstart를 실행하시기 전에 1.6.2 소스로 재빌드 (mvn clean install) 하지 않으셨다면 재빌드 부탁드립니다.

**Comment by achiz** [comment]
@Xylus 넵 조언감사합니다. 여러버전으로 셋팅하면서 뭔가 꼬인거같네요. 테스트후 다시 피드백 드리겠습니다.

**Comment by minwoo-jung** [comment]
master에도 문제가 없도록 커밋 해두었습니다.
