### ISSUE TITLE
Message too long when sending TSpan via udp

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#3231]
our agent show logs like follows, any suggestion or help?
```
2017-08-09 13:00:07 [INFO ](c.n.p.p.s.UdpDataSender            :139) packet send error. size:895, TSpan(agentId:...

java.io.IOException: Message too long
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.navercorp.pinpoint.profiler.sender.UdpDataSender.sendPacket(UdpDataSender.java:134)
	at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
```

i also find some logs when starting:
```
2017-08-09 10:40:29 [INFO ](c.n.p.p.s.UdpDataSender            :77 ) UdpDataSender initialized. host=xxx, port=9996
2017-08-09 10:40:29 [INFO ](c.n.p.p.s.UdpDataSender            :102) DatagramSocket.setSendBufferSize() error. 1048576!=212992
2017-08-09 10:40:29 [INFO ](c.n.p.p.s.UdpDataSender            :77 ) UdpDataSender initialized. host=xxx, port=9995
2017-08-09 10:40:29 [INFO ](c.n.p.p.s.AsyncQueueingExecutor    :78 ) Pinpoint-UdpSpanDataExecutor(15-0) started.
2017-08-09 10:40:29 [INFO ](c.n.p.p.s.UdpDataSender            :102) DatagramSocket.setSendBufferSize() error. 1048576!=212992

````

**Comment by emeroad** [comment]
The max buffer size of socket is determined by the kernel.
We recommend tuning the linux kernel option.
 - https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Web_Platform/5/html/Administration_And_Configuration_Guide/jgroups-perf-udpbuffer.html
 - https://github.com/naver/pinpoint/blob/master/collector/src/main/resources/pinpoint-collector.properties
```
# change OS level read/write socket buffer size (for linux)
#sudo sysctl -w net.core.rmem_max=
#sudo sysctl -w net.core.wmem_max=
# check current values using: 
#$ /sbin/sysctl -a | grep -e rmem -e wmem
```

However, the UDP packet loss of the agent is not a problem. It is safe to ignore.
