### ISSUE TITLE
No Data 

### ISSUE THREAD

**Issue by maxiaoxian** [naver/pinpoint#3250]
web、collect、agent、hbase have been working properly
but webui show not Data

**Comment by maxiaoxian** [comment]
cut some logger ;

2017-08-16 16:34:39 [DEBUG](c.n.p.w.c.ScatterChartController   :165) fetch scatter data. RANGE=Range{from=1502872482892, to=1502872484892, range=2000}, X-Group-Unit:987, Y-Group-Unit:57, LIMIT=5000, BACKWARD_DIRECTION:false, FILTER:
2017-08-16 16:34:39 [DEBUG](w.d.h.HbaseApplicationTraceIndexDao:293) scanTraceScatterDataMadeOfDotGroup
2017-08-16 16:34:39 [DEBUG](c.n.p.c.h.HbaseTemplate2           :564) DistributedScanner createTime: 74ms
2017-08-16 16:34:39 [DEBUG](c.n.p.c.h.HbaseTemplate2           :572) DistributedScanner scanTime: 31ms
2017-08-16 16:34:39 [INFO ](c.n.p.w.c.ScatterChartController   :182) Fetch scatterData time : 108ms
2017-08-16 16:34:39 [DEBUG](c.n.p.w.d.h.HbaseMapResponseTimeDao:74 ) selectResponseTime applicationName:iCareM(STAND_ALONE:1000), Range{from=1502872184892, to=1502872484892, range=300000}
2017-08-16 16:34:39 [DEBUG](c.n.p.w.d.h.HbaseMapResponseTimeDao:94 ) scan time:Range{from=1502872139999, to=1502872440000, range s=300} 
2017-08-16 16:34:39 [DEBUG](c.n.p.c.h.HbaseTemplate2           :564) DistributedScanner createTime: 6ms
2017-08-16 16:34:39 [DEBUG](c.n.p.c.h.HbaseTemplate2           :572) DistributedScanner scanTime: 10ms
2017-08-16 16:34:39 [DEBUG](c.n.p.w.d.h.HbaseMapResponseTimeDao:81 ) Self data []
2017-08-16 16:34:40 [INFO ](c.n.p.w.w.ActiveThreadCountHandler :306) ActiveThreadTimerTask started.
2017-08-16 16:34:40 [INFO ](c.n.p.w.w.WorkerActiveManager      :148) AgentCheckTimerTask started.
2017-08-16 16:34:40 [INFO ](c.n.p.w.w.WorkerActiveManager      :121) ReactiveTimerTask started.
2017-08-16 16:34:40 [INFO ](ActiveThreadCountResponseAggregator:167) activeWorker applicationName:iCareM, agentId:1
2017-08-16 16:34:40 [INFO ](c.n.p.w.w.ActiveThreadCountWorker  :126) ActiveThreadCountWorker reactive. applicationName:iCareM, agentId:1
2017-08-16 16:34:40 [WARN ](c.n.p.w.c.ClusterManager           :165) iCareM/1/1502850908333 couldn't find agent.
2017-08-16 16:34:40 [INFO ](c.n.p.w.w.WorkerActiveManager      :91 ) addReactiveWorker. applicationName:iCareM, agent:1
2017-08-16 16:34:40 [INFO ](c.n.p.w.w.WorkerActiveManager      :101) addReactiveWorker turnOn:true
2017-08-16 16:34:41 [INFO ](c.n.p.w.w.ActiveThreadCountHandler :306) ActiveThreadTimerTask started.
2017-08-16 16:34:41 [DEBUG](c.n.p.w.c.ScatterChartController   :165) fetch scatter data. RANGE=Range{from=1502872484892, to=1502872486892, range=2000}, X-Group-Unit:987, Y-Group-Unit:57, LIMIT=5000, BACKWARD_DIRECTION:false, FILTER:
2017-08-16 16:34:41 [DEBUG](w.d.h.HbaseApplicationTraceIndexDao:293) scanTraceScatterDataMadeOfDotGroup
2017-08-16 16:34:41 [DEBUG](c.n.p.c.h.HbaseTemplate2           :564) DistributedScanner createTime: 65ms
2017-08-16 16:34:41 [DEBUG](c.n.p.c.h.HbaseTemplate2           :572) DistributedScanner scanTime: 27ms
2017-08-16 16:34:41 [INFO ](c.n.p.w.c.ScatterChartController   :182) Fetch scatterData time : 95ms
2017-08-16 16:34:41 [DEBUG](c.n.p.w.d.h.HbaseMapResponseTimeDao:74 ) selectResponseTime applicationName:iCareM(STAND_ALONE:1000), Range{from=1502872186892, to=1502872486892, range=300000}
2017-08-16 16:34:41 [DEBUG](c.n.p.w.d.h.HbaseMapResponseTimeDao:94 ) scan time:Range{from=1502872139999, to=1502872440000, range s=300} 
2017-08-16 16:34:41 [DEBUG](c.n.p.c.h.HbaseTemplate2           :564) DistributedScanner createTime: 5ms
2017-08-16 16:34:41 [DEBUG](c.n.p.c.h.HbaseTemplate2           :572) DistributedScanner scanTime: 7ms
2017-08-16 16:34:41 [DEBUG](c.n.p.w.d.h.HbaseMapResponseTimeDao:81 ) Self data []
2017-08-16 16:34:42 [INFO ](c.n.p.w.w.ActiveThreadCountHandler :306) ActiveThreadTimerTask started.
2017-08-16 16:34:43 [INFO ](c.n.p.w.w.ActiveThreadCountHandler :306) ActiveThreadTimerTask started.

**Comment by maxiaoxian** [comment]
agent exception logger :
2017-08-16 16:52:56 [INFO ](c.n.p.p.s.TcpDataSender            :230) request fail. request:RetryMessage{retryCount=2, maxRetryCount=3, bytes=121, messageDescription='TApiMetaData'}, caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
	at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Unknown Source)

**Comment by maxiaoxian** [comment]
but the quickstart testapp is right

**Comment by maxiaoxian** [comment]
Does local collection have an impact?

**Comment by maxiaoxian** [comment]
Does Eclipse run agent have an impact?

**Comment by Xylus** [comment]
Hi @maxiaoxian 
From your agent log, it looks like the agent cannot connect to the collector. Please check your agent's *pinpoint.config* tcp/udp port settings and the ports your collector is listening to.

**Comment by maxiaoxian** [comment]
collector listen 0.0.0.0，agent can send data, and hbase has data. only webui show no data

**Comment by maxiaoxian** [comment]
Hi @Xylus 
i use spring boot web application ,and use eclipse run it . have an impact?

**Comment by Xylus** [comment]
If you're running Tomcat on Spring Boot using eclipse, then probably yes as eclipse launches spring boot using it's own bootstrap main (I think, please correct me if I'm mistaken).
In this case, pinpoint agent does not identify the application as `SPRING_BOOT` and will not register tomcat class file transformers.

You should be able to get around this by setting the following options in *pinpoint.config*:
```
profiler.applicationservertype=SPRING_BOOT
profiler.tomcat.conditional.transform=false
```

**Comment by maxiaoxian** [comment]
Hi @Xylus
That's the question. 
but still thow PinpointSocketException: timeout

**Comment by Xylus** [comment]
What's the question? I don't get it.
If you're asking why it's throwing timeout exception, please see [this](https://github.com/naver/pinpoint/issues/3250#issuecomment-322719771) comment.
If you're asking if spring boot web application using eclipse could cause issues, please see [this](https://github.com/naver/pinpoint/issues/3250#issuecomment-322725011) comment.

**Comment by maxiaoxian** [comment]
The problem has already been solved, thank you.

**Comment by tonylit** [comment]
How did you solve the problem?
