### ISSUE TITLE
Pinpoint couldn't trace the libraries in Apache Spring boot - java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3417]
#### Description
Pinpoint couldn't trace the libraries with below exception - EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling - java.io.IOException: Connection reset by peer

#### Environment

* Pinpoint version: 1.6.1
* Env: Apache Spring boot, Linux 
* Additional details (e.g. how your collector/web is set up): Collector and web are running in the different boxes 

LOSE_BY_CLIENT ,before:RUN_SIMPLEX ,current:BEING_CLOSE_BY_CLIENT).
2017-09-28 04:47:27 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@212f6733 handleClosePacket() completed.
2017-09-28 04:47:27 [WARN ](o.j.n.c.SimpleChannelHandler       ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-09-28 04:47:27 [INFO ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@1f57539 channelClosed() started.
2017-09-28 04:47:27 [INFO ](h.DoNothingChannelStateEventHandler) DoNothingChannelStateEventHandler eventPerformed(). pinpointServer:DefaultPinpointServer@212f6733(remote:/127.0.0.1:59426, state:CLOSED_BY_CLIENT), code:CLOSED_BY_CLIENT

**Comment by dinesh4747** [comment]
JVM Flow details - It just consumes messages from Kafka and put it in SEDA Queue and Camel threads will process the messages from SEDA and updates the Oracle DB through JDBC 

Kindly let me know if you require any further information regarding the same

**Comment by koo-taejin** [comment]
hi dinesh4747 

This log occurs when  pinpoint connection broken between  agent and  collector or collector and web .
additionally this message is a normal procedure termination. (RUN -> BEING_CLOSE_BY_CLIENT -> CLOSED_BY_CLIENT)
I think it would be better to check why remote module was shutdowned.

**Comment by dinesh4747** [comment]
we have resolved that issue and but still we couldn't see the requests flowing through and Response chart and scatter chart is empty
