### ISSUE TITLE
Response Summary and Active thread chart are empty

### ISSUE THREAD

**Issue by GyaneshRahatekar** [naver/pinpoint#3419]
#### Environment

* Pinpoint version: 1.6.2
* OS, WAS, affected library, etc: RHEL 7.2 jboss
* Additional details (e.g. how your collector/web is set up):
hbase ,collector /web all are in one node
#### Additional Info

[ACS_10.135.136.101-pinpoint.log](https://github.com/naver/pinpoint/files/1341577/ACS_10.135.136.101-pinpoint.log)

**Comment by GyaneshRahatekar** [comment]
Response Summary and Active thread chart are empty.
I can see Java heap and memory details charts and as per the log its communicating witg agent is perfectly fine. however its showing No data for real time as well no data for response chart.
Environment
I am using Pinpoint 1.6.2 version (latest release).
jboss:
Agent is running on java 1.7
Could you please help me on this?

**Comment by koo-taejin** [comment]
hi GyaneshRahatekar 

If you look at the below logs
```
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:676)
	at com.navercorp.pinpoint.profiler.sender.UdpDataSender.sendPacket(UdpDataSender.java:134)
	at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
	at java.lang.Thread.run(Thread.java:745)
```
you can see occur exception when transfer data.
It is recommended that agent can connect to the collector's UDP ports 9995 and 9996.
and check that access is blocked by iptables or firewalls.

thanks.
