### ISSUE TITLE
Quickstart web failed start, class not found

### ISSUE THREAD

**Issue by lorenzoguglielmo** [naver/pinpoint#3429]
Hi to everyone,
trying to start quickstart installation for evaluate Pinpoint.
All the packets are on the same (brand new) machine. Everything is fine running first quickstart scripts, but fails when try to run quickstart/start-web.sh.

My env is:

uname -a:
Linux xxx.xxx.xxx 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

release:
CentOS Linux release 7.3.1611 (Core)

JAVA env:

JAVA_HOME=/usr/lib/jvm/jdk1.8.0_101
JAVA_6_HOME=/usr/lib/jvm/jdk1.6.0_45
JAVA_7_HOME=/usr/lib/jvm/jdk1.7.0_79
JAVA_8_HOME=/usr/lib/jvm/jdk1.8.0_101

After quickstart/start-web.sh is launched, the process fails, here the logs:

INFO: Initializing ProtocolHandler ["http-bio-28080"]
Oct 06, 2017 2:53:40 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Oct 06, 2017 2:53:40 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47
Oct 06, 2017 2:54:22 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/pinpoint/pinpoint-master/quickstart/web/target/deploy/WEB-INF/lib/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/pinpoint/pinpoint-master/quickstart/web/target/apache-tomcat-maven-plugin/pinpoint-web/WEB-INF/lib/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Oct 06, 2017 2:54:23 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
2017-10-06 14:54:23 [INFO ](o.s.w.c.ContextLoader              :304) Root WebApplicationContext: initialization started
2017-10-06 14:54:23 [INFO ](o.s.w.c.s.XmlWebApplicationContext :582) Refreshing Root WebApplicationContext: startup date [Fri Oct 06 14:54:23 CEST 2017]; root of context hierarchy
2017-10-06 14:54:24 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-web.xml]
2017-10-06 14:54:31 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-hbase.xml]
2017-10-06 14:54:32 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-datasource.xml]
2017-10-06 14:54:32 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-dao-config.xml]
2017-10-06 14:54:32 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-cache.xml]
2017-10-06 14:54:32 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  :317) Loading XML bean definitions from class path resource [applicationContext-websocket.xml]
2017-10-06 14:54:32 [INFO ](.s.b.f.s.DefaultListableBeanFactory:828) Overriding bean definition for bean 'spanMapper' with a different definition: replacing [Generic bean: class [com.navercorp.pinpoint.web.mapper.SpanMapper]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [/root/pinpoint/pinpoint-master/quickstart/web/target/deploy/WEB-INF/classes/com/navercorp/pinpoint/web/mapper/SpanMapper.class]] with [Generic bean: class [com.navercorp.pinpoint.web.mapper.SpanMapper]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [applicationContext-web.xml]]
2017-10-06 14:54:35 [INFO ](utowiredAnnotationBeanPostProcessor:155) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-10-06 14:54:36 [DEBUG](o.a.i.l.LogFactory                 :128) Logging initialized using 'class org.apache.ibatis.logging.slf4j.Slf4jImpl' adapter.
2017-10-06 14:54:36 [WARN ](o.s.w.c.s.XmlWebApplicationContext :550) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseAgentEventDao': Unsatisfied dependency expressed through field 'hbaseOperations2'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao] for bean with name 'agentDownloadInfoDao' defined in class path resource [applicationContext-dao-config.xml]; nested exception is java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
2017-10-06 14:54:36 [ERROR](o.s.w.c.ContextLoader              :350) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseAgentEventDao': Unsatisfied dependency expressed through field 'hbaseOperations2'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao] for bean with name 'agentDownloadInfoDao' defined in class path resource [applicationContext-dao-config.xml]; nested exception is java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao] for bean with name 'agentDownloadInfoDao' defined in class path resource [applicationContext-dao-config.xml]; nested exception is java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:403)
        at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:220)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1260)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
        ... 34 more
Oct 06, 2017 2:54:36 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseAgentEventDao': Unsatisfied dependency expressed through field 'hbaseOperations2'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao] for bean with name 'agentDownloadInfoDao' defined in class path resource [applicationContext-dao-config.xml]; nested exception is java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao] for bean with name 'agentDownloadInfoDao' defined in class path resource [applicationContext-dao-config.xml]; nested exception is java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1385)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:641)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:425)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:403)
        at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:220)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1260)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
        at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:401)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1432)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1377)
        ... 34 more

Oct 06, 2017 2:54:36 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Oct 06, 2017 2:54:36 PM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [264] milliseconds.
Oct 06, 2017 2:54:36 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors

Any help would be appreciated.

**Comment by koo-taejin** [comment]
hi lorenzoguglielmo

Fixed missing part of quickstart's spring configuration.
please try it again.

thanks.

**Comment by lorenzoguglielmo** [comment]
hi koo-taejin

thank you so much for fixing it
now it works perfectly
