### ISSUE TITLE
hbase database not started , getting error 

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3473]
database not started  we are getting below error ....

 resubmits = 0 batch = installed = 1 done = 0 error = 0, /hbase/splitWAL/WALs%2Flocalhost%2C49928%2C1508757668805-splitting%2Flocalhost%252C49928%252C1508757668805.1508757684907=last_update = -1 last_version = 38 cur_worker_name = null status = in_progress incarnation = 2 resubmits = 0 batch = installed = 1 done = 0 error = 0}
2017-10-23 20:29:45,193 INFO  [main-EventThread] coordination.SplitLogManagerCoordination: task /hbase/splitWAL/RESCAN0000518704 entered state: DONE localhost,61046,1508770576214
2017-10-23 20:29:46,192 INFO  [main-EventThread] coordination.SplitLogManagerCoordination: task /hbase/splitWAL/RESCAN0000518705 entered state: DONE localhost,61046,1508770576214
2017-10-23 20:29:46,410 ERROR [main] master.HMasterCommandLine: Master exiting
java.lang.RuntimeException: Master not initialized after 200000ms seconds
        at org.apache.hadoop.hbase.util.JVMClusterUtil.startup(JVMClusterUtil.java:225)
        at org.apache.hadoop.hbase.LocalHBaseCluster.startup(LocalHBaseCluster.java:409)
        at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:225)
        at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:137)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:126)
        at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2610)
2017-10-23 20:29:46,412 INFO  [Thread-5] regionserver.ShutdownHook: Shutdown hook starting; hbase.shutdown.hook=true; fsShutdownHook=org.apache.hadoop.fs.FileSystem$Cache$ClientFinalizer@5b367418
2017-10-23 20:29:46,412 INFO  [Thread-5] regionserver.ShutdownHook: Starting fs shutdown hook thread.
2017-10-23 20:29:46,413 INFO  [Thread-5] regionserver.ShutdownHook: Shutdown hook finished.

**Comment by minwoo-jung** [comment]
Where do you see this log?

**Comment by minyk** [comment]
I think the problem is this: 

```
2017-10-23 20:29:46,410 ERROR [main] master.HMasterCommandLine: Master exiting
java.lang.RuntimeException: Master not initialized after 200000ms seconds
```

Somehow HBase init is too slow( > 200000ms) than expected. What is the environments for HBase ? VM or physical, how many cpus and/or mem ?

**Comment by prashantnitt07** [comment]
hi ,
**HBase** Env : VM (Linux)

**Memory -**
             total       used       free     shared    buffers     cached
Mem:            15         12          2          0          0          9
-/+ buffers/cache:          2         13
Swap:           15          0         15


**CPU**

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
Stepping:              4
CPU MHz:               2992.788
BogoMIPS:              5985.57
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-3

**Comment by minyk** [comment]
@prashantnitt07 It seems good to me. Could you provide more(or full) log here?
