### ISSUE TITLE
How can I set proxy for pinpoint

### ISSUE THREAD

**Issue by teotia39** [naver/pinpoint#3488]
##########
while Installing pinpoint :    " ./mvnw install -Dmaven.test.skip=true"

getting Timeout error as :  

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)
        at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:64)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)

My linux instance is potected via a proxy server .

How to provide proxy details to pinpoint , so that installation goes smooth and call from pinpoint application to internet also go via a proxy server.

**Comment by emeroad** [comment]
Sorry. We can not support your network problem.

**Comment by teotia39** [comment]
M not asking to support network problem , am asking is there any configuration which i have to do in proxied environment in pinpoint files or pinpoint won't work in machines where proxy is cofigured , My machine internally has proper access to the repo , When i do wget to restricted URL , I get proper response , Its only via pinpoint script it fails , M asking proxy confoguration in pinpooint files

**Comment by Xylus** [comment]
@teotia39 
The `mvnw` command is simply a wrapper for maven - provided so that you don't have to install maven yourself.
You can always install maven and run the command using `mvn` if the wrapper's not working.
If it still fails with the same error message, then you'll have to configure your maven installation to suit your environment.
