### ISSUE TITLE
WEBLOGIC pinpoint agent thread deadlock

### ISSUE THREAD

**Issue by CHENTIANHAO123** [naver/pinpoint#3515]
#### Description
Thread deadlock

#### Environment

* Pinpoint version:1.7.0
* OS, WAS, affected library, etc:linux
* Additional details (e.g. how your collector/web is set up):

#### Additional Info
two thread happen deadlock,Main Thread and send agentInfo thread.

===== FULL THREAD DUMP ===============
Thu Nov  2 15:27:44 2017
Oracle JRockit(R) R28.2.5-20-152429-1.6.0_37-20120927-1915-linux-ia32

"Main Thread" id=1 idx=0x4 tid=214552 prio=5 alive, blocked, native_blocked
    -- Blocked trying to get lock: com/navercorp/pinpoint/bootstrap/classloader/PinpointURLClassLoader@0xb73e15a0[thin lock]
    at jrockit/vm/Threads.sleep(I)V(Native Method)
    at jrockit/vm/Locks.waitForThinRelease(Locks.java:955)
    at jrockit/vm/Locks.monitorEnterSecondStageHard(Locks.java:1083)
    at jrockit/vm/Locks.monitorEnterSecondStage(Locks.java:1005)
    at jrockit/vm/Locks.monitorEnter(Locks.java:2179)
    at jrockit/vm/Classes.loadClassInternal(Classes.java:42)
    at jrockit/vm/RNI.c2java(IIIII)V(Native Method)
    at jrockit/vm/RNI.generateVirtualCode(Ljava/lang/Object;II)I(Native Method)
    at com/navercorp/pinpoint/profiler/instrument/transformer/DebugTransformerRegistry.findTransformer(DebugTransformerRegistry.java:0)
    at com/navercorp/pinpoint/profiler/instrument/transformer/DebugTransformerRegistry.findTransformer(DebugTransformerRegistry.java:89)
    at com/navercorp/pinpoint/profiler/MatchableClassFileTransformerDispatcher.transform(MatchableClassFileTransformerDispatcher.java:125)
    at sun/instrument/TransformerManager.transform(TransformerManager.java:169)
    at sun/instrument/InstrumentationImpl.transform(InstrumentationImpl.java:365)
    at jrockit/vm/RNI.c2java(IIIII)V(Native Method)
    at java/lang/ClassLoader.defineClass1(Ljava/lang/String;[BIILjava/security/ProtectionDomain;Ljava/lang/String;Z)Ljava/lang/Class;(Native Method)
    at java/lang/ClassLoader.defineClassCond(ClassLoader.java:631)
    at java/lang/ClassLoader.defineClass(ClassLoader.java:615)
    at java/security/SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java/net/URLClassLoader.defineClass(URLClassLoader.java:283)
    at java/net/URLClassLoader.access$000(URLClassLoader.java:58)
    at java/net/URLClassLoader$1.run(URLClassLoader.java:197)
    at jrockit/vm/AccessController.doPrivileged(AccessController.java:254)
    at java/net/URLClassLoader.findClass(URLClassLoader.java:190)
    at java/lang/ClassLoader.loadClass(ClassLoader.java:306)
    ^-- Holding lock: sun/misc/Launcher$AppClassLoader@0xb82b9558[recursive]
    at sun/misc/Launcher$AppClassLoader.loadClass(Launcher.java:308)
    ^-- Holding lock: sun/misc/Launcher$AppClassLoader@0xb82b9558[recursive]
    at java/lang/ClassLoader.loadClass(ClassLoader.java:247)
    at jrockit/vm/Classes.loadClassInternal(Classes.java:76)
    ^-- Holding lock: sun/misc/Launcher$AppClassLoader@0xb82b9558[thin lock]
    at jrockit/vm/RNI.c2java(IIIII)V(Native Method)
    -- end of trace

.............

"Pinpoint-agentInfo-sender(17-0)" id=188 idx=0x304 tid=216748 prio=5 alive, blocked, native_blocked, daemon
    -- Blocked trying to get lock: sun/misc/Launcher$AppClassLoader@0xb82b9558[thin lock]
    at jrockit/vm/Threads.sleep(I)V(Native Method)
    at jrockit/vm/Locks.waitForThinRelease(Locks.java:955)
    at jrockit/vm/Locks.monitorEnterSecondStageHard(Locks.java:1083)
    at jrockit/vm/Locks.monitorEnterSecondStage(Locks.java:1005)
    at jrockit/vm/Locks.monitorEnter(Locks.java:2179)
    at sun/misc/Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java/lang/ClassLoader.loadClass(ClassLoader.java:247)
    at com/navercorp/pinpoint/bootstrap/classloader/PinpointURLClassLoader.loadClass(PinpointURLClassLoader.java:67)
    ^-- Holding lock: com/navercorp/pinpoint/bootstrap/classloader/PinpointURLClassLoader@0xb73e15a0[recursive]
    at java/lang/ClassLoader.loadClass(ClassLoader.java:247)
    at jrockit/vm/Classes.loadClassInternal(Classes.java:76)
    ^-- Holding lock: com/navercorp/pinpoint/bootstrap/classloader/PinpointURLClassLoader@0xb73e15a0[thin lock]
    at jrockit/vm/RNI.c2java(IIIII)V(Native Method)
    at jrockit/vm/RNI.generateVirtualCode(Ljava/lang/Object;II)I(Native Method)
    at com/navercorp/pinpoint/profiler/AgentInfoSender$AgentInfoSendRunnableWrapper.run(AgentInfoSender.java:0)
    at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:439)
    at java/util/concurrent/FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
    at java/util/concurrent/FutureTask.runAndReset(FutureTask.java:150)
    at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
    at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
    at java/util/concurrent/ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
    at java/util/concurrent/ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java/lang/Thread.run(Thread.java:662)
    at jrockit/vm/RNI.c2java(IIIII)V(Native Method)

**Comment by koo-taejin** [comment]
hi CHENTIANHAO123

Currently, there is a potential risk that a pinpoint will deadlock if you use oracle jvm version less 6 or lower.
However, in case of 7 or more, there is no problem using parallel classloader.
I checked it only for oracle jvm.
I will check jrockit can use parallel classloader like oracle jvm 7+.

thanks.

**Comment by CHENTIANHAO123** [comment]
Hi @koo-taejin 
Thanks for your reply, if this bug will be fix in next version?

**Comment by koo-taejin** [comment]
If jrockit does not support parallel classloader, there is no guarantee that it will be fixed.
We recommend using oracle jvm7 or higher.

**Comment by koo-taejin** [comment]
I downloaded the latest version of jrockit, looked at the code, and found that the parallel classloader was not available.

Here are the versions i looked at:
`` `
version: jrockit-jre1.6.0_45-R28.2.7
link: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-jrockit-2192437.html
`` `

As a workaround, I'll search at how to preload that class,
But if fix that part, the potential risk will still exist if you do not use oracle jvm 7+.

if possible, i recommend using oralce jvm. (currently, weblogic can run with oracle jvm )

thanks.

**Comment by CHENTIANHAO123** [comment]
@koo-taejin
I think jrockit does support parallel classloader,because the deadlock  does not occur on all host,
It just occur on some host, the agent in another host start normally, all host use the same jrockit_jdk_1.6+.

**Comment by koo-taejin** [comment]
Deadlocks occur when multiple threads are running. This is a timing problem, so it depends on each application.

Add to,
jrockit does not support parallel classloaders because it is merged with oracle jvm since 1.7, and it is impossible not to cause deadlocks in jrockit.

**Comment by CHENTIANHAO123** [comment]
@koo-taejin，thanks for your precious reply!
We hava a lots of weblogic applications using pinpoint now... They all use jdk1.6....
I look forward to you can find another way to preload that class。
Thank you very much.

**Comment by koo-taejin** [comment]
@CHENTIANHAO123 

Can i get pinpoint agent's full log when deadlock occured. 
additional,  Is your version 1.7.0 is latest master? If not, let me know at git commit hash value.
If deadlocks occur frequently, it might be helpful to provide with jvm -verbose:class option. 
If you are deadlocked while running with this option, please post log.

thanks.

**Comment by CHENTIANHAO123** [comment]
The agent log  and threaddump in txt file.
The git commit hash value is 7fff3906f44cd7d5ab1297a4d5bd101d4dd15feb.
Thanks! 
[pinpointAgent.txt](https://github.com/naver/pinpoint/files/1440659/pinpointAgent.txt)


[threaddump.txt](https://github.com/naver/pinpoint/files/1440643/threaddump.txt)

**Comment by CHENTIANHAO123** [comment]
@koo-taejin @emeroad 
Hey,brothers,Is there any way to fix this bug?Thanks!!!

**Comment by CHENTIANHAO123** [comment]
if I locked  the  ContextClassLoaderExecuteTemplate<V> . execute  ,  for example:
   public synchronized V execute(){}  
Do you think this is effective?Thanks!!!

**Comment by Xylus** [comment]
Hi @CHENTIANHAO123 
Could you give it a try with the latest source from master? It might not solve everything, but it would hopefully isolate the problem to elsewhere.
Thanks.

**Comment by CHENTIANHAO123** [comment]
@Xylus Thanks,It does work.The application start normally now.

**Comment by Xylus** [comment]
Please feel free to reopen if the issue persists.
Thanks!

**Comment by CHENTIANHAO123** [comment]
@Xylus @koo-taejin hello，Could you tell me why use Task instead of ScheduledThreadPoolExecutor can isolate the deadlock problem to elsewhere. How does it work？ I think the deadlock problem is caused by the jdk1.6 synchronization loadclass method.
