### ISSUE TITLE
Exception occurred while trying to CRUD userGroup information

### ISSUE THREAD

**Issue by prashantnitt07** [naver/pinpoint#3532]
hi ,
we are getting below error  , JDBC connection cannt create . please check .

log path name : /app/pinpoint/apache-tomcat/logs
file name :catalina.out

**2017-11-07 18:12:23 [INFO ](c.n.p.w.c.ScatterChartController   ) Fetch scatterData time : 40ms
2017-11-07 18:12:23 [INFO ](c.n.p.w.c.ScatterChartController   ) Fetch scatterData time : 13ms
2017-11-07 18:12:29 [ERROR](c.n.p.w.c.UserController           ) can't select user
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
        at com.sun.proxy.$Proxy56.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:191)
        at com.navercorp.pinpoint.web.dao.mysql.MysqlUserDao.selectUser(MysqlUserDao.java:58)
        at com.navercorp.pinpoint.web.service.UserServiceImpl.selectUser(UserServiceImpl.java:53)
        at com.navercorp.pinpoint.web.controller.UserController.getUser(UserController.java:99)**

**Comment by minwoo-jung** [comment]
please ref https://github.com/naver/pinpoint/blob/master/doc/alarm.md.
