### ISSUE TITLE
dubbox 2.8.4 exception bug

### ISSUE THREAD

**Issue by kingtiger2** [naver/pinpoint#3553]
2017-11-15 17:51:19 [WARN ](c.n.p.p.c.DefaultTrace             ) [DefaultTrace] Corrupted call stack found.
com.navercorp.pinpoint.exception.PinpointException: not empty call stack.
	at com.navercorp.pinpoint.profiler.context.DefaultTrace.close(DefaultTrace.java:177)
	at com.navercorp.pinpoint.bootstrap.interceptor.SpanSimpleAroundInterceptor.deleteTrace(SpanSimpleAroundInterceptor.java:106)
	at com.navercorp.pinpoint.bootstrap.interceptor.SpanSimpleAroundInterceptor.after(SpanSimpleAroundInterceptor.java:99)
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:44)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:57)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:70)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:132)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy10.findNativeAreaList(proxy10.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

@majinkai  @Xylus

**Comment by Xylus** [comment]
Hi @kingtiger2 
This look similar to #3318 
Dubbo plugin as a whole will be looked into after 1.7.0. Thanks.

**Comment by kingtiger2** [comment]
When release 1.7.0

在 2017-11-16 14:25:27，"HyunGil Jeong" <notifications@github.com> 写道：


Closed #3553.
