### ISSUE TITLE
does not support jboss5?

### ISSUE THREAD

**Issue by tonykokhan** [naver/pinpoint#3568]
- my pinpoint agent log:
`Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/logging/PLoggerFactory
	at com.navercorp.pinpoint.plugin.spring.beans.SpringBeansConfig.<init>(SpringBeansConfig.java:44)
	at com.navercorp.pinpoint.plugin.spring.beans.interceptor.TargetBeanFilter.of(TargetBeanFilter.java:41)
	... 134 more`

- my jboss5 log:
`2017-11-17 14:38:21,967 INFO  [STDOUT] (Prototyper) [onlineexam] [ERROR] 2017-11-17 14:38:21.021 Prototyper org.logicalcobwebs.proxool.proxoolPool_exam Prototype
org.logicalcobwebs.proxool.ProxoolException: Unexpected prototyping problem
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:229)
	at org.logicalcobwebs.proxool.Prototyper.sweep(Prototyper.java:102)
	at org.logicalcobwebs.proxool.PrototyperThread.run(PrototyperThread.java:44)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at org.logicalcobwebs.proxool.DefaultConnectionBuilder.buildConnection(DefaultConnectionBuilder.java:39)
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:159)
	... 2 common frames omitted
2017-11-17 14:38:21,968 INFO  [STDOUT] (Prototyper) [onlineexam] [ERROR] 2017-11-17 14:38:21.021 Prototyper org.logicalcobwebs.proxool.proxoolPool_test Prototype
org.logicalcobwebs.proxool.ProxoolException: Unexpected prototyping problem
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:229)
	at org.logicalcobwebs.proxool.Prototyper.sweep(Prototyper.java:102)
	at org.logicalcobwebs.proxool.PrototyperThread.run(PrototyperThread.java:44)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at org.logicalcobwebs.proxool.DefaultConnectionBuilder.buildConnection(DefaultConnectionBuilder.java:39)
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:159)
	... 2 common frames omitted
2017-11-17 14:38:21,968 INFO  [STDOUT] (Prototyper) [onlineexam] [ERROR] 2017-11-17 14:38:21.021 Prototyper org.logicalcobwebs.proxool.proxoolPool_myuni Prototype
org.logicalcobwebs.proxool.ProxoolException: Unexpected prototyping problem
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:229)
	at org.logicalcobwebs.proxool.Prototyper.sweep(Prototyper.java:102)
	at org.logicalcobwebs.proxool.PrototyperThread.run(PrototyperThread.java:44)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at org.logicalcobwebs.proxool.DefaultConnectionBuilder.buildConnection(DefaultConnectionBuilder.java:39)
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:159)
	... 2 common frames omitted
2017-11-17 14:38:21,969 INFO  [STDOUT] (Prototyper) [onlineexam] [ERROR] 2017-11-17 14:38:21.021 Prototyper org.logicalcobwebs.proxool.proxoolPool_report Prototype
org.logicalcobwebs.proxool.ProxoolException: Unexpected prototyping problem
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:229)
	at org.logicalcobwebs.proxool.Prototyper.sweep(Prototyper.java:102)
	at org.logicalcobwebs.proxool.PrototyperThread.run(PrototyperThread.java:44)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at org.logicalcobwebs.proxool.DefaultConnectionBuilder.buildConnection(DefaultConnectionBuilder.java:39)
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:159)
	... 2 common frames omitted
2017-11-17 14:38:21,970 INFO  [STDOUT] (Prototyper) [onlineexam] [ERROR] 2017-11-17 14:38:21.021 Prototyper org.logicalcobwebs.proxool.proxoolPooli_exam Prototype
org.logicalcobwebs.proxool.ProxoolException: Unexpected prototyping problem
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:229)
	at org.logicalcobwebs.proxool.Prototyper.sweep(Prototyper.java:102)
	at org.logicalcobwebs.proxool.PrototyperThread.run(PrototyperThread.java:44)
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/interceptor/registry/InterceptorRegistry
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at org.logicalcobwebs.proxool.DefaultConnectionBuilder.buildConnection(DefaultConnectionBuilder.java:39)
	at org.logicalcobwebs.proxool.Prototyper.buildConnection(Prototyper.java:159)
	... 2 common frames omitted`

**Comment by emeroad** [comment]
Pinpoint does not support jboss5.
