### ISSUE TITLE
ConflictingBeanDefinitionException on SNAPSHOT

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#3573]
`
20-Nov-2017 10:15:57.420 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initi
alized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
 org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [applicati
onContext-web.xml]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean n
ame 'applicationCpuLoadService' for bean class [com.navercorp.pinpoint.web.service.stat.ApplicationCpuLoadService] conflicts with existing, no
n-compatible bean definition of same name and class [com.navercorp.pinpoint.web.service.ApplicationCpuLoadService]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:414)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.
java:129)
`
#### Description
After building pinpoint from git/master, and deploy it on apache tomcat 8.5, I cannot start 
the application because of the above error 

Thanks for your help . 

Olivier

**Comment by minwoo-jung** [comment]
I'm currently buinding master branch code, It Ok.
Please retry checkout and build. 
I recommand don't use snapshot, use [1.6.2 version](https://github.com/naver/pinpoint/tree/1.6.2).

**Comment by ofauchon** [comment]
I built it because I need HTTP Status Code error feature. 
I'll try 1.7.0-RC1 that has just been released last night.

Thanks.
Olivier
