### ISSUE TITLE
pinpoint start failed.

### ISSUE THREAD

**Issue by saver123sc** [naver/pinpoint#3579]
After deploymented  agent1.70 ，the following error after start the websphere server:
native_stderr.log:

2017-11-21 14:40:30 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint start failed.
com.navercorp.pinpoint.bootstrap.BootStrapException: execute fail. Error:null
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:52)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:73)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:45)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:39)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:515)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:78)
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
	... 9 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: com/ibm/lang/management/OperatingSystemMXBean.getProcessCpuTimeByNS()J
  at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:63)
  while locating com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor
  at com.navercorp.pinpoint.profiler.context.module.ApplicationContextModule.configure(ApplicationContextModule.java:258)
  while locating com.navercorp.pinpoint.profiler.monitor.AgentStatMonitor

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:102)
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:86)
	at com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:125)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:118)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:69)
	... 15 more
Caused by: java.lang.NoSuchMethodError: com/ibm/lang/management/OperatingSystemMXBean.getProcessCpuTimeByNS()J
	at com.navercorp.pinpoint.profiler.monitor.metric.cpu.ibm.Java6CpuLoadMetric.getSnapshot(Java6CpuLoadMetric.java:47)
	at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:40)
	at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:26)
	at com.navercorp.pinpoint.profiler.monitor.collector.AgentStatCollector.collect(AgentStatCollector.java:99)
	at com.navercorp.pinpoint.profiler.monitor.collector.AgentStatCollector.collect(AgentStatCollector.java:34)
	at com.navercorp.pinpoint.profiler.monitor.CollectJob.run(CollectJob.java:67)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.preLoadClass(DefaultAgentStatMonitor.java:104)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:91)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:63)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor$$FastClassByGuice$$1e15b61b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 23 more

*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
************ Start Display Current Environment ************
WebSphere Platform 7.0.0.0 [ND 7.0.0.0 r0835.03] running with process name saverNode01Cell\saverNode01\server1 and process id 16969
Host Operating System is Linux, version 3.10.0-693.el7.x86_64
Java version = 1.6.0, Java Compiler = j9jit24, Java VM name = IBM J9 VM
was.install.root = /opt/IBM/WebSphere/AppServer
user.install.root = /opt/IBM/WebSphere/AppServer/profiles/test01
Java Home = /opt/IBM/WebSphere/AppServer/java/jre
ws.ext.dirs = /opt/IBM/WebSphere/AppServer/java/lib:/opt/IBM/WebSphere/AppServer/profiles/test01/classes:/opt/IBM/WebSphere/AppServer/classes:/opt/IBM/WebSphere/AppServer/lib:/opt/IBM/WebSphere/AppServer/installedChannels:/opt/IBM/WebSphere/AppServer/lib/ext:/opt/IBM/WebSphere/AppServer/web/help:/opt/IBM/WebSphere/AppServer/deploytool/itp/plugins/com.ibm.etools.ejbdeploy/runtime
Classpath = /opt/IBM/WebSphere/AppServer/profiles/test01/properties:/opt/IBM/WebSphere/AppServer/properties:/opt/IBM/WebSphere/AppServer/lib/startup.jar:/opt/IBM/WebSphere/AppServer/lib/bootstrap.jar:/opt/IBM/WebSphere/AppServer/lib/jsf-nls.jar:/opt/IBM/WebSphere/AppServer/lib/lmproxy.jar:/opt/IBM/WebSphere/AppServer/lib/urlprotocols.jar:/opt/IBM/WebSphere/AppServer/deploytool/itp/batchboot.jar:/opt/IBM/WebSphere/AppServer/deploytool/itp/batch2.jar:/opt/IBM/WebSphere/AppServer/java/lib/tools.jar:/data/pp-agent/pinpoint-bootstrap-1.7.0-SNAPSHOT.jar:/data/pp-agent/pinpoint-bootstrap-1.7.0-SNAPSHOT.jar
Java Library path = /opt/IBM/WebSphere/AppServer/java/jre/lib/amd64/compressedrefs:/opt/IBM/WebSphere/AppServer/java/jre/lib/amd64:/opt/IBM/WebSphere/AppServer/bin::/usr/lib
************* End Display Current Environment *************

**Comment by Xylus** [comment]
Hi @saver123sc 
Does the problem exist in 1.6.2?

Could you check your jre for `long com.ibm.lang.management.OperatingSystemMXBean.getProcessCpuTimeByNS()` method? 
It should be there as per the [documentation]( https://www.ibm.com/support/knowledgecenter/en/SSYKE2_6.0.0/com.ibm.java.api.60.doc/com.ibm.lang.management/com/ibm/lang/management/OperatingSystemMXBean.html).

Could you also post your agent log so we can take a look at it? (The log file is located under *$PINPOINT_AGENT/log* directory).

In the mean time, you could also try setting `profiler.jvm.vendor.name=oracle` in *pinpoint.config* and see if that works.
Thanks.

**Comment by saver123sc** [comment]
@Xylus 

Thank you,Problems on websphere7, I have solved it by reshipment wesphere

**Comment by Xylus** [comment]
Glad to hear you worked it out :+1:

**Comment by chuanyi-fang** [comment]
> @Xylus
> 
> Thank you,Problems on websphere7, I have solved it by reshipment wesphere

I also get this problem. And how to solve it.

**Comment by chuanyi-fang** [comment]
I have found the method in the "jlm.jar" of WAS's "jre.pak".And solved now.
![image](https://user-images.githubusercontent.com/20055737/45728906-b5242e00-bbfc-11e8-83dd-c0f372bca988.png)

**Comment by Xylus** [comment]
resolved via #4694
