### ISSUE TITLE
1.7.0-RC1 calls api.github.com and fails when unreachable

### ISSUE THREAD

**Issue by ofauchon** [naver/pinpoint#3580]
2017-11-21 09:37:14 [INFO ](AgentStatDaoFactory$JvmGcDaoFactory) AgentStatDao Compatibility v2
2017-11-21 09:37:15 [WARN ](utowiredAnnotationBeanPostProcessor) Autowired annotation should only be used on methods with parameters: public java.util.List com.navercorp.pinpoint.web.dao.rest.GithubAgentDownloadInfoDao.getDownloadInfoList()
2017-11-21 09:37:15 [WARN ](o.s.w.c.s.XmlWebApplicationContext ) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'agentInfoServiceImpl': Unsatisfied dependency expressed through field 'agentDownloadInfoDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentDownloadInfoDao': Injection of autowired dependencies failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/naver/pinpoint/releases": api.github.com; nested exception is java.net.UnknownHostException: api.github.com
2017-11-21 09:37:15 [INFO ](onManager$HConnectionImplementation) Closing zookeeper sessionid=0x15fca95f3a20017
2017-11-21 09:37:15 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          ) Session: 0x15fca95f3a20017 closed
2017-11-21 09:37:15 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         ) EventThread shut down
2017-11-21 09:37:15 [INFO ](c.n.p.c.h.HbaseTemplate2           ) HBaseTemplate2.destroy()
2017-11-21 09:37:15 [WARN ](c.n.p.c.h.HbaseTemplate2           ) count -1
2017-11-21 09:37:15 [INFO ](c.n.p.c.h.PooledHTableFactory      ) PooledHTableFactory.destroy()
2017-11-21 09:37:15 [INFO ](onManager$HConnectionImplementation) Closing zookeeper sessionid=0x15fca95f3a20016
2017-11-21 09:37:15 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          ) Session: 0x15fca95f3a20016 closed
2017-11-21 09:37:15 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         ) EventThread shut down
2017-11-21 09:37:15 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed

#### Description

Pinpoint wants to connect to api.github.com for an unknow reason, and it seems it stop startup
when unreachable. 

Please provide a fix/workaroud, and keep Pinpoint working standalone without external calls. 

Thanks 
Olivier

**Comment by koo-taejin** [comment]
hi ofauchon

Thank you for your reporting.
In the 1.7.0 stable version, I will fix there is no problem even if can't connect with the Github API.

thanks.

**Comment by ofauchon** [comment]
Hi, 

Could you tell us more about this request ? Why is is needed ? 

Maybe a quick fix would be check if a local copy of https://api.github.com/repos/naver/pinpoint/releases exists in the webapp and disable download if present.

Maybe "https://api.github.com/repos/naver/pinpoint/releases" could be defined in configuration file so we can change it to "file://path/to/pinpoint/releases" if needed.

Olivier

**Comment by mabunixda** [comment]
I already reported this behavior but could not rebuild it ...

**Comment by koo-taejin** [comment]
@ofauchon

This feature is added to make it easier for users to apply the agent.

Basically, we use github api to get two kinds of information.
agent download path and version information to be applied when creating jvm argument info.
![jvm arg](https://user-images.githubusercontent.com/10057874/33104539-15b5f07e-cf6c-11e7-94ac-86cdc482ab9f.png)

AgentDownloadInfoDao is a Spring bean, and it is implemented so that people who use it can extend it to their own environment.

However, It is no good that If can't connect to github, then application can not be started. 
I will fix it. 

@mabunixda I have misunderstood you'r comment.  

thanks.

**Comment by ofauchon** [comment]
Thanks for the details !

Here is a very dirty_ hack for the impatients :-) 

```
@@ -51,10 +51,12 @@ public class GithubAgentDownloadInfoDao implements AgentDownloadInfoDao {
     public List<AgentDownloadInfo> getDownloadInfoList() {
         RestTemplate restTemplate = new RestTemplate();

-        String responseBody = restTemplate.getForObject(GITHUB_API_URL, String.class);
+        //String responseBody = restTemplate.getForObject(GITHUB_API_URL, String.class);
+        String responseBody = "";
```

**Comment by koo-taejin** [comment]
fix the problem and code was merged in master branch.

In addition, if you have own repository, you can add it as a configuration.

```
# pinpoint-web.properties
web.installation.pinpointVersion=1.7.0-SNAPSHOT
web.installation.downloadUrl=http://~~~~~
```

thanks.

**Comment by ofauchon** [comment]
Thanks for the fix, i'll try it as soon as possible 
Olivier

**Comment by prashantnitt07** [comment]
Dear Member ,
PinPoint webView is not started and showing "No webpage was found for the web address:"

I have added as per given by you in pinpoint-web.properties file 
# pinpoint-web.properties
web.installation.pinpointVersion=1.7.0-SNAPSHOT
web.installation.downloadUrl=http://~~~~~

but not issues resolved . please find below error detail . 

2017-11-28 20:24:05 [INFO ](onManager$HConnectionImplementation) Closing zookeeper sessionid=0x15f7d244a2f00d0
2017-11-28 20:24:05 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          ) Session: 0x15f7d244a2f00d0 closed
2017-11-28 20:24:05 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         ) EventThread shut down
2017-11-28 20:24:05 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'agentInfoServiceImpl': Unsatisfied dependency expressed through field 'agentDownloadInfoDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentDownloadInfoDao': Injection of autowired dependencies failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.github.com/repos/naver/pinpoint/releases": Connection timed out (Connection timed out); nested exception is java.net.ConnectException: Connection timed out (Connection timed out)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)

**Comment by koo-taejin** [comment]
hi prashantnitt07 

please verify that you are working with current master branch.
In the case of RC1, even if you set the above, the problem still exists.

thanks.
