### ISSUE TITLE
pinpoint web start failed

### ISSUE THREAD

**Issue by WangHouLing** [naver/pinpoint#3585]
Hi,
Excuse me, when I started pinpoint web the log included error message`2017-11-23 11:52:13 [ERROR](StatDaoFactory$DataSourceDaoFactory:87 ) AgentStatDao configured for compatibilityMode, but AgentStat and AgentStatV2 tables do not exist
`. But Hbase table list included AgentStat and AgentStatV2 tables. I don't know the meaning of this message.
Please help me solve this problem.I would appreciate it if you can help me!

#### Description

There is detail error message:
```
2017-11-23 11:52:13 [WARN ](o.a.h.h.MetaTableAccessor          :345) No serialized HRegionInfo in keyvalues={Traces,;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.dd9e3ec4990d9014b1c163ff6b9f505f./info:seqnumDuringOpen/1511344313057/Put/vlen=8/seqid=0, Traces,;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.dd9e3ec4990d9014b1c163ff6b9f505f./info:server/1511344313057/Put/vlen=15/seqid=0, Traces,;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.dd9e3ec4990d9014b1c163ff6b9f505f./info:serverstartcode/1511344313057/Put/vlen=8/seqid=0}
2017-11-23 11:52:13 [WARN ](o.a.h.h.MetaTableAccessor          :345) No serialized HRegionInfo in keyvalues={Traces,<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.5e32d915f26196d6460ac1f0d1bb1cd1./info:seqnumDuringOpen/1511344325841/Put/vlen=8/seqid=0, Traces,<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.5e32d915f26196d6460ac1f0d1bb1cd1./info:server/1511344325841/Put/vlen=15/seqid=0, Traces,<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.5e32d915f26196d6460ac1f0d1bb1cd1./info:serverstartcode/1511344325841/Put/vlen=8/seqid=0}
2017-11-23 11:52:13 [WARN ](o.a.h.h.MetaTableAccessor          :345) No serialized HRegionInfo in keyvalues={Traces,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.e97e975debbc8f1bacf1f2e5957d99c1./info:seqnumDuringOpen/1511344351845/Put/vlen=8/seqid=0, Traces,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.e97e975debbc8f1bacf1f2e5957d99c1./info:server/1511344351845/Put/vlen=15/seqid=0, Traces,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.e97e975debbc8f1bacf1f2e5957d99c1./info:serverstartcode/1511344351845/Put/vlen=8/seqid=0}
2017-11-23 11:52:13 [WARN ](o.a.h.h.MetaTableAccessor          :345) No serialized HRegionInfo in keyvalues={Traces,>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.a846acb147ad4d6a89de63767fe0fc80./info:seqnumDuringOpen/1511344318672/Put/vlen=8/seqid=0, Traces,>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.a846acb147ad4d6a89de63767fe0fc80./info:server/1511344318672/Put/vlen=15/seqid=0, Traces,>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.a846acb147ad4d6a89de63767fe0fc80./info:serverstartcode/1511344318672/Put/vlen=8/seqid=0}
2017-11-23 11:52:13 [WARN ](o.a.h.h.MetaTableAccessor          :345) No serialized HRegionInfo in keyvalues={Traces,?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.c164bfbac92bca366dbf13eece8162fd./info:seqnumDuringOpen/1511344333457/Put/vlen=8/seqid=0, Traces,?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.c164bfbac92bca366dbf13eece8162fd./info:server/1511344333457/Put/vlen=15/seqid=0, Traces,?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.c164bfbac92bca366dbf13eece8162fd./info:serverstartcode/1511344333457/Put/vlen=8/seqid=0}
2017-11-23 11:52:13 [WARN ](o.a.h.h.MetaTableAccessor          :345) No serialized HRegionInfo in keyvalues={hbase:namespace,,1504250793480.92b4cbace8bd4e8d54986261857fec2c./info:seqnumDuringOpen/1511344360500/Put/vlen=8/seqid=0, hbase:namespace,,1504250793480.92b4cbace8bd4e8d54986261857fec2c./info:server/1511344360500/Put/vlen=15/seqid=0, hbase:namespace,,1504250793480.92b4cbace8bd4e8d54986261857fec2c./info:serverstartcode/1511344360500/Put/vlen=8/seqid=0}
2017-11-23 11:52:13 [ERROR](StatDaoFactory$DataSourceDaoFactory:87 ) AgentStatDao configured for compatibilityMode, but AgentStat and AgentStatV2 tables do not exist
2017-11-23 11:52:13 [WARN ](o.s.w.c.s.XmlWebApplicationContext :488) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceService' defined in file [/u01/hitoa-pinpoint/social-pinpoint/code/pinpoint/web/target/deploy/WEB-INF/classes/com/navercorp/pinpoint/web/service/stat/DataSourceService.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.navercorp.pinpoint.web.dao.stat.DataSourceDao]: : Error creating bean with name 'dataSourceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
2017-11-23 11:52:13 [INFO ](onManager$HConnectionImplementation:1710) Closing zookeeper sessionid=0x15fe67973ba001e
2017-11-23 11:52:13 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :684) Session: 0x15fe67973ba001e closed
2017-11-23 11:52:13 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         :512) EventThread shut down
2017-11-23 11:52:13 [INFO ](c.n.p.c.h.HbaseTemplate2           :126) HBaseTemplate2.destroy()
2017-11-23 11:52:13 [WARN ](c.n.p.c.h.HbaseTemplate2           :148) count -1
2017-11-23 11:52:13 [INFO ](c.n.p.c.h.PooledHTableFactory      :108) PooledHTableFactory.destroy()
2017-11-23 11:52:13 [INFO ](onManager$HConnectionImplementation:1710) Closing zookeeper sessionid=0x15fe67973ba001d
2017-11-23 11:52:13 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :684) Session: 0x15fe67973ba001d closed
2017-11-23 11:52:13 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         :512) EventThread shut down
2017-11-23 11:52:13 [ERROR](o.s.w.c.ContextLoader              :331) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSourceService' defined in file [/u01/hitoa-pinpoint/social-pinpoint/code/pinpoint/web/target/deploy/WEB-INF/classes/com/navercorp/pinpoint/web/service/stat/DataSourceService.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.navercorp.pinpoint.web.dao.stat.DataSourceDao]: : Error creating bean with name 'dataSourceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1040)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1702)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:482)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1525)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 60 more
Caused by: java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
	at com.navercorp.pinpoint.web.dao.hbase.stat.AgentStatDaoFactory.getDao(AgentStatDaoFactory.java:88)
	at com.navercorp.pinpoint.web.dao.hbase.stat.AgentStatDaoFactory$DataSourceDaoFactory.getObject(AgentStatDaoFactory.java:282)
	at com.navercorp.pinpoint.web.dao.hbase.stat.AgentStatDaoFactory$DataSourceDaoFactory.getObject(AgentStatDaoFactory.java:267)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 69 more
```
#### Environment

* Pinpoint version:1.6.2
* OS:Centos 7
* Additional details:
Hbase tables:
```
hbase(main):001:0> list
TABLE                                                                                                                                                          
AgentEvent                                                                                                                                                     
AgentInfo                                                                                                                                                      
AgentLifeCycle                                                                                                                                                 
AgentStat                                                                                                                                                      
AgentStatV2                                                                                                                                                    
ApiMetaData                                                                                                                                                    
ApplicationIndex                                                                                                                                               
ApplicationIndexType                                                                                                                                           
ApplicationMapStatisticsCallee_Ver2                                                                                                                            
ApplicationMapStatisticsCaller_Ver2                                                                                                                            
ApplicationMapStatisticsSelf_Ver2                                                                                                                              
ApplicationTraceIndex                                                                                                                                          
HostApplicationMap_Ver2                                                                                                                                        
SqlMetaData_Ver2                                                                                                                                               
StringMetaData                                                                                                                                                 
TraceV2                                                                                                                                                        
Traces                                                                                                                                                         
17 row(s) in 0.3620 seconds

=> ["AgentEvent", "AgentInfo", "AgentLifeCycle", "AgentStat", "AgentStatV2", "ApiMetaData", "ApplicationIndex", "ApplicationIndexType", "ApplicationMapStatisticsCallee_Ver2", "ApplicationMapStatisticsCaller_Ver2", "ApplicationMapStatisticsSelf_Ver2", "ApplicationTraceIndex", "HostApplicationMap_Ver2", "SqlMetaData_Ver2", "StringMetaData", "TraceV2", "Traces"]
```

**Comment by minwoo-jung** [comment]
did you configure your hbase address in hbase.properties?

pinpoint-web/main/resources/hbase.properties
```
hbase.client.host=your_hbase_address
hbase.client.port=your_hbase_port
```

**Comment by WangHouLing** [comment]
I installed hbase, pinpoint-web and pinpoint cooector in the same host. So I didn't change this hbase configuration.
```
hbase.client.host=localhost
hbase.client.port=2181
```

**Comment by Xylus** [comment]
@WangHouLing 
From the warning logs prior to the exception, I think your hbase meta and region info are out of sync.
Not sure what caused it, maybe your hbase logs might have left something?

If you don't find anything weird, you could always try reinstalling/reinitializing your hbase.

**Comment by WangHouLing** [comment]
@Xylus 
Thanks for your reply!
I have run `vim hbase-apps-master-localhost.localdomain.log`, the logs as follows:
```
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={Traces,:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.025de5252dfa898e456f1855df1d9d89./info:seqnumDuringOpen/1511344321908/Put/vlen=8/seqid=0, Traces,:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.025de5252dfa898e456f1855df1d9d89./info:server/1511344321908/Put/vlen=15/seqid=0, Traces,:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.025de5252dfa898e456f1855df1d9d89./info:serverstartcode/1511344321908/Put/vlen=8/seqid=0}
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={Traces,;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.dd9e3ec4990d9014b1c163ff6b9f505f./info:seqnumDuringOpen/1511344313057/Put/vlen=8/seqid=0, Traces,;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.dd9e3ec4990d9014b1c163ff6b9f505f./info:server/1511344313057/Put/vlen=15/seqid=0, Traces,;\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.dd9e3ec4990d9014b1c163ff6b9f505f./info:serverstartcode/1511344313057/Put/vlen=8/seqid=0}
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={Traces,<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.5e32d915f26196d6460ac1f0d1bb1cd1./info:seqnumDuringOpen/1511344325841/Put/vlen=8/seqid=0, Traces,<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.5e32d915f26196d6460ac1f0d1bb1cd1./info:server/1511344325841/Put/vlen=15/seqid=0, Traces,<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.5e32d915f26196d6460ac1f0d1bb1cd1./info:serverstartcode/1511344325841/Put/vlen=8/seqid=0}
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={Traces,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.e97e975debbc8f1bacf1f2e5957d99c1./info:seqnumDuringOpen/1511344351845/Put/vlen=8/seqid=0, Traces,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.e97e975debbc8f1bacf1f2e5957d99c1./info:server/1511344351845/Put/vlen=15/seqid=0, Traces,=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.e97e975debbc8f1bacf1f2e5957d99c1./info:serverstartcode/1511344351845/Put/vlen=8/seqid=0}
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={Traces,>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.a846acb147ad4d6a89de63767fe0fc80./info:seqnumDuringOpen/1511344318672/Put/vlen=8/seqid=0, Traces,>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.a846acb147ad4d6a89de63767fe0fc80./info:server/1511344318672/Put/vlen=15/seqid=0, Traces,>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.a846acb147ad4d6a89de63767fe0fc80./info:serverstartcode/1511344318672/Put/vlen=8/seqid=0}
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={Traces,?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.c164bfbac92bca366dbf13eece8162fd./info:seqnumDuringOpen/1511344333457/Put/vlen=8/seqid=0, Traces,?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.c164bfbac92bca366dbf13eece8162fd./info:server/1511344333457/Put/vlen=15/seqid=0, Traces,?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00,1504251031062.c164bfbac92bca366dbf13eece8162fd./info:serverstartcode/1511344333457/Put/vlen=8/seqid=0}
2017-11-23 15:21:25,123 WARN  [154988899@qtp-711112124-0] hbase.MetaTableAccessor: No serialized HRegionInfo in keyvalues={hbase:namespace,,1504250793480.92b4cbace8bd4e8d54986261857fec2c./info:seqnumDuringOpen/1511344360500/Put/vlen=8/seqid=0, hbase:namespace,,1504250793480.92b4cbace8bd4e8d54986261857fec2c./info:server/1511344360500/Put/vlen=15/seqid=0, hbase:namespace,,1504250793480.92b4cbace8bd4e8d54986261857fec2c./info:serverstartcode/1511344360500/Put/vlen=8/seqid=0}
2017-11-23 15:22:14,475 WARN  [region-location-3] regionserver.StoreFileInfo: Skipping file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd because it is empty. HBASE-646 DATA LOSS?
2017-11-23 15:22:14,477 WARN  [region-location-3] regionserver.HRegionFileSystem: Invalid StoreFile: file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd
2017-11-23 15:23:14,475 WARN  [region-location-2] regionserver.StoreFileInfo: Skipping file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd because it is empty. HBASE-646 DATA LOSS?
2017-11-23 15:23:14,475 WARN  [region-location-2] regionserver.HRegionFileSystem: Invalid StoreFile: file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd
2017-11-23 15:24:14,474 WARN  [region-location-4] regionserver.StoreFileInfo: Skipping file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd because it is empty. HBASE-646 DATA LOSS?
2017-11-23 15:24:14,475 WARN  [region-location-4] regionserver.HRegionFileSystem: Invalid StoreFile: file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd
2017-11-23 15:24:14,557 WARN  [region-location-3] regionserver.StoreFileInfo: Skipping file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd because it is empty. HBASE-646 DATA LOSS?
2017-11-23 15:24:14,557 WARN  [region-location-3] regionserver.HRegionFileSystem: Invalid StoreFile: file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd
2017-11-23 15:25:14,548 WARN  [region-location-2] regionserver.StoreFileInfo: Skipping file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd because it is empty. HBASE-646 DATA LOSS?
2017-11-23 15:25:14,548 WARN  [region-location-2] regionserver.HRegionFileSystem: Invalid StoreFile: file:/u01/hitoa/hbase-1.2.4/data/data/hbase/meta/1588230740/info/e2c2caa8f4e0459b843c11ea3777b7fd
```
```
$ vim hbase-apps-master-localhost.localdomain.out
2017-11-23 15:40:26,550 INFO  [main] util.VersionInfo: HBase 1.2.4
2017-11-23 15:40:26,550 INFO  [main] util.VersionInfo: Source code repository git://asf-dev/home/busbey/projects/hbase revision=67592f3d062743907f8c5ae00dbbe1ae4f69e5af
2017-11-23 15:40:26,551 INFO  [main] util.VersionInfo: Compiled by busbey on Tue Oct 25 18:10:20 CDT 2016
2017-11-23 15:40:26,551 INFO  [main] util.VersionInfo: From source with checksum b45f19b5ac28d9651aa2433a5fa33aa0
2017-11-23 15:40:26,971 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-11-23 15:40:27,369 INFO  [main] zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x1fe20588 connecting to ZooKeeper ensemble=localhost:2181
2017-11-23 15:40:27,379 INFO  [main] zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2017-11-23 15:40:27,379 INFO  [main] zookeeper.ZooKeeper: Client environment:host.name=localhost
2017-11-23 15:40:27,379 INFO  [main] zookeeper.ZooKeeper: Client environment:java.version=1.8.0_112
2017-11-23 15:40:27,379 INFO  [main] zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
2017-11-23 15:40:27,379 INFO  [main] zookeeper.ZooKeeper: Client environment:java.home=/u01/hitoa/jdk1.8.0_112/jre
```
Maybe you're right. I'm so sorry, this is my first time learn about hbase. Could you tell me the steps to reinstall hbase? I have tried to reinstall hbase, but when I created pinpoint tables that displayed the tables already exited. Is that means I need to delete hbase which I have installed?
There are my steps to reinstall:
```
tar -xzvf hbase-1.2.4-bin.tar.gz
```
```
vim /etc/profile
export HBASE_HOME=/u01/hitoa/hbase-1.2.4
```
```
source /etc/profile
```

Edit hbase-site.xml:
```
vim hbase-1.2.4/conf/hbase-site.xml

<configuration>
  <property>
    <name>hbase.rootdir</name>
    <value>file:/usr/apm/hbase-1.2.4/data</value>
  </property>
  <property>
    <name>hbase.cluster.distributed</name>
    <value>true</value>
  </property>
  <property>
    <name>hbase.regionserver.handler.count</name>
    <value>20</value>
  </property>
  <property>
    <name>hbase.zookeeper.quorum</name>
    <value>localhost</value>
  </property>
  <property>
    <name>hbase.zookeeper.property.clientPort</name>
    <value>2181</value>
  </property>
  <property>
    <name>zookeeper.session.timeout</name>
    <value>200000</value>
  </property>
</configuration>
```
Editing hbase-env.sh and setting `export HBASE_MANAGES_ZK=false`

I don't know whether it is correct.
Please help me, thank you.

**Comment by WangHouLing** [comment]
@Xylus 
You're right, I tried to reinstall hbase. Pinpoint startup successfully.
Thank you very much! :) 👍
