### ISSUE TITLE
[HELP] KeeperErrorCode = ConnectionLoss for /hbase/root-region-server

### ISSUE THREAD

**Issue by geniuszhe** [naver/pinpoint#363]
Hi,
 I use pinpoint to monitor my application. Yesterday the pinpoint ran no problem. But today I found something wrong with my hbase. I'm new to Hbase , I search the error on the Internet,but I can't solve it. I deleted hbase, ran quickstart/start-hbase.sh again .But i didn't help too.

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/root-region-server
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
	at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:193)
	at org.apache.hadoop.hbase.zookeeper.ZKUtil.watchAndCheckExists(ZKUtil.java:420)
	at org.apache.hadoop.hbase.zookeeper.ZooKeeperNodeTracker.start(ZooKeeperNodeTracker.java:76)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.ensureZookeeperTrackers(HConnectionManager.java:727)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:786)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:129)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

 Looking forward to your response,Thanks.

**Comment by Xylus** [comment]
Hi geniuszhe,
Have you resolved the problem?

It seems like it's a hbase/zk issue, which I don't think I can be of much help.
Google led me to the following post:
http://hortonworks.com/community/forums/topic/unable-to-connect-to-remote-server-using-hbase/
although I'm not sure if it fits the problem you're describing.

You could also try deleting hbase and running `quickstart/start-hbase.sh` again just like you've done above, but try deleting the **quickstart/data** directory as well (and don't forget to run `quickstart/init-hbase.sh` again).

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [pinpoint] [HELP] KeeperErrorCode = ConnectionLoss for /hbase/root-region-server (#363)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-27 08:00 ~ 2015-04-30 19:00 GMT +09:00]<br>Refresh 휴가중입니다. 급한용무는 정상혁님에게 전달부탁드립니다
--------------------------------------------

**Comment by geniuszhe** [comment]
I tried deleting the quickstart/data directory , it's worked well again. Thank you ! I monitored over time to see if there are problems again .

**Comment by Xylus** [comment]
awesome, let us know if you've got more questions!

**Comment by geniuszhe** [comment]
Oh no, the same error happened again . Maybe I should solve the problem from the zk .
