### ISSUE TITLE
Collector can't network agent via ports

### ISSUE THREAD

**Issue by donghuahuang** [naver/pinpoint#3643]
Hi,
I try to update pinpoint version from 1.5.2 to 1.7.0-RC2 in testing environment then encounter a problem.I have tried to change network ports into 19994\19995\19996 between collector (**pinpoint-collector.properties** and **deprecated-pinpoint-collector.properties**) and agent(**pinpoint.config**) but it still doesn't work.Web、Hbase、my project have been working properly.The ports can be modified correctly before in v1.5.2.Could you tell what to do to configure network?
Thx.

#### Environment

* Pinpoint version:1.7.0-RC2
* OS, WAS, affected library, etc:CentOS 7
* Additional details (e.g. how your collector/web is set up):

#### Additional Info

I ran network.sh script, all output were failed:
java.net.SocketTimeoutException: Receive timed out
        at java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:146)
        at java.net.DatagramSocket.receive(DatagramSocket.java:817)
        at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
        at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
        at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPStat(NetworkAvailabilityChecker.java:83)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:60)
UDP-STAT:// 10.91.230.57
    => 10.91.230.57:9995 [FAIL]

java.net.SocketTimeoutException: Receive timed out
        at java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:146)
        at java.net.DatagramSocket.receive(DatagramSocket.java:817)
        at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
        at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
        at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPSpan(NetworkAvailabilityChecker.java:92)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:66)
UDP-SPAN:// 10.91.230.57
    => 10.91.230.57:9996 [FAIL]

java.net.ConnectException:  Connection denied 
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at com.navercorp.pinpoint.tools.network.TCPChecker.createSocket(TCPChecker.java:65)
        at com.navercorp.pinpoint.tools.network.TCPChecker.check(TCPChecker.java:31)
        at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:42)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkTCP(NetworkAvailabilityChecker.java:100)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:72)
TCP:// 10.91.230.57
    => 10.91.230.57:9994 [FAIL]

**Comment by koo-taejin** [comment]
hi donghuahuang 

networktest.sh tries to access port that is included in your pinpoint.config configuration.
Please check you have changed other pinpoint.config setting

thanks.

**Comment by donghuahuang** [comment]
Thanks a ton for your help! I have found the issue. I forgot to shut down the websphere server before modifying ports so it won't work......Sorry to trouble you,I hope everyone can see this fixed issue.
Thanks again.
