### ISSUE TITLE
NotFoundInstrumentException

### ISSUE THREAD

**Issue by CHENTIANHAO123** [naver/pinpoint#3651]
Hello,I get a Exception when the application start. can you help me? Thanks.

#### Description
agentCl:com.navercorp.pinpoint.bootstrap.PinpointURLClassLoader@7335ea8e Cause:com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find method executeQuery with parameter types: [java.lang.String]
com.navercorp.pinpoint.exception.PinpointException: com.navercorp.pinpoint.bootstrap.instrument.NotFoundInstrumentException: Cannot find method executeQuery with parameter types: [java.lang.String]
       at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:77)
       at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform0(DefaultClassFileTransformerDispatcher.java:126)
       at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:107)
       at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
       at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2496)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2496)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2496)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2496)
       at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:860)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
       at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
       at org.postgresql.jdbc4.Jdbc4Connection.createStatement(Jdbc4Connection.java:30)
       at org.postgresql.jdbc3.AbstractJdbc3Connection.createStatement(AbstractJdbc3Connection.java:232)
       at org.postgresql.jdbc2.AbstractJdbc2Connection.createStatement(AbstractJdbc2Connection.java:286)
       at org.apache.tomcat.dbcp.dbcp.DelegatingConnection.createStatement(DelegatingConnection.java:257)
       at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.validateConnection(PoolableConnectionFactory.java:654)
       at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1558)
       at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
       at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
       at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
       at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
       at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:182)
       at org.springframework.orm.ibatis.SqlMapClientTemplate.insert(SqlMapClientTemplate.java:364)
       at com.llp.wifi.vpn.dao.impl.DfpCallbackParamDaoImpl.insertDfpCallbackLog(DfpCallbackParamDaoImpl.java:17)
       at com.llp.wifi.vpn.biz.operlog.impl.DfpCallbackParamLogServiceImpl.insertDfpCallbackLog(DfpCallbackParamLogServiceImpl.java:30)
       at com.llp.wifi.vpn.biz.obtain.impl.DfpCallbackServiceImpl.callbackProcess(DfpCallbackServiceImpl.java:139)
       at com.llp.wifi.vpn.biz.quartz.CallbackProcessQuartz.start(CallbackProcessQuartz.java:59)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
       at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
       at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
       at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
       at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)

#### Environment

* Pinpoint version:pinpoint-agent-1.7.0-SNAPSHOT
* OS, WAS, affected library, etc:linux,tomcat7
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment]
Hi @CHENTIANHAO123 
What's your postgresql java driver version?

**Comment by CHENTIANHAO123** [comment]
@Xylus Hi,postgresql-9.4-1201.jdbc4.jar.

**Comment by CHENTIANHAO123** [comment]
@Xylus Hello,there is another question about call tree, the Argument show Corrupted(waiting for packet) in some call tree,and the call tree is done. Is there any wrong with pinpoint? thanks.

**Comment by Xylus** [comment]
@CHENTIANHAO123 
Just tested it out using 9.4-1201-jdbc4 driver and it seems to be working well, hmm..
We did however have an issue that got fixed back in July that might have been related to this (https://github.com/naver/pinpoint/pull/3159).
Could you try again with an agent built from master if your agent is from a while ago?
If it still doesn't work, please post your entire agent log so we can take a closer look at it.
Thanks.

And the **Corrupted** argument in the call tree normally indicates packet loss over udp.

**Comment by CHENTIANHAO123** [comment]
@Xylus Oh,,,my agent version is 1.6.1... I will update my agent and have a try. Thank you!!!!!!!!
