### ISSUE TITLE
compile pinpoint web failed, download node.exe failed

### ISSUE THREAD

**Issue by y00221875** [naver/pinpoint#3810]
I try to compile pinpoint by maven, but it failed.

the error log on the console is:
[INFO] Downloading https://nodejs.org/dist/v5.11.1/win-x64/node.exe to D:\SetupF
ile\repository\com\github\eirslett\node\5.11.1\node-5.11.1-windows-x64.exe
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2018-02-06T20:42:43+08:00
[INFO] Final Memory: 23M/328M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:ins
tall-node-and-npm (install node and npm) on project pinpoint-web: Could not down
load Node.js from: https://nodejs.org/dist/v5.11.1/win-x64/node.exe: Could not d
ownload https://nodejs.org/dist/v5.11.1/win-x64/node.exe: Connect to nodejs.org:
443 [nodejs.org/104.20.22.46, nodejs.org/104.20.23.46] failed: Connection timed
out: connect -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.eirslett:frontend-maven-plugin:1.0:install-node-and-npm (install node
and npm) on project pinpoint-web: Could not download Node.js from: https://nodej
s.org/dist/v5.11.1/win-x64/node.exe: Could not download https://nodejs.org/dist/
v5.11.1/win-x64/node.exe
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: Could not download Node
.js from: https://nodejs.org/dist/v5.11.1/win-x64/node.exe: Could not download h
ttps://nodejs.org/dist/v5.11.1/win-x64/node.exe
        at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailu
reException(MojoUtils.java:25)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:97)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException:
 Could not download Node.js from: https://nodejs.org/dist/v5.11.1/win-x64/node.e
xe
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInsta
ller$NodeAndNPMInstallAction.installNodeForWindows(NodeAndNPMInstaller.java:254)

        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInsta
ller$NodeAndNPMInstallAction.install(NodeAndNPMInstaller.java:71)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInsta
ller.install(NodeAndNPMInstaller.java:46)
        at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo
.execute(InstallNodeAndNpmMojo.java:72)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:89)
        ... 22 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.DownloadException: Cou
ld not download https://nodejs.org/dist/v5.11.1/win-x64/node.exe
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.
download(FileDownloader.java:71)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInsta
ller$NodeAndNPMInstallAction.downloadFile(NodeAndNPMInstaller.java:298)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInsta
ller$NodeAndNPMInstallAction.downloadFileIfMissing(NodeAndNPMInstaller.java:292)

        at com.github.eirslett.maven.plugins.frontend.lib.DefaultNodeAndNPMInsta
ller$NodeAndNPMInstallAction.installNodeForWindows(NodeAndNPMInstaller.java:247)

        ... 26 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to nodejs.org:
443 [nodejs.org/104.20.22.46, nodejs.org/104.20.23.46] failed: Connection timed
out: connect
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
(DefaultHttpClientConnectionOperator.java:151)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
ntExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java
:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
Client.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
Client.java:107)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.
execute(FileDownloader.java:86)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultFileDownloader.
download(FileDownloader.java:59)
        ... 29 more
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSL
ConnectionSocketFactory.java:337)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
(DefaultHttpClientConnectionOperator.java:134)
        ... 40 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

pom.xml relative configuration is:
 <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.0</version>
                <configuration>
                    <workingDirectory>${basedir}/target</workingDirectory>
                    <srcdir>${basedir}/target/main/webapp</srcdir>
                    <outputdir>${basedir}/target/main/webapp</outputdir>
                    <installDirectory>target</installDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v5.11.1</nodeVersion>
                            <npmVersion>3.9.6</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>grunt build</id>
                        <goals>
                            <goal>grunt</goal>
                        </goals>
                        <configuration>
                            <arguments>${grunt.build.command}</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by Xylus** [comment]
Hi @y00221875 
It seems like the connection to *https://nodejs.org/dist/v5.11.1/win-x64/node.exe* is timing out from where you're running the maven build.

**Comment by y00221875** [comment]
yes, the problem has been resolved. the reason is dowloading node.exe failed , I modify the dowload address to a locale address.
