### ISSUE TITLE
SpanDecoderV0 firstSpanEvent is null

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#3855]
#### Description
While SpanDecoderV0 throws the Exception
```java
[WARN ](c.n.p.c.s.b.s.t.v.SpanDecoderV0    ) firstSpanEvent is null. bug!!!! firstSpanEventSequence:-1
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanDecoderV0.readQualifier(SpanDecoderV0.java:399)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanDecoderV0.readSpanChunk(SpanDecoderV0.java:59)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanDecoderV0.decode(SpanDecoderV0.java:42)
```
Is that a bug ? And in which situation can cause that ? 
#### Environment

* Pinpoint version:1.7.2
* OS, WAS, affected library, etc: WAS
* Additional details (e.g. how your collector/web is set up):

**Comment by geekMessi** [comment]
By the way ,why **SpanEncoderV0** encode qualifier  with  'firstEvent'?
```java
    private ByteBuffer encodeQualifier(byte type, String applicationId, String agentId, long agentStartTime, long spanId, SpanEventBo firstEvent) 
```

**Comment by woniuzhang** [comment]
I have the same problem . 
Environment
Pinpoint version:1.7.3
OS: CentOS Linux release 7.4.1708 (Core)
