### ISSUE TITLE
Corrupted(invalid sequence) while viewing the call stack trace inferring to Collector class

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#3870]
Hi Team,

In couple of JVM servers I see that we couldn't able to see the complete trace since it is giving us "Corrupted(invalid sequence)"

I have also increased the UDP Span and Stat worker thread as below, but still that doesn't help the cause

# number of udp statworker threads
collector.receiver.stat.worker.threadSize=512
# capacity of udp statworker queue
collector.receiver.stat.worker.queueSize=256

# number of udp statworker threads
collector.receiver.span.worker.threadSize=512
# capacity of udp statworker queue
collector.receiver.span.worker.queueSize=256
# monitoring for udp stat worker

# number of tcp worker threads
collector.receiver.base.worker.threadSize=256
# capacity of tcp worker queue
collector.receiver.base.worker.queueSize=1024
# monitoring for tcp worker

while looking at the stat log , we dont see any rejected count exception as well, could you please help u debugging further

**Comment by Xylus** [comment]
Hi @dinesh4747 
There might be something missing in one of our plugins.
What kind of transaction is generating corrupted spans?
Can you replicate the transaction and send us the agent log for it?

**Comment by dinesh4747** [comment]
<img width="1309" alt="screen shot 2018-02-28 at 12 33 56 pm" src="https://user-images.githubusercontent.com/23452852/36774364-c5762a88-1c83-11e8-80a6-df9c9d2fa58c.png">

**Comment by dinesh4747** [comment]
[agent-pinpoint.log](https://github.com/naver/pinpoint/files/1770083/agent-pinpoint.log)

HI @Xylus - Attached the agent logs where we are having the corrupted (Invalid sequence) and from the logs i couldnt infer any substantial

**Comment by dinesh4747** [comment]
Requesting you to validate and confirm is there any issue from agent logs

**Comment by dinesh4747** [comment]
From the agent log i could observe the below trace 

2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120
2018-03-01 03:22:46 [WARN ](c.n.p.p.s.AsyncQueueingExecutor    :154) Pinpoint-UdpSpanDataExecutor(15-0) Drop data. queue is full. size:5120

**Comment by Xylus** [comment]
Hi @dinesh4747 
```
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.navercorp.pinpoint.profiler.sender.UdpDataSender.sendPacket(UdpDataSender.java:134)
	at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
	at java.lang.Thread.run(Thread.java:745)
```
seems to be the problem.

**Comment by dinesh4747** [comment]
@xylus  - It looks like some PinpointUdpDataexecutor drop data queue is full size:5120 also one of the contributor 

Is there anyway if we increase the Udp worker thread size will resolve be the problem?

**Comment by dinesh4747** [comment]
Just wanted to understand like whether issue is on the agent machine or collector machine where we need to increase the Udp size will solve the problem

**Comment by Xylus** [comment]
The log you've posted is being generated because the queue is not being cleared fast enough.
Increasing worker thread size would resolve the problem if everything is working correctly and if the issue is solely due to too many trace data being generated.

However, with the information you've provided, there seems to be a [network issue](https://github.com/naver/pinpoint/issues/3870#issuecomment-369797898) so I was suggesting you look into that first.
