### ISSUE TITLE
Problems starting JBoss (6.4) and agent not appearing on pinPoint

### ISSUE THREAD

**Issue by JaviBeCl** [naver/pinpoint#3925]
#### Description
We have been having many problems to start JBoss 6.4 after including agent lines in its ini file.
The most recurring problem was JBoss started, but we were not able to see the agent in pinPoint

#### Environment

* Pinpoint version: 1.7.1
* OS, WAS, affected library, etc: 
  -> Red Hat Enterprise Linux Server release 5.11
  -> java version 1.6.0_22
  -> JBOSS 6.4

**Comment by minwoo-jung** [comment]
Please show log message when jboss started

**Comment by JaviBeCl** [comment]
Hi Minwoo-jung, thanks for your reply.

I have problems with client as I am not being allowed to attach logs...
Will do as I get allowed.
Anyway, is there any clue I could check on log?


Thanks in advance.

**Comment by JaviBeCl** [comment]
Hi minwoo-jung, I have the log now.

[server.log](https://github.com/naver/pinpoint/files/1879425/server.log)
[console.log](https://github.com/naver/pinpoint/files/1879426/console.log)

Hope it helps.

Thanks a lot.

**Comment by minwoo-jung** [comment]
Ok I will see this issue.

**Comment by minwoo-jung** [comment]
Please show me the agent log of Pinpoint. 

And check below log. is it ok?
```
[0m[32m13:10:20,794 FINE  [javax.enterprise.resource.webcontainer.jsf.application] (ServerService Thread Pool -- 101) java.lang.NoSuchMethodException: org.jboss.as.jsf.injection.JandexAnnotationProvider.<init>(javax.servlet.ServletContext, com.sun.faces.spi.AnnotationProvider): java.lang.NoSuchMethodException: org.jboss.as.jsf.injection.JandexAnnotationProvider.<init>(javax.servlet.ServletContext, com.sun.faces.spi.AnnotationProvider)
	at java.lang.Class.getConstructor0(Class.java:2706) [rt.jar:1.6.0_22]
	at java.lang.Class.getDeclaredConstructor(Class.java:1985) [rt.jar:1.6.0_22]
	at com.sun.faces.spi.ServiceFactoryUtils.getProviderFromEntry(ServiceFactory.java:83) [jsf-impl-2.1.28.SP11-redhat-1.jar:2.1.28.SP11-redhat-1]
	at com.sun.faces.spi.AnnotationProviderFactory.createAnnotationProvider(AnnotationProviderFactory.java:70) [jsf-impl-2.1.28.SP11-redhat-1.jar:2.1.28.SP11-redhat-1]
	at com.sun.faces.config.ConfigManager$AnnotationScanTask.<init>(ConfigManager.java:805) [jsf-impl-2.1.28.SP11-redhat-1.jar:2.1.28.SP11-redhat-1]
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:349) [jsf-impl-2.1.28.SP11-redhat-1.jar:2.1.28.SP11-redhat-1]
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:216) [jsf-impl-2.1.28.SP11-redhat-1.jar:2.1.28.SP11-redhat-1]
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3339) [jbossweb-7.5.27.Final-redhat-1.jar:7.5.27.Final-redhat-1]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3780) [jbossweb-7.5.27.Final-redhat-1.jar:7.5.27.Final-redhat-1]
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163) [jboss-as-web-7.5.19.Final-redhat-2.jar:7.5.19.Final-redhat-2]
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61) [jboss-as-web-7.5.19.Final-redhat-2.jar:7.5.19.Final-redhat-2]
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96) [jboss-as-web-7.5.19.Final-redhat-2.jar:7.5.19.Final-redhat-2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) [rt.jar:1.6.0_22]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [rt.jar:1.6.0_22]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [rt.jar:1.6.0_22]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_22]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_22]
	at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_22]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
```

```
INFO - Recuperamos los datos del web.xml...
INFO - *****LA URL AL WEB.XML ES: /content/G3.war/WEB-INF/web.xml
ERROR - Error en la tarea del demonio de la comprobacion de cache de Sesiones del WebService de G3. Motivo:

ERROR - /content/G3.war/WEB-INF/web.xml (No existe el fichero o el directorio)
java.io.FileNotFoundException: /content/G3.war/WEB-INF/web.xml (No existe el fichero o el directorio)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:106)
	at java.io.FileInputStream.<init>(FileInputStream.java:66)
	at es.juntadeandalucia.g3.webservices.demonio.SessionDaemonJob.execute(SessionDaemonJob.java:110)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:203)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
INFO - Fin del demonio de comprobacion de sesiones en cache
```
