### ISSUE TITLE
java.lang.NoClassDefFoundError: org.apache.log4j.LogManager on WAS with pinpoint1.6.2

### ISSUE THREAD

**Issue by zhangzhaoyu** [naver/pinpoint#3936]
#### Description
When I run pinpoint-agent-1.6.2 with WAS 8.5.5.9 on IBM jdk 1.7, I get the following error:

```
Fatal error: processing of -javaagent failed
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org.apache.log4j.LogManager
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:236)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:62)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:94)
	at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:46)
	at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:35)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:65)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:236)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:78)
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:73)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:88)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:613)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:404)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:419)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:599)
	at com.navercorp.pinpoint.bootstrap.classloader.ParallelCapablePinpointURLClassLoader.loadClass(ParallelCapablePinpointURLClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:690)
	... 32 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:88)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:613)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:404)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:419)
Caused by: java.lang.NoClassDefFoundError: org.apache.log4j.LogManager
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:236)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:62)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:94)
	at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:46)
	at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:35)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:65)
	at java.lang.J9VMInternals.initializeImpl(Native Method)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:236)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:78)
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:73)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:599)
	at com.navercorp.pinpoint.bootstrap.classloader.ParallelCapablePinpointURLClassLoader.loadClass(ParallelCapablePinpointURLClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:690)
	... 32 more

Fatal error: processing of -javaagent failed
************ Start Display Current Environment ************
Log file started at: [3/23/18 14:51:43:059 GMT+08:00]
************* End Display Current Environment *************
```

The log shows that It can not find log4j, but the jar is just in pinpoint-agent-1.6.2/lib/. I want to know does pinpoint support WAS ?

**Comment by jaehong-kim** [comment]
@zhangzhaoyu 
Are you using websphere ?
Try the latest version of pinpoint.

**Comment by hustcxx** [comment]
how to configure  on websphere ?please help me .
