### ISSUE TITLE
pinpoint-web not supporting mysql/percona enforce_gtid_consistency

### ISSUE THREAD

**Issue by markusgothe** [naver/pinpoint#4034]
It looks like pinpoint is using transactional unsafe statements when writing to a percona xtradb cluster (5.7.21). This causes errors when enforce_gtid_consistency is set to ON
Stacktrace follows below under Additional Info

Is this something that can be changed?

Same goes for pxc_strict_mode but keeping that set to permissive is no problem.

If you need more information please let me know

#### Environment
* Pinpoint version: 1.6.2
* OS: CentOS 7
* DB: 3 node perconaXtraDB cluster with version 5.7.21

#### Additional Info
2018-04-19 11:54:00 [ERROR](s.s.s.TaskUtils$LoggingErrorHandler:95 ) Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: org.springframework.dao.DataAccessResourceFailureException: Could not obtain last_insert_id(); nested exception is java.sql.SQLException: Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.
        at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:63)
        at com.navercorp.pinpoint.web.batch.BatchJobLauncher.alarmJob(BatchJobLauncher.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by minwoo-jung** [comment]
This exception have relevance to jobrepository logic of spring batch.
