### ISSUE TITLE
DubboProviderInterceptor NPE

### ISSUE THREAD

**Issue by steveguoshao** [naver/pinpoint#4135]
pinpoint:1.7.2
dubbo:2.6.1
spring boot: 15.8.RELEASE

cause:
2018-05-17 14:41:57 [WARN ](.n.p.p.d.i.DubboProviderInterceptor) BEFORE. Caused:null
java.lang.NullPointerException
        at com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboProviderInterceptor.doInBeforeTrace(DubboProviderInterceptor.java:161)
        at com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboProviderInterceptor.before(DubboProviderInterceptor.java:51)
        at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.before(ExceptionHandleAroundInterceptor.java:35)
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java)
        at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:48)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:52)
        at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:61)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:41)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:71)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:102)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:168)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by yiyuqiuchi** [comment]
+1

**Comment by lightling** [comment]
+1

**Comment by lightling** [comment]
Somebody in the same problem?

**Comment by jiaqifeng** [comment]
@steveguoshao Would you try the 1.7.3 version of pinpoint? If NPE still exist please let me know.

**Comment by huanlixin888** [comment]
I  try the 1.7.3 version of pinpoint NPE still exist ! @jiaqifeng

**Comment by wukong0503** [comment]
+1

**Comment by wukong0503** [comment]
Is it because of dubbo's version is too old? There is no `DelegateProviderMetaDataInvoker.java`

**Comment by hoperuin** [comment]
pinpoint:1.7.3
dubbo:2.5.5
jdk:1.7

same error

No.161 line is : 
recorder.recordServiceType(DubboConstants.DUBBO_PROVIDER_SERVICE_TYPE);

My dubbo service protocol is RMI.

**Comment by hoperuin** [comment]
Ohh,My test app is OK!
Cause:
agent version:1.7.3
collector/web version:1.6.1

I update pinpoint to 1.6.1,the error is gone!

collector/web base :https://hub.docker.com/r/yous/pinpoint/

**Comment by jiaqifeng** [comment]
@wukong0503 What's your dubbo version?
@hoperuin Since it happens for 1.7.3, I will check it later while maybe a little longer.

**Comment by jaehong-kim** [comment]
Fix #4410

**Comment by steveguoshao** [comment]
@jaehong-kim Can I only update The Dubbo plugin into 1.7.3？

**Comment by jaehong-kim** [comment]
@steveguoshao 
1.8.0-SNAPSHOT

**Comment by steveguoshao** [comment]
@jaehong-kim When will the release of 1.8.0.RELEASE？
I want to move the new dubbo plugin from 1.8.0-SNAPSHOT to 1.7.3

**Comment by caiyisam** [comment]
1.7.3
DubboProviderInterceptor.before
Change from "if (trace == null)" to "if (trace == null || !trace.canSampled())"
