### ISSUE TITLE
Aliyun Message Service Timeout

### ISSUE THREAD

**Issue by linux0x5c** [naver/pinpoint#4165]
#### Description
When I open the pinpoint-agent on tomcat,my Aliyun Message Service cant't connect Aliyun Message Server,it reported an errror,Socket TimeOut.

#### Environment
* Pinpoint version: Pinpoint 1.7.3
* OS: CentOS 7.3
* Tomcat: apache-tomcat-7.0.63
* JDK: 1.8

#### Additional Info
org.springframework.beans.factory.support.DisposableBeanAdapter] - Invocation of destroy method 'close' failed on bean with name 'sqlSession'
java.lang.UnsupportedOperationException: Manual close is not allowed over a Spring managed SqlSession
        at org.mybatis.spring.SqlSessionTemplate.close(SqlSessionTemplate.java:307)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:350)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:540)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:516)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:827)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:485)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:921)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:895)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:841)
        at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:579)
        at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:115)
        at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5064)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5726)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1590)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1579)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
		
		
		
[org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager] - Connection released: [id: http-outgoing-1][route: {}->http://1463939778802068.mns.cn-beijing.aliyun
cs.com:80][total kept alive: 0; route allocated: 0 of 4000; total allocated: 0 of 4000]
send-message wrong:
[Error Code]:, [Message]:null, [RequestId]: null
        at com.aliyun.mns.client.impl.AbstractAction.executeWithCustomHeaders(AbstractAction.java:139)
        at com.aliyun.mns.client.CloudQueue.putMessage(CloudQueue.java:586)
        at com.echemi.b2b.market.util.MqSendUtil.sendMessage(MqSendUtil.java:72)
        at com.echemi.b2b.market.util.MqSendUtil.sendMessage(MqSendUtil.java:101)
        at com.echemi.b2b.market.util.MqSendUtil.sendMessage(MqSendUtil.java:43)
        at com.echemi.b2b.market.service.Impl.BuyingleadManageBusServiceImpl.saveOrUpdate(BuyingleadManageBusServiceImpl.java:881)
        at com.echemi.b2b.market.action.BuyingleadManageController.saveOrUpdate(BuyingleadManageController.java:1261)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:472)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.handleRequestInternal(MultiActionController.java:409)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:154)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1753)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1712)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
        at org.apache.http.impl.nio.client.InternalRequestExecutor.timeout(InternalRequestExecutor.java:116)
[org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl] - http-outgoing-1 0.0.0.0:38446<->182.92.18.99:80[CLOSED][]: Shutdown
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
[org.apache.http.impl.nio.client.InternalIODispatch] - http-outgoing-1 [CLOSED]: Disconnected
Caused by: java.net.SocketTimeoutException
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
        at org.apache.http.impl.nio.client.InternalRequestExecutor.timeout(InternalRequestExecutor.java:116)
[org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl] - http-outgoing-1 0.0.0.0:38446<->182.92.18.99:80[CLOSED][]: Shutdown
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
        at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
[org.apache.http.impl.nio.client.InternalIODispatch] - http-outgoing-1 [CLOSED]: Disconnected
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)

**Comment by linux0x5c** [comment]
My java code's method is httpasyncclient. Lib: Apache HTTP Client  4.x

**Comment by RoySRose** [comment]
Hello, @linux0x5c.
It doesn't look like the connection problem is affected by Pinpoint. No one in our team has the experience of using Aliyun Message Service. If you can show me any error logs in Pinpoint Agent Collector or Web, please do. Otherwise, there aren't many thing that I can guide you on this.
Please share if get the chance to solve it:)

**Comment by linux0x5c** [comment]
Hello,@RoySRose 
I have a new discovery,hhen I use the following method,Set HTTP header contentType,a socket timeout can then occur if you use a pinpoint trace.

**Comment by linux0x5c** [comment]
this my java method:

public static void testPinPoint(String postUrl) {
    	CloseableHttpAsyncClient httpclient = HttpAsyncClients.custom().build();
    	httpclient.start();
    	HttpPost httpPost = new HttpPost(postUrl);
    	
    	//custom repeat stream entity
    	BasicHttpEntity basicHttpEntity = new BasicHttpEntity(){
    		@Override
    		public boolean isRepeatable() {
    			// TODO Auto-generated method stub
    			return this.getContent().markSupported();
    		}
    		
    		@Override
    	    public void writeTo(final OutputStream outstream) throws IOException {
    	        Args.notNull(outstream, "Output stream");
    	        System.out.println("writeTo::::::::::::::::::::::::::::");
    	        final InputStream instream = this.getContent();
    	        instream.reset();
    	        try {
    	            final byte[] buffer = new byte[OUTPUT_BUFFER_SIZE];
    	            int l;
    	            if (this.getContentLength() < 0) {
    	                // consume until EOF
    	                while ((l = instream.read(buffer)) != -1) {
    	                    outstream.write(buffer, 0, l);
    	                }
    	            } else {
    	                // consume no more than length
    	                long remaining = this.getContentLength();
    	                while (remaining > 0) {
    	                    l = instream.read(buffer, 0, (int)Math.min(OUTPUT_BUFFER_SIZE, remaining));
    	                    if (l == -1) {
    	                        break;
    	                    }
    	                    outstream.write(buffer, 0, l);
    	                    remaining -= l;
    	                }
    	            }
    	        } finally {
    	            //instream.close();
    	        }
    	    }
    	};
    	
    	byte[] bytearray = "123456".getBytes();
    	basicHttpEntity.setContent(new ByteArrayInputStream("123456".getBytes()));
    	basicHttpEntity.setContentLength(bytearray.length);
    	//when set contentType socket will be timeout
    	basicHttpEntity.setContentType("text/plain;charset=UTF-8");
    	basicHttpEntity.setChunked(false);
    	
    	httpPost.setEntity(basicHttpEntity);
    	Future<HttpResponse> future = httpclient.execute(httpPost, new FutureCallback<HttpResponse>(){

			@Override
			public void completed(HttpResponse result) {
			}
			@Override
			public void failed(Exception ex) {
				ex.printStackTrace();
			}

			@Override
			public void cancelled() {
			}
    		
    	});
    	try{
    		future.get();
    	}catch (Exception e) {
			// TODO: handle exception
    		e.printStackTrace();
		}
    	System.out.println("sucess.............");
    	
    }
