### ISSUE TITLE
PINPOINT INTERNAL ERROR

### ISSUE THREAD

**Issue by zzfox** [naver/pinpoint#4196]
#### Description
After reset of the network, agent try to reconect the collector.  web console show "**PINPOINT INTERNAL ERROR**" , about 30 minuts later , error auto recovered.

#### Environment

* Pinpoint version: 1.7.3
* agent win10 ,  other: centOs 7

#### Additional Info
agent log:
**manul reset network :** 
2018-06-09 16:13:47 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@6622fc65 exceptionCaught() occurred. state:RUN_SIMPLEX. Caused:远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。

**auto reconnect :**
2018-06-09 16:13:58 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@2cc4310a{channel=[id: 0xa321593f, /172.31.252.230:53514 => /172.31.31.188:9995]state=SocketState(NONE->BEING_CONNECT)}
2018-06-09 16:13:58 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@7e28ff56{channel=[id: 0xee7f953c, /172.31.252.230:53513 => /172.31.31.188:9996]state=SocketState(NONE->BEING_CONNECT)}
2018-06-09 16:13:58 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@73ab83b6{channel=[id: 0x07a406e6, /172.31.252.230:53518 => /172.31.31.188:9994]state=SocketState(NONE->BEING_CONNECT)}

**Comment by koo-taejin** [comment]
hi zzfox 

If the network is automatically recovered after it is reset, this is normal situation.

Does the web console mean messages in the Active Thread Chart?
And if it also is automatically recovered, it is normal situation.

thanks.

**Comment by zzfox** [comment]
Thank you for your reply. 
It is true "The Active Thread Chart shows  PINPOINT INTERNAL ERROR". I mean that ,  The agent reconnected success immediately，but The "Active Thread Chart" recovered about 30 minutes later . How can i reduce the recover time ? And I have not found some configuration to ajust the time.

**Comment by koo-taejin** [comment]
There is no configuration for recovered time.
It is normal to end within a few seconds in general.

Please post errors to the web, collector, and profiler when the error occurs.

thanks.

**Comment by zzfox** [comment]
There is no error in pinpoint-web, I found some message in pinpoint-collector log:

[Please click here for detail info ](https://github.com/zzfox/pinpoint-issue/blob/master/reconnect.txt)

2018-06-12 14:28:23 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@64729f3 handleHandshake() started. requestId:0, data:{socketId=38}
2018-06-12 14:28:23 [INFO ](h.DoNothingChannelStateEventHandler) DoNothingChannelStateEventHandler eventPerformed(). pinpointServer:DefaultPinpointServer@64729f3(remote:/172.16.20.29:65270, state:RUN_SIMPLEX, healthCheckState:WAIT), code:RUN_SIMPLEX
2018-06-12 14:28:23 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@64729f3 stateTo() completed. Socket state change success(updateWanted:RUN_SIMPLEX ,before:RUN_WITHOUT_HANDSHAKE ,current:RUN_SIMPLEX).
2018-06-12 14:28:23 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@64729f3 handleHandshake() completed(isFirst:true). requestId:0, responseCode:SIMPLEX_COMMUNICATION
2018-06-12 14:28:58 [INFO ](c.n.p.c.c.ClusterPointRouter       ) handleStreamCreate packet:BasicStreamPacket{streamChannelId=8}, streamChannel:ServerStreamChannel[Channel:[id: 0x3a17df40, /172.16.17.90:62441 => /172.16.17.90:9997], StreamId:8, State:CONNECT_ARRIVED].
2018-06-12 14:28:58 [INFO ](c.n.p.c.c.r.f.LoggingFilter        ) LoggingFilter doEvent StreamEvent{{remoteAddress=/172.16.17.90:9997, applicationName=gateway, agentId=gateway-3, startTimeStamp=1528784572359, streamChannelContext=ServerStreamChannel[Channel:[id: 0x3a17df40, /172.16.17.90:62441 => /172.16.17.90:9997], StreamId:8, State:CONNECT_ARRIVED]., streamChannelId=8, requestObject=TCmdActiveThreadCount()}.
2018-06-12 14:28:58 [WARN ](c.n.p.c.c.r.StreamRouteHandler     ) Ambiguous ClusterPoint gateway, gateway-3, 1528784572359 (Valid Agent list=[PinpointServerClusterPoint(gateway/gateway-3/1528784572359), version:1.7.3, supportCommandList:[ACTIVE_THREAD_COUNT, ACTIVE_THREAD_DUMP, ECHO, ACTIVE_THREAD_LIGHT_DUMP], pinpointServer:DefaultPinpointServer@52901817(remote:/172.16.20.29:65006, state:RUN_DUPLEX, healthCheckState:WAIT), PinpointServerClusterPoint(gateway/gateway-3/1528784572359), version:1.7.3, supportCommandList:[ACTIVE_THREAD_COUNT, ACTIVE_THREAD_DUMP, ECHO, ACTIVE_THREAD_LIGHT_DUMP], pinpointServer:DefaultPinpointServer@56dbd084(remote:/172.16.20.29:65086, state:RUN_DUPLEX, healthCheckState:WAIT)]).
**2018-06-12 14:28:58 [WARN ](c.n.p.c.c.ClusterPointRouter       ) handleStreamRouteCreate failed. command:TCmdActiveThreadCount(), routeResult:NOT_FOUND**

**Comment by zzfox** [comment]
add config info

[pinpoint-collector.properties](https://github.com/zzfox/pinpoint-issue/blob/master/pinpoint-collector.properties)
[pinpoint-web.properties](https://github.com/zzfox/pinpoint-issue/blob/master/pinpoint-web.properties)
[pinpoint.config](https://github.com/zzfox/pinpoint-issue/blob/master/pinpoint.config)

**Comment by koo-taejin** [comment]
@zzfox 

The problem seems to be that the agent looking at the collector is not unique.

In the case of pinpoint, the agent must reconnect to the collector only after the connection it has is finished.
(This is normal situation. if there are no errors in the code.)

However, i can see that two or more connections are maintained on the same agent in you posted log.
I can see that two connections are alived from 14:26:02 to 14:43:21.
```
2018-06-12 14:25:02 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@52901817(remote:/172.16.20.29:65006, state:RUN_DUPLEX, healthCheckState:WAIT), State=RUN_DUPLEX)
2018-06-12 14:26:02 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@56dbd084(remote:/172.16.20.29:65086, state:RUN_DUPLEX, healthCheckState:WAIT), State=RUN_DUPLEX)


2018-06-12 14:43:21 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@52901817(remote:/172.16.20.29:65006, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), State=UNEXPECTED_CLOSE_BY_CLIENT)
```

I can see suddenly disconnect connection in collector's log. (without any of the healthcheck events happening)
It looks like a ghost connection.
```
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-06-12 14:43:21 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@52901817(remote:/172.16.20.29:65006, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), State=UNEXPECTED_CLOSE_BY_CLIENT)
```

Can I get some agent's logs.

thanks.

**Comment by zzfox** [comment]
@koo-taejin 
There are two projects on 172.16.20.29, means two agent. so sorry , I should have told you earlier.
  you can see the structure at [here](https://github.com/zzfox/pinpoint-issue/blob/master/20180612-1708/succ.png)

[agent-gateway.log](https://github.com/zzfox/pinpoint-issue/blob/master/20180612-1708/agent-gateway.log)

[agent-service.log](https://github.com/zzfox/pinpoint-issue/blob/master/20180612-1708/agent-service.log)

[collector.log](https://github.com/zzfox/pinpoint-issue/blob/master/20180612-1708/collector-catalina.out)

[error_img](https://github.com/zzfox/pinpoint-issue/blob/master/20180612-1708/error-1.png)

**Comment by koo-taejin** [comment]
@zzfox 

Checking the logs, I knewed that the agent was running two on the same ip.
If you look at the logs of agents and collectors

The agent is aware that the connection is broken, and the collector is not aware that the connection is broken.
(It looks like a typical ghost connection.)

It is impossible to solve perfectly.
However, I will try to develop the function to reduce the time of recovery.
If the function development starts later, I will link the issue.

Thank you very much for creating a detailed and well-crafted issue.

**Comment by zzfox** [comment]
@koo-taejin 
Thank you and I have been deployed pinpoint in the production environment.

**Comment by koo-taejin** [comment]
@zzfox 
#4346 #4350 Now you can make settings.

As-Is
```
Agent -> Collector PING interval (default 5min) 
Collector -> Agent PING interval (default 5min) (It operates after receiving the ping once from the agent.)
Maximum time  collector waits for the first ping from Agent (default 30min) (If recived nothing, then connection is disconnected.) 
```

I recommend you to set it up as follows.
If so, I think the problem can be get better or solved.
```
# in pinpoint.config
# Agent -> Collector PING interval 60000 ~ 18000 (1 ~ 3 minutes)
profiler.tcpdatasender.client.ping.interval=

# in pinpoint-collector.properties
# Collector -> Agent PING interval 60000 ~ 18000 (1 ~ 3 minutes)
collector.receiver.base.ping.interval=

# in pinpoint-collector.properties
# Collector pings as much as possible (Agent-> Collector PING interval * 3 + 1 minute)
collector.receiver.base.pingwait.timeout= 
```

thanks.
