### ISSUE TITLE
when we use pinpoint to monitor pinpoint-web，can not trace the call stack

### ISSUE THREAD

**Issue by xttyawei** [naver/pinpoint#4212]
we deploy pinpoint to monitor pinpoint-web, but get several problems. What is the matter, and how to solve  @Xylus 
we add agent in pinpoint-web catalina.sh, and can see the data in web, but in the transaction detail, we can not get the call trace 
![image](https://user-images.githubusercontent.com/40187665/41337449-d54d4b26-6f21-11e8-99cf-c24b89d2b281.png)
and in the agent log, i get the following error
2018-06-13 14:18:32 [DEBUG](faultClassFileTransformerDispatcher:115) [transform] classLoader:WebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@260e86a1
 className:com.fasterxml.jackson.databind.ObjectReader transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate
2018-06-13 14:18:32 [ERROR](faultClassFileTransformerDispatcher:132) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:WebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@260e86a1
 ctxCl:WebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@260e86a1
 agentCl:com.navercorp.pinpoint.bootstrap.classloader.ParallelCapablePinpointURLClassLoader@67117f44 Cause:Cannot find suitable constructor for com.navercorp.pinpoint.plugin.jackson.interceptor.ReadValueInterceptor
com.navercorp.pinpoint.exception.PinpointException: Cannot find suitable constructor for com.navercorp.pinpoint.plugin.jackson.interceptor.ReadValueInterceptor
        at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:88)
        at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:76)
        at com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.getInterceptor(AnnotatedInterceptorFactory.java:114)
        at com.navercorp.pinpoint.profiler.instrument.ASMMethod.createInterceptor(ASMMethod.java:238)
        at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:228)
        at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addScopedInterceptor(ASMMethod.java:142)
        at com.navercorp.pinpoint.plugin.jackson.JacksonPlugin.addInterceptor(JacksonPlugin.java:194)
        at com.navercorp.pinpoint.plugin.jackson.JacksonPlugin.access$100(JacksonPlugin.java:37)
        at com.navercorp.pinpoint.plugin.jackson.JacksonPlugin$3.doInTransform(JacksonPlugin.java:156)
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
        at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform0(DefaultClassFileTransformerDispatcher.java:126)
        at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:107)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2541)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:858)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1301)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1166)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.springframework.util.ClassUtils.getMostSpecificMethod(ClassUtils.java:768)
        at org.springframework.cache.interceptor.AbstractFallbackCacheOperationSource.computeCacheOperations(AbstractFallbackCacheOperationSource.java:130)
        at org.springframework.cache.interceptor.AbstractFallbackCacheOperationSource.getCacheOperations(AbstractFallbackCacheOperationSource.java:96)
        at org.springframework.cache.interceptor.CacheOperationSourcePointcut.matches(CacheOperationSourcePointcut.java:39)
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:225)
        at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:262)
        at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:294)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:118)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:88)
        at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:69)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:330)
        at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:293)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1717)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:113)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1525)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-06-13 14:18:35 [DEBUG](t.i.StandardServiceStartInterceptor:121) AFTER org.apache.catalina.core.StandardService  args:() result:null

**Comment by Xylus** [comment]
Hi @xttyawei 
Please provide some basic information about your environment (eg pinpoint version you're using (both web and the agent attached to it).

That said, the error log is most likely due to mismatch in jackson versions and should just disable jackson from being traced.
What is the url for the trace you've used here, and what were you expecting to see in the call stack? (also, please check your *profiler.sampling.rate*)

**Comment by xttyawei** [comment]
@Xylus , thank you for replay.
we are using version 1.6.2 both for web and agent.
i will check the config file again,  the call stacks have no deeper info for all the urls, and we can not get the MySQL icon in the server map either.

**Comment by xttyawei** [comment]
hi @Xylus , please refer to the following image, as you can see, the call stack can not go deeper,almost every transaction stopped at 'invoke', is this normal situation?  
![image](https://user-images.githubusercontent.com/40187665/41582862-5f36a5aa-73d5-11e8-9a3b-860138e75be3.png)

**Comment by xttyawei** [comment]
@Xylus @jaehong-kim @emeroad  hi everyone，would you please help me，i deployed the pinpoint-agent 1.6.2 in pinpoint-web 1.6.2, and config the mysql database and startup it,  i can see the following servermap as image 1, actually， i add a usergroup and a user successfully as image 2, in my opinion i should see mysql icon in servermap, right?  and also about the call stack , almost all the transactions stopped at 'invoke', can not go deeper as image 3, is this normal situation?
![image](https://user-images.githubusercontent.com/40187665/41589902-4be8cb82-73e8-11e8-80a7-b6461e6afe5d.png)

![image](https://user-images.githubusercontent.com/40187665/41589972-774250c8-73e8-11e8-8c4b-15839f59693b.png)

![image](https://user-images.githubusercontent.com/40187665/41590140-e3072b80-73e8-11e8-84c9-6c3b0980d8a3.png)

**Comment by emeroad** [comment]
Fixed #4293 
 - Please refer to workaround

**Comment by xttyawei** [comment]
thank you @emeroad

**Comment by emeroad** [comment]
hi @xttyawei 
I found a new solution.
 - #4293 Add <Loader delegate="true"/> to $TOMCAT_HOME/conf/context.xml
   https://tomcat.apache.org/tomcat-8.5-doc/class-loader-howto.html
