### ISSUE TITLE
Error! java.lang.NullPointerException

### ISSUE THREAD

**Issue by yin-bp** [naver/pinpoint#4283]
Error! java.lang.NullPointerException in pp 1.7.3

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at com.navercorp.pinpoint.web.task.RequestContextPropagatingTaskDecorator$RequestContextPropagatingRunnable.run(RequestContextPropagatingTaskDecorator.java:50)
	at com.navercorp.pinpoint.web.task.SecurityContextPropagatingTaskDecorator$SecurityContextPropagatingRunnable.run(SecurityContextPropagatingTaskDecorator.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1302)
	at java.util.Collections.unmodifiableList(Collections.java:1287)
	at com.navercorp.pinpoint.web.vo.ResponseHistograms.getResponseTimeList(ResponseHistograms.java:45)
	at com.navercorp.pinpoint.web.applicationmap.appender.histogram.datasource.ResponseHistogramsNodeHistogramDataSource.createNodeHistogram(ResponseHistogramsNodeHistogramDataSource.java:43)
	at com.navercorp.pinpoint.web.applicationmap.appender.histogram.DefaultNodeHistogramFactory.createWasNodeHistogram(DefaultNodeHistogramFactory.java:58)
	at com.navercorp.pinpoint.web.applicationmap.appender.histogram.DefaultNodeHistogramAppender$1.get(DefaultNodeHistogramAppender.java:83)
	at com.navercorp.pinpoint.web.applicationmap.appender.histogram.DefaultNodeHistogramAppender$1.get(DefaultNodeHistogramAppender.java:80)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1590)
	... 6 more

```
The reason is as follows ： 
Method getResponseTimeList  in class com.navercorp.pinpoint.web.vo.ResponseHistograms did not judge variable responseTimes is null or not,then an Null point Exception occur.

```
   public List<ResponseTime> getResponseTimeList(Application application) {
        List<ResponseTime> responseTimes = responseTimeMap.get(application);
        return Collections.unmodifiableList(responseTimes);
    }
```

These code should been modified as follow:

```
   public List<ResponseTime> getResponseTimeList(Application application) {
        List<ResponseTime> responseTimes = responseTimeMap.get(application);
        if (responseTimes == null) {
            responseTimes = new ArrayList<>();
            responseTimeMap.put(application, responseTimes);
        }
        return Collections.unmodifiableList(responseTimes);
    }

```

**Comment by Xylus** [comment]
@yin-bp Good catch!
Thanks for reporting.
Please feel free to make a fix and throw us a PR if you'd like.
If not, let me know so we can get the fix in.

**Comment by yin-bp** [comment]
Please fixed it yourself.

**Comment by Xylus** [comment]
@yin-bp Fixed and merged to master.
Thanks again!
