### ISSUE TITLE
 EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught()

### ISSUE THREAD

**Issue by yxz1025** [naver/pinpoint#4292]
2018-06-23 15:13:01 [WARN ](o.j.n.c.SimpleChannelHandler       :76 ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.io.IOException: Connection reset by peer
  at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
  at sun.nio.ch.IOUtil.read(IOUtil.java:192)
  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
  at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
2018-06-23 15:13:01 [DEBUG](.n.p.r.s.DefaultPinpointServerState:110) DefaultPinpointServer@7933f6f3 stateTo() started. to:UNEXPECTED_CLOSE_BY_CLIENT
2018-06-23 15:13:01 [INFO ](c.z.ZookeeperProfilerClusterManager:103) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7933f6f3(remote:/100.97.72.2:61073, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), State=UNEXPECTED_CLOSE_BY_CLIENT)

**Comment by koo-taejin** [comment]
hi yxz1025

This is because the connection with the agent has been terminated.
(For example, an agent's application restarts or terminates)
Generally, it is a normal situation.

thanks.

**Comment by yxz1025** [comment]
thank you

**Comment by yxz1025** [comment]
2018-06-25 09:53:23 [ERROR](SimpleAsyncUncaughtExceptionHandler:37 ) Unexpected error occurred invoking async method 'public void com.navercorp.pinpoint.collector.service.AgentEventService.handleEvent(com.navercorp.pinpoint.rpc.server.PinpointServer,long,com.navercorp.pinpoint.common.server.util.AgentEventType)'.
java.lang.NullPointerException
  at com.navercorp.pinpoint.collector.service.AgentEventService.handleEvent(AgentEventService.java:84)
  at com.navercorp.pinpoint.collector.service.AgentEventService.handleEvent(AgentEventService.java:73)
  at com.navercorp.pinpoint.collector.service.AgentEventService$$FastClassBySpringCGLIB$$badd1194.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
  at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
2018-06-25 09:53:23 [DEBUG](c.n.p.c.r.h.AgentLifeCycleHandler  :61 ) socketId not found, agent does not support life cycle management - pinpointServer:DefaultPinpointServer@282e6448(remote:/100.117.87.1:11312, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT)

@koo-taejin

**Comment by koo-taejin** [comment]
this issue was resolved via link #4193
