### ISSUE TITLE
zookeeper  Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

### ISSUE THREAD

**Issue by god8816** [naver/pinpoint#4416]
2018-07-27 17:19:31 [WARN ](o.a.z.ClientCnxn                   ) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
2018-07-27 17:19:31 [WARN ](c.n.p.c.c.z.ZookeeperJobWorker     ) handleUpdate failed. caused:Instance must be connected., jobSize:1
com.navercorp.pinpoint.collector.cluster.zookeeper.exception.ConnectionException: Instance must be connected.
	at com.navercorp.pinpoint.collector.cluster.zookeeper.DefaultZookeeperClient.checkState(DefaultZookeeperClient.java:273)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.DefaultZookeeperClient.exists(DefaultZookeeperClient.java:255)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.handleUpdate(ZookeeperJobWorker.java:341)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.handle(ZookeeperJobWorker.java:323)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.run(ZookeeperJobWorker.java:228)
	at java.lang.Thread.run(Thread.java:745)
2018-07-27 17:19:32 [WARN ](c.n.p.c.c.z.ZookeeperJobWorker     ) handleUpdate failed. caused:Instance must be connected., jobSize:1
com.navercorp.pinpoint.collector.cluster.zookeeper.exception.ConnectionException: Instance must be connected.
	at com.navercorp.pinpoint.collector.cluster.zookeeper.DefaultZookeeperClient.checkState(DefaultZookeeperClient.java:273)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.DefaultZookeeperClient.exists(DefaultZookeeperClient.java:255)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.handleUpdate(ZookeeperJobWorker.java:341)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.handle(ZookeeperJobWorker.java:323)
	at com.navercorp.pinpoint.collector.cluster.zookeeper.ZookeeperJobWorker.run(ZookeeperJobWorker.java:228)
	at java.lang.Thread.run(Thread.java:745)
2018-07-27 17:19:32 [WARN ](o.a.z.ClientCnxn                   ) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

pinpoint version：1.7.3  
zookeeper  version: 3.4.6

**Comment by RoySRose** [comment]
Hello, @god8816
Do check your configuration on your zookeeper cluster's address

**Comment by god8816** [comment]
Hello,@RoySRose 
  my  zookeeper  single node , not cluster's。

**Comment by koo-taejin** [comment]
@god8816 
I hope you write a little more detailed explanation.
If disconnected from the zookeeper server, this is a normal log.

Therefore, it is impossible to judge whether there is a problem.

Please explain in detail what kind of operation after connection brokened.
It is even better if you give them a situation that can be reproduced.

**Comment by god8816** [comment]
@koo-taejin  zookeeper 
[admin@vm-xaj-vmc-pinpoint-collector-d01 classes]$ telnet zookeeper-test.idc.yst.com.cn 2181
Trying 10.213.2.141...
Connected to zookeeper-test.idc.yst.com.cn.
Escape character is '^]'     
it can connected from the zookeeper server

**Comment by god8816** [comment]
@koo-taejin  why pinpoint can not Connected zookeeper?

**Comment by koo-taejin** [comment]
@god8816 

Please check your zookeepr related settings.
If there are no problems with the settings.
It is recommended to test the connection using the Zookeeper library.

**Comment by rambolijian** [comment]
same problem here.

But my pinpoint was working before today. Now It's broken, I check the log. It's the same issue. connects ZK refused.

**Comment by loyalvares** [comment]
**zookeeper Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect**
**_"server null"_** indicates that you have forgotten to pass the server parameters while running your zookeeper CLI.
Your command should be like this:
./zkCli.sh -server <hostname:port>
If you don't specify port it will take the default 2181.
