### ISSUE TITLE
pinpoint-agent can not connect   pinpoint-collector

### ISSUE THREAD

**Issue by god8816** [naver/pinpoint#4422]
2018-07-30 16:39:38 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@77aca585{channel=[id: 0x7d129268, /10.213.4.137:37653 => /10.213.4.135:9994]state=SocketState(NONE->BEING_CONNECT)}
2018-07-30 16:43:28 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.
2018-07-30 16:48:28 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.
2018-07-30 16:53:28 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.
2018-07-30 16:58:28 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.
2018-07-30 17:03:28 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.
2018-07-30 17:08:28 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.
2018-07-30 17:10:04 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:07 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:10 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:13 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:16 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:19 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:22 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:26 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:29 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:32 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:35 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:38 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:41 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:44 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:47 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:50 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:53 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:10:57 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:11:00 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:11:03 [WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='10.213.4.135', port=9994}
2018-07-30 17:11:03 [WARN ](c.n.p.r.c.DefaultPinpointClient    ) reconnectClientHandler:DefaultPinpointClientHandler@6103ff59{channel=[id: 0xe7ecf128, /10.213.4.137:38785 => /10.213.4.135:9994]state=SocketState(NONE->BEING_CONNECT)}

**Comment by RoySRose** [comment]
Hello, @god8816 

You should check the IP settings in the configuration file or the firewall settings.

Also [Agent - Collector checker](https://naver.github.io/pinpoint/troubleshooting_network.html) might help you:)

**Comment by god8816** [comment]
hello, @RoySRose
[root@vm-xaj-vmc-pp-agent-d01 script]# sh /home/admin/work/ppagent/pinpoint-agent-1.7.3/script/networktest.sh
: command not foundagent/pinpoint-agent-1.7.3/script/networktest.sh: line 2:
/..: No such file or directoryint-agent-1.7.3/script/networktest.sh: line 4: cd: /home/admin/work/ppagent/pinpoint-agent-1.7.3/script
: command not foundagent/pinpoint-agent-1.7.3/script/networktest.sh: line 5:
CLASSPATH=
Error: Could not find or load main class com.navercorp.pinpoint.tools.NetworkAvailabilityChecker


[root@vm-xaj-vmc-pp-agent-d01 tools]# java -jar  pinpoint-tools-1.7.3.jar  /home/admin/work/ppagent/pinpoint-agent-1.7.3/pinpoint.config
no main manifest attribute, in pinpoint-tools-1.7.3.jar

**Comment by god8816** [comment]
2018-07-31 13:38:10 [WARN ](c.n.p.p.s.RetryQueue               ) discard retry message(RetryMessage{retryCount=3, maxRetryCount=3, bytes=1079, messageDescription='TSqlMetaData'}).
2018-07-31 13:38:10 [INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:RetryMessage{retryCount=3, maxRetryCount=3, bytes=105, messageDescription='TStringMetaData'}, caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
	at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RoySRose** [comment]
About the log of [Agent - Collector checker](https://naver.github.io/pinpoint/troubleshooting_network.html) Please read the documents carefully.

You see.... there isn't anything I can do for you even I want to, if you have incorrectly set the configuration or it's about the firewall
