### ISSUE TITLE
Error creating bean with name 'pinpointSocketManager'

### ISSUE THREAD

**Issue by cowboy93** [naver/pinpoint#451]
Tomcat 7 에서 collector와 web을 기동하려는데 잘 안되서 문의 드립니다. 

바쁘시겠지만 확인 부탁드리겠습니다. 

1. 자바 버전은 다음과 같습니다. 
 java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

2. 기본 환경은 MAC OS 입니다. 

3. web관련 오류 로그는 다음과 같습니다. 
15:55:13 INFO (o.s.c.e.EhCacheManagerFactoryBean  :164) Shutting down EhCache CacheManager
15:55:13 ERROR(o.a.h.h.c.HConnectionManager       :338) Connection not found in the list, can't delete it (connection key=HConnectionKey{properties={hbase.rpc.timeout=60000, hbase.zookeeper.property.clientPort=2181, hbase.client.pause=1000, zookeeper.znode.parent=/hbase, hbase.client.retries.number=14, hbase.zookeeper.quorum=localhost}, username='1000893'}). May be the key was modified?
15:55:13 ERROR(o.s.w.c.ContextLoader              :319) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pinpointSocketManager' defined in class path resource [applicationContext-web.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.navercorp.pinpoint.web.server.PinpointSocketManager]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.navercorp.pinpoint.rpc.server.ServerPipelineFactory.<init>(Lcom/navercorp/pinpoint/rpc/server/PinpointServerAcceptor$PinpointServerChannelHandler;)V
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1045)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:949)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:626)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.navercorp.pinpoint.web.server.PinpointSocketManager]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.navercorp.pinpoint.rpc.server.ServerPipelineFactory.<init>(Lcom/navercorp/pinpoint/rpc/server/PinpointServerAcceptor$PinpointServerChannelHandler;)V
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280)
	... 27 more
Caused by: java.lang.NoSuchMethodError: com.navercorp.pinpoint.rpc.server.ServerPipelineFactory.<init>(Lcom/navercorp/pinpoint/rpc/server/PinpointServerAcceptor$PinpointServerChannelHandler;)V
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.addPipeline(PinpointServerAcceptor.java:136)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:101)
	at com.navercorp.pinpoint.web.server.PinpointSocketManager.<init>(PinpointSocketManager.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 29 more
5월 21, 2015 3:55:13 오후 org.apache.catalina.core.StandardContext startInternal
심각: One or more listeners failed to start. Full details will be found in the appropriate container log file
5월 21, 2015 3:55:13 오후 org.apache.catalina.core.StandardContext startInternal
심각: Context [] startup failed due to previous errors

4. collector관련 오류는 다음과 같습니다. 
05-21 15:55:09 [ERROR](o.s.w.c.ContextLoader              :319) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tcpReceiver' defined in class path resource [applicationContext-collector.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.navercorp.pinpoint.collector.receiver.tcp.TCPReceiver]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.navercorp.pinpoint.rpc.server.ServerPipelineFactory.<init>(Lcom/navercorp/pinpoint/rpc/server/PinpointServerAcceptor$PinpointServerChannelHandler;)V
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1045)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:949)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:626)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5528)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.navercorp.pinpoint.collector.receiver.tcp.TCPReceiver]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.navercorp.pinpoint.rpc.server.ServerPipelineFactory.<init>(Lcom/navercorp/pinpoint/rpc/server/PinpointServerAcceptor$PinpointServerChannelHandler;)V
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280)
	... 27 more
Caused by: java.lang.NoSuchMethodError: com.navercorp.pinpoint.rpc.server.ServerPipelineFactory.<init>(Lcom/navercorp/pinpoint/rpc/server/PinpointServerAcceptor$PinpointServerChannelHandler;)V
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.addPipeline(PinpointServerAcceptor.java:136)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:101)
	at com.navercorp.pinpoint.collector.receiver.tcp.TCPReceiver.<init>(TCPReceiver.java:105)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 29 more
5월 21, 2015 3:55:09 오후 org.apache.catalina.core.StandardContext startInternal
심각: One or more listeners failed to start. Full details will be found in the appropriate container log file
5월 21, 2015 3:55:09 오후 org.apache.catalina.core.StandardContext startInternal
심각: Context [/pinpoint-collector-1.5.0-SNAPSHOT] startup failed due to previous errors

**Comment by cowboy93** [comment]
그리고 코드 버전은 최신 버전입니다.

**Comment by cowboy93** [comment]
내부 개발자 분을 통해서 원인 파악 및 조치 완료 되었습니다. 

가이드 문서에 
만약 이전 버전으로 빌드가 된 상태라면
mvn clean verify -Dmaven.test.skip=true
를 먼저 실행하기 바란다.

라고 명시해 주셔야 할 것 같습니다. 

그렇지 않으면, 
WEB-INF/lib/
에 예전 버전의 라이브러리도 같이 포함되어서 정상적인 기동이 되지 않습니다. ^^;

**Comment by nstopkimsk** [comment]
가이드 문서에 기록하도록 하겠습니다. 감사합니다.
