### ISSUE TITLE
pinpoint raised dubbo interceptor nullpoint exception

### ISSUE THREAD

**Issue by stoneLee81** [naver/pinpoint#4536]
**What version of pinpoint are you using?**
master/v1.7.3

**What did you do to trigger the bug?**
The env conf successfully and could get data in WEBUI, but when calling dubbo provider, the pippoint dubbo interceptor exception raised.

**Expected behavior**

**Logs**
INFO -  [DUBBO] Notify urls for subscribe url consumer:///com.alibaba.dubbo.monitor.MonitorService?category=providers,configurators,routers&dubbo=2.6.2&interface=com.alibaba.dubbo.monitor.MonitorService&pid=7832&timestamp=1535006765142, urls: [empty:///com.alibaba.dubbo.monitor.MonitorService?category=providers&dubbo=2.6.2&interface=com.alibaba.dubbo.monitor.MonitorService&pid=7832&timestamp=1535006765142, empty:///com.alibaba.dubbo.monitor.MonitorService?category=configurators&dubbo=2.6.2&interface=com.alibaba.dubbo.monitor.MonitorService&pid=7832&timestamp=1535006765142, empty:///com.alibaba.dubbo.monitor.MonitorService?category=routers&dubbo=2.6.2&interface=com.alibaba.dubbo.monitor.MonitorService&pid=7832&timestamp=1535006765142], dubbo version: 2.6.2, current host: 172.16.16.9
2018-08-23 14:47:00 [WARN ](.n.p.p.d.i.DubboProviderInterceptor) BEFORE. Caused:null
java.lang.NullPointerException
	at com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboProviderInterceptor.doInBeforeTrace(DubboProviderInterceptor.java:161)
	at com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboProviderInterceptor.before(DubboProviderInterceptor.java:51)
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.before(ExceptionHandleAroundInterceptor.java:35)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java)
	at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.aicall.filter.dubbo.DubboCatCrossFilter.invoke(DubboCatCrossFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by koo-taejin** [comment]
hi @stoneLee81 

Resolved in this issue via #4135.
