### ISSUE TITLE
pinpoint1.8+jdk1.6x-error

### ISSUE THREAD

**Issue by delgyd** [naver/pinpoint#4553]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:323)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:338)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider weblogic.xml.jaxp.RegistryDocumentBuilderFactory not found
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:129)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:849)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:773)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:66)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:112)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:100)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:46)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:35)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:63)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:58)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:53)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:128)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:82)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
./startWebLogic.sh: line 184: 103242 Aborted                 ${JAVA_HOME}/bin/java ${JAVA_VM} ${MEM_ARGS} -Dweblogic.Name=${SERVER_NAME} -Djava.security.policy=${WL_HOME}/server/lib/weblogic.policy ${JAVA_OPTIONS} ${PROXY_SETTINGS} ${SERVER_CLASS

**Comment by emeroad** [comment]
https://stackoverflow.com/questions/4925901/classcastexception-while-parsing-xml-with-weblogic

**Comment by emeroad** [comment]
refer to : #6101
