### ISSUE TITLE
java.lang.ClassNotFoundException: javax.servlet.AsyncListener

### ISSUE THREAD

**Issue by tonylit** [naver/pinpoint#4564]
Hi, 
1.8.0-RC1 release notes
WildFly 8.1.0.Final

some error messages：
`2018-08-29 19:04:03 [WARN ](.i.c.JarProfilerPluginClassInjector) Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))
com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:86)
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:66)
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:156)
	at com.navercorp.pinpoint.profiler.instrument.ScopeFactory.newScopeInfo(ScopeFactory.java:36)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:227)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:127)
	at com.navercorp.pinpoint.plugin.undertow.UndertowPlugin$1.doInTransform(UndertowPlugin.java:68)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:57)
	at com.navercorp.pinpoint.profiler.MatchableClassFileTransformerDispatcher.transform(MatchableClassFileTransformerDispatcher.java:131)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92)
	at org.jboss.modules.Module.loadModuleClass(Module.java:568)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134)
	at io.undertow.server.protocol.http.HttpTransferEncoding.setupRequest(HttpTransferEncoding.java:89)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:151)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:91)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:43)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.NioTcpServerHandle.handleReady(NioTcpServerHandle.java:53)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)
Caused by: java.lang.RuntimeException: com.navercorp.pinpoint.plugin.undertow.UndertowAsyncListener define fail Caused by:null
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.handleDefineClassFail(ReflectionDefineClass.java:59)
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.defineClass(ReflectionDefineClass.java:53)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:300)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:287)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:225)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.getClassLoaderAttachment(PlainClassLoaderHandler.java:171)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:127)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:83)
	... 34 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.defineClass(ReflectionDefineClass.java:49)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: javax/servlet/AsyncListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	... 44 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.AsyncListener from [Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134)
	... 47 more
2018-08-29 19:04:03 [ERROR](c.n.p.p.BaseClassFileTransformer   ) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. url:jar:file:/opt/wildfly/modules/system/layers/base/io/undertow/core/main/undertow-core-1.0.15.Final.jar!/ cl:ModuleClassLoader for Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base)) ctxCl:ModuleClassLoader for Module "org.wildfly.extension.io:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base)) agentCl:ParallelClassLoader{name='pinpoint.agent'} com.navercorp.pinpoint.bootstrap.classloader.ParallelClassLoader@5e481248 Cause:Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))
com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:71)
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:156)
	at com.navercorp.pinpoint.profiler.instrument.ScopeFactory.newScopeInfo(ScopeFactory.java:36)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:227)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:127)
	at com.navercorp.pinpoint.plugin.undertow.UndertowPlugin$1.doInTransform(UndertowPlugin.java:68)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:57)
	at com.navercorp.pinpoint.profiler.MatchableClassFileTransformerDispatcher.transform(MatchableClassFileTransformerDispatcher.java:131)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:361)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:482)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:277)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:92)
	at org.jboss.modules.Module.loadModuleClass(Module.java:568)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134)
	at io.undertow.server.protocol.http.HttpTransferEncoding.setupRequest(HttpTransferEncoding.java:89)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:151)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:91)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:43)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.NioTcpServerHandle.handleReady(NioTcpServerHandle.java:53)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)
Caused by: com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:86)
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:66)
	... 33 more
Caused by: java.lang.RuntimeException: com.navercorp.pinpoint.plugin.undertow.UndertowAsyncListener define fail Caused by:null
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.handleDefineClassFail(ReflectionDefineClass.java:59)
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.defineClass(ReflectionDefineClass.java:53)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:300)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:287)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:225)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.getClassLoaderAttachment(PlainClassLoaderHandler.java:171)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:127)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:83)
	... 34 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.defineClass(ReflectionDefineClass.java:49)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: javax/servlet/AsyncListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	... 44 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.AsyncListener from [Module "io.undertow.core:main" from local module loader @4a951911 (finder: local module finder @55b62629 (roots: /opt/wildfly/modules,/opt/wildfly/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134)
	... 47 more`

**Comment by jaehong-kim** [comment]
@tonylit 
Not yet supporting wildfly.
It seems to be a problem that occurs when the UndertowPlugin is executed and the javax.servlet.AsyncListener class is not found.

Set Undertow plugin to disable.
~~~
profiler.undertow.enable=false
~~~

Otherwise, you need to be able to read javax.servlet.AsyncListener from wildfly(e.g. modules/system/layers/base/javax/servlet/api/main/jboss-servlet-api_3.1_spec-1.0.0.Final.jar)
