### ISSUE TITLE
no data send to collector when agent attach to weblogic with ibm jdk

### ISSUE THREAD

**Issue by aximo** [naver/pinpoint#4585]
**What version of pinpoint are you using?**
master/v1.8.0

**Describe the bug**
I hava war deployed in weblogic with ibm jdk, agent start successfully,but no data send to collector,even agent info.

**What did you do to trigger the bug?**
1.  attach the agent weblogic ,the java properties are:
```
java.vendor=IBM Corporation
java.vm.specification.vendor=Sun Microsystems Inc.
java.runtime.version=pxa6470sr3-20121025_01 (SR3)
java.compiler=j9jit26
java.version=1.7.0
java.endorsed.dirs=/usr/local/incomev3_ndev/java-x86_64-70/jre/lib/endorsed:/usr/local/incomev3_ndev/Middleware/wlserver_12.1/endorsed
java.class.version=51.0
java.home=/usr/local/incomev3_ndev/java-x86_64-70/jre
java.vm.info=JRE 1.7.0 Linux amd64-64 20121024_126071 (JIT enabled, AOT enabled)
java.vm.version=2.6
...
```
2.  start the weblogic, and pinpoint log show:
```
...
2018-09-06 10:31:17 [INFO ](DefaultAnnotationKeyRegistryService:89 ) add Plugin AnnotationKey:AnnotationKey{code=112, name='hystrix.command.fallback.cause}
2018-09-06 10:31:17 [INFO ](DefaultAnnotationKeyRegistryService:89 ) add Plugin AnnotationKey:AnnotationKey{code=113, name='hystrix.command.exception}
2018-09-06 10:31:17 [INFO ](DefaultAnnotationKeyRegistryService:89 ) add Plugin AnnotationKey:AnnotationKey{code=115, name='hystrix.command.key}
2018-09-06 10:31:17 [INFO ](DefaultAnnotationKeyRegistryService:89 ) add Plugin AnnotationKey:AnnotationKey{code=116, name='hystrix.command.group.key}
2018-09-06 10:31:17 [INFO ](DefaultAnnotationKeyRegistryService:89 ) add Plugin AnnotationKey:AnnotationKey{code=117, name='hystrix.thread.pool.key}
2018-09-06 10:31:17 [INFO ](DefaultAnnotationKeyRegistryService:89 ) add Plugin AnnotationKey:AnnotationKey{code=118, name='hystrix.collapser.key}
2018-09-06 10:32:16 [INFO ](c.n.p.r.c.PinpointClientHandshaker :312) PinpointClientHandshaker@2a4c962e HandshakeJob completed.

```

no more logs in pinpoint.log
3.  the agent is not appeared in web ui, and the pinpoint.log has no log about agent info send.

**Expected behavior**
the data can be sent to collector.

**Additional context**
I check the network,there is no problem
```
[incomev3_gs_ndev@xen12-213 gs]$ netstat -ano |grep 9994
tcp        0      0 ::ffff:172.25.12.213:52331  ::ffff:172.25.13.46:9994    ESTABLISHED keepalive (3310.39/0/0)
```

I just change config in pinpoint.config file with
```
profiler.collector.ip=172.25.13.46
profiler.applicationservertype=WEBLOGIC
```

**Comment by RoySRose** [comment]
Hello, @aximo 

why don't you try the [network test](https://naver.github.io/pinpoint/troubleshooting_network.html)

**Comment by aximo** [comment]
@RoySRose 

i check the network, there is no problem.

I get the error：
```
Caused by: java.lang.NoSuchMethodError: com/ibm/lang/management/OperatingSystemMXBean.getProcessCpuLoad()D
        at com.navercorp.pinpoint.profiler.monitor.metric.cpu.ibm.DefaultCpuLoadMetric.getSnapshot(DefaultCpuLoadMetric.java:40)
        at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:40)
        at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:26)
```

it seems that the method **getProcessCpuLoad**  lost int ibm jdk7. and i check the jdk source, the method lost indeed.

I fix the issue by adding a switch in com.navercorp.pinpoint.profiler.context.provider.stat.cpu.CpuLoadMetricProvider.get()

**Comment by Xylus** [comment]
Hi @aximo 
Looks like your version of ibm jdk 7 does not have `com.ibm.lang.management.OperatingSystemMXBean.getProcessCpuLoad()`.
We've used https://www.ibm.com/support/knowledgecenter/en/SSYKE2_7.0.0/com.ibm.java.api.70.doc/com.ibm.lang.management/com/ibm/lang/management/OperatingSystemMXBean.html as reference, and tested using the jdk we got from ibm developer's site : 
```
java version "1.7.0"
Java(TM) SE Runtime Environment (build pxa6470_27sr3fp40-20160422_01(SR3 FP40))
IBM J9 VM (build 2.7, JRE 1.7.0 Linux amd64-64 Compressed References 20160406_298393 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160406_0942_B298393
JIT  - tr.r13.java_20160328_114186
GC   - R27_Java727_SR3_20160406_0942_B298393_CMPRSS
J9CL - 20160406_298393)
JCL - 20160421_01 based on Oracle jdk7u101-b14
```
Looks like there are other ibm java versions out there.
Could you (if possible) share where we can gain access to the jdk you're using? We'd like to run tests on it to see what else breaks.

Either way, we'll add a fix to take care of such cases for 1.8.1.
Thanks for reporting.

**Comment by Xylus** [comment]
@aximo 
Thanks for the upload.
Unfortunately, I can't register on Baidu to get the download working.
Is there any other way I could get the binary? You can simply point me to where I can get it if it's available to the public.

**Comment by aximo** [comment]
@Xylus 

pls down sdk from https://github.com/aximo/public-repo

by the way, the com.ibm.lang.management.OperatingSystemMXBean.getSystemCpuLoad() lost in our ibm java sdk 1.6,so pinpoint agent fail at com.navercorp.pinpoint.profiler.monitor.metric.cpu.ibm.Java6CpuLoadMetric.getSnapshot().

 I also upload it.

**Comment by Xylus** [comment]
@aximo 
Awesome, thank you very much!
We'll have a fix in for both. Does your ibm java 8 work okay?
