### ISSUE TITLE
collector failed to handle concurrent job using hadoop

### ISSUE THREAD

**Issue by pikuzi** [naver/pinpoint#4607]
**What version of pinpoint are you using?**
v1.7.3

**Describe your problem**
We have pinpoint 1.7.3 agent deployed for java application, and pinpoint collector, web connected with hadoop 2.7.6 (three nodes cluster), but we got error from the collector as below,

2018-09-12 19:51:26 [WARN ](o.j.n.c.SimpleChannelHandler       :76 ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.util.concurrent.RejectedExecutionException: Task com.navercorp.pinpoint.collector.receiver.tcp.AgentBaseDataReceiver$3@4a9b01d8 rejected from java.util.concurrent.ThreadPoolExecutor@5df91120[Running, pool size = 8, active threads = 8, queued tasks = 1024, completed tasks = 0]
  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
  at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
  at com.navercorp.pinpoint.collector.receiver.tcp.AgentBaseDataReceiver.requestResponse(AgentBaseDataReceiver.java:172)
  at com.navercorp.pinpoint.collector.receiver.tcp.AgentBaseDataReceiver.access$100(AgentBaseDataReceiver.java:55)
  at com.navercorp.pinpoint.collector.receiver.tcp.AgentBaseDataReceiver$1.handleRequest(AgentBaseDataReceiver.java:137)
  at com.navercorp.pinpoint.rpc.server.DefaultPinpointServer.handleRequest(DefaultPinpointServer.java:374)
  at com.navercorp.pinpoint.rpc.server.DefaultPinpointServer.messageReceived(DefaultPinpointServer.java:320)
  at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.messageReceived(PinpointServerAcceptor.java:384)
  at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
  at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

I also checked the log in agent, nothing help.

2018-09-12 20:32:08 [INFO ](c.n.p.p.AgentInfoSender            ) Sending AgentInfo TAgentInfo(hostname:VM_66_91_centos, ip:10.218.66.91, ..........................
 jvmInfo:TJvmInfo(version:0, vmVersion:1.8.0_181, gcType:SERIAL))
2018-09-12 20:32:12 [WARN ](c.n.p.p.AgentInfoSender            ) request timed out while waiting for response.

**What have you done?**
Steps you have taken to trigger the problem, for example:
1. Launched '...' with agent
2. Tried tracing '...' (see agent log below)
3. Collector outputs trace log (see collector log below)
4. No trace shows up in the web UI (see web log below)
all aboves were done and logs genated as above.

**Screenshots**
don't need screenshot
**Logs**
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

**Additional context**
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.
it is very typically java aplication using tomcat or jar, also we have multiple applications using pinpoint to monitor, so I believe the problem is not with the applications but pinpoint collector itself.
BTW: we have testing environment has the same pinpoint version installed, the only difference is using single node Hbase, but it works very well.

thanks a lot for your help.

**Comment by koo-taejin** [comment]
hi @pikuzi 

The problem can be adjusted by modifying the number of threads and the size of the queue.
(in pinpoint-collector.properties)

However, a completed tasks value of 0 means that the logic may be stopped at some point.

I recommand to record the collector's thread dump in that situation.
and try to find where the operation is not completed

thanks.
