### ISSUE TITLE
Pinpoint Agent load failure

### ISSUE THREAD

**Issue by shenhongwei33** [naver/pinpoint#4630]
WebSphere Platform 7.0.0.0 [ND 7.0.0.0 r0835.03] running with process name spark-w1Node01Cell\spark-w1Node01\server1 and process id 10489
Host Operating System is Linux, version 3.10.0-327.28.3.el7.x86_64
Java version = 1.6.0, Java Compiler = j9jit24, Java VM name = IBM J9 VM
was.install.root = /data/WAS
user.install.root = /data/WAS/profiles/AppSrv01
Java Home = /data/WAS/java/jre
ws.ext.dirs = /data/WAS/java/lib:/data/WAS/profiles/AppSrv01/classes:/data/WAS/classes:/data/WAS/lib:/data/WAS/installedChannels:/data/WAS/lib/ext:/data/WAS/web/help:/data/WAS/deploytool/itp/plugins/com.ibm.etools.ejbdeploy/runtime
Classpath = /data/WAS/profiles/AppSrv01/properties:/data/WAS/properties:/data/WAS/lib/startup.jar:/data/WAS/lib/bootstrap.jar:/data/WAS/lib/jsf-nls.jar:/data/WAS/lib/lmproxy.jar:/data/WAS/lib/urlprotocols.jar:/data/WAS/deploytool/itp/batchboot.jar:/data/WAS/deploytool/itp/batch2.jar:/data/WAS/java/lib/tools.jar:/data/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar:/data/pinpoint-agent/pinpoint-bootstrap-1.5.0.jar
Java Library path = /data/WAS/java/jre/lib/amd64/compressedrefs:/data/WAS/java/jre/lib/amd64:/data/WAS/bin::/usr/lib
************* End Display Current Environment *************
2018-09-17 19:56:47 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint start failed.
com.navercorp.pinpoint.bootstrap.BootStrapException: execute fail. Error:null
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:52)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:73)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:45)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:45)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:39)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:515)
	at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:78)
	at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
	... 9 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: com/ibm/lang/management/OperatingSystemMXBean.getProcessCpuTimeByNS()J
  at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:63)
  while locating com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor
  at com.navercorp.pinpoint.profiler.context.module.ApplicationContextModule.configure(ApplicationContextModule.java:258)
  while locating com.navercorp.pinpoint.profiler.monitor.AgentStatMonitor

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:102)
	at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:86)
	at com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:125)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:118)
	at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:69)
	... 15 more
Caused by: java.lang.NoSuchMethodError: com/ibm/lang/management/OperatingSystemMXBean.getProcessCpuTimeByNS()J
	at com.navercorp.pinpoint.profiler.monitor.metric.cpu.ibm.Java6CpuLoadMetric.getSnapshot(Java6CpuLoadMetric.java:47)
	at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:40)
	at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:26)
	at com.navercorp.pinpoint.profiler.monitor.collector.AgentStatCollector.collect(AgentStatCollector.java:99)
	at com.navercorp.pinpoint.profiler.monitor.collector.AgentStatCollector.collect(AgentStatCollector.java:34)
	at com.navercorp.pinpoint.profiler.monitor.CollectJob.run(CollectJob.java:67)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.preLoadClass(DefaultAgentStatMonitor.java:104)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:91)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:63)
	at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor$$FastClassByGuice$$1e15b61b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 23 more

*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************
How to solve this problem？

**Comment by chuanyi-fang** [comment]
I found that there isn't " java.lang.management" in the IBM JDK 1.6
So pp-agent can't suppot  the  IBM JDK 1.6, is it right?
@emeroad

![image](https://user-images.githubusercontent.com/20055737/45656389-b891b980-bb17-11e8-8dea-83252f1d77ca.png)


![image](https://user-images.githubusercontent.com/20055737/45656365-926c1980-bb17-11e8-9786-46846331ec02.png)

**Comment by Xylus** [comment]
@chuanyi-fang 
Looks like your version of ibm java 6 does not have the method above.
We'll fix the startup error in the next version.

In the mean time, could you try it again with the jdk 6 downloaded from the ibm website?
Thanks.

**Comment by chuanyi-fang** [comment]
#3579

**Comment by Xylus** [comment]
resolved via #4694
