### ISSUE TITLE
There is a com.aliyun.oss.InconsistentException in aliyun_sdk_oss 2.8.1 with pinponit 1.7.3

### ISSUE THREAD

**Issue by reymont** [naver/pinpoint#4667]
pinpoint=1.7.3
com.aliyun.oss:aliyun-sdk-oss=2.8.1

The shell is:
```
java -server -Xmx300m -javaagent:/pinpoint-agent-1.7.3/pinpoint-bootstrap-1.7.3.jar \
    -Dpinpoint.agentId=PoiApplication \
    -Dpinpoint.applicationName=PoiApplication \
    -Dfile.encoding=UTF-8 -jar jego-managerportal-poi-5.2.0.2.jar \
    --spring.cloud.config.uri=http://configuration-service.dev03.svc.cluster.local:8888

```

The client invoke:
```java
public OSSClient client;
client = new OSSClient(endpoint, accessKeyId, accessKeySecret);
result = client.putObject(accessService.defaultBucketName, key, content, meta);
```

got the error:
```log
com.aliyun.oss.InconsistentException: InconsistentException 
[RequestId]: 5BA9B6486D740B8A2FCECDA0
[ClientChecksum]: 711120333747229212
[ServerChecksum]: 9180275173150973139
	at com.aliyun.oss.internal.OSSUtils.checkChecksum(OSSUtils.java:484)
	at com.aliyun.oss.internal.OSSObjectOperation.putObject(OSSObjectOperation.java:154)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:473)
	at com.aliyun.oss.OSSClient.putObject(OSSClient.java:455)
	at com.cmi.jego.poi.action.BaseController.putObject(BaseController.java:321)
	at com.cmi.jego.poi.action.BaseController.uploadFileOSS(BaseController.java:255)
```

**Comment by reymont** [comment]
i find the season that aliyun ossclient also use httpclient to check the checksum of inputstream. i just omitted to trace the httpclient.

**Comment by tuzhis** [comment]
1.7.0 also trigger this problem，find out two solutions：
1. if use pinpoint1.7.x need modify config
```
profiler.apache.httpclient3.io=false 
profiler.apache.httpclient4.io=false
```
2. upgrade pinpoint to 1.8.x or above
