### ISSUE TITLE
collector-1.6.0 Erroneous invalid packetType received. packetType

### ISSUE THREAD

**Issue by hanrongsu** [naver/pinpoint#4754]
hello, collector-1.6.0 Erroneous  invalid packetType received. packetType,What is the reason?
The detailed logs are as follows:

2018-10-12 11:24:42 [ERROR] (com.navercorp.pinpoint.rpc.codec.PacketDecoder : 105 ) invalid packetType received. packetType:23821, channel:[id: 0x4b6d8a71, /10.11.23.67:56922 => /10.34.231.102:9994]
2018-10-12 11:24:42 [WARN ] (com.navercorp.pinpoint.collector.rpc.handler.AgentLifeCycleChangeEventHandler : 64 ) AgentLifeCycleChangeEventHandler exceptionCaught(). pinpointServer:DefaultPinpointServer@e8431e1(remote:/10.208.222.14:56922, state:UNEXPECTED_CLOSE_BY_CLIENT), code:UNEXPECTED_CLOSE_BY_CLIENT. error: null.
java.lang.NullPointerException
	at com.navercorp.pinpoint.collector.rpc.handler.AgentEventHandler.handleEvent(AgentEventHandler.java:83)
	at com.navercorp.pinpoint.collector.rpc.handler.AgentEventHandler.handleEvent(AgentEventHandler.java:68)
	at com.navercorp.pinpoint.collector.rpc.handler.AgentLifeCycleChangeEventHandler.eventPerformed(AgentLifeCycleChangeEventHandler.java:58)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.executeChangeEventHandler(DefaultPinpointServerState.java:125)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.to(DefaultPinpointServerState.java:114)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServerState.toUnexpectedClosedByPeer(DefaultPinpointServerState.java:94)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServer.stop(DefaultPinpointServer.java:144)
	at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.channelDisconnected(PinpointServerAcceptor.java:377)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:120)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.channelDisconnected(FrameDecoder.java:365)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:102)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:81)
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.channel.SimpleChannelHandler.closeRequested(SimpleChannelHandler.java:334)
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:260)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.close(Channels.java:812)
	at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:205)
	at com.navercorp.pinpoint.rpc.codec.PacketDecoder.decode(PacketDecoder.java:106)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by koo-taejin** [comment]
hi @hanrongsu 

It may be related to the issue.
#3217

Please change the version of all agents connected to the collector and collector to 1.7.0 or higher.
And check continue to have problems.

thanks.

**Comment by hanrongsu** [comment]
@koo-taejin ok,Thank you for the reply!
