### ISSUE TITLE
pinpoint configuration can‘t add User and User Group

### ISSUE THREAD

**Issue by dxs08091** [naver/pinpoint#4777]
i can't add User Group and User,my version is 1.7.3+hbase1.2.6

![image](https://user-images.githubusercontent.com/23046387/47250614-d9bb3200-d456-11e8-9272-b926d1720085.png)

**Comment by minwoo-jung** [comment]
Hi @dxs08091
Did you see log message in pinpoint web?

**Comment by minwoo-jung** [comment]
Hi @dxs08091
Did you see log message in pinpoint web?

**Comment by dxs08091** [comment]
the log :



[ERROR](c.n.p.w.c.UserGroupController      ) Exception occurred while trying to CRUD userGroup information
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure


The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:289)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:447)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy40.createUserGroup(Unknown Source)
        at com.navercorp.pinpoint.web.controller.UserGroupController.createUserGroup(UserGroupController.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)





At 2018-10-22 13:55:15, "Minwoo Jung" <notifications@github.com> wrote:


Hi @dxs08091
Did you see log message in pinpoint web?

**Comment by minwoo-jung** [comment]
Please ref [doc](https://github.com/naver/pinpoint/blob/master/doc/alarm.md#3-configuring-mysql)
