### ISSUE TITLE
com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception

### ISSUE THREAD

**Issue by fionaliupw** [naver/pinpoint#4780]
**What version of pinpoint are you using?**
master/v1.7.2 etc.

**Describe your problem**
the application is deployded in the method of weblogic.When we start the application,agent log and weblogic startup log both threw the following error log.

please help me check the quetion, thank you very much.

**Logs**
agent log:
2018-10-15 22:30:02 [ERROR](c.n.p.p.BaseClassFileTransformer   ) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate threw an exception. cl:weblogic.utils.classloaders.ChangeAwareClassLoader@447cfb2 finder: weblogic.utils.classloaders.CodeGenClassFinder@38f42ac9 annotation: nbmis@nbmis ctxCl:weblogic.utils.classloaders.ChangeAwareClassLoader@447cfb2 finder: weblogic.utils.classloaders.CodeGenClassFinder@38f42ac9 annotation: nbmis@nbmis agentCl:com.navercorp.pinpoint.bootstrap.classloader.PinpointURLClassLoader@54cbf30e Cause:null
java.lang.NullPointerException
	at com.navercorp.pinpoint.plugin.spring.web.SpringWebMvcPlugin$1.doInTransform(SpringWebMvcPlugin.java:56)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at com.navercorp.pinpoint.profiler.MatchableClassFileTransformerDispatcher.transform(MatchableClassFileTransformerDispatcher.java:131)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:343)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:302)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:270)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:64)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:49)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:343)
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:302)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:270)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:64)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:49)
	at weblogic.xml.schema.binding.util.ClassUtil.loadNonArrayClass(ClassUtil.java:95)
	at weblogic.xml.schema.binding.util.ClassUtil.loadClass(ClassUtil.java:72)
	at weblogic.wsee.deploy.WSEEWebModule.getLinkMap(WSEEWebModule.java:129)
	at weblogic.wsee.deploy.WSEEModule.prepare(WSEEModule.java:85)
	at weblogic.wsee.deploy.AppDeploymentExtensionFactory.prepare(AppDeploymentExtensionFactory.java:79)
	at weblogic.wsee.deploy.AppDeploymentExtensionFactory.access$100(AppDeploymentExtensionFactory.java:15)
	at weblogic.wsee.deploy.AppDeploymentExtensionFactory$1.prepare(AppDeploymentExtensionFactory.java:219)
	at weblogic.application.internal.flow.AppDeploymentExtensionFlow.prepare(AppDeploymentExtensionFlow.java:23)
	at weblogic.application.internal.BaseDeployment$1.next(BaseDeployment.java:648)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52)
	at weblogic.application.internal.BaseDeployment.prepare(BaseDeployment.java:191)
	at weblogic.application.internal.SingleModuleDeployment.prepare(SingleModuleDeployment.java:44)
	at weblogic.application.internal.DeploymentStateChecker.prepare(DeploymentStateChecker.java:154)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.prepare(AppContainerInvoker.java:61)
	at weblogic.deploy.internal.targetserver.AppDeployment.prepare(AppDeployment.java:144)
	at weblogic.management.deploy.internal.DeploymentAdapter$1.doPrepare(DeploymentAdapter.java:39)
	at weblogic.management.deploy.internal.DeploymentAdapter.prepare(DeploymentAdapter.java:191)
	at weblogic.management.deploy.internal.AppTransition$1.transitionApp(AppTransition.java:21)
	at weblogic.management.deploy.internal.ConfiguredDeployments.transitionApps(ConfiguredDeployments.java:240)
	at weblogic.management.deploy.internal.ConfiguredDeployments.prepare(ConfiguredDeployments.java:165)
	at weblogic.management.deploy.internal.ConfiguredDeployments.deploy(ConfiguredDeployments.java:122)
	at weblogic.management.deploy.internal.DeploymentServerService.resume(DeploymentServerService.java:180)
	at weblogic.management.deploy.internal.DeploymentServerService.start(DeploymentServerService.java:96)
	at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:263)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)

**Comment by emeroad** [comment]
duplicate : #4781
