### ISSUE TITLE
When deploying pinpoint-web-1.8.0.war in EAP7 getting error org.springframework.beans.factory.UnsatisfiedDependencyException

### ISSUE THREAD

**Issue by asahu5** [naver/pinpoint#4817]
**Environment :-** 
pinpoint1.8
EAP7

I have started habse from pinpoint-master/quickstart/bin and tables also created .
Now when trying to deploy pinpoint-web-1.8.0.war  in EAP7 getting the below error.

**Steps I have taken to trigger the problem -**

1. Started HBASE and ran the init script from master/quickstarte/bin
2. did jboss(EAP7) configuration in standalone.conf where defiled the agent and other recommended classpath. 
3. now when deploying pinpoint-web-1.8.0.war getting below error 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseAgentInfoDao': Unsatisfied dependency expressed through field 'hbaseOperations2'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTemplate' defined in class path resource [applicationContext-hbase.xml]: Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'com.navercorp.pinpoint.common.hbase.HbaseConfigurationFactoryBean' to required type 'org.apache.hadoop.conf.Configuration' for property 'configuration'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'com.navercorp.pinpoint.common.hbase.HbaseConfigurationFactoryBean' to required type 'org.apache.hadoop.conf.Configuration' for property 'configuration': no matching editors or conversion strategy found
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hbaseTemplate' defined in class path resource [applicationContext-hbase.xml]: Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'com.navercorp.pinpoint.common.hbase.HbaseConfigurationFactoryBean' to required type 'org.apache.hadoop.conf.Configuration' for property 'configuration'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'com.navercorp.pinpoint.common.hbase.HbaseConfigurationFactoryBean' to required type 'org.apache.hadoop.conf.Configuration' for property 'configuration': no matching editors or conversion strategy found 
<img width="263" alt="hbase" src="https://user-images.githubusercontent.com/44440667/47645006-bc444180-db95-11e8-82aa-fdd2ad199524.PNG">
<img width="862" alt="standalone_conf" src="https://user-images.githubusercontent.com/44440667/47645014-c23a2280-db95-11e8-9625-de1823aab64a.PNG">
[server log](https://github.com/naver/pinpoint/files/2524891/server.log)

**Comment by emeroad** [comment]
We do not recommend installing pinpoint-agent on pinpoint-web

https://github.com/naver/pinpoint#supported-modules
In addition, pinpoint-agent does not support EAP7.

**Comment by asahu5** [comment]
Do you want to say that we should not set the path of pinpoint-agent in server if deploying pinpoint-web?

I tried deploying pinpoint-web and pinpoint-collector wars on EAP6.4.0 but getting the below error.
Can you please suggest the recommended version of EAP for pinpoint.
 
10:17:50,902 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."pinpoint-collector-1.8.0.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."pinpoint-collector-1.8.0.war".PARSE: JBAS018733: Failed to process phase PARSE of deployment "pinpoint-collector-1.8.0.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_181]
Caused by: java.lang.ExceptionInInitializerError
	at org.jboss.as.jaxrs.deployment.JaxrsAnnotationProcessor.deploy(JaxrsAnnotationProcessor.java:45)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [jboss-as-server-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
	... 5 more
Caused by: java.lang.IllegalArgumentException: A componentized DotName must have a componentized prefix, or null
	at org.jboss.jandex.DotName.<init>(DotName.java:121)
	at org.jboss.jandex.DotName.createComponentized(DotName.java:91)
	at org.jboss.as.jaxrs.JaxrsAnnotations.<init>(JaxrsAnnotations.java:59)
	at org.jboss.as.jaxrs.JaxrsAnnotations.<clinit>(JaxrsAnnotations.java:34)
	... 7 more
