### ISSUE TITLE
wildfly-14 startup failure with pinpoint agent

### ISSUE THREAD

**Issue by weijieliefu** [naver/pinpoint#4924]
I add:
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_HOME/modules/org/jboss/logmanager/main/jboss-logmanager-2.1.4.Final.jar"
JAVA_OPTS="$JAVA_OPTS  -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,org.jboss.byteman,com.navercorp.pinpoint.bootstrap,org.jboss.logmanager,com.navercorp.pinpoint.common,com.navercorp.pinpoint.exception"

but:
java.lang.NoClassDefFoundError: org/jboss/logmanager/Logger
	at org.jboss.as.server.Main.main(Main.java:89)
	at org.jboss.modules.Module.run(Module.java:352)
	at org.jboss.modules.Module.run(Module.java:320)
	at org.jboss.modules.Main.main(Main.java:593)
Caused by: java.lang.ClassNotFoundException: org.jboss.logmanager.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.JDKSpecific.getSystemClass(JDKSpecific.java:180)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:395)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 4 more

**Comment by jackstonemiller** [comment]
I study it, this problem cause: Wildfly start up , and trigger JMX initialization, and JMX itself have their own logging.

**Comment by jackstonemiller** [comment]
@RoySRose Do you hava any good solution?

**Comment by jackstonemiller** [comment]
I make it

**Comment by RoySRose** [comment]
Hello, @jackstonemiller 
I don't know much about wildfly. So I can't give you any solutions.
If you are willing to contribute a solution? Great!
