### ISSUE TITLE
calleeApplicationName must not be null

### ISSUE THREAD

**Issue by lawrencewu** [naver/pinpoint#4949]
**What version of pinpoint are you using?**
v1.7.2 

the collector log:

```
2018-12-04 16:36:35 [WARN ](c.n.p.c.h.SpanHandler              ) Span handle error. Caused:calleeApplicationName must not be null. Span:TSpan(agentId:172.29.xx.xx, applicationName:mbp-mapi, agentStartTime:1542378836019, transactionId:00 01 B3 A0 C5 E7 F1 2C F6 88 86 34, spanId:-9006460842191983249, startTime:1543912592531, elapsed:3024, rpc:/mapi/queryAuthStatus, serviceType:1030, endPoint:mapi.xxx.com.cn:80, remoteAddr:172.28.xx.xx, flag:0, err:1, spanEventList:[TSpanEvent(sequence:2, startElapsed:0, serviceType:5071, depth:3, apiId:6), TSpanEvent(sequence:7, startElapsed:0, serviceType:5071, depth:7, apiId:6), TSpanEvent(sequence:6, startElapsed:0, serviceType:5071, depth:6, apiId:-8), TSpanEvent(sequence:8, startElapsed:0, serviceType:5071, depth:6, apiId:84), TSpanEvent(sequence:9, startElapsed:0, serviceType:5071, apiId:74), TSpanEvent(sequence:10, startElapsed:0, serviceType:5071, apiId:84), TSpanEvent(sequence:12, startElapsed:0, endElapsed:2, serviceType:9110, endPoint:172.28.xx.xx:20880, annotations:[TAnnotation(key:90, value:<TAnnotationValue stringValue:[Ljava.lang.Object;@682f7d9e>), TAnnotation(key:91, value:<TAnnotationValue stringValue:RpcResult [result=Response{success=true, result=true}, exception...(70)>)], depth:7, nextSpanId:4700683536434750270, destinationId:172.28.149.106:20880, apiId:299), TSpanEvent(sequence:11, startElapsed:0, endElapsed:2, serviceType:5071, apiId:66), TSpanEvent(sequence:15, startElapsed:2, serviceType:5071, depth:8, apiId:9), TSpanEvent(sequence:16, startElapsed:2, endElapsed:3021, serviceType:9110, nextSpanId:2651926900460208743, apiId:299, exceptionInfo:TIntStringValue(intValue:-3, stringValue:Failed to invoke the method $invoke in the service com.alibaba.dubbo.rpc.service.GenericService. Tried 1 times of the providers [172.28.xx.xx:20880] (1/4) from the registry dubbo-zk.bestpay.mid:2181 on the consumer 172.28.161.76 using the dubbo version 2....(2141))), TSpanEvent(sequence:14, startElapsed:2, endElapsed:3021, serviceType:5071, depth:7, apiId:-7), TSpanEvent(sequence:13, startElapsed:2, endElapsed:3021, serviceType:5071, depth:6, apiId:-26), TSpanEvent(sequence:5, startElapsed:0, endElapsed:3023, serviceType:5071, depth:5, apiId:-51), TSpanEvent(sequence:4, startElapsed:0, endElapsed:3023, serviceType:5071, depth:4, apiId:50), TSpanEvent(sequence:3, startElapsed:0, endElapsed:3023, serviceType:5071, apiId:-304), TSpanEvent(sequence:1, startElapsed:0, endElapsed:3024, serviceType:5051, depth:2, apiId:-301), TSpanEvent(sequence:0, startElapsed:0, endElapsed:3024, serviceType:1031, depth:1, apiId:-1)], apiId:1, applicationServiceType:1030)
java.lang.NullPointerException: calleeApplicationName must not be null
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapStatisticsCallerDao.update(HbaseMapStatisticsCallerDao.java:88)
        at com.navercorp.pinpoint.collector.handler.StatisticsHandler.updateCaller(StatisticsHandler.java:59)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.insertSpanEventStat(SpanHandler.java:183)
        at com.navercorp.pinpoint.collector.handler.SpanHandler.handleSimple(SpanHandler.java:90)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:122)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:101)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:51)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:186)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-12-04 16:36:39 [WARN ](c.n.p.c.h.SpanChunkHandler         ) SpanChunk handle error Caused:calleeApplicationName must not be null
java.lang.NullPointerException: calleeApplicationName must not be null
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapStatisticsCallerDao.update(HbaseMapStatisticsCallerDao.java:88)
        at com.navercorp.pinpoint.collector.handler.StatisticsHandler.updateCaller(StatisticsHandler.java:59)
        at com.navercorp.pinpoint.collector.handler.SpanChunkHandler.handleSimple(SpanChunkHandler.java:89)
        at com.navercorp.pinpoint.collector.receiver.AbstractDispatchHandler.dispatchSendMessage(AbstractDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.DispatchHandlerWrapper.dispatchSendMessage(DispatchHandlerWrapper.java:49)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:122)
        at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:101)
        at com.navercorp.pinpoint.collector.receiver.udp.PooledPacketWrap.run(PooledPacketWrap.java:51)
        at com.navercorp.pinpoint.collector.receiver.udp.UDPReceiver$1.run(UDPReceiver.java:186)
        at com.navercorp.pinpoint.collector.monitor.MonitoredExecutorService$InstrumentedRunnable.run(MonitoredExecutorService.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

seems something wrong with the Dubbo plugin.
pls help to resolve this issue

**Comment by Xylus** [comment]
Hi @lawrencewu 
This may have been fixed in 1.8.0.
Could you try using pinpoint agent 1.8.0 and let us know if the problem persists?
Thanks.

**Comment by lawrencewu** [comment]
@Xylus OK,  I'll try to replace this plugin jar.  and another issue as the picture  below.
![image](https://user-images.githubusercontent.com/6634942/49433290-a0fbd000-f7ec-11e8-9754-5851d309f6aa.png)

**Comment by Xylus** [comment]
`Corrupted(invalid sequence)` *usually* occurs when packet is lost between the agent and the collector.
But for this particular case, it may be more related to the issue above.
Please give 1.8.0 agent a try and let us know what happens.
Thanks.
