### ISSUE TITLE
Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core" version 2.0.13.Final

### ISSUE THREAD

**Issue by weijieliefu** [naver/pinpoint#4954]
Through the following error reports, I realized that： the wildfly using the ModuleClassLoader to load the undertow .The PlainClassLoaderHandler want to load the  ConnectorsExecuteRootHandlerInterceptor by ModuleClassLoader,but failed.I even change the code to use the BootStrapClassLoader to undertow-plugin's Classes , but the more undertow's classes was NoClassDefFoundError. 
How to solve this problem about class loading？

error reports：
com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core" version 2.0.13.Final from local module loader @53c6f96d (finder: local module finder @435cc7f9 (roots: /root/myapps/wildfly-14.0.1.Final/modules,/root/myapps/wildfly-14.0.1.Final/modules/system/layers/base))
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:71)
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:156)
	at com.navercorp.pinpoint.profiler.instrument.ScopeFactory.newScopeInfo(ScopeFactory.java:36)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:227)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:127)
	at com.navercorp.pinpoint.plugin.undertow.UndertowPlugin$1.doInTransform(UndertowPlugin.java:68)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:57)
	at com.navercorp.pinpoint.profiler.MatchableClassFileTransformerDispatcher.transform(MatchableClassFileTransformerDispatcher.java:131)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at io.undertow.server.protocol.http.HttpRequestParser$$generated.handleHeader(Unknown Source)
	at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:287)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: com.navercorp.pinpoint.exception.PinpointException: Failed to load plugin class com.navercorp.pinpoint.plugin.undertow.interceptor.ConnectorsExecuteRootHandlerInterceptor with classLoader ModuleClassLoader for Module "io.undertow.core" version 2.0.13.Final from local module loader @53c6f96d (finder: local module finder @435cc7f9 (roots: /root/myapps/wildfly-14.0.1.Final/modules,/root/myapps/wildfly-14.0.1.Final/modules/system/layers/base))
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:86)
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:66)
	... 30 more
Caused by: java.lang.RuntimeException: com.navercorp.pinpoint.plugin.undertow.common.servlet.util.HttpServletRequestAdaptor define fail Caused by:null
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.handleDefineClassFail(ReflectionDefineClass.java:59)
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.defineClass(ReflectionDefineClass.java:53)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.defineClass(PlainClassLoaderHandler.java:300)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.define0(PlainClassLoaderHandler.java:287)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.defineJarClass(PlainClassLoaderHandler.java:225)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.getClassLoaderAttachment(PlainClassLoaderHandler.java:171)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass0(PlainClassLoaderHandler.java:127)
	at com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:83)
	... 31 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.navercorp.pinpoint.profiler.instrument.classloading.ReflectionDefineClass.defineClass(ReflectionDefineClass.java:49)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: com/navercorp/pinpoint/bootstrap/plugin/request/RequestAdaptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	... 42 more
Caused by: java.lang.ClassNotFoundException: com.navercorp.pinpoint.bootstrap.plugin.request.RequestAdaptor from [Module "io.undertow.core" version 2.0.13.Final from local module loader @53c6f96d (finder: local module finder @435cc7f9 (roots: /root/myapps/wildfly-14.0.1.Final/modules,/root/myapps/wildfly-14.0.1.Final/modules/system/layers/base))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 45 more

**Comment by emeroad** [comment]
Pinpoint does not support wildfly-14

**Comment by weijieliefu** [comment]
ok,i see.thank you !

**Comment by emeroad** [comment]
Resolved at #4979
