### ISSUE TITLE
Error while connecting pinpoint-agent, pinpoint-collector and pinpoint-web in distributed mode using Hbase/hdfs

### ISSUE THREAD

**Issue by soniayush** [naver/pinpoint#4996]
Hi Pinpoint Team,

I am trying to install pinpoint in distributed mode.
I have three machines say M1,M2 & M3.

M1 - hbase with hdfs, my application & pinpoint agent are installed.
M2 - pinpoint collector in deployed.
M3 - pinpoint web in deployed.

Versions I am using:
--------------------
hbase - 1.2.6
pinpoint - collector - 1.8.0
pinpoint - web - 1.8.0
pinpoint - agent - 1.8.0

Problem:
--------
When i start my application with pinpoint agent, i can see in it's logs following error:

[INFO ](c.n.p.p.s.TcpDataSender@Default    ) request fail. request:TApiMetaData(agentId:101-Agent, agentStartTime:1544605730813, apiId:-1, apiInfo:Asynchronous Invocation, line:-1, type:200) Caused:timeout

And, on pinpoint collector machine i can see below error:

org.apache.thrift.TException: invalid header Caused by:invalid signature :100

**finally, there is no data going to hbase from collector and hence pinpoint-web has nothing to display.**

Things already done:
--------------------
I have already created tables in hbase.
I have also tested the script given in pinpoint-agent 'networktest.sh' for connection with collector machine. it gives me success results.

Please help me here in getting this done. additional details can be provided as and when needed.

Thanks and waiting for your response.

**Comment by Xylus** [comment]
Hi @soniayush,
I just tested with 1.8.0 collector and agent and it seems to be working fine.
Could you try moving your collector to M1 (so that your agent and collector are in the same machine) and see if it works?
If it does work, then it should be a network issue.
Thanks.

**Comment by soniayush** [comment]
Hi @Xylus, thanks for replying.
Yes, when i deploy all of them on same machine then it works fine. But in distributed mode it is not.
Is there any specific configuration required for hbase-collector connection for distributed mode ? 
Thanks,

**Comment by Xylus** [comment]
Hmm, there shouldn't be any special configuration required to run them in separate machines apart from changing `profiler.collector.ip` in *pinpoint.config*.

**Comment by soniayush** [comment]
Hi, I am getting below exception while trying to connect collector to remote hbase machine.
any idea ?

2019-01-03 23:26:55 [WARN ](c.n.p.c.r.u.BaseUDPHandlerFactory  ) packet serialize error. SendSocketAddress:/10.148.218.163:43620 Cause:invalid header Caused by:invalid signature :100
org.apache.thrift.TException: invalid header Caused by:invalid signature :100
	at com.navercorp.pinpoint.thrift.io.HeaderTBaseDeserializer.readHeader(HeaderTBaseDeserializer.java:105)
	at com.navercorp.pinpoint.thrift.io.HeaderTBaseDeserializer.readInternal(HeaderTBaseDeserializer.java:75)
	at com.navercorp.pinpoint.thrift.io.HeaderTBaseDeserializer.deserialize(HeaderTBaseDeserializer.java:66)
	at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:89)
	at com.navercorp.pinpoint.collector.receiver.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:72)
	at com.navercorp.pinpoint.collector.receiver.udp.Task.run(Task.java:44)
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.navercorp.pinpoint.io.header.InvalidHeaderException: invalid signature :100
	at com.navercorp.pinpoint.io.header.ByteArrayHeaderReader.readHeader(ByteArrayHeaderReader.java:56)
	at com.navercorp.pinpoint.thrift.io.HeaderTBaseDeserializer.readHeader(HeaderTBaseDeserializer.java:103)
	... 9 more

Thanks,
