### ISSUE TITLE
1.8.1-RC1

### ISSUE THREAD

**Issue by joybinr** [naver/pinpoint#5012]
**What version of pinpoint are you using?**
1.8.1-RC1

2018-12-15 13:14:00 [WARN ](c.n.p.p.i.c.URLClassLoaderHandler  ) Failed to load plugin class com.navercorp.pinpoint.plugin.redis.lettuce.EndPointAccessor with classLoader com.zving.preloader.PreClassLoader@6a9287b1
java.lang.ClassNotFoundException: com.navercorp.pinpoint.plugin.redis.lettuce.EndPointAccessor
	at com.zving.preloader.PreClassLoader.loadData(PreClassLoader.java:105)
	at com.zving.preloader.PreClassLoader.findClass(PreClassLoader.java:116)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.zving.preloader.PreClassLoader.loadClass(PreClassLoader.java:95)
	at com.navercorp.pinpoint.profiler.instrument.classloading.URLClassLoaderHandler.injectClass(URLClassLoaderHandler.java:66)
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:57)
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:164)
	at com.navercorp.pinpoint.profiler.instrument.ASMClass.addField(ASMClass.java:236)
	at com.navercorp.pinpoint.plugin.redis.lettuce.LettucePlugin$3.doInTransform(LettucePlugin.java:119)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.zving.preloader.PreClassLoader.findClass(PreClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.zving.preloader.PreClassLoader.loadClass(PreClassLoader.java:95)
	at com.zving.nosql.redis.RedisPool.createClusterConnection(RedisPool.java:86)
	at com.zving.nosql.redis.RedisPool.<init>(RedisPool.java:41)
	at com.zving.nosql.redis.RedisPoolManager.getPool(RedisPoolManager.java:52)
	at com.zving.nosql.redis.util.RedisUtil.exists(RedisUtil.java:270)
	at com.zving.sso.LoginUI.doLogin(LoginUI.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zving.framework.core.method.FacadeMemberMethodLocator.execute(FacadeMemberMethodLocator.java:45)
	at com.zving.framework.core.handler.ActionHandler.invoke(ActionHandler.java:139)
	at com.zving.framework.core.handler.ActionHandler.handle(ActionHandler.java:98)
	at com.zving.framework.core.DispatchServlet.handleURL(DispatchServlet.java:371)
	at com.zving.framework.core.DispatchServlet.service(DispatchServlet.java:254)
	at com.zving.preloader.facade.ServletFacade.service(ServletFacade.java:40)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.zving.zas.client.ZASFilter.doFilter(ZASFilter.java:116)
	at com.zving.preloader.facade.FilterFacade.doFilter(FilterFacade.java:41)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:905)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:592)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2036)
	at java.lang.Thread.run(Thread.java:748)

2018-12-15 13:14:03 [WARN ](c.n.p.p.i.c.URLClassLoaderHandler  ) Failed to load plugin class com.navercorp.pinpoint.plugin.httpclient4.interceptor.HttpClientExecuteMethodWithHttpRequestInterceptor with classLoader com.zving.preloader.PreClassLoader@6a9287b1
java.lang.ClassNotFoundException: com.navercorp.pinpoint.plugin.httpclient4.interceptor.HttpClientExecuteMethodWithHttpRequestInterceptor
	at com.zving.preloader.PreClassLoader.loadData(PreClassLoader.java:105)
	at com.zving.preloader.PreClassLoader.findClass(PreClassLoader.java:116)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.zving.preloader.PreClassLoader.loadClass(PreClassLoader.java:95)
	at com.navercorp.pinpoint.profiler.instrument.classloading.URLClassLoaderHandler.injectClass(URLClassLoaderHandler.java:66)
	at com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:57)
	at com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:164)
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:72)
	at com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.getInterceptor(AnnotatedInterceptorFactory.java:106)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.createInterceptor(ASMMethod.java:220)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:209)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addScopedInterceptor(ASMMethod.java:155)
	at com.navercorp.pinpoint.plugin.httpclient4.HttpClient4Plugin.injectHttpClientExecuteMethodWithHttpRequestInterceptor(HttpClient4Plugin.java:153)
	at com.navercorp.pinpoint.plugin.httpclient4.HttpClient4Plugin.access$000(HttpClient4Plugin.java:43)
	at com.navercorp.pinpoint.plugin.httpclient4.HttpClient4Plugin$3.doInTransform(HttpClient4Plugin.java:134)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.zving.preloader.PreClassLoader.findClass(PreClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.zving.preloader.PreClassLoader.loadClass(PreClassLoader.java:95)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.zving.preloader.PreClassLoader.findClass(PreClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.zving.preloader.PreClassLoader.loadClass(PreClassLoader.java:95)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.zving.preloader.PreClassLoader.findClass(PreClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.zving.preloader.PreClassLoader.loadClass(PreClassLoader.java:95)
	at com.zving.publicpackage.bl.ServerBL.getHttpClient(ServerBL.java:474)
	at com.zving.publicpackage.bl.ServerBL.get(ServerBL.java:384)
	at com.zving.publicpackage.bl.ServerBL.getJSONObject(ServerBL.java:321)
	at com.zving.publicpackage.bl.ServerBL.sendRequest(ServerBL.java:272)
	at com.zving.publicpackage.bl.ServerBL.sendRequest(ServerBL.java:222)
	at com.zving.publicpackage.bl.ServerBL.sendRequest(ServerBL.java:231)
	at com.zving.centre.bl.NewTrainCetreBL.getCoursePaperIds(NewTrainCetreBL.java:569)
	at com.zving.centre.bl.NewTrainCetreBL.setChapt(NewTrainCetreBL.java:471)
	at com.zving.centre.bl.NewTrainCetreBL.getQuestionSQL(NewTrainCetreBL.java:418)
	at com.zving.centre.bl.NewTrainCetreBL.getQuestionSQL(NewTrainCetreBL.java:394)
	at com.zving.centre.ui.NewTrainCetreUI.load(NewTrainCetreUI.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zving.framework.core.method.FacadeMemberMethodLocator.execute(FacadeMemberMethodLocator.java:45)
	at com.zving.framework.core.handler.AjaxHandler.execute(AjaxHandler.java:114)
	at com.zving.framework.core.handler.AbstractHtmlHandler.handle(AbstractHtmlHandler.java:27)
	at com.zving.framework.core.DispatchServlet.handleURL(DispatchServlet.java:371)
	at com.zving.framework.core.DispatchServlet.service(DispatchServlet.java:254)
	at com.zving.preloader.facade.ServletFacade.service(ServletFacade.java:40)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:905)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:592)
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2036)
	at java.lang.Thread.run(Thread.java:748)

**Comment by emeroad** [comment]
Take a look at `com.zving.preloader.PreClassLoader` class

**Comment by joybinr** [comment]
Sent to emeroad@gmail.com and look forward to your reply


> Take a look at `com.zving.preloader.PreClassLoader` class
