### ISSUE TITLE
pinpoint-1.8.1-RC1 web start failed 

### ISSUE THREAD

**Issue by gaoyaqiu** [naver/pinpoint#5039]
Hi,
I tried to start the web system locally, but the startup failed.
Please help me solve this problem.I would appreciate it if you can help me!

**Description**

There is detail error message:

```
2018-12-24 14:52:26 [INFO ](c.s.u.ThreadPoolExecutorFactoryBean:166) Initializing ExecutorService 'hbaseThreadPool'
2018-12-24 14:52:26 [WARN ](o.a.h.u.NativeCodeLoader           :62 ) Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2018-12-24 14:52:30 [INFO ](o.a.h.h.z.RecoverableZooKeeper     :120) Process identifier=hconnection-0x22b35036 connecting to ZooKeeper ensemble=localhost:2181
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:host.name=localhost
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.version=1.8.0_171
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.vendor=Oracle Corporation
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.class.path=/Users/gaoyaqiu/Documents/data/tools/tomcat/apache-tomcat-8.0.11/bin/bootstrap.jar:/Users/gaoyaqiu/Documents/data/tools/tomcat/apache-tomcat-8.0.11/bin/tomcat-juli.jar:/Users/gaoyaqiu/Library/Caches/IntelliJIdea2018.2/captureAgent/debugger-agent.jar:/Users/gaoyaqiu/Library/Caches/IntelliJIdea2018.2/groovyHotSwap/gragent.jar
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.library.path=/Users/gaoyaqiu/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.io.tmpdir=/Users/gaoyaqiu/Documents/data/tools/tomcat/apache-tomcat-8.0.11/temp
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:java.compiler=<NA>
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:os.name=Mac OS X
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:os.arch=x86_64
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:os.version=10.13.6
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:user.name=gaoyaqiu
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:user.home=/Users/gaoyaqiu
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :100) Client environment:user.dir=/Users/gaoyaqiu/Documents/data/tools/tomcat/apache-tomcat-8.0.11/bin
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :438) Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x22b350360x0, quorum=localhost:2181, baseZNode=/hbase
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         :975) Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         :852) Socket connection established to localhost/0:0:0:0:0:0:0:1:2181, initiating session
2018-12-24 14:52:30 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         :1235) Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 0x167ddd8ff6c0007, negotiated timeout = 40000
2018-12-24 14:52:31 [INFO ](o.a.h.h.c.ZooKeeperRegistry        :107) ClusterId read in ZooKeeper is null
2018-12-24 14:52:33 [WARN ](o.s.w.c.s.XmlWebApplicationContext :551) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultApplicationFactory': Unsatisfied dependency expressed through field 'registry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceTypeRegistryService' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'typeLoaderService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'typeLoaderService' defined in class path resource [applicationContext-web.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
2018-12-24 14:52:33 [INFO ](c.n.p.c.h.HbaseTemplate2           :126) HBaseTemplate2.destroy()
2018-12-24 14:52:33 [WARN ](c.n.p.c.h.HbaseTemplate2           :149) count -1
2018-12-24 14:52:33 [INFO ](c.n.p.c.h.ConnectionFactoryBean    :79 ) Hbase Connection destroy()
2018-12-24 14:52:33 [INFO ](onManager$HConnectionImplementation:1710) Closing zookeeper sessionid=0x167ddd8ff6c0007
2018-12-24 14:52:33 [INFO ](o.a.h.h.s.o.a.z.ZooKeeper          :684) Session: 0x167ddd8ff6c0007 closed
2018-12-24 14:52:33 [INFO ](o.a.h.h.s.o.a.z.ClientCnxn         :512) EventThread shut down
2018-12-24 14:52:33 [INFO ](c.s.u.ThreadPoolExecutorFactoryBean:203) Shutting down ExecutorService 'hbaseThreadPool'
2018-12-24 14:52:33 [ERROR](o.s.w.c.ContextLoader              :350) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'hbaseApplicationIndexDao': Unsatisfied dependency expressed through field 'applicationNameMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultApplicationFactory': Unsatisfied dependency expressed through field 'registry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceTypeRegistryService' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'typeLoaderService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'typeLoaderService' defined in class path resource [applicationContext-web.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:364)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4751)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5175)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1588)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:463)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:413)
24-Dec-2018 14:52:33.143 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Error listenerStart
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:835)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationNameMapper': Unsatisfied dependency expressed through field 'applicationFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultApplicationFactory': Unsatisfied dependency expressed through field 'registry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceTypeRegistryService' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'typeLoaderService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'typeLoaderService' defined in class path resource [applicationContext-web.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:364)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
	... 60 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultApplicationFactory': Unsatisfied dependency expressed through field 'registry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceTypeRegistryService' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'typeLoaderService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'typeLoaderService' defined in class path resource [applicationContext-web.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:586)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:364)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1269)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
	... 73 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceTypeRegistryService' defined in class path resource [applicationContext-web.xml]: Cannot resolve reference to bean 'typeLoaderService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'typeLoaderService' defined in class path resource [applicationContext-web.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:145)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1136)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1064)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:583)
	... 86 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'typeLoaderService' defined in class path resource [applicationContext-web.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:279)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 101 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 110 more
Caused by: java.lang.IllegalArgumentException: unknown plugin jar:file:/Users/gaoyaqiu/git/pinpoint/web/target/deploy/WEB-INF/lib/pinpoint-jboss-plugin-1.8.1-RC1.jar!/com/navercorp/pinpoint/plugin/jboss/JbossTypeProvider.class
	at com.navercorp.pinpoint.common.plugin.ServerPluginLoader.newPlugin(ServerPluginLoader.java:72)
	at com.navercorp.pinpoint.common.plugin.ServerPluginLoader.load(ServerPluginLoader.java:50)
	at com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService.<init>(ServerTraceMetadataLoaderService.java:52)
	at com.navercorp.pinpoint.common.server.util.ServerTraceMetadataLoaderService.<init>(ServerTraceMetadataLoaderService.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 112 more
24-Dec-2018 14:52:33.174 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[2018-12-24 02:52:33,251] Artifact pinpoint-web:war exploded: Error during artifact deployment. See server log for details.
```
**Environment**

* Pinpoint version:1.8.1-RC1
* Hbase tables:
```
Version 1.2.6, rUnknown, Mon May 29 02:25:32 CDT 2017

hbase(main):001:0> list
TABLE                                                                                                                                             
AgentEvent                                                                                                                                        
AgentInfo                                                                                                                                         
AgentLifeCycle                                                                                                                                    
AgentStatV2                                                                                                                                       
ApiMetaData                                                                                                                                       
ApplicationIndex                                                                                                                                  
ApplicationMapStatisticsCallee_Ver2                                                                                                               
ApplicationMapStatisticsCaller_Ver2                                                                                                               
ApplicationMapStatisticsSelf_Ver2                                                                                                                 
ApplicationStatAggre                                                                                                                              
ApplicationTraceIndex                                                                                                                             
HostApplicationMap_Ver2                                                                                                                           
SqlMetaData_Ver2                                                                                                                                  
StringMetaData                                                                                                                                    
TraceV2                                                                                                                                           
15 row(s) in 0.6600 seconds

=> ["AgentEvent", "AgentInfo", "AgentLifeCycle", "AgentStatV2", "ApiMetaData", "ApplicationIndex", "ApplicationMapStatisticsCallee_Ver2", "ApplicationMapStatisticsCaller_Ver2", "ApplicationMapStatisticsSelf_Ver2", "ApplicationStatAggre", "ApplicationTraceIndex", "HostApplicationMap_Ver2", "SqlMetaData_Ver2", "StringMetaData", "TraceV2"]
hbase(main):002:0> 
```
Hbase properties
```
hbase.client.host=localhost
hbase.client.port=2181

# hbase default:/hbase
hbase.zookeeper.znode.parent=/hbase

# hbase namespace to use default:default
hbase.namespace=default

# hbase timeout option==================================================================================
# hbase default:true
hbase.ipc.client.tcpnodelay=true
# hbase default:60000
hbase.rpc.timeout=10000
# hbase default:Integer.MAX_VALUE
hbase.client.operation.timeout=10000

# hbase socket read timeout. default: 200000
hbase.ipc.client.socket.timeout.read=20000
# socket write timeout. hbase default: 600000
hbase.ipc.client.socket.timeout.write=30000

#==================================================================================
# hbase client thread pool option
hbase.client.thread.max=64
hbase.client.threadPool.queueSize=5120
# prestartAllCoreThreads
hbase.client.threadPool.prestart=false

#==================================================================================
# hbase parallel scan options
hbase.client.parallel.scan.enable=true
hbase.client.parallel.scan.maxthreads=64
hbase.client.parallel.scan.maxthreadsperscan=16
```
* zookeeper data
![image](https://user-images.githubusercontent.com/8586794/50393399-fa727180-0790-11e9-84c4-89a977e2394b.png)

**Comment by emeroad** [comment]
hi @gaoyaqiu 
![image](https://user-images.githubusercontent.com/7564547/50393723-8093b580-079b-11e9-89f2-d8d394d23a3c.png)

![image](https://user-images.githubusercontent.com/7564547/50393731-8f7a6800-079b-11e9-8964-15c1d242e2a0.png)


Normally pluginURL should get the name of the jar file.

What WAS are you using?

**Comment by gaoyaqiu** [comment]
@emeroad 
I am testing the local environment email alert, and now I am getting an error when I start pinpoint-web.
I debugged and found that the path to the plugin jar package is different from what you sent. Is it related to the MAC system? I am using a MAC computer.

![image](https://user-images.githubusercontent.com/8586794/50395345-5263a500-079e-11e9-95b0-2e0d61b84b80.png)
![image](https://user-images.githubusercontent.com/8586794/50395357-60192a80-079e-11e9-9245-6ce4b8949429.png)

**Comment by gaoyaqiu** [comment]
I am using 1.8.0_171, which version is available?

**Comment by minwoo-jung** [comment]
Hi @gaoyaqiu 

I tested on MacOS.  Pinpoint-web  works so well.
version infomation
- tomcat : 8.5.8
- jvm : 9.0.4 and 1.8.0_101

**Comment by gaoyaqiu** [comment]
@minwoo-jung 
Thanks.I have time to try it.

**Comment by gaoyaqiu** [comment]
Okay thank you.
