### ISSUE TITLE
ArrayIndexOutOfBoundsException in BytesUtils.intToSVar32

### ISSUE THREAD

**Issue by frwh47** [naver/pinpoint#5040]
Hi,

I am running pinpoint system. It looks very good. 
However, I found some error in collector log, as follow

2018-12-24 16:14:21 [WARN ](c.n.p.c.h.t.ThriftSpanHandler      ) Span handle error. Caused:5. Span:TSpan(agentId:22.96, applicationName:css, agentStartTime:1545296898138, transactionId:00 01 DA D0 FD D6 FC 2C FB 82 7D, spanId:-520285607336789963, parentSpanId:-1, startTime:1545639262803, elapsed:6, rpc:/service/css/userAccount, serviceType:1010, endPoint:xxxxxx:80, remoteAddr:10.103.10.103, annotations:[TAnnotation(key:46, value:<TAnnotationValue intValue:200>)], flag:0, err:0, spanEventList:[TSpanEvent(sequence:1, startElapsed:2, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:494>)], depth:2, apiId:352), TSpanEvent(sequence:4, startElapsed:2, serviceType:6062, depth:4, apiId:79), TSpanEvent(sequence:5, startElapsed:4, serviceType:6062, apiId:-90), TSpanEvent(sequence:3, startElapsed:2, endElapsed:2, serviceType:5510, annotations:[TAnnotation(key:-30, value:<TAnnotationValue intValue:38>)], depth:3, apiId:81), TSpanEvent(sequence:2, startElapsed:2, endElapsed:2, serviceType:5071, apiId:28), TSpanEvent(sequence:8, startElapsed:4, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:209>)], depth:4, apiId:352), TSpanEvent(sequence:10, startElapsed:4, serviceType:6062, depth:5, apiId:79), TSpanEvent(sequence:11, startElapsed:6, serviceType:6062, apiId:-90), TSpanEvent(sequence:9, startElapsed:4, endElapsed:2, serviceType:5510, annotations:[TAnnotation(key:-30, value:<TAnnotationValue intValue:-42>)], apiId:-84), TSpanEvent(sequence:7, startElapsed:4, endElapsed:2, serviceType:5071, depth:3, apiId:-15), TSpanEvent(sequence:6, startElapsed:4, endElapsed:2, serviceType:5071, depth:2, apiId:15), TSpanEvent(sequence:12, startElapsed:6, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:317>)], depth:2, apiId:-356), TSpanEvent(sequence:13, startElapsed:6, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:317>)], apiId:-356), TSpanEvent(sequence:14, startElapsed:6, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:317>)], apiId:346), TSpanEvent(sequence:15, startElapsed:6, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:1317404482>)], apiId:354), TSpanEvent(sequence:16, startElapsed:6, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:392>)], apiId:358), TSpanEvent(sequence:17, startElapsed:6, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:392>)], apiId:-356), TSpanEvent(sequence:0, startElapsed:0, endElapsed:6, serviceType:1011, annotations:[TAnnotation(key:41, value:<TAnnotationValue stringValue:parkId=1003155&mothedName=GetParkUserAccount&tArgs={"ClientIdentity":{"ComputerInfo":"6FCD9FB3335A2CE2431104008E322...(494)>)], depth:1, apiId:-2)], parentApplicationType:0, apiId:2, applicationServiceType:1010, loggingTransactionInfo:0)
java.lang.ArrayIndexOutOfBoundsException: 5
	at com.navercorp.pinpoint.common.util.BytesUtils.writeVar64(BytesUtils.java:405)
	at com.navercorp.pinpoint.common.util.BytesUtils.intToVar32(BytesUtils.java:369)
	at com.navercorp.pinpoint.common.util.BytesUtils.intToSVar32(BytesUtils.java:363)
	at com.navercorp.pinpoint.io.util.AnnotationTranscoder.encode(AnnotationTranscoder.java:166)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanEncoderV0.writeAnnotationList(SpanEncoderV0.java:362)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanEncoderV0.writeNextSpanEvent(SpanEncoderV0.java:330)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanEncoderV0.writeSpanEventList(SpanEncoderV0.java:112)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanEncoderV0.encodeSpanColumnValue(SpanEncoderV0.java:195)
	at com.navercorp.pinpoint.common.server.bo.serializer.trace.v2.SpanSerializerV2.serialize(SpanSerializerV2.java:35)
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseTraceDaoV2.insert(HbaseTraceDaoV2.java:64)
	at com.navercorp.pinpoint.collector.service.TraceService.insertSpan(TraceService.java:70)
	at com.navercorp.pinpoint.collector.handler.thrift.ThriftSpanHandler.handleSimple(ThriftSpanHandler.java:71)
	at com.navercorp.pinpoint.collector.handler.thrift.ThriftSpanHandler.handleSimple(ThriftSpanHandler.java:53)
	at com.navercorp.pinpoint.collector.receiver.thrift.SpanDispatchHandler.dispatchSendMessage(SpanDispatchHandler.java:58)
	at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchSendMessage(DelegateDispatchHandler.java:56)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:97)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:72)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.Task.run(Task.java:44)
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	
	

I don't understand what's wrong happened, please help me to fix these errors
thanks a lot

**Comment by emeroad** [comment]
hi @frwh47 
There is a bug in BytesUtils.intToSVar32()

java.lang.ArrayIndexOutOfBoundsException: 5
~~at com.navercorp.pinpoint.common.util.BytesUtils.writeVar64(BytesUtils.java:405)~~ <- BytesUtils.writeVar32()
at com.navercorp.pinpoint.common.util.BytesUtils.intToVar32(BytesUtils.java:369)
at com.navercorp.pinpoint.common.util.BytesUtils.intToSVar32(BytesUtils.java:363)
...

I will fix this bug in 1.8.1

**Comment by frwh47** [comment]
good job
