### ISSUE TITLE
calleeApplicationName must not be null

### ISSUE THREAD

**Issue by frwh47** [naver/pinpoint#5045]
I have set up pinpoint 1.8.1-SNAPSHOT
There are some errors in collector log as follow, 
please help to fix them

2018-12-25 14:41:21 [WARN ](c.n.p.c.h.t.ThriftSpanHandler      ) Span handle error. Caused:calleeApplicationName must not be null. Span:TSpan(agentId:22.92.01, applicationName:parking, agentStartTime:1545718822188, transactionId:00 0A 32 32 2E 39 36 BD C7 8B 82 FE 2C B4 AE 17, spanId:-290930311717535740, parentSpanId:5667517440345093409, startTime:1545720081907, elapsed:27, rpc:kafka://topic=parkingRecordOut?partition=5&offset=91152, serviceType:8660, endPoint:[10.103.22.89:9093, 10.103.22.92:9093, 10.103.22.93:9093], remoteAddr:[10.103.22.89:9093, 10.103.22.92:9093, 10.103.22.93:9093], annotations:[TAnnotation(key:140, value:<TAnnotationValue stringValue:parkingRecordOut>), TAnnotation(key:141, value:<TAnnotationValue intValue:5>), TAnnotation(key:142, value:<TAnnotationValue longValue:91152>)], flag:0, err:1, spanEventList:[TSpanEvent(sequence:1, startElapsed:0, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:971>)], depth:2, apiId:-290), TSpanEvent(sequence:2, startElapsed:0, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:915>)], apiId:307), TSpanEvent(sequence:3, startElapsed:1, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:1021>)], apiId:302), TSpanEvent(sequence:4, startElapsed:1, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:915>)], apiId:-290), TSpanEvent(sequence:5, startElapsed:16, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:11>)], apiId:302), TSpanEvent(sequence:6, startElapsed:16, serviceType:5013, annotations:[TAnnotation(key:9003, value:<TAnnotationValue intValue:383>)], apiId:302), TSpanEvent(sequence:7, startElapsed:16, endElapsed:1, serviceType:9110, nextSpanId:3153201042135244428, apiId:592, exceptionInfo:TIntStringValue(intValue:27, stringValue:Failed to invoke remote method: queryInvoiceSwitch, provider: dubbo://10.103.23.95:20992/com.xxx.invoice.api.service.InvoiceQueryService?anyhost=true&application=wukong-parking-qa&check=false&cluster=failfast&default.reference.filter=traceConsumerFilter&de...(1841))), TSpanEvent(sequence:0, startElapsed:0, endElapsed:27, serviceType:8661, depth:1, apiId:601)], parentApplicationName:css, parentApplicationType:1010, acceptorHost:topic:parkingRecordOut, apiId:-602, applicationServiceType:1010, loggingTransactionInfo:0)
java.lang.NullPointerException: calleeApplicationName must not be null
	at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapStatisticsCallerDao.update(HbaseMapStatisticsCallerDao.java:91)
	at com.navercorp.pinpoint.collector.service.StatisticsService.updateCaller(StatisticsService.java:59)
	at com.navercorp.pinpoint.collector.service.TraceService.insertSpanEventList(TraceService.java:194)
	at com.navercorp.pinpoint.collector.service.TraceService.insertSpanEventStat(TraceService.java:176)
	at com.navercorp.pinpoint.collector.service.TraceService.insertSpan(TraceService.java:74)
	at com.navercorp.pinpoint.collector.handler.thrift.ThriftSpanHandler.handleSimple(ThriftSpanHandler.java:71)
	at com.navercorp.pinpoint.collector.handler.thrift.ThriftSpanHandler.handleSimple(ThriftSpanHandler.java:53)
	at com.navercorp.pinpoint.collector.receiver.thrift.SpanDispatchHandler.dispatchSendMessage(SpanDispatchHandler.java:58)
	at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchSendMessage(DelegateDispatchHandler.java:56)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:97)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.BaseUDPHandlerFactory$DispatchPacket.receive(BaseUDPHandlerFactory.java:72)
	at com.navercorp.pinpoint.collector.receiver.thrift.udp.Task.run(Task.java:44)
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by koo-taejin** [comment]
@majinkai 
Is there any problem with following modification?
```
### ASIS
  if (throwable == null) {
         String endPoint = RpcContext.getContext().getRemoteAddressString();
         // RPC client have to record end point (server address)
         recorder.recordEndPoint(endPoint);

         // Optionally, record the destination id (logical name of server. e.g. DB name)
         recorder.recordDestinationId(endPoint);
         recorder.recordAttribute(DubboConstants.DUBBO_ARGS_ANNOTATION_KEY, invocation.getArguments());
         recorder.recordAttribute(DubboConstants.DUBBO_RESULT_ANNOTATION_KEY, result);
    } else {
        recorder.recordException(throwable);
    }
			
### TOBE
    String endPoint = RpcContext.getContext().getRemoteAddressString();
    // RPC client have to record end point (server address)
    recorder.recordEndPoint(endPoint);

    // Optionally, record the destination id (logical name of server. e.g. DB name)
    recorder.recordDestinationId(endPoint);
    recorder.recordAttribute(DubboConstants.DUBBO_ARGS_ANNOTATION_KEY, invocation.getArguments());
    recorder.recordAttribute(DubboConstants.DUBBO_RESULT_ANNOTATION_KEY, result);

    if (throwable != null) {
        recorder.recordException(throwable);	
	}
			
```
https://github.com/naver/pinpoint/blame/master/plugins/dubbo/src/main/java/com/navercorp/pinpoint/plugin/dubbo/interceptor/DubboConsumerInterceptor.java#L99

If  use RECORD_STATICS for the service type, must include destinationId.

Please give me your opinion. :)
