### ISSUE TITLE
Whether pinpoint supports mongodb with authentication

### ISSUE THREAD

**Issue by wiliiwin** [naver/pinpoint#5067]
Whether pinpoint supports mongodb with authentication,I now use the mongodb with verification to report the following error

`2019-01-02 09:06:48 [WARN ](c.n.p.p.i.f.GuardExceptionHandler  ) Exception occurred from interceptor
java.lang.NullPointerException
        at com.navercorp.pinpoint.plugin.mongo.interceptor.MongoDriverGetDatabaseInterceptor.after(MongoDriverGetDatabaseInterceptor.java:67)
        at com.navercorp.pinpoint.bootstrap.interceptor.scope.ExceptionHandleScopedInterceptor.after(ExceptionHandleScopedInterceptor.java:79)
        at com.mongodb.MongoClient.getDatabase(MongoClient.java:532)
        at io.xhance.data.common.MongoHelper.getCollection(MongoHelper.java:71)
        at io.xhance.data.common.MongoHelper.insertBatch(MongoHelper.java:140)
        at io.xhance.data.click_handling.NginxLogHandler.handler(NginxLogHandler.java:298)
        at io.xhance.data.click_handling.Consumer.main(Consumer.java:57)
2019-01-02 09:06:48 [WARN ](c.n.p.p.i.f.GuardExceptionHandler  ) Exception occurred from interceptor
java.lang.NullPointerException
        at com.navercorp.pinpoint.plugin.mongo.interceptor.MongoDriverGetCollectionInterceptor.after(MongoDriverGetCollectionInterceptor.java:66)
        at com.navercorp.pinpoint.bootstrap.interceptor.scope.ExceptionHandleScopedInterceptor.after(ExceptionHandleScopedInterceptor.java:79)
        at com.mongodb.client.internal.MongoDatabaseImpl.getCollection(MongoDatabaseImpl.java:130)
        at com.mongodb.client.internal.MongoDatabaseImpl.getCollection(MongoDatabaseImpl.java:125)
        at io.xhance.data.common.MongoHelper.getCollection(MongoHelper.java:72)
        at io.xhance.data.common.MongoHelper.insertBatch(MongoHelper.java:140)
        at io.xhance.data.click_handling.NginxLogHandler.handler(NginxLogHandler.java:298)
        at io.xhance.data.click_handling.Consumer.main(Consumer.java:57)`

**Comment by RoySRose** [comment]
Hello, @wiliiwin 

sorry for the trouble, I'm on it, found the reason and fixed it hopefully...
Started testing, if nothing shows up, hopefully. We will release the fix in few days.

If you are in hurry or like to help with the test to speed things up.
here is the [hopefully fixed agent](https://github.com/RoySRose/pinpoint/releases/download/temporary/pinpoint-agent-1.8.2-SNAPSHOT.jar)

or you can build with below [source code](https://github.com/RoySRose/pinpoint/tree/MongoHotFix)
