### ISSUE TITLE
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout springboot项目错报

### ISSUE THREAD

**Issue by springClound-Wang** [naver/pinpoint#5129]
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireTimeout(DefaultFuture.java:120)
	at com.navercorp.pinpoint.rpc.DefaultFuture.run(DefaultFuture.java:235)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:748)
2019-01-12 16:15:37 [INFO ](c.n.p.p.s.TcpDataSender@Default    :273) request fail. request:RetryMessage{retryCount=2, maxRetryCount=3, bytes=85, messageDescription='TApiMetaData'}, caused:timeout
com.navercorp.pinpoint.rpc.PinpointSocketException: timeout

**Comment by Xylus** [comment]
Check your connection.

**Comment by springClound-Wang** [comment]
> 检查你的连接。

在哪检查我的连接

**Comment by springClound-Wang** [comment]
> 检查你的连接。
do you speak  chinese?

**Comment by Xylus** [comment]
Unfortunately no.

**Comment by springClound-Wang** [comment]
> 很不幸的是，不行。

Can you tell me where to check my configuration connection?

**Comment by springClound-Wang** [comment]
> > 很不幸的是，不行。
> 
> 你能告诉我在哪里查看配置连接吗？

How to configure my connection?

> 很不幸的是，不行。

How to configure my connection?

**Comment by Xylus** [comment]
Please take a look at the [installation guide](http://naver.github.io/pinpoint/installation.html).
In particular, [agent configuration](http://naver.github.io/pinpoint/installation.html#configuration-2) and [network test](http://naver.github.io/pinpoint/troubleshooting_network.html).
