### ISSUE TITLE
why pinpoint-web-1.9.0-SNAPSHOT.war can`t  send mail

### ISSUE THREAD

**Issue by suiyuewuheng** [naver/pinpoint#5288]
I read this configure http://naver.github.io/pinpoint/alarm.html
I cloned the latest package and compiled it，When I deploy it into the container，it has error,i only modify batch.properties file and jdbc.properties file

### pinpoint web error  log：
2019-02-28 15:33:00 [INFO ](o.s.b.c.l.s.SimpleJobLauncher      ) Job: [FlowJob: [name=alarmJob]] launched with the following parameters: [{schedule.date=1551385980005}]
2019-02-28 15:33:00 [INFO ](o.s.b.c.j.SimpleStepHandler        ) Executing step: [alarmPartitionStep]
2019-02-28 15:33:01 [INFO ](o.s.b.c.l.s.SimpleJobLauncher      ) Job: [FlowJob: [name=alarmJob]] completed with the following parameters: [{schedule.date=1551385980005}] and the following status: [COMPLETED]
2019-02-28 15:36:00 [INFO ](o.s.b.c.l.s.SimpleJobLauncher      ) Job: [FlowJob: [name=alarmJob]] launched with the following parameters: [{schedule.date=1551386160009}]
2019-02-28 15:36:00 [INFO ](o.s.b.c.j.SimpleStepHandler        ) Executing step: [alarmPartitionStep]
**2019-02-28 15:36:01 [ERROR](c.n.p.w.a.SpringSmtpMailSender     ) can't send alarm email. Rule{ruleId='1', applicationId='myphp', serviceType='PHP', checkerName='TOTAL COUNT', threshold=4, userGroupId='pins', smsSend=false, emailSend=true, notes=''}
	at com.navercorp.pinpoint.web.alarm.SpringSmtpMailSender.sendEmail(SpringSmtpMailSender.java:81)
	at com.navercorp.pinpoint.web.alarm.DefaultAlarmMessageSender.sendEmail(DefaultAlarmMessageSender.java:41)
	at com.navercorp.pinpoint.web.alarm.AlarmWriter.sendAlarmMessage(AlarmWriter.java:65)
	at com.navercorp.pinpoint.web.alarm.AlarmWriter.write(AlarmWriter.java:52)**
2019-02-28 15:36:01 [INFO ](o.s.b.c.l.s.SimpleJobLauncher      ) Job: [FlowJob: [name=alarmJob]] completed with the following parameters: [{schedule.date=1551386160009}] and the following status: [COMPLETED]

### 
**my jdbc.properties file.**
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/pinpoint?characterEncoding=UTF-8
jdbc.username=admin
jdbc.password=admin

**my  batch.proferties file**
#batch enable config
batch.enable=true

#batch server ip to execute batch
batch.server.ip=127.0.0.1
batch.server.env=release

#smtp config
pinpoint.url=http://pinpoint.com:28080
alarm.mail.server.url=smtp.sina.com
alarm.mail.server.port=25
alarm.mail.server.userName=admin@sina.com
alarm.mail.server.password=xxxxxx
alarm.mail.sender.address=admin@sina.com

#flink server list
batch.flink.server=

**Comment by Xylus** [comment]
Hi @suiyuewuheng 
The error log above should have a "Caused by" log which tells you what caused the exception to be thrown.

**Comment by pwvictor** [comment]
@suiyuewuheng @Xylus 
Same error.  The config file was wrong.
change alarm.mail.server.userName  to   alarm.mail.server.username       lowercase

**Comment by minwoo-jung** [comment]
@pwvictor
Thank you~^^ I will fix it.

**Comment by minwoo-jung** [comment]
[I commited~.](https://github.com/naver/pinpoint/commit/906c6581c7dab0f3892f5407c527f80f7c2e743e)

**Comment by ipaste** [comment]
there is another situation, in my environment, it doesn't need to config the username and password, just send the mail use the smtp server, how can this be done?

**Comment by minwoo-jung** [comment]
Hi @ipaste
Did you test?
I think that if you do not need a password username, it works fine without setting it. 
Currently I am using it.
