### ISSUE TITLE
question about a topology map display

### ISSUE THREAD

**Issue by superzhengzhe** [naver/pinpoint#5290]
Why does a node not display a topology map on the front page, but when a method is clicked can a topology map display？

**Comment by superzhengzhe** [comment]
how can i do to display a topology map on the front page？

**Comment by superzhengzhe** [comment]
when I use pinpoint-1.5.2 the front page can display a topology map，but when I use pinpoint-1.8.2 the front page can not display a topology map！
![q1](https://user-images.githubusercontent.com/9037988/53683014-e883f080-3d36-11e9-84b5-b38e528b9c27.png)
![q2](https://user-images.githubusercontent.com/9037988/53683019-0a7d7300-3d37-11e9-9188-508aeb1babd1.png)

**Comment by Xylus** [comment]
Hi @superzhengzhe 
Is the first screenshot from 1.8.2 and the second from 1.5.2? Is it just the agent version that's different or are the screenshots from different versions of pinpoint web as well?
We're gonna need more detail, such as what you're trying to trace for *jdh-ent* agent, version of pinpoint web, agent/web log etc for us to help solve your problem.

**Comment by superzhengzhe** [comment]
Thank you for your reply!My pinpoint version is：pinpoint-agent-1.8.2.tar，pinpoint-collector-1.8.2.war，pinpoint-web-1.8.2.war，hbase-2.0.4. I just saw pinpoint 1.8  only compatible HBase version 1.X on the official website. I wonder if that's the reason. Please provide an email address to provide a pointpin log for your investigation. Thank you.

**Comment by Xylus** [comment]
@superzhengzhe Yup, that could be the reason- but pinpoint 1.5.2 should also not have worked with hbase-2.0.4.
Please give it a try with hbase 1.2.x and let me know if it fixes your issue.
Thanks.

**Comment by ClamRen** [comment]
I also have the same proble!

**Comment by superzhengzhe** [comment]
@Xylus Sorry, I reused HBase 1.2.X and found that the problem was solved. Now I can see the topology. Thank you.
![10](https://user-images.githubusercontent.com/9037988/53712361-7cfa6a00-3e81-11e9-8650-2cd7e56b4b5a.png)

**Comment by Xylus** [comment]
@superzhengzhe Awesome, glad it worked out.
@ClamRen Check out the comment above and see if it's applicable to your issue.

**Comment by ClamRen** [comment]
I used to install hbase-2.1.3 and there just one topology map on the web page. Follw above comment, I switch to hbase-2.1.3., and then restart all, by there is no topology map. So I switch to hbase-2.1.3 and restart all progress again, strangely there is nothing.

when i run command: java -javaagent:agentpath -Dpinpoint.agentId=test1234 -Dpinpoint.applicationName=test1234 -jar build/libs/client.jar occur exception:

2019-03-04 14:28:02 [WARN ](c.n.p.r.DefaultFuture              ) FutureListener.onComplete() fail Caused:cannot be started once stopped
java.lang.IllegalStateException: cannot be started once stopped
	at org.jboss.netty.util.HashedWheelTimer.start(HashedWheelTimer.java:279)
	at org.jboss.netty.util.HashedWheelTimer.newTimeout(HashedWheelTimer.java:337)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender.retryRequest(TcpDataSender.java:328)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender.access$200(TcpDataSender.java:55)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender$2.onComplete(TcpDataSender.java:275)
	at com.navercorp.pinpoint.rpc.DefaultFuture.fireOnComplete(DefaultFuture.java:181)
	at com.navercorp.pinpoint.rpc.DefaultFuture.notifyListener(DefaultFuture.java:143)
	at com.navercorp.pinpoint.rpc.DefaultFuture.setFailure(DefaultFuture.java:109)
	at com.navercorp.pinpoint.rpc.client.RequestManager.close(RequestManager.java:201)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientHandler.closeResources(DefaultPinpointClientHandler.java:504)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientHandler.channelClosed(DefaultPinpointClientHandler.java:561)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:106)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:371)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)
	at org.jboss.netty.channel.Channels$6.run(Channels.java:457)
	at org.jboss.netty.channel.socket.ChannelRunnableWrapper.run(ChannelRunnableWrapper.java:40)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-04 14:28:02 [WARN ](c.n.p.p.AgentInfoSender            ) request failed.
com.navercorp.pinpoint.rpc.PinpointSocketException: socket closed
	at com.navercorp.pinpoint.rpc.client.RequestManager.close(RequestManager.java:188)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientHandler.closeResources(DefaultPinpointClientHandler.java:504)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClientHandler.channelClosed(DefaultPinpointClientHandler.java:561)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:106)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:371)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)
	at org.jboss.netty.channel.Channels$6.run(Channels.java:457)
	at org.jboss.netty.channel.socket.ChannelRunnableWrapper.run(ChannelRunnableWrapper.java:40)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
I do't know why?

**Comment by ClamRen** [comment]
I solve the problem follow above command. It's that i made some mistake when install hbase. Thanks a lot!
