### ISSUE TITLE
A problem about Pinpoint-UdpSpanDataExecutor(8-0) doExecute(). Unexpected Error. Cause:Buffer size cannot exceed 65507  in pinpoint-agent logs

### ISSUE THREAD

**Issue by lanyuange** [naver/pinpoint#5374]
2019-03-19 10:41:43 [WARN ](ecutor@Pinpoint-UdpSpanDataExecutor) Pinpoint-UdpSpanDataExecutor(8-0) doExecute(). Unexpected Error. Cause:Buffer size cannot exceed 65507. (now:41104, input-size:33681
com.navercorp.pinpoint.thrift.io.BufferOverflowException: Buffer size cannot exceed 65507. (now:41104, input-size:33681
        at com.navercorp.pinpoint.thrift.io.UnsafeByteArrayOutputStream.write(UnsafeByteArrayOutputStream.java:99)
        at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
        at org.apache.thrift.protocol.TCompactProtocol.writeBinary(TCompactProtocol.java:380)
        at org.apache.thrift.protocol.TCompactProtocol.writeString(TCompactProtocol.java:364)
        at com.navercorp.pinpoint.thrift.dto.TStringStringValue$TStringStringValueStandardScheme.write(TStringStringValue.java:419)
        at com.navercorp.pinpoint.thrift.dto.TStringStringValue$TStringStringValueStandardScheme.write(TStringStringValue.java:370)
        at com.navercorp.pinpoint.thrift.dto.TStringStringValue.write(TStringStringValue.java:314)
        at com.navercorp.pinpoint.thrift.dto.TAnnotationValue.standardSchemeWriteValue(TAnnotationValue.java:515)
        at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:244)
        at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:213)
        at org.apache.thrift.TUnion.write(TUnion.java:152)
        at com.navercorp.pinpoint.thrift.dto.TAnnotation$TAnnotationStandardScheme.write(TAnnotation.java:416)
        at com.navercorp.pinpoint.thrift.dto.TAnnotation$TAnnotationStandardScheme.write(TAnnotation.java:368)
        at com.navercorp.pinpoint.thrift.dto.TAnnotation.write(TAnnotation.java:314)
        at com.navercorp.pinpoint.thrift.dto.TSpanEvent$TSpanEventStandardScheme.write(TSpanEvent.java:1693)
        at com.navercorp.pinpoint.thrift.dto.TSpanEvent$TSpanEventStandardScheme.write(TSpanEvent.java:1488)
        at com.navercorp.pinpoint.thrift.dto.TSpanEvent.write(TSpanEvent.java:1335)
        at com.navercorp.pinpoint.thrift.dto.TSpanChunk$TSpanChunkStandardScheme.write(TSpanChunk.java:1262)
        at com.navercorp.pinpoint.thrift.dto.TSpanChunk$TSpanChunkStandardScheme.write(TSpanChunk.java:1101)
        at com.navercorp.pinpoint.thrift.dto.TSpanChunk.write(TSpanChunk.java:989)
        at com.navercorp.pinpoint.thrift.io.HeaderTBaseSerializer.serialize(HeaderTBaseSerializer.java:76)
        at com.navercorp.pinpoint.thrift.io.HeaderTBaseSerializer.serialize(HeaderTBaseSerializer.java:68)
        at com.navercorp.pinpoint.profiler.sender.ThriftUdpMessageSerializer.serialize(ThriftUdpMessageSerializer.java:91)
        at com.navercorp.pinpoint.profiler.sender.ThriftUdpMessageSerializer.serialize(ThriftUdpMessageSerializer.java:73)
        at com.navercorp.pinpoint.profiler.sender.ThriftUdpMessageSerializer.serializer(ThriftUdpMessageSerializer.java:65)
        at com.navercorp.pinpoint.profiler.sender.ThriftUdpMessageSerializer.serializer(ThriftUdpMessageSerializer.java:35)
        at com.navercorp.pinpoint.profiler.sender.UdpDataSender.sendPacket(UdpDataSender.java:128)
        at com.navercorp.pinpoint.profiler.sender.UdpDataSender.access$000(UdpDataSender.java:38)
        at com.navercorp.pinpoint.profiler.sender.UdpDataSender$1.execute(UdpDataSender.java:89)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:166)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
        at java.lang.Thread.run(Thread.java:748)

**Comment by koo-taejin** [comment]
please checking out this issue #4815

**Comment by lanyuange** [comment]
oK

**Comment by lanyuange** [comment]
Modified the following places, or not
profiler.io.buffering.buffersize=10

collector.receiver.stat.tcp=true
collector.receiver.stat.tcp=true
