### ISSUE TITLE
The topology map of applications cannot be fully displayed

### ISSUE THREAD

**Issue by ClamRen** [naver/pinpoint#5415]
I develop a plugin for my rpc program,and use private servertype.but I can't see the fully topology from my first application.and my servertype is difined as follow: 
public static final ServiceType ICE_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1900, "ICE_PROVIDER", RECORD_STATISTICS);
    public static final ServiceType ICE_CONSUMER_SERVICE_TYPE = ServiceTypeFactory.of(9900, "ICE_CONSUMER", RECORD_STATISTICS);

**Comment by Xylus** [comment]
Hi @ClamRen 
Can't really tell you what exactly is the problem with the details you've provided, but here are some things to check.
Have you implemented **TraceMetadataProvider** for your service types as detailed [here](http://naver.github.io/pinpoint/1.8.2/plugindevguide.html#ii-pinpoint-plugin-structure)?
Have you restarted collector/web with your plugin included in their library path?
Is your plugin propagating trace between Ice Consumer and Provider?

**Comment by ClamRen** [comment]
yes, I boroow other rpc plugin serviceType code such as dubbo, I can see fully topology of all application.The follow serviceType code "1110" and "9110" is dubbo.
public static final ServiceType ICE_PROVIDER_SERVICE_TYPE = ServiceTypeFactory.of(1110, "ICE_PROVIDER");
    public static final ServiceType ICE_CONSUMER_SERVICE_TYPE = ServiceTypeFactory.of(9110, "ICE_CONSUMER", RECORD_STATISTICS);

**Comment by Xylus** [comment]
If your agent started without an error with the code above (duplicate service type code between dubbo plugin and your plugin), then you probably haven't implemented **TraceMetadataProvider** for your plugin.
Please read [this](http://naver.github.io/pinpoint/1.8.2/plugindevguide.html#ii-pinpoint-plugin-structure), especially the following:

> Pinpoint plugin consists of TraceMetadataProvider and ProfilerPlugin implementations. TraceMetadataProvider implementation provides ServiceType and AnnotationKey to Pinpoint Agent, Web and Collector. ProfilerPlugin implementations are used by Pinpoint Agent to transform target classes to record trace data.
> 
>Plugins are deployed as jar files. Pinpoint Agent searches TraceMetadataProvider and ProfilerPlugin implementations using ServiceLoader from the plugin directory, while Web and Collector look into WEB-INF/lib directory. ServiceLoader requires provider configuration file located in META-INF/services, so you must put the following files in the plugin jar file.
> 
> * META-INF/services/com.navercorp.pinpoint.bootstrap.plugin.ProfilerPlugin
> * META-INF/services/com.navercorp.pinpoint.common.trace.TraceMetadataProvider

**Comment by ClamRen** [comment]
public class IceTraceMetadataProvider implements TraceMetadataProvider {
    @Override
    public void setup(TraceMetadataSetupContext context) {
        context.addServiceType(IceConstants.ICE_PROVIDER_SERVICE_TYPE);
        context.addServiceType(IceConstants.ICE_CONSUMER_SERVICE_TYPE);
        context.addServiceType(IceConstants.ICE_PROVIDER_SERVICE_NO_STATISTICS_TYPE);
        context.addAnnotationKey(IceConstants.ICE_ARGS_ANNOTATION_KEY);
        context.addAnnotationKey(IceConstants.ICE_RESULT_ANNOTATION_KEY);
        context.addAnnotationKey(IceConstants.ICE_RPC_ANNOTATION_KEY);
        context.addAnnotationKey(IceConstants.MY_ARGS_ANNOTATION_KEY);
    }
}

com.navercorp.pinpoint.plugin.ice.IcePlugin
com.navercorp.pinpoint.plugin.ice.IceTraceMetadataProvider

![Screenshot from 2019-03-26 17-56-19](https://user-images.githubusercontent.com/26928232/54988785-24d30580-4ff2-11e9-8db7-4211da184425.png)
serverType 1900 990
![Screenshot from 2019-03-26 17-52-46](https://user-images.githubusercontent.com/26928232/54988825-33b9b800-4ff2-11e9-8709-ff0b6f2dd6a8.png)
serverType 1110 9110(dubbo)

**Comment by ClamRen** [comment]
> public class IceTraceMetadataProvider implements TraceMetadataProvider {
> @override
> public void setup(TraceMetadataSetupContext context) {
> context.addServiceType(IceConstants.ICE_PROVIDER_SERVICE_TYPE);
> context.addServiceType(IceConstants.ICE_CONSUMER_SERVICE_TYPE);
> context.addServiceType(IceConstants.ICE_PROVIDER_SERVICE_NO_STATISTICS_TYPE);
> context.addAnnotationKey(IceConstants.ICE_ARGS_ANNOTATION_KEY);
> context.addAnnotationKey(IceConstants.ICE_RESULT_ANNOTATION_KEY);
> context.addAnnotationKey(IceConstants.ICE_RPC_ANNOTATION_KEY);
> context.addAnnotationKey(IceConstants.MY_ARGS_ANNOTATION_KEY);
> }
> }
> 
> com.navercorp.pinpoint.plugin.ice.IcePlugin
> com.navercorp.pinpoint.plugin.ice.IceTraceMetadataProvider
> 
> ![Screenshot from 2019-03-26 17-56-19](https://user-images.githubusercontent.com/26928232/54988785-24d30580-4ff2-11e9-8db7-4211da184425.png)
> serverType 1900 990
> ![Screenshot from 2019-03-26 17-52-46](https://user-images.githubusercontent.com/26928232/54988825-33b9b800-4ff2-11e9-8709-ff0b6f2dd6a8.png)
> serverType 1110 9110(dubbo)

**Comment by ClamRen** [comment]
above serverType corret 1900 9900

**Comment by ClamRen** [comment]
I remove dubbo plugin when i use ice rpc.

**Comment by Xylus** [comment]
Hmm, that's weird.
Have you restarted your collector with your plugin included?
You should see `add Plugin ServiceType:ICE_PROVIDER_SERVICE_TYPE` etc in your collector log.

**Comment by ClamRen** [comment]
yes, I restart the collector but the problem still exist. I want to know which log record the set in.

**Comment by ClamRen** [comment]
![Screenshot from 2019-03-27 09-24-00](https://user-images.githubusercontent.com/26928232/55043743-7c18ba80-5072-11e9-8014-7d8e08b06d3c.png)
the caller api is undefine and the callee is't viewed.

**Comment by Xylus** [comment]
The normal WAS log you're using to deploy collector and web.
When your collector/web starts up, it should print out the following, which tells you that the plugin metadata are loaded.
```
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) Loading TraceMetadataProviders
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) Loading TraceMetadataProvider: com.navercorp.pinpoint.plugin.activemq.client.ActiveMQClientTraceMetadataProvider name:com.navercorp.pinpoint.plugin.activemq.client.ActiveMQClientTraceMetadataProvider@53205685
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) Loading TraceMetadataProvider: com.navercorp.pinpoint.plugin.akka.http.AkkaHttpMetadataProvider name:com.navercorp.pinpoint.plugin.akka.http.AkkaHttpMetadataProvider@37eb088f
...
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) Finished loading ServiceType:
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) TOMCAT(1010) from com.navercorp.pinpoint.plugin.tomcat.TomcatTypeProvider
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) TOMCAT_METHOD(1011) from com.navercorp.pinpoint.plugin.tomcat.TomcatTypeProvider
2019-03-27 10:53:44 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) JETTY(1030) from com.navercorp.pinpoint.plugin.jetty.JettyTypeProvider
...
```
Please check the log above for your plugin's metadata.

If you can't find the log, can you check pinpoint collector/web war file you're using, and see if your plugin is in the `WEB-INF/lib` directory?

**Comment by ClamRen** [comment]
I can't find my plugin in WEB-INF/lib. so I mv my plugin to WEB-INF/lib. and restart collect.
the catalina log:27-Mar-2019 10:31:56.750 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-18080"]
27-Mar-2019 10:31:56.756 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[HTTP/1.1-18080]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-18080]]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:639)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:662)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	... 12 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:219)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1087)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:265)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:68)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	... 13 more

27-Mar-2019 10:31:56.757 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-18009"]
27-Mar-2019 10:31:56.758 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[AJP/1.3-18009]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[AJP/1.3-18009]]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:639)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:662)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	... 12 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:219)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1087)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:265)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	... 13 more

27-Mar-2019 10:31:56.758 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 298 ms
27-Mar-2019 10:31:56.774 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
27-Mar-2019 10:31:56.774 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.38
27-Mar-2019 10:31:56.790 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/zhongrentang/cp4cc_test/call_trace_test/pinpoint/pp-cl/tomcat-pp-cl/webapps/ROOT.war]
27-Mar-2019 10:32:00.312 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
27-Mar-2019 10:32:03.783 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/zhongrentang/cp4cc_test/call_trace_test/pinpoint/pp-cl/tomcat-pp-cl/webapps/ROOT.war] has finished in [6,994] ms
27-Mar-2019 10:32:03.785 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 7026 ms

![Screenshot from 2019-03-27 10-37-40](https://user-images.githubusercontent.com/26928232/55046457-b25b3780-507c-11e9-83ac-fc42e185073d.png)

**Comment by Xylus** [comment]
@ClamRen 
Yup, you'll need your plugin in both your collector and web's library path (WEB-INF/lib).
You can simplify rebuild collector and web (assuming your plugins module have dependency to your plugin) to have your plugin included as they both have the plugins module as dependencies.

Also don't forget to add images to your web module (detailes [here](http://naver.github.io/pinpoint/1.8.2/plugindevguide.html#4-adding-images)) if you need them.

**Comment by ClamRen** [comment]
After i rebuild entire project,the problem has been resolved. and I hava a problem, when use annotaionkey codes for private use, the recorder.recordAttribute's info can't find in the Call Tree.

definition of annotaionkey codes:
public static final AnnotationKey ICE_ARGS_ANNOTATION_KEY = AnnotationKeyFactory.of(900, "ice.args", VIEW_IN_RECORD_SET);
    public static final AnnotationKey ICE_RESULT_ANNOTATION_KEY = AnnotationKeyFactory.of(901, "ice.result", VIEW_IN_RECORD_SET);
    public static final AnnotationKey ICE_RPC_ANNOTATION_KEY = AnnotationKeyFactory.of(902, "ice.rpc", VIEW_IN_RECORD_SET);
    public static final AnnotationKey MY_ARGS_ANNOTATION_KEY = AnnotationKeyFactory.of(903, "myarg", VIEW_IN_RECORD_SET);

record info code:
recorder.recordAttribute(IceConstants.ICE_ARGS_ANNOTATION_KEY, argStr.toString());
recorder.recordAttribute(IceConstants.ICE_RESULT_ANNOTATION_KEY, result);

**Comment by ClamRen** [comment]
from catalina.out can only find ICE_PROVIDER,ICE_CONSUMER,ICE_CONSUMER, the ANNOTATION_KEY can't find.
2019-03-27 15:46:01 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:ICE_PROVIDER
2019-03-27 15:46:01 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:ICE_CONSUMER
2019-03-27 15:46:01 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:ICE
