### ISSUE TITLE
collector  NullPointerException

### ISSUE THREAD

**Issue by tian-github** [naver/pinpoint#5432]
#### What version of pinpoint are you using?
version 
pinpoint-collector-1.8.1-RC1
hbase version  1.4.8

#### Describe your problem**
WebUI console , I can't get the call stack information  , and can't get the jvm stat info .
but I can get the basic information .

#### Logs
I got the issue like this [#issues](https://github.com/naver/pinpoint/issues/4292) ,but not the same .

collector  logs
``
2019-03-28 12:43:27 [ERROR](SimpleAsyncUncaughtExceptionHandler) Unexpected error occurred invoking async method: public void com.navercorp.pinpoint.collector.receiver.thrift.tcp.AgentEventHandler.handleEvent(com.navercorp.pinpoint.rpc.server.PinpointServer,long,com.navercorp.pinpoint.common.server.util.AgentEventType)
java.lang.NullPointerException
	at com.navercorp.pinpoint.collector.receiver.thrift.tcp.AgentEventHandler.handleEvent(AgentEventHandler.java:58)
	at com.navercorp.pinpoint.collector.receiver.thrift.tcp.AgentEventHandler$$FastClassBySpringCGLIB$$414dc1ff.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-28 12:43:27 [ERROR](SimpleAsyncUncaughtExceptionHandler) Unexpected error occurred invoking async method: public void com.navercorp.pinpoint.collector.receiver.thrift.tcp.AgentLifeCycleEventHandler.handleLifeCycleEvent(com.navercorp.pinpoint.rpc.server.PinpointServer,long,com.navercorp.pinpoint.common.server.util.AgentLifeCycleState,int)
java.lang.NullPointerException
	at com.navercorp.pinpoint.collector.receiver.thrift.tcp.AgentLifeCycleEventHandler.handleLifeCycleEvent(AgentLifeCycleEventHandler.java:69)
	at com.navercorp.pinpoint.collector.receiver.thrift.tcp.AgentLifeCycleEventHandler$$FastClassBySpringCGLIB$$508275eb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``

**Comment by koo-taejin** [comment]
hi @tian-github 

Please change Collector module's  log level to DEBUG and post the whole log which containing the error message you posted.

thanks

**Comment by tian-github** [comment]
thanks @koo-taejin 
I upgrade to pinpoint-collector-1.8.1 to resolve the problem , but I aslo can't get the jvm info,and the stat info , webui like this ( no data collected)
![web-ui](https://github.com/tian-github/imageBed/raw/master/pic/pinpoint.png)

but ,i found the collector stat.log , the jvm information has been reported
`2019-03-29 06:01:07 [INFO ](c.n.p.c.StateReport                ) type=TIMER, name=baseDataReceiverWorker.dispatchDuration, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
2019-03-29 06:01:07 [INFO ](c.n.p.c.StateReport                ) type=TIMER, name=baseDataReceiverWorker.duration, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
2019-03-29 06:01:07 [INFO ](c.n.p.c.StateReport                ) type=TIMER, name=spanReceiverExecutor.dispatchDuration, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
2019-03-29 06:01:07 [INFO ](c.n.p.c.StateReport                ) type=TIMER, name=spanReceiverExecutor.duration, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
2019-03-29 06:01:07 [INFO ](c.n.p.c.StateReport                ) type=TIMER, name=statReceiverExecutor.dispatchDuration, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
2019-03-29 06:01:07 [INFO ](c.n.p.c.StateReport                ) type=TIMER, name=statReceiverExecutor.duration, count=0, min=0.0, max=0.0, mean=0.0, stddev=0.0, median=0.0, p75=0.0, p95=0.0, p98=0.0, p99=0.0, p999=0.0, mean_rate=0.0, m1=0.0, m5=0.0, m15=0.0, rate_unit=events/second, duration_unit=milliseconds
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=baseDataReceiverWorker.completed, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=baseDataReceiverWorker.running, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.garbage-collectors.PS-MarkSweep.count, value=3
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.garbage-collectors.PS-MarkSweep.time, value=241
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.garbage-collectors.PS-Scavenge.count, value=9
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.garbage-collectors.PS-Scavenge.time, value=221
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.heap.committed, value=1272971264
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.heap.init, value=245366784
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.heap.max, value=3467640832
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.heap.usage, value=0.16411535668524507
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.heap.used, value=569093112
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.non-heap.committed, value=75759616
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.non-heap.init, value=2555904
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.non-heap.max, value=-1
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.non-heap.usage, value=-7.4303176E7
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.non-heap.used, value=74303176
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Code-Cache.committed, value=18874368
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Code-Cache.init, value=2555904
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Code-Cache.max, value=251658240
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Code-Cache.usage, value=0.07434412638346354
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Code-Cache.used, value=18709312
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Compressed-Class-Space.committed, value=6029312
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Compressed-Class-Space.init, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Compressed-Class-Space.max, value=1073741824
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Compressed-Class-Space.usage, value=0.005403369665145874
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Compressed-Class-Space.used, value=5801824
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Metaspace.committed, value=50855936
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Metaspace.init, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Metaspace.max, value=-1
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Metaspace.usage, value=0.9790802001953125
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.Metaspace.used, value=49792040
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Eden-Space.committed, value=911212544
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Eden-Space.init, value=61865984
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Eden-Space.max, value=1113587712
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Eden-Space.usage, value=0.44547242992566355
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Eden-Space.used, value=496072624
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Old-Gen.committed, value=266338304
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Old-Gen.init, value=163577856
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Old-Gen.max, value=2600468480
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Old-Gen.usage, value=0.02807974353913338
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Old-Gen.used, value=73020488
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Survivor-Space.committed, value=95420416
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Survivor-Space.init, value=9961472
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Survivor-Space.max, value=95420416
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Survivor-Space.usage, value=0.0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.pools.PS-Survivor-Space.used, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.total.committed, value=1348730880
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.total.init, value=247922688
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.total.max, value=3467640831
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.memory.total.used, value=643396288
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.blocked.count, value=14
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.count, value=199
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.daemon.count, value=198
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.deadlock.count, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.deadlocks, value=[]
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.new.count, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.runnable.count, value=30
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.terminated.count, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.timed_waiting.count, value=12
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.thread-states.waiting.count, value=143
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.vm.name, value=2833@ip-172-31-6-25.eu-west-1.compute.internal
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.vm.uptime, value=1386804
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=jvm.vm.vendor, value=Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.191-b12 (1.8)
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=spanReceiverExecutor.completed, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=spanReceiverExecutor.running, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=statReceiverExecutor.completed, value=0
2019-03-29 06:02:07 [INFO ](c.n.p.c.StateReport                ) type=GAUGE, name=statReceiverExecutor.running, value=0
`

**Comment by tian-github** [comment]
hi @koo-taejin  , I make a mistake , the stat.log is the collector monitor data (com.navercorp.pinpoint.collector.monitor.CollectorMetric)
---
collector server:
I open the DEBUG log , I found com.navercorp.pinpoint.collector.handler.thrift.ThriftAgentEventHandler to handle hbase table AgentStatV2 , but i  grep keyword  `ThriftAgentEventHandler `  found nothing .

I didn't  found log about `agentStat` , the agent log:
 ```
2019-03-29 03:57:34 [INFO ](c.n.p.p.AgentInfoSender            ) AgentInfo sent.
2019-03-29 03:57:36 [INFO ](c.n.p.p.AgentInfoSender            ) Sending AgentInfo TAgentInfo(hostname:preproduct-1, ip:172.31.0.50, ports:, agentId:item-api, applicationName:item-api, serviceType:1210, pid:12642, agentVersion:1.8.1, vmVersion:1.8.0_191, startTimestamp:1553846243935, serverMetaData:TServerMetaData(serverInfo:Apache Tomcat/8.5.34, vmArgs:[-javaagent:/data/pinpoint_agent/pinpoint-bootstrap-1.8.1.jar, -Dpinpoint.agentId=item-api, -Dpinpoint.applicationName=item-api, -Dspring.profiles.active=pre], serviceInfos:[TServiceInfo(serviceName:Spring Boot (JarLauncher), serviceLibs:[
...//ignoe about this 
]), TServiceInfo(serviceName:Tomcat/localhost/, serviceLibs:[])]), jvmInfo:TJvmInfo(version:0, vmVersion:1.8.0_191, gcType:PARALLEL), container:false)
2019-03-29 03:57:36 [INFO ](c.n.p.p.AgentInfoSender            ) AgentInfo sent.
2019-03-29 07:58:26 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@4b672daa HandshakeJob completed.
2019-03-29 08:06:12 [INFO ](c.n.p.p.i.ASMAspectWeaver          ) weaving sourceClass=org/apache/catalina/connector/RequestFacade adviceClass=com/navercorp/pinpoint/plugin/tomcat/aspect/RequestFacadeAspect
2019-03-29 08:06:12 [INFO ](c.n.p.p.i.ASMAspectWeaver          ) weaving method=getHeaderNames()Ljava/util/Enumeration;

```

**Comment by tian-github** [comment]
> ./networktest.sh
```
CLASSPATH=./tools/pinpoint-tools-1.8.1.jar:
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.engine=ASM
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.interface.cache.size=4
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.interface.cache.entry.size=16
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.annotation.cache.size=4
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.annotation.cache.entry.size=4
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.super.cache.size=4
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.instrument.matcher.super.cache.entry.size=4
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.interceptorregistry.size=8192
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.collector.span.ip=172.31.6.25
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.collector.span.port=9996
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.collector.stat.ip=172.31.6.25
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.collector.stat.port=9995
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.collector.tcp.ip=172.31.6.25
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.collector.tcp.port=9994
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spandatasender.write.queue.size=5120
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spandatasender.socket.sendbuffersize=1048576
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spandatasender.socket.timeout=3000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spandatasender.chunk.size=16384
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spandatasender.socket.type=OIO
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spandatasender.transport.type=UDP
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.statdatasender.write.queue.size=5120
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.statdatasender.socket.sendbuffersize=1048576
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.statdatasender.socket.timeout=3000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.statdatasender.chunk.size=16384
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.statdatasender.socket.type=OIO
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.statdatasender.transport.type=UDP
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.command.accept.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.command.activethread.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.command.activethread.count.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.command.activethread.threaddump.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.command.activethread.threadlightdump.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.client.write.timeout=3000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.client.request.timeout=3000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.client.reconnect.interval=3000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.client.ping.interval=300000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.tcpdatasender.client.handshake.interval=60000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.pinpoint.activethread=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.pinpoint.datasource=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.pinpoint.datasource.tracelimitsize=20
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.monitor.deadlock.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.monitor.deadlock.interval=60000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.callstack.max.depth=64
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jdbc.sqlcachesize=1024
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jdbc.tracesqlbindvalue=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.sampling.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.sampling.rate=1
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.io.buffering.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.io.buffering.buffersize=20
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.os.name=null
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jvm.vendor.name=
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jvm.stat.collect.interval=5000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jvm.stat.batch.send.count=6
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.jvm.stat.collect.detailed.metrics=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.agentInfo.send.retry.interval=300000
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.applicationservertype=null
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.include=
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.interceptor.exception.propagate=false
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.lambda.expressions.support=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.proxy.http.header.enable=true
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.guice.module.factory=null
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.application.namespace=
2019-03-29 22:04:44 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) configuration loaded successfully.
java.net.SocketTimeoutException: Receive timed out
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
	at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
	at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
	at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPStat(NetworkAvailabilityChecker.java:83)
	at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:60)
UDP-STAT:// ip-172-31-6-25.eu-west-1.compute.internal
    => 172.31.6.25:9995 [FAIL]

java.net.SocketTimeoutException: Receive timed out
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
	at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
	at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
	at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPSpan(NetworkAvailabilityChecker.java:92)
	at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:66)
UDP-SPAN:// ip-172-31-6-25.eu-west-1.compute.internal
    => 172.31.6.25:9996 [FAIL]

TCP:// ip-172-31-6-25.eu-west-1.compute.internal
    => 172.31.6.25:9994 [SUCCESS]

```
