### ISSUE TITLE
agent-it  run Log4jIT error , the same error in the added test class

### ISSUE THREAD

**Issue by licoco** [naver/pinpoint#5441]
2019-04-02 09:21:30 [INFO ](com.navercorp.pinpoint.bootstrap.config.DefaultProfilerConfig) profiler.spring.beans.[0-9]+(.scope|.base-packages|.name.pattern|.class.pattern|.annotation)={profiler.spring.beans.3.scope=post-processor, profiler.spring.beans.2.base-packages=com.navercorp.test.pinpoint, profiler.spring.beans.1.scope=post-processor, profiler.spring.beans.3.base-packages=com.navercorp.test.pinpoint, profiler.spring.beans.2.class.pattern=.*Morae, profiler.spring.beans.1.name.pattern=ma.*, outer, profiler.spring.beans.2.scope=post-processor, profiler.spring.beans.1.base-packages=com.navercorp.test.pinpoint, profiler.spring.beans.3.annotation=org.springframework.stereotype.Component}
2019-04-02 09:21:32 [WARN ](.p.s.f.FileDescriptorMetricProvider) Unsupported operating system WINDOW/JAVA_8/ORACLE
2019-04-02 09:21:32 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
[SharedPinpointPluginTest]testClazzName:com.navercorp.pinpoint.plugin.log4j.Log4jIT, mavenDependencyResolverClassPaths:D:\Program%20Files\repo\org\eclipse\aether\aether-impl\1.0.1.v20141111\aether-impl-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\apache\maven\maven-model\3.2.5\maven-model-3.2.5.jar;D:\Program%20Files\repo\com\google\guava\guava\20.0\guava-20.0.jar;D:\Program%20Files\repo\org\codehaus\plexus\plexus-interpolation\1.21\plexus-interpolation-1.21.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-transport-http\1.0.1.v20141111\aether-transport-http-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\apache\maven\wagon\wagon-provider-api\1.0\wagon-provider-api-1.0.jar;D:\Program%20Files\repo\org\apache\maven\maven-repository-metadata\3.2.5\maven-repository-metadata-3.2.5.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-transport-file\1.0.1.v20141111\aether-transport-file-1.0.1.v20141111.jar;E:\workspace\github\pinpoint-1.9\test\target\classes;D:\Program%20Files\repo\org\eclipse\aether\aether-spi\1.0.1.v20141111\aether-spi-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\apache\maven\maven-model-builder\3.2.5\maven-model-builder-3.2.5.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-transport-classpath\1.0.1.v20141111\aether-transport-classpath-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-util\1.0.1.v20141111\aether-util-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\codehaus\plexus\plexus-component-annotations\1.5.5\plexus-component-annotations-1.5.5.jar;D:\Program%20Files\repo\org\codehaus\plexus\plexus-utils\3.0.20\plexus-utils-3.0.20.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-transport-wagon\1.0.1.v20141111\aether-transport-wagon-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\apache\maven\maven-aether-provider\3.2.5\maven-aether-provider-3.2.5.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-api\1.0.1.v20141111\aether-api-1.0.1.v20141111.jar;D:\Program%20Files\repo\org\eclipse\aether\aether-connector-basic\1.0.1.v20141111\aether-connector-basic-1.0.1.v20141111.jar
[com.navercorp.pinpoint.plugin.log4j.Log4jIT] TestParameter{testId='log4j-1.2.16:child:-1', testMavenDependencies='log4j:log4j:1.2.16;'}
[com.navercorp.pinpoint.plugin.log4j.Log4jIT] TestParameter{testId='log4j-1.2.17:child:-1', testMavenDependencies='log4j:log4j:1.2.17;'}
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/RepositorySystemSession
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.navercorp.pinpoint.test.plugin.shared.ReflectionDependencyResolver.get(ReflectionDependencyResolver.java:36)
	at com.navercorp.pinpoint.test.plugin.shared.SharedPinpointPluginTest.getTestDependencies(SharedPinpointPluginTest.java:114)
	at com.navercorp.pinpoint.test.plugin.shared.SharedPinpointPluginTest.newTestCaseInfo(SharedPinpointPluginTest.java:101)
	at com.navercorp.pinpoint.test.plugin.shared.SharedPinpointPluginTest.execute(SharedPinpointPluginTest.java:143)
	at com.navercorp.pinpoint.test.plugin.shared.SharedPinpointPluginTest.main(SharedPinpointPluginTest.java:56)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.RepositorySystemSession
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.navercorp.pinpoint.test.plugin.shared.MavenDependencyResolverClassLoader.loadClass(MavenDependencyResolverClassLoader.java:45)
	... 10 more
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

Process finished with exit code 0

**Comment by licoco** [comment]
#5405  It's a problem.

**Comment by licoco** [comment]
@minwoo-jung
