### ISSUE TITLE
java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by zhangiicc** [naver/pinpoint#5451]
collector-log
```
2019-04-02 17:45:55 [WARN ](o.j.n.c.SimpleChannelHandler       ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@51d0a763(remote:/100.97.222.3:38045, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), State=UNEXPECTED_CLOSE_BY_CLIENT)
2019-04-02 17:45:55 [INFO ](.r.AgentLifeCycleChangeEventHandler) AgentLifeCycleChangeEventHandler eventPerformed(). pinpointServer:DefaultPinpointServer@51d0a763(remote:/100.97.222.3:38045, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), code:UNEXPECTED_CLOSE_BY_CLIENT
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@51d0a763 stateTo() completed. Socket state change success(updateWanted:UNEXPECTED_CLOSE_BY_CLIENT ,before:RUN_WITHOUT_HANDSHAKE ,current:UNEXPECTED_CLOSE_BY_CLIENT).
2019-04-02 17:45:55 [INFO ](.s.a.AgentLifeCycleAsyncTaskService) Handle lifecycle event - pinpointServer:{}, state:Unexpected Shutdown
2019-04-02 17:45:55 [WARN ](.p.c.s.a.AgentEventAsyncTaskService) maybe not yet received the handshake data - pinpointServer:{}
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.PinpointServerAcceptor   ) channelConnected started. channel:[id: 0xbedc9da6, /58.210.134.158:6363 => /10.96.188.25:9994]
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@7c21431a start() started. channel:[id: 0xbedc9da6, /58.210.134.158:6363 => /10.96.188.25:9994].
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7c21431a(remote:/58.210.134.158:6363, state:CONNECTED, healthCheckState:WAIT), State=CONNECTED)
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@7c21431a stateTo() completed. Socket state change success(updateWanted:CONNECTED ,before:NONE ,current:CONNECTED).
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7c21431a(remote:/58.210.134.158:6363, state:RUN_WITHOUT_HANDSHAKE, healthCheckState:WAIT), State=RUN_WITHOUT_HANDSHAKE)
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@7c21431a stateTo() completed. Socket state change success(updateWanted:RUN_WITHOUT_HANDSHAKE ,before:CONNECTED ,current:RUN_WITHOUT_HANDSHAKE).
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@7c21431a start() completed.
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@7c21431a handleHandshake() started. requestId:0, data:{serviceType=1010, socketId=1961, hostName=pinpoint, agentId=pinpoint-5dbd7, supportCommandList=[730, 740, 710, 750], ip=172.26.0.110, pid=1225, supportServer=true, version=1.8.0, applicationName=test11, startTimestamp=1554165781558}
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7c21431a(remote:/58.210.134.158:6363, state:RUN_DUPLEX, healthCheckState:WAIT), State=RUN_DUPLEX)
2019-04-02 17:45:55 [INFO ](c.n.p.c.c.ClusterPointRepository   ) addClusterPoint(clusterPoint = [PinpointServerClusterPoint(test11/pinpoint-5dbd7/1554165781558), version:1.8.0, supportCommandList:[ACTIVE_THREAD_COUNT, ACTIVE_THREAD_DUMP, ECHO, ACTIVE_THREAD_LIGHT_DUMP], pinpointServer:DefaultPinpointServer@7c21431a(remote:/58.210.134.158:6363, state:RUN_DUPLEX, healthCheckState:WAIT)])
2019-04-02 17:45:55 [INFO ](.r.AgentLifeCycleChangeEventHandler) AgentLifeCycleChangeEventHandler eventPerformed(). pinpointServer:DefaultPinpointServer@7c21431a(remote:/58.210.134.158:6363, state:RUN_DUPLEX, healthCheckState:WAIT), code:RUN_DUPLEX
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@7c21431a stateTo() completed. Socket state change success(updateWanted:RUN_DUPLEX ,before:RUN_WITHOUT_HANDSHAKE ,current:RUN_DUPLEX).
2019-04-02 17:45:55 [INFO ](.s.a.AgentLifeCycleAsyncTaskService) Handle lifecycle event - pinpointServer:{serviceType=1010, socketId=1961, hostName=pinpoint, agentId=pinpoint-5dbd7, supportCommandList=[730, 740, 710, 750], ip=172.26.0.110, pid=1225, supportServer=true, version=1.8.0, applicationName=test11, startTimestamp=1554165781558}, state:Running
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.PinpointServerAcceptor   ) channelConnected started. channel:[id: 0x2c874433, /100.97.219.130:60394 => /10.96.188.25:9994]
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@7b049170 start() started. channel:[id: 0x2c874433, /100.97.219.130:60394 => /10.96.188.25:9994].
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7b049170(remote:/100.97.219.130:60394, state:CONNECTED, healthCheckState:WAIT), State=CONNECTED)
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@7b049170 stateTo() completed. Socket state change success(updateWanted:CONNECTED ,before:NONE ,current:CONNECTED).
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7b049170(remote:/100.97.219.130:60394, state:RUN_WITHOUT_HANDSHAKE, healthCheckState:WAIT), State=RUN_WITHOUT_HANDSHAKE)
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@7b049170 stateTo() completed. Socket state change success(updateWanted:RUN_WITHOUT_HANDSHAKE ,before:CONNECTED ,current:RUN_WITHOUT_HANDSHAKE).
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@7b049170 start() completed.
2019-04-02 17:45:55 [WARN ](o.j.n.c.SimpleChannelHandler       ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@7b049170(remote:/100.97.219.130:60394, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), State=UNEXPECTED_CLOSE_BY_CLIENT)
2019-04-02 17:45:55 [INFO ](.r.AgentLifeCycleChangeEventHandler) AgentLifeCycleChangeEventHandler eventPerformed(). pinpointServer:DefaultPinpointServer@7b049170(remote:/100.97.219.130:60394, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), code:UNEXPECTED_CLOSE_BY_CLIENT
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@7b049170 stateTo() completed. Socket state change success(updateWanted:UNEXPECTED_CLOSE_BY_CLIENT ,before:RUN_WITHOUT_HANDSHAKE ,current:UNEXPECTED_CLOSE_BY_CLIENT).
2019-04-02 17:45:55 [INFO ](.s.a.AgentLifeCycleAsyncTaskService) Handle lifecycle event - pinpointServer:{}, state:Unexpected Shutdown
2019-04-02 17:45:55 [WARN ](.p.c.s.a.AgentEventAsyncTaskService) maybe not yet received the handshake data - pinpointServer:{}
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@7c21431a handleHandshake() completed(isFirst:true). requestId:0, responseCode:DUPLEX_COMMUNICATION
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.PinpointServerAcceptor   ) channelConnected started. channel:[id: 0xdf559205, /100.97.223.131:11461 => /10.96.188.25:9994]
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@525e52cc start() started. channel:[id: 0xdf559205, /100.97.223.131:11461 => /10.96.188.25:9994].
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@525e52cc(remote:/100.97.223.131:11461, state:CONNECTED, healthCheckState:WAIT), State=CONNECTED)
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@525e52cc stateTo() completed. Socket state change success(updateWanted:CONNECTED ,before:NONE ,current:CONNECTED).
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@525e52cc(remote:/100.97.223.131:11461, state:RUN_WITHOUT_HANDSHAKE, healthCheckState:WAIT), State=RUN_WITHOUT_HANDSHAKE)
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@525e52cc stateTo() completed. Socket state change success(updateWanted:RUN_WITHOUT_HANDSHAKE ,before:CONNECTED ,current:RUN_WITHOUT_HANDSHAKE).
2019-04-02 17:45:55 [INFO ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@525e52cc start() completed.
2019-04-02 17:45:55 [WARN ](o.j.n.c.SimpleChannelHandler       ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-02 17:45:55 [INFO ](c.z.ZookeeperProfilerClusterManager) eventPerformed() started. (PinpointServer=DefaultPinpointServer@525e52cc(remote:/100.97.223.131:11461, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), State=UNEXPECTED_CLOSE_BY_CLIENT)
2019-04-02 17:45:55 [INFO ](.r.AgentLifeCycleChangeEventHandler) AgentLifeCycleChangeEventHandler eventPerformed(). pinpointServer:DefaultPinpointServer@525e52cc(remote:/100.97.223.131:11461, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT), code:UNEXPECTED_CLOSE_BY_CLIENT
2019-04-02 17:45:55 [INFO ](.s.a.AgentLifeCycleAsyncTaskService) Handle lifecycle event - pinpointServer:{}, state:Unexpected Shutdown
2019-04-02 17:45:55 [INFO ](.n.p.r.s.DefaultPinpointServerState) DefaultPinpointServer@525e52cc stateTo() completed. Socket state change success(updateWanted:UNEXPECTED_CLOSE_BY_CLIENT ,before:RUN_WITHOUT_HANDSHAKE ,current:UNEXPECTED_CLOSE_BY_CLIENT).
2019-04-02 17:45:55 [WARN ](.p.c.s.a.AgentEventAsyncTaskService) maybe not yet received the handshake data - pinpointServer:{}

```
vim hbase.properties
```
hbase.client.host=10.96.188.25,10.96.188.22,10.96.188.23
hbase.client.port=2181

# hbase default:/hbase
hbase.zookeeper.znode.parent=/hbase

# hbase namespace to use default:default
hbase.namespace=default

# hbase timeout option==================================================================================
# hbase default:true
hbase.ipc.client.tcpnodelay=true
# hbase default:60000
hbase.rpc.timeout=10000
# hbase default:Integer.MAX_VALUE
hbase.client.operation.timeout=10000

# hbase socket read timeout. default: 200000
hbase.ipc.client.socket.timeout.read=20000
# socket write timeout. hbase default: 600000
hbase.ipc.client.socket.timeout.write=60000

# ==================================================================================
# hbase client thread pool option
hbase.client.thread.max=64
hbase.client.threadPool.queueSize=5120
# prestartAllCoreThreads
hbase.client.threadPool.prestart=false

# enable hbase async operation. default: false
hbase.client.async.enable=false
# the max number of the buffered asyncPut ops for each region. default:10000
hbase.client.async.in.queuesize=10000
# periodic asyncPut ops flush time. default:100
hbase.client.async.flush.period.ms=100
# the max number of the retry attempts to insert queue before dropping the request. default:10000
hbase.client.async.max.retries.in.queue=10000
```
**vim pinpoint-collector.properties**
```
# base data receiver config  ---------------------------------------------------------------------
collector.receiver.base.ip=0.0.0.0
collector.receiver.base.port=9994

# number of tcp worker threads
collector.receiver.base.worker.threadSize=8
# capacity of tcp worker queue
collector.receiver.base.worker.queueSize=1024
# monitoring for tcp worker
collector.receiver.base.worker.monitor=true

collector.receiver.base.request.timeout=3000
collector.receiver.base.closewait.timeout=3000
# 5 min
collector.receiver.base.ping.interval=300000
# 30 min
collector.receiver.base.pingwait.timeout=1800000 

# stat receiver config  ---------------------------------------------------------------------
collector.receiver.stat.udp=true
collector.receiver.stat.udp.ip=0.0.0.0
collector.receiver.stat.udp.port=9995
collector.receiver.stat.udp.receiveBufferSize=4194304

# Should keep in mind that TCP transport load balancing is per connection.(UDP transport loadbalancing is per packet)
collector.receiver.stat.tcp=false
collector.receiver.stat.tcp.ip=0.0.0.0
collector.receiver.stat.tcp.port=9995

collector.receiver.stat.tcp.request.timeout=3000
collector.receiver.stat.tcp.closewait.timeout=3000
# 5 min
collector.receiver.stat.tcp.ping.interval=300000
# 30 min
collector.receiver.stat.tcp.pingwait.timeout=1800000 

# number of udp statworker threads
collector.receiver.stat.worker.threadSize=8
# capacity of udp statworker queue
collector.receiver.stat.worker.queueSize=64
# monitoring for udp stat worker
collector.receiver.stat.worker.monitor=true


# span receiver config  ---------------------------------------------------------------------
collector.receiver.span.udp=true
collector.receiver.span.udp.ip=0.0.0.0
collector.receiver.span.udp.port=9996
collector.receiver.span.udp.receiveBufferSize=4194304

# Should keep in mind that TCP transport load balancing is per connection.(UDP transport loadbalancing is per packet)
collector.receiver.span.tcp=false
collector.receiver.span.tcp.ip=0.0.0.0
collector.receiver.span.tcp.port=9996

collector.receiver.span.tcp.request.timeout=3000
collector.receiver.span.tcp.closewait.timeout=3000
# 5 min
collector.receiver.span.tcp.ping.interval=300000
# 30 min
collector.receiver.span.tcp.pingwait.timeout=1800000 

# number of udp statworker threads
collector.receiver.span.worker.threadSize=32
# capacity of udp statworker queue
collector.receiver.span.worker.queueSize=256
# monitoring for udp stat worker
collector.receiver.span.worker.monitor=true


# configure l4 ip address to ignore health check logs
collector.l4.ip=

# change OS level read/write socket buffer size (for linux)
#sudo sysctl -w net.core.rmem_max=
#sudo sysctl -w net.core.wmem_max=
# check current values using:
#$ /sbin/sysctl -a | grep -e rmem -e wmem

# number of agent event worker threads
collector.agentEventWorker.threadSize=4
# capacity of agent event worker queue
collector.agentEventWorker.queueSize=1024

statistics.flushPeriod=1000

# -------------------------------------------------------------------------------------------------
# The cluster related options are used to establish connections between the agent, collector, and web in order to send/receive data between them in real time.
# You may enable additional features using this option (Ex : RealTime Active Thread Chart).
# -------------------------------------------------------------------------------------------------
# Usage : Set the following options for collector/web components that reside in the same cluster in order to enable this feature.
# 1. cluster.enable (pinpoint-web.properties, pinpoint-collector.properties) - "true" to enable
# 2. cluster.zookeeper.address (pinpoint-web.properties, pinpoint-collector.properties) - address of the ZooKeeper instance that will be used to manage the cluster
# 3. cluster.web.tcp.port (pinpoint-web.properties) - any available port number (used to establish connection between web and collector)
# -------------------------------------------------------------------------------------------------
# Please be aware of the following:
#1. If the network between web, collector, and the agents are not stable, it is advisable not to use this feature.
#2. We recommend using the cluster.web.tcp.port option. However, in cases where the collector is unable to establish connection to the web, you may reverse this and make the web establish connection to the collector.
#   In this case, you must set cluster.connect.address (pinpoint-web.properties); and cluster.listen.ip, cluster.listen.port (pinpoint-collector.properties) accordingly.
cluster.enable=true
cluster.zookeeper.address=10.96.188.25,10.96.188.22,10.96.188.23
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=10.96.188.25
cluster.listen.port=9090

#collector.admin.password=
#collector.admin.api.rest.active=
#collector.admin.api.jmx.active=

collector.spanEvent.sequence.limit=10000

# Flink configuration
flink.cluster.enable=false
flink.cluster.zookeeper.address=localhost
flink.cluster.zookeeper.sessiontimeout=3000

collector.receiver.grpc=false
collector.receiver.grpc.ip=0.0.0.0
collector.receiver.grpc.port=9997
# number of tcp worker threads
collector.receiver.grpc.worker.threadSize=8
# capacity of tcp worker queue
collector.receiver.grpc.worker.queueSize=1024
# monitoring for tcp worker
collector.receiver.grpc.worker.monitor=true
# Milliseconds, Default 5 min
# As collector.receiver.grpc.ping.interval
collector.receiver.grpc.keepalive.time=300000
# Milliseconds, Default 30 min
# As collector.receiver.grpc.pingwait.timeout
collector.receiver.grpc.keepalive.timeout=1800000

collector.receiver.span.grpc=false
collector.receiver.span.grpc.ip=0.0.0.0
collector.receiver.span.grpc.port=9998
# Milliseconds, Default 5 min
collector.receiver.span.grpc.keepalive.time=300000
# Milliseconds, Default 30 min
collector.receiver.span.grpc.keepalive.timeout=1800000 
# number of span worker threads
collector.receiver.span.grpc.worker.threadSize=32
# capacity of span worker queue
collector.receiver.span.grpc.worker.queueSize=256
# monitoring for span worker
collector.receiver.span.grpc.worker.monitor=true

collector.receiver.stat.grpc=false
collector.receiver.stat.grpc.ip=0.0.0.0
collector.receiver.stat.grpc.port=9999
# Milliseconds, Default 5 min
collector.receiver.stat.grpc.keepalive.time=300000
# Milliseconds, Default 30 min
collector.receiver.stat.grpc.keepalive.timeout=1800000 
# number of span worker threads
collector.receiver.stat.grpc.worker.threadSize=32
# capacity of span worker queue
collector.receiver.stat.grpc.worker.queueSize=256
# monitoring for span worker
collector.receiver.stat.grpc.worker.monitor=true
```

**Comment by zhangiicc** [comment]
[root@master classes]# getenforce 
Disabled
[root@master classes]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@node1 tomcat-collector]# telnet master 2181
Trying 10.96.188.25...
Connected to master.
Escape character is '^]'.
^]

**Comment by koo-taejin** [comment]
hi @zhangiicc 

At your log, 

```
58.210.134.158:6363
```
 connected normally and finished handshake. 

```
100.97.222.3:38045
100.97.219.130:60394
100.97.223.131:11461
```
You can see that terminate the connection as soon as  connected.
"UNEXPECTED_CLOSE_BY_CLIENT' (client disconnect connection)

I recommand to check why remote addresses shut down as soon as they connect. 
(Sometimes, only checking the statuses, such as l7, may be repeated. )

thanks.

**Comment by zhangiicc** [comment]
thanks
