### ISSUE TITLE
weave enhance occur java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by linxiaobai** [naver/pinpoint#5477]
I use ppt weave method to enchance `redis.clients.jedis.Jedis` class.

I want to mock some special redis call, I write some code like this.

```java
@Aspect
public abstract class JedisAspect {
//... other method
@JointPoint
abstract ScanResult<String> __sscan(String key, String cursor);

//not ok
@PointCut
public ScanResult<String> sscan(String key, int cursor) {
        RedisSpanEventData redisSpanEventData = takeTopRedisSpanEventDataByCommands("sscan", key, cursor);
        if (redisSpanEventData != null) {
            return SerializeUtil.jsonDeserialize(redisSpanEventData.getResult(),
                new TypeReference<ScanResult<String>>() {
                });
        } else {
            return __sscan(key, cursor);
        }
    }
``` 

I found when I deserialize object with generic type, like `ScanResult<String>`, it will occur VerifyError. But deserialize simple object will be ok.
```java
//ok
@PointCut
    public List<String> blpop(String arg) {
        RedisSpanEventData redisSpanEventData = takeTopRedisSpanEventDataByCommands("blpop", arg);
        if (redisSpanEventData != null) {
            return SerializeUtil.jsonDeserializeList(redisSpanEventData.getResult(), ArrayList.class, String.class);
        } else {
            return __blpop(arg);
        }
    }
```
**error msg**
```java
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.enniu.redis.client.EnniuJedisCommands]: Factory method 'enniuJedisCommands' threw exception; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    redis/clients/jedis/Jedis.sscan(Ljava/lang/String;I)Lredis/clients/jedis/ScanResult; @33: invokespecial
  Reason:
    Type 'redis/clients/jedis/Jedis' (current frame, stack[3]) is not assignable to 'com/enniu/nozdormu/plugin/redis/aspect/JedisAspect'
  Current Frame:
    bci: @33
    flags: { }
    locals: { 'redis/clients/jedis/Jedis', 'java/lang/String', integer, 'com/enniu/nozdormu/replay/model/RedisSpanEventData' }
    stack: { 'java/lang/String', uninitialized 28, uninitialized 28, 'redis/clients/jedis/Jedis' }
  Bytecode:
    0x0000000: 2a13 0728 2b04 bd05 bc59 031c b805 e053
    0x0000010: b705 be4e 2dc6 0016 2db6 05c1 bb07 2a59
    0x0000020: 2ab7 072d b807 31c0 0483 b02a 2b1c b607
    0x0000030: 33b0
  Stackmap Table:
    append_frame(@43,Object[#1457])

	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 51 common frames omitted
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    redis/clients/jedis/Jedis.sscan(Ljava/lang/String;I)Lredis/clients/jedis/ScanResult; @33: invokespecial
  Reason:
    Type 'redis/clients/jedis/Jedis' (current frame, stack[3]) is not assignable to 'com/enniu/nozdormu/plugin/redis/aspect/JedisAspect'
  Current Frame:
    bci: @33
    flags: { }
    locals: { 'redis/clients/jedis/Jedis', 'java/lang/String', integer, 'com/enniu/nozdormu/replay/model/RedisSpanEventData' }
    stack: { 'java/lang/String', uninitialized 28, uninitialized 28, 'redis/clients/jedis/Jedis' }
  Bytecode:
    0x0000000: 2a13 0728 2b04 bd05 bc59 031c b805 e053
    0x0000010: b705 be4e 2dc6 0016 2db6 05c1 bb07 2a59
    0x0000020: 2ab7 072d b807 31c0 0483 b02a 2b1c b607
    0x0000030: 33b0
  Stackmap Table:
    append_frame(@43,Object[#1457])

	at redis.clients.jedis.JedisClusterConnectionHandler.initializeSlotsCache(JedisClusterConnectionHandler.java:34)
	at redis.clients.jedis.JedisClusterConnectionHandler.<init>(JedisClusterConnectionHandler.java:17)
	at redis.clients.jedis.JedisSlotBasedConnectionHandler.<init>(JedisSlotBasedConnectionHandler.java:24)
	at redis.clients.jedis.BinaryJedisCluster.<init>(BinaryJedisCluster.java:48)
	at redis.clients.jedis.JedisCluster.<init>(JedisCluster.java:88)
	at com.enniu.redis.client.JedisUtil.genJedisCluster(JedisUtil.java:55)
	at com.enniu.redis.client.JedisUtil.genJedisCommands(JedisUtil.java:111)
	at com.enniu.redis.client.EnniuJedisCommands$Inner.gen(EnniuJedisCommands.java:1949)
	at com.enniu.redis.client.EnniuJedisCommands$Inner.gen(EnniuJedisCommands.java:1940)
	at com.enniu.redis.client.proxy.AbChangeAbleSource.changeConfig(AbChangeAbleSource.java:124)
	at com.enniu.redis.client.proxy.AbChangeAbleSource$1.notify(AbChangeAbleSource.java:87)
	at com.enniu.middleware.common.config.ConfigManager.init(ConfigManager.java:66)
	at com.enniu.redis.client.proxy.AbChangeAbleSource.init(AbChangeAbleSource.java:66)
	at com.enniu.redis.client.EnniuJedisCommands.init(EnniuJedisCommands.java:74)
	at com.enniu.redis.client.spring.EnniuRedisAutoConfiguration.enniuJedisCommands(EnniuRedisAutoConfiguration.java:38)
	at com.enniu.redis.client.spring.EnniuRedisAutoConfiguration$$EnhancerBySpringCGLIB$$4ee3ec43.CGLIB$enniuJedisCommands$0(<generated>)
	at com.enniu.redis.client.spring.EnniuRedisAutoConfiguration$$EnhancerBySpringCGLIB$$4ee3ec43$$FastClassBySpringCGLIB$$a1886df3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.enniu.redis.client.spring.EnniuRedisAutoConfiguration$$EnhancerBySpringCGLIB$$4ee3ec43.enniuJedisCommands(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 52 common frames omitted

```

there is my deserialize code
```java
public static <T> T jsonDeserialize(String jsonString, TypeReference<T> typeReference) {
        if (StringUtils.isEmpty(jsonString)) {
            return null;
        }

        try {
            return objectMapper.readValue(jsonString, typeReference);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }

public static <T> List<T> jsonDeserializeList(String jsonString, Class<? extends List> collectionClass, Class<T>
        elementClass) {

        try {
            JavaType javaType = objectMapper.getTypeFactory().constructParametricType(collectionClass, elementClass);
            return objectMapper.readValue(jsonString, javaType);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
```

Can someone help me? thanks!

**Comment by linxiaobai** [comment]
```java
public List<String> blpop(String arg) {
    RedisSpanEventData redisSpanEventData = this.takeTopRedisSpanEventDataByCommands("blpop", arg);
    return redisSpanEventData != null ? SerializeUtil.jsonDeserializeList(redisSpanEventData.getResult(), ArrayList.class, String.class) : this.__blpop_$$pinpoint(arg);
}


private ScanResult<String> __sscan_$$pinpoint(String key, int cursor) {
    return this.sscan(key, cursor, new ScanParams());
}

public ScanResult<String> sscan(String key, int cursor) {
    RedisSpanEventData redisSpanEventData = this.takeTopRedisSpanEventDataByCommands("sscan", key, cursor);
    return redisSpanEventData != null ? (ScanResult)SerializeUtil.jsonDeserialize(redisSpanEventData.getResult(), ScanResult.class) : this.__sscan_$$pinpoint(key, cursor);
}

```

maybe it's related the generics are erased?

**Comment by linxiaobai** [comment]
I change the deserializa and fix it.
```java
public static <T> T jsonDeserialize(String jsonString, Class<T> beanClass, Class<?> genericClass) {
        if (StringUtils.isEmpty(jsonString)) {
            return null;
        }
        JavaType type = objectMapper.getTypeFactory().constructParametricType(beanClass, genericClass);
        try {
            return objectMapper.readValue(jsonString, type);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }
```

```java
  public ScanResult<String> sscan(String key, int cursor) {
        RedisSpanEventData redisSpanEventData = this.takeTopRedisSpanEventDataByCommands("sscan", key, cursor);
        return redisSpanEventData != null ? (ScanResult)SerializeUtil.jsonDeserialize(redisSpanEventData.getResult(), ScanResult.class, String.class) : this.__sscan_$$pinpoint(key, cursor);
    }

    public ScanResult<String> sscan(String key, String cursor) {
        return this.sscan(key, cursor, new ScanParams());
    }

```
