### ISSUE TITLE
getting connectivity issues between agent and pinpoint-collector -Connection refused: /127.0.0.1:9994

### ISSUE THREAD

**Issue by asahu4** [naver/pinpoint#5564]
Environment :-
java 8
Pinpoint 1.8.3
deploying all the 3 components in same server (Ubuntu)

getting connectivity issues between agent and pinpoint-collector
============================================

Tomcat  Log
===========================

1.2019-05-06 18:31:26 [WARN ](c.n.p.r.s.DefaultPinpointServer    ) DefaultPinpointServer@4d8b1026 sendClosePacket() write fail. channel:[id: 0x71adf292, /127.0.0.1:47868 :> /127.0.0.1:65535] Caused:null
java.nio.channels.ClosedChannelException
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-05-06 18:31:31 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@556d0826 exceptionCaught() occurred. state:NONE. Caused:Connection refused: /127.0.0.1:9994
java.net.ConnectException: Connection refused: /127.0.0.1:9994
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

019-05-06 18:31:33 [WARN ](c.n.p.p.AgentInfoSender            ) request failed.
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
	at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.newReconnectException(ReconnectStateClientHandler.java:84)
	at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.reconnectFailureFuture(ReconnectStateClientHandler.java:70)
	at com.navercorp.pinpoint.rpc.client.ReconnectStateClientHandler.request(ReconnectStateClientHandler.java:89)
	at com.navercorp.pinpoint.rpc.client.DefaultPinpointClient.request(DefaultPinpointClient.java:123)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:344)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:230)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:208)
	at com.navercorp.pinpoint.profiler.sender.TcpDataSender$1.execute(TcpDataSender.java:108)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:166)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
	at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
	at java.lang.Thread.run(Thread.java:748)
06-May-2019 18:31:33.868 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
06-May-2019 18:31:33.870 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
2019-05-06 18:31:33 [WARN ](c.n.p.p.AgentInfoSender            ) request failed.
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...

Agent Log
===============================
2019-05-06 18:31:26 [WARN ](o.j.n.c.SimpleChannelHandler       ) EXCEPTION, please implement com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor$PinpointServerChannelHandler.exceptionCaught() for proper handling.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-05-06 18:31:31 [WARN ](.p.r.c.DefaultPinpointClientHandler) DefaultPinpointClientHandler@556d0826 exceptionCaught() occurred. state:NONE. Caused:Connection refused: /127.0.0.1:9994
java.net.ConnectException: Connection refused: /127.0.0.1:9994
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
201

**Comment by koo-taejin** [comment]
hi @asahu4 

It is strange that the Collector log attempts to connect to the 9994 port. 
It is recommended that you check the overall setup or environment again.
If  agent is attached to a collector module, this is not supported.

thanks.
