### ISSUE TITLE
Application Inspector can not use in1.8.3  bug??

### ISSUE THREAD

**Issue by hu0514** [naver/pinpoint#5602]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran '...' with agent attached
2. '...' method invoked
3. '...' interceptor threw '...' exception

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by hu0514** [comment]
docker-compose  1.8.3 can not show Application Inspector page

**Comment by hu0514** [comment]
docker-compose  1.8.3 can not show Application Inspector page

**Comment by RoySRose** [comment]
@hu0514 
Have you set Flink modules as instructed in the pinpoint-docker guide?

**Comment by hu0514** [comment]
@RoySRose Yes, but the package I uploaded with flink is version 1.7.2. I can't build 1.8.3 successfully. Can you upload a 1.8.3 jar?

**Comment by hu0514** [comment]
@RoySRose  the pinpoint-flink-taskmanager container log
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:29539, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:12652, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:30819, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:27445, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:24948, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:31087, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:27447, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:28941, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]
2019-05-15 01:59:35,052 ERROR com.navercorp.pinpoint.rpc.codec.ServerPacketDecoder          - invalid packetType received. packetType:2573, channel:[id: 0xc01546e9, /140.206.62.214:61241 :> /172.19.0.8:19994]

**Comment by RoySRose** [comment]
@hu0514 

I have added the recent versions of the flink-job. Please check.

**Comment by hu0514** [comment]
@RoySRose 
Have you tested it yourself? I used your 1.8.3 package to report the following error (in the case of submit)
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:545)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:419)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:80)
	at org.apache.flink.client.program.ClusterClient.getOptimizedPlan(ClusterClient.java:318)
	at org.apache.flink.runtime.webmonitor.handlers.JarActionHandler.getJobGraphAndClassLoader(JarActionHandler.java:72)
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.handleJsonRequest(JarRunHandler.java:61)
	at org.apache.flink.runtime.webmonitor.handlers.AbstractJsonRequestHandler.handleRequest(AbstractJsonRequestHandler.java:41)

**Comment by hu0514** [comment]
My method of operation:
1, docker-compose pull
2, docker-compose up -d
3, submint the jar in flink

**Comment by hu0514** [comment]
@RoySRose

**Comment by RoySRose** [comment]
@hu0514 

Sorry about the jar file. It shouldn't have been uploaded.
You need to build with the environment set up as [guided](http://naver.github.io/pinpoint/applicationinspector.html#3-configuration)
and try.

**Comment by hu0514** [comment]
@RoySRose   I only need to build the flink-job.jar package? Then use the existing docker?

**Comment by hu0514** [comment]
Finished, thank you

**Comment by RoySRose** [comment]
@hu0514 

Good for you :)
