### ISSUE TITLE
pinpoint-agent-1.7.2 does not work with OpenJDK on FreeBSD

### ISSUE THREAD

**Issue by chuanyi-fang** [naver/pinpoint#5626]
**pinpoint-agent does not work with OpenJDK 7 and FreeBSD 8.2。**
**Logs Follows**

2019-05-23 11:14:28 [WARN ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint start failed.
com.navercorp.pinpoint.bootstrap.BootStrapException: execute fail. Error:null
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:52)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader.boot(AgentClassLoader.java:73)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:125)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.navercorp.pinpoint.bootstrap.AgentClassLoader$2.call(AgentClassLoader.java:78)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:42)
        ... 9 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.UnsatisfiedLinkError: com.sun.management.UnixOperatingSystem.getProcessCpuLoad()D
  at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:63)
  while locating com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor
  at com.navercorp.pinpoint.profiler.context.module.ApplicationContextModule.configure(ApplicationContextModule.java:258)
  while locating com.navercorp.pinpoint.profiler.monitor.AgentStatMonitor

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:102)
        at com.navercorp.pinpoint.profiler.context.module.DefaultApplicationContext.<init>(DefaultApplicationContext.java:86)
        at com.navercorp.pinpoint.profiler.DefaultAgent.newApplicationContext(DefaultAgent.java:125)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:118)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<init>(DefaultAgent.java:69)
        ... 15 more
Caused by: java.lang.UnsatisfiedLinkError: com.sun.management.UnixOperatingSystem.getProcessCpuLoad()D
        at com.sun.management.UnixOperatingSystem.getProcessCpuLoad(Native Method)
        at com.navercorp.pinpoint.profiler.monitor.metric.cpu.oracle.DefaultCpuLoadMetric.getSnapshot(DefaultCpuLoadMetric.java:40)
        at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:40)
        at com.navercorp.pinpoint.profiler.monitor.collector.cpu.DefaultCpuLoadMetricCollector.collect(DefaultCpuLoadMetricCollector.java:26)
        at com.navercorp.pinpoint.profiler.monitor.collector.AgentStatCollector.collect(AgentStatCollector.java:99)
        at com.navercorp.pinpoint.profiler.monitor.collector.AgentStatCollector.collect(AgentStatCollector.java:34)
        at com.navercorp.pinpoint.profiler.monitor.CollectJob.run(CollectJob.java:67)
        at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.preLoadClass(DefaultAgentStatMonitor.java:104)
        at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:91)
        at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor.<init>(DefaultAgentStatMonitor.java:63)
        at com.navercorp.pinpoint.profiler.monitor.DefaultAgentStatMonitor$$FastClassByGuice$$1e15b61b.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        ... 23 more

*****************************************************************************
* Pinpoint Agent load failure
*****************************************************************************

**Comment by Xylus** [comment]
Hi @chuanyi-fang 
Thanks for reporting.
It looks like the build of FreeBSD openjdk build you're using doesn't have `com.sun.management.UnixOperatingSystem.getProcessCpuLoad()` implemented.

From searching the net, it seems like FreeBSD openjdk `1.8.0_112` has this fixed.
Do you think you could try this out on `1.8.0_112`?
