### ISSUE TITLE
 I am going to install pinpoint1.8.3, pinpoint-c-agent. Can this be used?

### ISSUE THREAD

**Issue by lianfulei** [naver/pinpoint#5653]

**Comment by RoySRose** [comment]
yes

**Comment by lianfulei** [comment]
2019-06-05 12:57:02 [WARN ](c.n.p.c.r.t.DefaultTCPPacketHandler) Unexpected error. remote:/192.168.1.6:44082 cause:Response fail. Error: Illegal State. pinpointServer:DefaultPinpointServer@b8fb70(remote:/192.168.1.6:44082, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT)
java.lang.IllegalStateException: Response fail. Error: Illegal State. pinpointServer:DefaultPinpointServer@b8fb70(remote:/192.168.1.6:44082, state:UNEXPECTED_CLOSE_BY_CLIENT, healthCheckState:WAIT)
	at com.navercorp.pinpoint.rpc.server.DefaultPinpointServer.response(DefaultPinpointServer.java:219)
	at com.navercorp.pinpoint.collector.receiver.tcp.TCPServerResponse.write(TCPServerResponse.java:61)
	at com.navercorp.pinpoint.collector.receiver.tcp.TCPServerResponse.write(TCPServerResponse.java:34)
	at com.navercorp.pinpoint.collector.handler.ApiMetaDataHandler.handleRequest(ApiMetaDataHandler.java:46)
	at com.navercorp.pinpoint.collector.receiver.TcpDispatchHandler.dispatchRequestMessage(TcpDispatchHandler.java:94)
	at com.navercorp.pinpoint.collector.receiver.DelegateDispatchHandler.dispatchRequestMessage(DelegateDispatchHandler.java:72)
	at com.navercorp.pinpoint.collector.receiver.tcp.DefaultTCPPacketHandler.handleRequest(DefaultTCPPacketHandler.java:106)
	at com.navercorp.pinpoint.collector.receiver.tcp.AgentBaseDataReceiverServerMessageListenerFactory$AgentBaseDataReceiverServerMessageListener$2.run(AgentBaseDataReceiverServerMessageListenerFactory.java:114)
	at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lianfulei** [comment]
这个算是错误吗？怎么解决
