### ISSUE TITLE
Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by carlgan** [naver/pinpoint#5673]
#### Prerequisites
windows 7 64bit 
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/

#### Describe your problem**
run command:   mvnw install -Dmaven.test.skip=true

Found "E:\pinpoint-master-win\.mvn\wrapper\maven-wrapper.jar"
Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)
        at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:64)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)

**Comment by koo-taejin** [comment]
Set your JAVA OPT to '-Dhttps.protocols=TLSv1.2' and try again.

**Comment by carlgan** [comment]
Thx, koo.
 I fix it with  JDK 1.8

**Comment by benamormed98** [comment]
the link of the jdk 1.8 please

**Comment by hadnet** [comment]
Link for jdk 1.8 https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html

**Comment by Sociopath-inc** [comment]
thx!it worked
