### ISSUE TITLE
pinpoint agent got a NotserializableException

### ISSUE THREAD

**Issue by ryanli870929** [naver/pinpoint#5846]
my agent version is v1.8.2。java version is 1.8。mosts of time the agent run in the right way。but when my project got an error，the agent thrown an excepton like this：
java.io.NotSerializableException: com.navercorp.pinpoint.profiler.context.DefaultAsyncContext
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at com.stnts.core.utils.ObjectUtils.serialize(ObjectUtils.java:61)

how can i fix this? 
ths

**Comment by emeroad** [comment]
This is a bug in the pinpoint.
When using Java Serialization, the fields that are added dynamically by the pinpoint must not be serialized.

the pinpoint uses the transient property when adding dynamic fields.

**Comment by emeroad** [comment]
@ryanli870929 
Hi~
The problem was resolved at #5851
