### ISSUE TITLE
The pinpoint-1.9.0-SNAPSHOT always  deadlock；

### ISSUE THREAD

**Issue by jiamine** [naver/pinpoint#5859]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

Hello，My pinpoint can send mail to my mailserver,But there is always such on error in log: 
2019-08-12 16:27:01 [INFO ](c.n.p.w.a.c.ResponseCountChecker   ) ResponseCountChecker result is false for application (sx). value is 0. (threshold : 30).
2019-08-12 16:27:01 [INFO ](o.s.b.c.l.s.SimpleJobLauncher      ) Job: [FlowJob: [name=alarmJob]] completed with the following parameters: [{schedule.date=1565598420000}] and the following status: [COMPLETED]
2019-08-12 16:30:00 [ERROR](s.s.s.TaskUtils$LoggingErrorHandler) Unexpected error occurred in scheduled task.
java.lang.IllegalStateException: org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:51)
        at com.navercorp.pinpoint.web.batch.BatchJobLauncher.flinkCheckJob(BatchJobLauncher.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.DeadlockLoserDataAccessException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:262)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:876)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:937)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:942)
        at org.springframework.batch.core.repository.dao.JdbcJobInstanceDao.createJobInstance(JdbcJobInstanceDao.java:115)
        at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:172)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy54.createJobExecution(Unknown Source)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:125)
        at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:49)
        ... 15 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:883)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:876)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639)
        ... 37 more

The issue has troubled me for a long time，no similar problem was found on the github,too。
applicationContext-batch-schedule.xml configured:
...........................................................................................
        <task:scheduled-tasks scheduler="scheduler">
        <task:scheduled ref="batchJobLauncher" method="alarmJob" cron="0 0/3 * * * *" />
        <task:scheduled ref="batchJobLauncher" method="agentCountJob" cron="0 0 2 * * *" />
                <task:scheduled ref="batchJobLauncher" method="flinkCheckJob" cron="0 0/10 * * * *" />
        </task:scheduled-tasks>
        <step id="alarmStep" xmlns="http://www.springframework.org/schema/batch">
            <tasklet task-executor="poolTaskExecutorForStep" throttle-limit="3">
                 <chunk reader="reader" processor="processor" writer="writer" commit-interval="1"/>
            </tasklet>
        </step>
        <task:scheduler id="scheduler" pool-size="10"/>
    
    <import resource="classpath:batch/applicationContext-batch.xml" />
    <import resource="classpath:batch/applicationContext-alarmJob.xml" />
    <import resource="classpath:batch/applicationContext-agentCountJob.xml" />
        <import resource="classpath:batch/applicationContext-flinkCheckJob.xml" />
................................................................................................
What should I do about all gods。。。。

**Comment by minwoo-jung** [comment]
@jiaxinmine

This issue is a job repsitory of spring batch issue. 
ex ) https://stackoverflow.com/questions/33630208/deadlock-when-creating-job-instances
https://jira.spring.io/browse/BATCH-2147

Did you modify the pool-size 1->10?

Recommend some things, first modify the value of isolationLevel, 
It is also recommended to modify other options related to tansaction.


I know a way to never cause deadlock problems.
If you use the db used in jobrepository as h2db with mvcc mode, no problem occurs.

**Comment by jiaxinmine** [comment]
> @jiaxinmine
> 
> This issue is a job repsitory of spring batch issue.
> ex ) https://stackoverflow.com/questions/33630208/deadlock-when-creating-job-instances
> https://jira.spring.io/browse/BATCH-2147
> 
> Did you modify the pool-size 1->10? Why did you modify pool size?
> We don't recommend edit pool-size.
> 
> Recommend some things, first modify the value of isolationLevel,
> It is also recommended to modify other options related to tansaction.
> 
> I know a way to never cause deadlock problems.
> If you use the db used in jobrepository as h2db with mvcc mode, no problem occurs.
> 
> Please edit your options and share them if you do not encounter any issues. It will be very helpful to others.

First,thank you very much for your reply!
I modify the pool-size 1->10， also because tomcat outputs the deadlock error.Just try to modify the pool-size value to see if it solves the problem.
The result is obviously not！！！！！！
"If you use the db used in jobrepository as h2db with mvcc mode, no problem occurs."
Sorry,I can't understand what your mean by this sentence.

**Comment by minwoo-jung** [comment]
@jiaxinmine
This problem is caused by multiple batches running at the same time.
Are you running multiple pinpoint-web servers?
The batch must be run on one instance(process).

**Comment by jiaxinmine** [comment]
> @jiaxinmine
> This problem is caused by multiple batches running at the same time.
> Are you running multiple pinpoint-web servers?
> The batch must be run on one instance(process).

oh!yes, that's true! I shut down other instances, and then run it for a while to observe. @minwoo-jung ,thank you very much!

**Comment by minwoo-jung** [comment]
@jiaxinmine
Congratulations^^ I'm so glad to work.

**Comment by jiaxinmine** [comment]
Thanks agin!!!
