### ISSUE TITLE
DubboConsumerIT raise NullPointerException

### ISSUE THREAD

**Issue by tankilo** [naver/pinpoint#5891]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master
#### Describe the bug
DubboConsumerIT rasie NullPointerException ,though the test pass.

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran `com.navercorp.pinpoint.plugin.dubbo.consumer.DubboConsumerIT`
2. `com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboConsumerInterceptor.getHostAddress` method invoked
3. DubboConsumerInterceptor threw NullPointerException exception
```
java.lang.NullPointerException
	at com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboConsumerInterceptor.getHostAddress(DubboConsumerInterceptor.java:77)
	at com.navercorp.pinpoint.plugin.dubbo.interceptor.DubboConsumerInterceptor.before(DubboConsumerInterceptor.java:69)
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.before(ExceptionHandleAroundInterceptor.java:40)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java)
	at com.navercorp.pinpoint.plugin.dubbo.consumer.DubboConsumerIT.testConsumer(DubboConsumerIT.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.navercorp.pinpoint.test.plugin.ForkedPinpointPluginTestRunner$1.evaluate(ForkedPinpointPluginTestRunner.java:63)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.navercorp.pinpoint.test.plugin.shared.SharedPinpointPluginTest$1.run(SharedPinpointPluginTest.java:176)
	at java.lang.Thread.run(Thread.java:748)
```

#### Expected behavior
NullPointerException  should not be thrown

#### Screenshots
![image](https://user-images.githubusercontent.com/10413284/63251380-2dc5bb80-c2a0-11e9-8aa4-3f8f9717798d.png)

**Comment by emeroad** [comment]
Thank you for your contribution

Would you backport this patch to 1.8.x branch?

**Comment by emeroad** [comment]
#5879
