### ISSUE TITLE
Can i add interceptor to the method inherited from superclasses?

### ISSUE THREAD

**Issue by tankilo** [naver/pinpoint#5919]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

```
public class MyResult extends CompletableFuture<Result>
```

```
transformTemplate.transform("com.tankilo.MyResult", new MyResultTransform());
```
```
// MyResult.java
InstrumentMethod complete = target.getDeclaredMethod("complete", "com.tankilo.Result");
```
When i debug the code, variable `complete` will be null,  this is because `getDeclaredMethod` has the same behaviour as `java.lang.Class.getDeclaredMethods() `, so  inherited methods is excluded.

`MyResult` is a shared variable between two threads, the result of an async opertaion.   
When `MyResult#complete` is called, i want to enhance this method with `AsyncContextSpanEventSimpleAroundInterceptor` and get the final result of the async opertaion.

So can i add interceptor to the method inherited from superclasses?

**Comment by tankilo** [comment]
I try to override method `complte` in `MyResult`
```
target.addDelegatorMethod("complete", "com.tankilo.Result");
```
Exception raised, this is because `com.navercorp.pinpoint.bootstrap.instrument.InstrumentClass#addDelegatorMethod` only check the closest superclass of `MyResult` (`AbstractResult`), but doesn't check the superclass of `AbstractResult` (`CompletableFuture`)

**Comment by emeroad** [comment]
`addDelegatorMethod` is limited to searching only 1depth parent.

We must add a multi-depth search API.

## example
```java
@Override
public InstrumentMethod addDelegatorMethod(int searchDepth, final String methodName, final String... paramTypes) throws InstrumentException {
   ... 
}
````

## pinpoint api
https://github.com/naver/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/instrument/ASMClass.java#L222

```java
@Override
    public InstrumentMethod addDelegatorMethod(final String methodName, final String... paramTypes) throws InstrumentException {
        // check duplicated method.
        if (getDeclaredMethod(methodName, paramTypes) != null) {
            throw new InstrumentException(getName() + " already have method(" + methodName + ").");
        }
//---------------------------------------------        
// Recursive search for super class
        final ASMClassNodeAdapter superClassNode = ASMClassNodeAdapter.get(this.pluginContext, classNode.getClassLoader(), classNode.getProtectionDomain(), this.classNode.getSuperClassInternalName());
        if (superClassNode == null) {
            throw new NotFoundInstrumentException(getName() + " not found super class(" + this.classNode.getSuperClassInternalName() + ")");
        }

        final String desc = JavaAssistUtils.javaTypeToJvmSignature(paramTypes);
        final ASMMethodNodeAdapter superMethodNode = superClassNode.getDeclaredMethod(methodName, desc);
        if (superMethodNode == null) {
            throw new NotFoundInstrumentException(methodName + desc + " is not found in " + superClassNode.getInternalName());
        }
//---------------------------------------------
        final ASMMethodNodeAdapter methodNode = this.classNode.addDelegatorMethod(superMethodNode);
        setModified(true);
        return new ASMMethod(this.engineComponent, this.pluginContext, this, methodNode);
    }
```
Contribution is welcome

**Comment by tankilo** [comment]
There is still an extra problem , In fact, I've made an ugly modification locally for test purpose.

![image](https://user-images.githubusercontent.com/10413284/63753661-1745e280-c8e6-11e9-8819-25451106fbcf.png)
With
```
target.addDelegatorMethod("complete", "java.lang.Object");
```
I output the generated class to the file, and find the generated method
```
public boolean complete(Object java_lang_Object) {
    return super.complete(java_lang_Object);
}
```
But the correct one should be 
```
@Override
public boolean complete(Result value) {
    return super.complete(value);
}
```

With 
```
target.addDelegatorMethod("complete", "java.lang.Object");
InstrumentMethod complete = target.getDeclaredMethod("complete", "java.lang.Object");
```

```
    org.apache.dubbo.rpc.AsyncRpcResult.class

    public boolean complete(Object _$PINPOINT$_result) {
        Interceptor interceptor = InterceptorRegistry.getInterceptor(5);
        _$PINPOINT$_result = null;
        _$PINPOINT$_throwable = null;
        _$PINPOINT$_args = new Object[]{_$PINPOINT$_result};
        ((AroundInterceptor) this).before(this, _$PINPOINT$_args);
        try {
            Object java_lang_Object = new Boolean(super.complete(_$PINPOINT$_result));
            _$PINPOINT$_throwable = null;
            ((AroundInterceptor) this).after(this, _$PINPOINT$_args, java_lang_Object, _$PINPOINT$_throwable);
            return super.complete(_$PINPOINT$_result);
        } catch (Throwable _$PINPOINT$_throwable) {
            _$PINPOINT$_result = null;
            ((AroundInterceptor) this).after(this, _$PINPOINT$_args, _$PINPOINT$_result, _$PINPOINT$_throwable);
            throw _$PINPOINT$_throwable;
        }
    }
```

And I got an error when the program is running, i simplify the classname when i posted the issue.In fact, i am writing a plugin fo the apache dubbo 2.7.3 async service future.

```
Exception in thread "main" org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service org.apache.dubbo.samples.async.api.AsyncService. Tried 3 times of the providers [10.45.18.255:20880] (1/1) from the registry 127.0.0.1:2181 on the consumer 10.45.18.255 using the dubbo version 2.7.3. Last error is: Bad type on operand stack
Exception Details:
  Location:
    org/apache/dubbo/rpc/AsyncRpcResult.complete(Ljava/lang/Object;)Z @32: invokespecial
  Reason:
    Type 'com/navercorp/pinpoint/bootstrap/interceptor/Interceptor' (current frame, stack[0]) is not assignable to 'org/apache/dubbo/rpc/AsyncRpcResult'
  Current Frame:
    bci: @32
    flags: { }
    locals: { 'com/navercorp/pinpoint/bootstrap/interceptor/Interceptor', null, null, '[Ljava/lang/Object;' }
    stack: { 'com/navercorp/pinpoint/bootstrap/interceptor/Interceptor', null }
  Bytecode:
    0x0000000: 1006 b800 284b 014c 014d 04bd 0139 5903
    0x0000010: 2b53 4e2a c001 3b2a 2db9 013e 0300 2a2b
    0x0000020: b701 3f59 bb01 415a 5fb7 0144 4c01 4d2a
    0x0000030: c001 3b2a 2d2b 2cb9 0147 0500 ac4d 014c
    0x0000040: 2ac0 013b 2a2d 2b2c b901 4705 002c bf  
  Exception Handler Table:
    bci [30, 61] => handler: 61
  Stackmap Table:
    full_frame(@61,{Object[#105],Object[#321],Null,Object[#331]},{Object[#31]})

	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:248)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at org.apache.dubbo.samples.async.AsyncConsumer.main(AsyncConsumer.java:42)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/dubbo/rpc/AsyncRpcResult.complete(Ljava/lang/Object;)Z @32: invokespecial
  Reason:
    Type 'com/navercorp/pinpoint/bootstrap/interceptor/Interceptor' (current frame, stack[0]) is not assignable to 'org/apache/dubbo/rpc/AsyncRpcResult'
  Current Frame:
    bci: @32
    flags: { }
    locals: { 'com/navercorp/pinpoint/bootstrap/interceptor/Interceptor', null, null, '[Ljava/lang/Object;' }
    stack: { 'com/navercorp/pinpoint/bootstrap/interceptor/Interceptor', null }
  Bytecode:
    0x0000000: 1006 b800 284b 014c 014d 04bd 0139 5903
    0x0000010: 2b53 4e2a c001 3b2a 2db9 013e 0300 2a2b
    0x0000020: b701 3f59 bb01 415a 5fb7 0144 4c01 4d2a
    0x0000030: c001 3b2a 2d2b 2cb9 0147 0500 ac4d 014c
    0x0000040: 2ac0 013b 2a2d 2b2c b901 4705 002c bf  
  Exception Handler Table:
    bci [30, 61] => handler: 61
  Stackmap Table:
    full_frame(@61,{Object[#105],Object[#321],Null,Object[#331]},{Object[#31]})

	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:173)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:52)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.samples.async.filter.LegacyBlockFilter.invoke(LegacyBlockFilter.java:46)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.samples.async.filter.AsyncPostprocessFilter.invoke(AsyncPostprocessFilter.java:46)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
```

**Comment by tankilo** [comment]
https://github.com/apache/dubbo/blob/dubbo-2.7.3/dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java

**Comment by tankilo** [comment]
How to enhance the generic method inherited from superclass?

**Comment by emeroad** [comment]
Perhaps this problem is bridge-method issue in java generic

https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html

I don't know much about it.
I will analyze this issue more.

**Comment by tankilo** [comment]
I learned the linked article above.  And think about the following.
```
-->Recursively finding the closet class which containing the method with specified method signature.
-->If the method is found, check org.objectweb.asm.tree.MethodNode#signature.
-->-->If the signature is not null, then it maybe a method of a generic class or a generic method or the mixture of these two situations.
-->-->-->Check class's signature (org.objectweb.asm.tree.ClassNode#signature). 
-->-->-->-->If it's  null, then it's a generic method, use com.navercorp.pinpoint.profiler.instrument.ASMClassNodeAdapter#addDelegatorMethod like before.
-->-->-->-->If it's not null, then compare ClassNode#signature with  MethodNode#signature.
-->-->-->-->-->If all the type wildcards are matched, it's the method of a generic class. 
               Two methods(one of them is a bridge method) need to be added(These two new method's MethodNode#signature are null).
-->-->-->-->-->If MethodNode has more type wildcards than ClassNode, then it's a mixture of a method of a generic class and a generic method. 
               We still need to generate a bridge method, but also need to take care of another method's signature(generic method signature).
-->-->If the signature is null, use com.navercorp.pinpoint.profiler.instrument.ASMClassNodeAdapter#addDelegatorMethod like before.
```

You are all good at asm, so i just put these words as a record. If i write these things , i need a longer time.

And you may need to check this project. https://github.com/infradna/bridge-method-injector
