### ISSUE TITLE
java.lang.NoClassDefFoundError: org/asynchttpclient/cookie/Cookie

### ISSUE THREAD

**Issue by liranzel** [naver/pinpoint#5980]
#### Prerequisites

- [V] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v1.8.3

#### Describe the bug
java.lang.NoClassDefFoundError: org/asynchttpclient/cookie/Cookie exceptions when tracing requests in a Spring Boot application

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran app with agent attached
2. For some requests I can see in the log java.lang.NoClassDefFoundError: org/asynchttpclient/cookie/Cookie exceptions
at com.navercorp.pinpoint.plugin.ning.asynchttpclient.NingCookieExtractorV2.getCookie(NingCookieExtractorV2.java:43)

#### Expected behavior
No exceptions, and request stored in pinpoint server

#### Logs

2019-09-09 06:57:53 [WARN ](c.n.p.p.i.f.GuardExceptionHandler  ) Exception occurred from interceptor	
	java.lang.NoClassDefFoundError: org/asynchttpclient/cookie/Cookie
	at com.navercorp.pinpoint.plugin.ning.asynchttpclient.NingCookieExtractorV2.getCookie(NingCookieExtractorV2.java:43)	
	at com.navercorp.pinpoint.plugin.ning.asynchttpclient.NingCookieExtractorV2.getCookie(NingCookieExtractorV2.java:29)	
	at com.navercorp.pinpoint.bootstrap.plugin.request.util.DefaultCookieRecorder.recordCookie(DefaultCookieRecorder.java:57)	
	at com.navercorp.pinpoint.bootstrap.plugin.request.util.DefaultCookieRecorder.record(DefaultCookieRecorder.java:49)	 
	at com.navercorp.pinpoint.plugin.ning.asynchttpclient.interceptor.ExecuteInterceptor.after(ExecuteInterceptor.java:141)	 
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:49)
	at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:235)	
	at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:204)
	at org.zendesk.client.v2.Zendesk.submit(Zendesk.java:1893)
	at org.zendesk.client.v2.Zendesk.createUser(Zendesk.java:779)

#### Additional context
The library I'm using - com.cloudbees.thirdparty:zendesk-java-client:0.9.0 uses org.asynchttpclient:async-http-client:2.3.0 which is higher than the version pinpoint agent uses. The new version (2.3.0) doesn't contain the Cookie class anymore. This prevents pinpoint from tracking requests that use the zendesk-java-client library. A possible fix would be to upgrade the asunc-http-client library pinpoint agent uses

**Comment by emeroad** [comment]
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/cookie/CookieStore.java

Changed from `org.asynchttpclient.cookie.Cookie` to `io.netty.handler.codec.http.cookie.Cookie`
