### ISSUE TITLE
Pinpoint1.8.1 after the establishment, into the pinpoint main interface, background log error?

### ISSUE THREAD

**Issue by 11628** [naver/pinpoint#6011]
java.lang.LinkageError: loader constraint violation: when resolving interface method "com.navercorp.pinpoint.bootstrap.context.SpanEventRecorder.recordServiceType(Lcom/navercorp/pinpoint/common/trace/ServiceType;)V" the class loader (instance of org/apache/catalina/loader/ParallelWebappClassLoader) of the current class, com/navercorp/pinpoint/plugin/spring/beans/interceptor/BeanMethodInterceptor, and the class loader (instance of <bootloader>) for the method's defining class, com/navercorp/pinpoint/bootstrap/context/SpanEventRecorder, have different Class objects for the type com/navercorp/pinpoint/common/trace/ServiceType used in the signature
	at com.navercorp.pinpoint.plugin.spring.beans.interceptor.BeanMethodInterceptor.before(BeanMethodInterceptor.java:57)
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleApiIdAwareAroundInterceptor.before(ExceptionHandleApiIdAwareAroundInterceptor.java:41)
	at com.navercorp.pinpoint.web.service.CommonServiceImpl.selectAllApplicationNames(CommonServiceImpl.java)
	at com.navercorp.pinpoint.web.controller.MainController.getApplicationGroup(MainController.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.navercorp.pinpoint.web.servlet.NoCacheFilter.doFilter(NoCacheFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-09-18 08:32:56 [WARN ](c.n.p.p.i.f.GuardExceptionHandler  ) Exception occurred from interceptor

**Comment by emeroad** [comment]
Since pinpoint-web and pinpoint-agent share the class, you may encounter class conflicts when using different versions.
Please use the same version.

**Comment by 11628** [comment]
> Since pinpoint-web and pinpoint-agent share the class, you may encounter class conflicts when using different versions.
> Please use the same version.

Pinpoint -web and pinpoint-agent version are 1.8.1

**Comment by emeroad** [comment]
If you are using tomcat 8.5 or higher, you must add the following option.

context.xml
```xml
<Context>
    <Loader delegate="true"/>
</Context>
```
https://tomcat.apache.org/tomcat-8.5-doc/config/loader.html

**Comment by 11628** [comment]
> If you are using tomcat 8.5 or higher, you must add the following option.
> 
> $TOMCAT_HOME/conf/context.xml
> 
> ```
> <Context>
>     <Loader delegate="true"/>
> </Context>
> ```
> 
> https://tomcat.apache.org/tomcat-8.5-doc/config/loader.html

Thank you very much. Just configure it @emeroad

**Comment by emeroad** [comment]
@11628 Good!

same issue : #5281
