### ISSUE TITLE
pinpoint PlainClassLoaderHandler  Failed to load plugin class

### ISSUE THREAD

**Issue by zengfr** [naver/pinpoint#6019]
2019-09-22 12:43:55 INFO Found plugins:D:\pinpoint\pinpoint-agent-1.8.5\plugin\pinpoint-log-plugin-1.0-SNAPSHOT.jar
........................................
2019-09-22 12:44:04 [WARN ](c.n.p.p.i.c.PlainClassLoaderHandler) Failed to load plugin class com.github.zengfr.conuniframework.pinpoint.plugin.log.interceptor.LogInterceptor with classLoader jdk.internal.loader.ClassLoaders$AppClassLoader@2437c6dc
java.lang.RuntimeException: com.github.zengfr.conuniframework.pinpoint.plugin.log.interceptor.LogInterceptor
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.loadClass(PlainClassLoaderHandler.java:206)

**Comment by zengfr** [comment]
2019-09-22 12:44:04 [WARN ](c.n.p.p.i.c.PlainClassLoaderHandler) Failed to load plugin class com.github.zengfr.conuniframework.pinpoint.plugin.log.interceptor.LogInterceptor with classLoader jdk.internal.loader.ClassLoaders$AppClassLoader@2437c6dc
java.lang.RuntimeException: com.github.zengfr.conuniframework.pinpoint.plugin.log.interceptor.LogInterceptor
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.loadClass(PlainClassLoaderHandler.java:206)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.PlainClassLoaderHandler.injectClass(PlainClassLoaderHandler.java:79)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JarProfilerPluginClassInjector.injectClass(JarProfilerPluginClassInjector.java:59)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.plugin.PluginInstrumentContext.injectClass(PluginInstrumentContext.java:164)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:72)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.getInterceptor(AnnotatedInterceptorFactory.java:106)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.ASMMethod.createInterceptor(ASMMethod.java:220)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:209)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.ASMMethod.addScopedInterceptor(ASMMethod.java:122)
	at com.github.zengfr.conuniframework.pinpoint.plugin.log.LogPlugin.addScopedInterceptor(LogPlugin.java:63)
	at com.github.zengfr.conuniframework.pinpoint.plugin.log.LogPlugin.access$000(LogPlugin.java:19)
	at com.github.zengfr.conuniframework.pinpoint.plugin.log.LogPlugin$1.doInTransform(LogPlugin.java:51)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerGuardDelegate.transform(MatchableClassFileTransformerGuardDelegate.java:75)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.javamodule.ClassFileTransformerModuleHandler.transform(ClassFileTransformerModuleHandler.java:61)
	at com.navercorp.pinpoint.bootstrap.java9.module.ClassFileTransformerModuleWrap.transform(ClassFileTransformerModuleWrap.java:46)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at ch.qos.logback.classic.LoggerContext.<init>(LoggerContext.java:79)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:59)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:50)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.github.zengfr.conuniframework.spring.eventbus.EventBusTest.<clinit>(EventBusTest.java:10)

**Comment by koo-taejin** [comment]
hi @zengfr 

Please post description more detail and method of reproducing it.
It is difficult to analyze the problem just because you posted it.

thanks.
