### ISSUE TITLE
elasticsearch bboss test failure

### ISSUE THREAD

**Issue by RoySRose** [naver/pinpoint#6048]
Hello, @yin-bp 

I've noticed that bboss plugin integration tests are failing in our daily routine test.

Do you mind checking `ElasticsearchExecutorIT.java` out?

**Comment by yin-bp** [comment]
Ok, let me look at this problem and solve it

**Comment by RoySRose** [comment]
attaching log, which may help you better
```
Error Message
java.lang.AssertionError: Cannot find apiId of [org.frameworkset.elasticsearch.client.ConfigRestClientUtil.createIndiceMapping(java.lang.String, java.lang.String)]
Stacktrace
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: Cannot find apiId of [org.frameworkset.elasticsearch.client.ConfigRestClientUtil.createIndiceMapping(java.lang.String, java.lang.String)]
	at com.navercorp.pinpoint.plugin.elasticsearchbboss.ElasticsearchExecutorIT.indiceCreate(ElasticsearchExecutorIT.java:116)
	at com.navercorp.pinpoint.plugin.elasticsearchbboss.ElasticsearchExecutorIT.testClientInterface(ElasticsearchExecutorIT.java:101)
```

**Comment by yin-bp** [comment]
Hi,@RoySRose :
This problem is caused by not enabling ElasticsearchBboss plugin, can enable the plugin in pinpoint.config:
profiler.elasticsearchbboss.enabled=true
