### ISSUE TITLE
Stop Pinpoint logging in catalina.out

### ISSUE THREAD

**Issue by amangupta0297** [naver/pinpoint#6089]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v1.7.3/v1.7.2 etc.

#### Describe your problem**
A clear and concise description of what is not working.

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Launched '...' with agent
2. Tried tracing '...' (see agent log below)
3. Collector outputs trace log (see collector log below)
4. No trace shows up in the web UI (see web log below)

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the part where you have encountered the problem. In case of agents, including the start-up log may be of great help.

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by amangupta0297** [comment]
Hi Team,

I want to stop pinpoint logging into catalina.out.
How to do that?
and If i want only ERROR logs, instead of WARN in catalina.out
by changing file pinpoint-agent/lib/log4j.xml, replacing WARN with ERROR will work?
if not, then how to do that.

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

<appender name="console" class="org.apache.log4j.ConsoleAppender">
    <param name="Threshold" value="WARN"/>
Log's in catalina.out

2019-10-12 09:32:34 WARN Pinpoint-UdpSpanDataExecutor(8-0) doExecute(). Unexpected Error. Cause:Buffer size cannot exceed 65507. (now:40121, input-size:39822
com.navercorp.pinpoint.thrift.io.BufferOverflowException: Buffer size cannot exceed 65507. (now:40121, input-size:39822
at com.navercorp.pinpoint.thrift.io.UnsafeByteArrayOutputStream.write(UnsafeByteArrayOutputStream.java:99)
at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
at org.apache.thrift.protocol.TCompactProtocol.writeBinary(TCompactProtocol.java:380)
at org.apache.thrift.protocol.TCompactProtocol.writeString(TCompactProtocol.java:364)
at com.navercorp.pinpoint.thrift.dto.TIntStringStringValue$TIntStringStringValueStandardScheme.write(TIntStringStringValue.java:503)
at com.navercorp.pinpoint.thrift.dto.TIntStringStringValue$TIntStringStringValueStandardScheme.write(TIntStringStringValue.java:448)
at com.navercorp.pinpoint.thrift.dto.TIntStringStringValue.write(TIntStringStringValue.java:384)
at com.navercorp.pinpoint.thrift.dto.TAnnotationValue.standardSchemeWriteValue(TAnnotationValue.java:503)
at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:244)
at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:213)

**Comment by amangupta0297** [comment]
Hi Team,

Any update?

Thanks in advance.

**Comment by koo-taejin** [comment]
hi @amangupta0297 

This exception is caused by span message that exceeded the maximum amount of packets udp could send.

If you have a lot of these packets, you can't solve them with the udp type.

If you want to solve this issue. then do follow things. 
1. Use TCP port  to accept SPAN data from the collector.
(This setting is located in the Collector Module under pincpoint-collector.properties.)

2. Change the transport type of the spandatasender to TCP in the agent's settings.
(This setting is located in the agent module under pinpoint.config.)

thanks.

**Comment by amangupta0297** [comment]
hi @koo-taejin 
Could you please specify the exact key:value to be modified for both files (pincpoint-collector.properties and pinpoint.config)
