### ISSUE TITLE
pinpoint agent1.8+ match weblogic11g(10.3.6) on aix6.1 start failed

### ISSUE THREAD

**Issue by ccdxwh** [naver/pinpoint#6101]
#### What version of pinpoint are you using?
pinpoint version:master:1.8.1/1.8.4

#### Describe the bug
pinpoint agent1.8+ match weblogic11g(10.3.6) on aix6.1 start failed

command parameter: 
export  JAVA_OPTIONS="-javaagent:/ppagent/pinpoint-agent/pinpoint-bootstrap-1.8.4.jar -Dpinpoint.applicationName=Admin13210 -Dpinpoint.agentId=Admin2  -Dpinpoint.container=true  ${JAVA_OPTIONS}"

#### logs
2019-10-18 15:04:14 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
        at java.lang.reflect.Method.invoke(Method.java:611)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider weblogic.xml.jaxp.RegistryDocumentBuilderFactory not found
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:849)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:773)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
        at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:66)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:112)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:100)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:46)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:35)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:63)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:56)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:39)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:527)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:58)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:53)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:128)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:82)
        ... 6 more

**Comment by emeroad** [comment]
```
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider weblogic.xml.jaxp.RegistryDocumentBuilderFactory not found
```
There is no weblogic-jaxp parser in weblogic.
Check `-Djavax.xml.parsers.DocumentBuilderFactory` SystemProperty of the weblogic.

**Comment by ccdxwh** [comment]
I have set the Property.
but it's doesn't work
  -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
do you have any suggestion?

**Comment by emeroad** [comment]
Could you show me error-log?

**Comment by ccdxwh** [comment]
my test_env JDK info:
 JDK：
 java version "1.6.0"
Java(TM) SE Runtime Environment (build pap6460sr16fp26-20160508_01(SR16 FP26))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 AIX ppc64-64 jvmap6460sr16fp25-20160413_299433 (JIT enabled, AOT enabled)
J9VM - 20160413_299433
JIT  - r9_20160328_114196
GC   - GA24_Java6_SR16_20160413_1159_B299433)
JCL  - 20160507_01
 
 
 ###pinpoint agent info
 export  JAVA_OPTIONS="-javaagent:/weblog1036/ppagent/pinpoint-agent-zag-RC1/pinpoint-bootstrap-1.8.1-RC1.jar -Dpinpoint.applicationName=Admin13210 -Dpinpoint.agentId=Adm
in2  -Dpinpoint.container=true    -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAX
ParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl   ${JAVA_OPTIONS}"


#error log
2019-10-24 16:16:52 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
 "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
        at java.lang.reflect.Method.invoke(Method.java:611)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl not found
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:849)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:773)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
        at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:66)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:112)
        at com.navercorp.pinpoint.rpc.server.PinpointServerAcceptor.<init>(PinpointServerAcceptor.java:100)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:46)
        at com.navercorp.pinpoint.rpc.ClassPreLoader.preload(ClassPreLoader.java:35)
        at com.navercorp.pinpoint.profiler.DefaultAgent.<clinit>(DefaultAgent.java:63)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:199)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:56)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:39)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:527)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader$1.call(AgentBootLoader.java:58)
        at com.navercorp.pinpoint.bootstrap.ContextClassLoaderExecuteTemplate.execute(ContextClassLoaderExecuteTemplate.java:41)
        at com.navercorp.pinpoint.bootstrap.AgentBootLoader.boot(AgentBootLoader.java:53)
        at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:128)
        at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:82)
        ... 6 more

**Comment by ccdxwh** [comment]
I have found these parameters
-Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl

are located in oralce jdk[jre/rt.jar],not in ibm jdk[jre/rt.jar]

**Comment by ccdxwh** [comment]
thank you 
i have test two way
1.import xercesImpl.jar and set -Djavax.xml.parsers.DocumentBuilderFactory
2.follow you suggestion
all works 

thank you very much
