### ISSUE TITLE
톰캣 8버전 구동시 에러가 발생합니다

### ISSUE THREAD

**Issue by harbris** [naver/pinpoint#618]
어플리케이션 환경은 tomcat8버전에 자바 8버전을 사용하고 있고

pinpoint 1.5 버전 설치하여 테스트 사이트까지 정상적으로 작동합니다

톰캣의 catalina.sh 부분의 아래와 같이 스크립트 기술해주었습니다

export AGENT_PATH=/usr/local/pinpoint/agent/target/pinpoint-agent
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:$AGENT_PATH/pinpoint-bootstrap-1.0.5.jar"
export CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=docswave"
export CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=docswave3.0"

일단 초반에 
이런 에러가 발생하고 
java.net.ConnectException: Connection refused: /127.0.0.1:9994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.jboss.netty.channel.sockva.net.ConnectException: Connection refused: /127.0.0.1:9994
et.nio.NioClientBoss.connect(NioClientBoss.java:150)
        va.net.ConnectException: Connection refused: /127.0.0.1:9994
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
        at org.jboss.netty.channel.sockva.net.ConnectException: Connection refused: /127.0.0.1:9994
at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

그 이후 계속적으로 아래의 에러가 발생합니다
2015-06-15 18:54:11 [DEBUG](c.n.p.p.i.b.JavaAssistClass        :719) addStaticBeforeInterceptor catch behavior:org.apache.catalina.core.StandardHostValve.invoke(org.apache.catalina.connector.Request,org.apache.catalina.connector.Response) code:{  com.navercorp.pinpoint.bootstrap.interceptor.SimpleAroundInterceptor interceptor = com.navercorp.pinpoint.bootstrap.interceptor.InterceptorRegistry.getSimpleInterceptor(3);  interceptor.before(this, $args);}
2015-06-15 18:54:11 [WARN ](c.n.p.p.s.TcpDataSender            :189) request fail. clazz:TApiMetaData(agentId:docswave, agentStartTime:1434362047204, apiId:-1, apiInfo:org.apache.catalina.core.StandardHostValve.invoke(org.apache.catalina.connector.Request request, org.apache.catalina.connector.Response response), line:111) Caused:reconnecting...
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateSocketHandler.newReconnectException(ReconnectStateSocketHandler.java:79)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateSocketHandler.reconnectFailureFuture(ReconnectStateSocketHandler.java:66)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateSocketHandler.request(ReconnectStateSocketHandler.java:84)
        at com.navercorp.pinpoint.rpc.client.PinpointSocket.request(PinpointSocket.java:127)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:221)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:195)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:150)
        at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)

혹시나 개선 방법이 있으면 알려주시면 감사하겠습니다

**Comment by minwoo-jung** [comment]
exception 코드를 보니 
pinpoint collector 서버에 접속하지 못하고 있는것같습니다.
collector 서버가 정상적으로 동작중인지 확인이 필요합니다.

**Comment by harbris** [comment]
도움을 주셔서 감사합니다
혹시 아래에 collector 스타트 될때 로그입니다
근데 pinpoin 기본으로 설치되는 test웹은 잘되던데 
회사 서비스를 적용하려고 하니 톰캣에서 계속 에러가 발생하네요

06-16 19:25:27 [INFO ](o.s.b.f.c.PropertiesFactoryBean    :172) Loading properties file from class path resource [pinpoint-collector.properties]
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :185) pinpoint-collector.properties read.
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) collector.tcpListenIp=0.0.0.0
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.tcpListenPort=29994
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) collector.udpStatListenIp=0.0.0.0
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatListenPort=29995
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatWorkerThread=16
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatWorkerQueueSize=128
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpStatSocketReceiveBufferSize=4194304
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) collector.udpSpanListenIp=0.0.0.0
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanListenPort=29996
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanWorkerThread=32
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanWorkerQueueSize=256
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) collector.udpSpanSocketReceiveBufferSize=4194304
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :236) cluster.enable=false
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :213) cluster.zookeeper.address=
06-16 19:25:27 [INFO ](c.n.p.c.c.CollectorConfiguration   :223) cluster.zookeeper.sessiontimeout=-1
06-16 19:25:27 [INFO ](c.n.p.c.d.AutoFlusher              :83) Auto flusher initialized.
06-16 19:25:28 [DEBUG](c.n.p.r.c.PinpointSocketFactory    :191) createBootStrap boss:1, worker:1
06-16 19:25:28 [INFO ](c.n.p.c.c.z.ZookeeperClusterService:81) pinpoint-collector cluster disable.
06-16 19:25:28 [DEBUG](c.n.p.r.s.PinpointServerSocket     :413) sendPing
06-16 19:25:28 [DEBUG](c.n.p.r.s.PinpointServerSocket     :446) newPingTimeout
06-16 19:25:28 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :230) Pinpoint-UDP-Span start.
06-16 19:25:28 [WARN ](c.n.p.c.r.u.BaseUDPReceiver        :211) DatagramSocket.setReceiveBufferSize() error. 4194304!=229376
06-16 19:25:28 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :236) UDP Packet reader:1 started.
06-16 19:25:28 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :230) Pinpoint-UDP-Stat start.
06-16 19:25:28 [WARN ](c.n.p.c.r.u.BaseUDPReceiver        :211) DatagramSocket.setReceiveBufferSize() error. 4194304!=229376
06-16 19:25:28 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :236) UDP Packet reader:1 started.
06-16 19:25:28 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :132) start ioThread localAddress:0.0.0.0/0.0.0.0, IoThread:Pinpoint-UDP-Span-Io(11-0)
06-16 19:25:28 [INFO ](c.n.p.c.r.u.BaseUDPReceiver        :132) start ioThread localAddress:0.0.0.0/0.0.0.0, IoThread:Pinpoint-UDP-Stat-Io(13-0)
06-16 19:25:29 [INFO ](o.s.w.c.ContextLoader              :313) Root WebApplicationContext: initialization completed in 6557 ms
Jun 16, 2015 7:25:30 PM org.apache.coyote.AbstractProtocol start

**Comment by minwoo-jung** [comment]
collector에 quickstart 에서 제공하는 web이 잘 붙는다면 collector는 문제가 없는것같습니다.

계속 에러가 발생한다는 회사의 톰켓 인스턴스에서 출력하는 에러 메시지를 공유 해주세요.
pinpoint agent 설치 경로의 log 폴더 하위의 OOOOO.log 파일 과  tomcat의 catalina.out에서 출력하는 에러 메시지 이면 됩니다.

**Comment by harbris** [comment]
감사합니다 .

일단 pinpoint agent 로그는 

java.net.ConnectException: Connection refused: /127.0.0.1:9994
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
at org.jboss.netty.channel.sockva.net.ConnectException: Connection refused: /127.0.0.1:9994
et.nio.NioClientBoss.connect(NioClientBoss.java:150)
va.net.ConnectException: Connection refused: /127.0.0.1:9994
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
at org.jboss.netty.channel.sockva.net.ConnectException: Connection refused: /127.0.0.1:9994
at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

저희 서비스 톰캣의 경우 start 시  아래의 내용이 계속적으로 발생하면서 
톰캣이 start 되지 않습니다

2015-06-15 18:54:48 [WARN ](c.n.p.p.s.TcpDataSender            :189) request fail. clazz:TApiMetaData(agentId:docswave, agentStartTime:1434362047204, apiId:287, apiInfo:com.sil.docswave.service.impl.CategoryServiceImpl.saveFileCopyFromAdmin(com.sil.docswave.dto.MemberDto memberDto, java.util.Map docswaveAdminReFileMap), line:412) Caused:reconnecting...
com.navercorp.pinpoint.rpc.PinpointSocketException: reconnecting...
        at com.navercorp.pinpoint.rpc.client.ReconnectStateSocketHandler.newReconnectException(ReconnectStateSocketHandler.java:79)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateSocketHandler.reconnectFailureFuture(ReconnectStateSocketHandler.java:66)
        at com.navercorp.pinpoint.rpc.client.ReconnectStateSocketHandler.request(ReconnectStateSocketHandler.java:84)
        at com.navercorp.pinpoint.rpc.client.PinpointSocket.request(PinpointSocket.java:127)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:221)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.doRequest(TcpDataSender.java:195)
        at com.navercorp.pinpoint.profiler.sender.TcpDataSender.sendPacket(TcpDataSender.java:150)
        at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
        at java.lang.Thread.run(Thread.java:745)

**Comment by minwoo-jung** [comment]
collector의 listening port와 pinpoint agent에서 설정된 collector port가 일치하지 않습니다.
port를 동일하게 하고 동작시켜보세요.

collector log
```
06-16 19:25:27 INFO collector.tcpListenPort=29994
 06-16 19:25:27 INFO collector.udpStatListenIp=0.0.0.0
 06-16 19:25:27 INFO collector.udpStatListenPort=29995
```

agent log
```
java.net.ConnectException: Connection refused: /127.0.0.1:9994
 at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
 at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
 at org.jboss.netty.channel.sockva.net.ConnectException: Connection refused: /127.0.0.1:9994
 et.nio.NioClientBoss.connect(NioClientBoss.java:150)
 va.net.ConnectException: Connection refused: /127.0.0.1:9994
```

추가로
회사 서비스에 pinpoint를 적용하신다면 master의 snapshot 버전을 사용하시는 것보다는
정식으로 릴리즈된 최신버전을 사용하시는게 좋을것같습니다.

**Comment by harbris** [comment]
agent config 부분에 collector 포트가 잘못 되어있었네요 감사합니다 

꾸준히 사용해보도록 하꼐요 ~ 감사합니다
