### ISSUE TITLE
Alarm not trigerring | Pinpoint 1.8.5

### ISSUE THREAD

**Issue by NishantRajak** [naver/pinpoint#6227]
Dear Pinpoint Community Members,

We are trying to configure Pinpoint alarm for one of our application. We have successfully configured MySQL. We are able to create and save User group as well as Alarm rules.

Problem that we are facing is- Despite of all setting the threasholds at minimum value e.g. TOTAL_COUNT=1, we are unable to see any alerts/ enrty inside the alarm_history or agent_statistics. tables. There is no error inside the tomcat-catalina log as well. 

We have followed all the steps mentioned on below URL:
https://github.com/naver/pinpoint/blob/master/doc/alarm.md#2-implementation--configuration

Please guide us to troubleshoot this issue. 

**Environment Details:**

Pinpoint Version: 1.8.5 [OS: Linux 7 x86_64]
MySQL : 8.0 [OS: Windows 2016 x64]

Thanks,
Nishant

**Comment by minwoo-jung** [comment]
1. Have you checked the logs to see if the alarm batch is working? 
If you can check the logs, showing the entire log will help me find the cause.

**Comment by NishantRajak** [comment]
Hello minwoo-jung,
Thanks for reply. We have made changes with batch.enable=true. Please refer the below logs:


[root@MyProdServer logs]# cat catalina.out | grep -i alarm
2019-11-22 13:41:46 [INFO ](o.s.b.f.x.XmlBeanDefinitionReader  ) Loading XML bean definitions from class path resource [batch/applicationContext-alarmJob.xml]
2019-11-22 13:41:46 [INFO ](.s.b.f.s.DefaultListableBeanFactory) Overriding bean definition for bean 'reader' with a different definition: replacing [Generic bean: class [com.navercorp.pinpoint.web.alarm.AlarmReader]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [batch/applicationContext-alarmJob.xml]] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in class path resource [batch/applicationContext-alarmJob.xml]]
2019-11-22 13:41:46 [INFO ](.s.b.f.s.DefaultListableBeanFactory) Overriding bean definition for bean 'processor' with a different definition: replacing [Generic bean: class [com.navercorp.pinpoint.web.alarm.AlarmProcessor]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [batch/applicationContext-alarmJob.xml]] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in class path resource [batch/applicationContext-alarmJob.xml]]
2019-11-22 13:41:46 [INFO ](.s.b.f.s.DefaultListableBeanFactory) Overriding bean definition for bean 'writer' with a different definition: replacing [Generic bean: class [com.navercorp.pinpoint.web.alarm.AlarmWriter]; scope=step; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=false; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [batch/applicationContext-alarmJob.xml]] with [Root bean: class [org.springframework.aop.scope.ScopedProxyFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in BeanDefinition defined in class path resource [batch/applicationContext-alarmJob.xml]]
2019-11-22 13:41:53 [INFO ](.m.m.a.RequestMappingHandlerMapping) Mapped "{[/alarmRule || /application/alarmRule],methods=[PUT]}" onto public java.util.Map<java.lang.String, java.lang.String> com.navercorp.pinpoint.web.controller.AlarmController.updateRule(com.navercorp.pinpoint.web.alarm.vo.Rule)
2019-11-22 13:41:53 [INFO ](.m.m.a.RequestMappingHandlerMapping) Mapped "{[/alarmRule || /application/alarmRule],methods=[POST]}" onto public java.util.Map<java.lang.String, java.lang.String> com.navercorp.pinpoint.web.controller.AlarmController.insertRule(com.navercorp.pinpoint.web.alarm.vo.Rule)
2019-11-22 13:41:53 [INFO ](.m.m.a.RequestMappingHandlerMapping) Mapped "{[/alarmRule || /application/alarmRule],methods=[DELETE]}" onto public java.util.Map<java.lang.String, java.lang.String> com.navercorp.pinpoint.web.controller.AlarmController.deleteRule(com.navercorp.pinpoint.web.alarm.vo.Rule)
2019-11-22 13:41:53 [INFO ](.m.m.a.RequestMappingHandlerMapping) Mapped "{[/alarmRule/checker || /application/alarmRule/checker],methods=[GET]}" onto public java.util.List<java.lang.String> com.navercorp.pinpoint.web.controller.AlarmController.getCheckerName()
2019-11-22 13:41:53 [INFO ](.m.m.a.RequestMappingHandlerMapping) Mapped "{[/alarmRule || /application/alarmRule],methods=[GET]}" onto public java.lang.Object com.navercorp.pinpoint.web.controller.AlarmController.getRule(java.lang.String,java.lang.String)

[root@MyProdServer logs]# cat catalina.out | grep -i mysql
2019-11-22 13:41:35 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) Loading TraceMetadataProvider: com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider name:com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider@66a880ab
2019-11-22 13:41:35 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) MYSQL(2100) from com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider
2019-11-22 13:41:35 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) MYSQL_EXECUTE_QUERY(2101) from com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider
2019-11-22 13:41:35 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:MYSQL
2019-11-22 13:41:35 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:MYSQL
2019-11-22 13:41:47 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) Loading TraceMetadataProvider: com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider name:com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider@7817d362
2019-11-22 13:41:47 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) MYSQL(2100) from com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider
2019-11-22 13:41:47 [INFO ](c.n.p.c.t.TraceMetadataLoader      ) MYSQL_EXECUTE_QUERY(2101) from com.navercorp.pinpoint.plugin.jdbc.mysql.MySqlTypeProvider
2019-11-22 13:41:47 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:MYSQL
2019-11-22 13:41:47 [INFO ](s.DefaultServiceTypeRegistryService) add Plugin ServiceType:MYSQL
2019-11-22 13:41:51 [DEBUG](.DefaultAnnotationKeyMatcherService) add AnnotationKeyMatcher ServiceType:MYSQL, AnnotationKeyMatcher:ExactMatcher(-1)
2019-11-22 13:41:51 [DEBUG](.DefaultAnnotationKeyMatcherService) add AnnotationKeyMatcher ServiceType:MYSQL, AnnotationKeyMatcher:ExactMatcher(-1)
2019-11-22 13:41:52 [INFO ](.s.b.c.r.s.JobRepositoryFactoryBean) No database type set, using meta data indicating: MYSQL


Regards,
Nishant

**Comment by NishantRajak** [comment]
We are also seeing below error message:


2019-11-22 15:24:00 [ERROR](o.s.b.c.s.AbstractStep             ) Encountered an error executing step alarmStep in job alarmJob
org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: java.sql.SQLException: Field 'rule_id' doesn't have a default value
### The error may involve com.navercorp.pinpoint.web.dao.AlarmDao.insertCheckerResult-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO alarm_history (application_id, checker_name, detected, sequence_count, timing_count)         VALUES             (?, ?, ?, ?, ?)
### Cause: java.sql.SQLException: Field 'rule_id' doesn't have a default value
; SQL []; Field 'rule_id' doesn't have a default value; nested exception is java.sql.SQLException: Field 'rule_id' doesn't have a default value
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:242)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at com.sun.proxy.$Proxy74.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	at com.navercorp.pinpoint.web.dao.mysql.MysqlAlarmDao.insertCheckerResult(MysqlAlarmDao.java:90)
	at com.navercorp.pinpoint.web.service.AlarmServiceImpl.updateBeforeCheckerResult(AlarmServiceImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy76.updateBeforeCheckerResult(Unknown Source)
	at com.navercorp.pinpoint.web.alarm.AlarmWriter.write(AlarmWriter.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy89.write(Unknown Source)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)
	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Field 'rule_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:44)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.navercorp.pinpoint.web.dao.ibatis.BindingLogPlugin32.intercept(BindingLogPlugin32.java:80)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:60)
	at com.sun.proxy.$Proxy105.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	... 51 more
2019-11-22 15:24:00 [ERROR](o.s.b.c.s.AbstractStep             ) Encountered an error executing step alarmPartitionStep in job alarmJob
org.springframework.batch.core.JobExecutionException: Partition handler returned an unsuccessful step
	at org.springframework.batch.core.partition.support.PartitionStep.doExecute(PartitionStep.java:112)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
	at com.navercorp.pinpoint.web.batch.JobLaunchSupport.run(JobLaunchSupport.java:49)
	at com.navercorp.pinpoint.web.batch.BatchJobLauncher.alarmJob(BatchJobLauncher.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by minwoo-jung** [comment]
@NishantRajak
I think you used the shapshot version of the schema file instead of the 1.8.5 schema file.
The problem seems to be due to the difference between the SQL statement and the schema.
Removing the rule_id column from the alarm_history table should not cause any problems.

**Comment by NishantRajak** [comment]
Dear minwoo-jung,

After creating new schema for 1.8.5 as suggested by you . We are getting below error message:


2019-11-26 15:29:44 [ERROR](c.n.p.w.c.UserGroupController      ) There is not userId or fail to create userGroup.
com.navercorp.pinpoint.web.vo.exception.PinpointUserGroupException: There is not userId or fail to create userGroup.
	at com.navercorp.pinpoint.web.service.UserGroupServiceImpl.createUserGroup(UserGroupServiceImpl.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy44.createUserGroup(Unknown Source)
	at com.navercorp.pinpoint.web.controller.UserGroupController.createUserGroup(UserGroupController.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.navercorp.pinpoint.web.servlet.NoCacheFilter.doFilter(NoCacheFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)


Regards,
Nishant

**Comment by minwoo-jung** [comment]
@NishantRajak 
Please change the value of the config.openSource key to true in pinpoint-web.properties.

**Comment by NishantRajak** [comment]
@minwoo-jung 
It seem this issue has been resolved after implementing the changes that you have suggested. Thank you so much !!

Regards,
Nishant

**Comment by minwoo-jung** [comment]
@NishantRajak
I'm glad it worked.
