### ISSUE TITLE
org.apache.maven.surefire.booter.SurefireBooterForkException at Pinpoint-agent it 

### ISSUE THREAD

**Issue by aravindhan87** [naver/pinpoint#6230]
Hi Team,

I am facing issue while installing pinpoint at this step.

[INFO] Reactor Summary for pinpoint-agent-distribution 2.0.0-SNAPSHOT:
[INFO] 
[INFO] pinpoint-agent-distribution ........................ SUCCESS [  8.790 s]
[INFO] pinpoint-agent-it .................................. FAILURE [33:56 min]
[INFO] pinpoint-agent-it8 ................................. SKIPPED
[INFO] pinpoint-collector ................................. SKIPPED
[INFO] pinpoint-plugin-bom ................................ SKIPPED
[INFO] pinpoint-web ....................................... SKIPPED
[INFO] pinpoint-hbase-distribution ........................ SKIPPED
[INFO] pinpoint-hbase-schema-definition ................... SKIPPED
[INFO] pinpoint-hbase-schema .............................. SKIPPED
[INFO] pinpoint-hbase-schema-manager ...................... SKIPPED
[INFO] pinpoint-flink ..................................... SKIPPED

Exception Stack trace:
===========================================================================
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.0:verify (test-on-jvm6) on project pinpoint-agent-it: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/YANTRIKS/aravindhan.p/Documents/pinpoint-master/agent-it/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Test mechanism :: null
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[](url)

JVM Dump File contents:
-==========================================================================

# Created at 2019-11-22T10:39:26.856
org.apache.maven.surefire.testset.TestSetFailedException: Test mechanism :: null
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:223)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.NullPointerException
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.extractDescriptionClassName(JUnit4RunListener.java:207)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.getClassName(JUnit4RunListener.java:178)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.createReportEntry(JUnit4RunListener.java:202)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.testStarted(JUnit4RunListener.java:91)
	at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
	at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestStatement.evaluate(PinpointPluginTestStatement.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite.access$200(PinpointPluginTestSuite.java:56)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite$3.run(PinpointPluginTestSuite.java:334)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite$1.schedule(PinpointPluginTestSuite.java:73)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite.runChildren(PinpointPluginTestSuite.java:332)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite.access$300(PinpointPluginTestSuite.java:56)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite$4.evaluate(PinpointPluginTestSuite.java:347)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	... 4 more

# Created at 2019-11-22T10:50:53.249
org.apache.maven.surefire.testset.TestSetFailedException: Test mechanism :: null
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:223)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.NullPointerException
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.extractDescriptionClassName(JUnit4RunListener.java:207)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.getClassName(JUnit4RunListener.java:178)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.createReportEntry(JUnit4RunListener.java:202)
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.testStarted(JUnit4RunListener.java:91)
	at org.junit.runner.notification.SynchronizedRunListener.testStarted(SynchronizedRunListener.java:49)
	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:121)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:118)
	at org.apache.maven.surefire.common.junit4.Notifier.fireTestStarted(Notifier.java:100)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestStatement.evaluate(PinpointPluginTestStatement.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite.access$200(PinpointPluginTestSuite.java:56)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite$3.run(PinpointPluginTestSuite.java:334)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite$1.schedule(PinpointPluginTestSuite.java:73)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite.runChildren(PinpointPluginTestSuite.java:332)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite.access$300(PinpointPluginTestSuite.java:56)
	at com.navercorp.pinpoint.test.plugin.PinpointPluginTestSuite$4.evaluate(PinpointPluginTestSuite.java:347)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	... 4 more

**Comment by koo-taejin** [comment]
@aravindhan87 

Can I get logs before and after the error that you mentioned?

thanks
