### ISSUE TITLE
Error building pinpoint-web

### ISSUE THREAD

**Issue by davide-parini** [naver/pinpoint#6300]
Hello, I'm getting the following error when trying to build tag 1.8.5 of pinpoint.
```
[INFO] --- frontend-maven-plugin:1.5:npm (npm install) @ pinpoint-web ---
[INFO] Found proxies: [xxxxx!{protocol='http', host='xxxxx', port=8080}]
[INFO] Running 'npm install --https-proxy=http://xxxxx:8080 --proxy=http://xxxxx:8080' in C:\dev\git\pinpoint-cb\web\target
[WARNING] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[WARNING] npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
[WARNING] npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[ERROR] npm ERR! Windows_NT 6.1.7601
[ERROR] npm ERR! argv "C:\\dev\\git\\pinpoint-cb\\web\\target\\node\\node.exe" "C:\\dev\\git\\pinpoint-cb\\web\\target\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--https-proxy=xxxxx:8080" "--proxy=xxxxx:8080"
[ERROR] npm ERR! node v5.11.1
[ERROR] npm ERR! npm  v3.9.6
[ERROR] npm ERR! code EMISSINGARG
[ERROR]
[ERROR] npm ERR! typeerror Error: Missing required argument #1
[ERROR] npm ERR! typeerror     at andLogAndFinish (C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\fetch-package-metadata.js:31:3)
[ERROR] npm ERR! typeerror     at fetchPackageMetadata (C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\fetch-package-metadata.js:51:22)
[ERROR] npm ERR! typeerror     at resolveWithNewModule (C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\install\deps.js:490:12)
[ERROR] npm ERR! typeerror     at C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\install\deps.js:491:7
[ERROR] npm ERR! typeerror     at C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\node_modules\iferr\index.js:13:50
[ERROR] npm ERR! typeerror     at C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\fetch-package-metadata.js:37:12
[ERROR] npm ERR! typeerror     at addRequestedAndFinish (C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\fetch-package-metadata.js:67:5)
[ERROR] npm ERR! typeerror     at returnAndAddMetadata (C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\fetch-package-metadata.js:121:7)
[ERROR] npm ERR! typeerror     at pickVersionFromRegistryDocument (C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\lib\fetch-package-metadata.js:138:20)
[ERROR] npm ERR! typeerror     at C:\dev\git\pinpoint-cb\web\target\node\node_modules\npm\node_modules\iferr\index.js:13:50
[ERROR] npm ERR! typeerror This is an error with npm itself. Please report this error at:
[ERROR] npm ERR! typeerror     <http://github.com/npm/npm/issues>
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     C:\dev\git\pinpoint-cb\web\target\npm-debug.log
```
Build command line
```
mvn clean package -Dmaven.test.skip=true --projects :pinpoint-web --also-make`
```
Maven environment
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: C:\dev\apache-maven-3.5.4
Java version: 1.8.0_73, vendor: Oracle Corporation, runtime: C:\dev\jdk-8u73-windows-x64\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
```
Forcing newer versions of node and npm in web/pom.xml seems to solve the issue.
```
                    <execution>
                        <id>install node and npm</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
<!--                             <nodeVersion>v5.11.1</nodeVersion> -->
<!--                             <npmVersion>3.9.6</npmVersion> -->
                            <nodeVersion>v10.6.0</nodeVersion>
                            <npmVersion>6.1.0</npmVersion>
                            <workingDirectory>${basedir}/target</workingDirectory>
                        </configuration>
                    </execution>

```
Is it ok to build with the newer versions of node and npm or is there a way to get it right without editing the pom?

**Comment by minwoo-jung** [comment]
@binDongKim 
Please take a look at this issue.

**Comment by minwoo-jung** [comment]
@davide-parini
Thanks for reporting the version issue. The next version will work with the higher version.

**Comment by geekMessi** [comment]
What's the problem with that bug ? I encountered the same issue that I complied failed suddenly !

**Comment by binDongKim** [comment]
@geekMessi We used quite old(or I would say outdated) version of node and npm in 1.8.5 and there seems to be a compatibility issue with it.

**Comment by geekMessi** [comment]
> @geekMessi We used quite old(or I would say outdated) version of node and npm in 1.8.5 and there seems to be a compatibility issue with it.

But the version of Pinpoint which I use is 1.7.X .
