### ISSUE TITLE
Agent is able to connect but not able to trace

### ISSUE THREAD

**Issue by krishnakumar9113** [naver/pinpoint#6451]
I tried to connect my pinpoint agent with a tomcat server. to profile one of the application hosted in it..
i have updated setenv.bat with pinpoint agent details as JVM args .

The application is throwing exception in tomcat console as below.

----------> Parent Classloader:
java.net.URLClassLoader@758f4f03
 agentCl:ParallelClassLoader{name='pinpoint.agent'} com.navercorp.pinpoint.bootstrap.classloader.ParallelClassLoader@5e481248 Cause:size=8192 id=9385
java.lang.IndexOutOfBoundsException: size=8192 id=9385
	at com.navercorp.pinpoint.bootstrap.interceptor.registry.DefaultInterceptorRegistryAdaptor.addInterceptor(DefaultInterceptorRegistryAdaptor.java:42)
	at com.navercorp.pinpoint.profiler.instrument.DefaultEngineComponent.addInterceptor(DefaultEngineComponent.java:71)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor0(ASMMethod.java:210)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:107)
	at com.navercorp.pinpoint.profiler.instrument.transformer.DebugTransformer.transform(DebugTransformer.java:75)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apac

**Comment by emeroad** [comment]
`InterceptorRegistry` size is not sufficient
Please change the options below

$PINPOINT_AGENT/profiles/$PROFILE/pinpoint-env.config
```
profiler.interceptorregistry.size=8192 
```
