### ISSUE TITLE
loadBalance mode on Postgres jdbc plugin is not working

### ISSUE THREAD

**Issue by tigerby** [naver/pinpoint#6476]
- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v1.8.5

#### Describe the bug
My application use postgresql with loadbalancing mode. When application is starting with pinpoint-agent, I found error attached and application and agent is not working properly. My jdbc stirng is like `jdbc:postgresql://10.x.x.x:31568,10.x.x.x:31568,10.x.x.x:31568/mydb?loadBalanceHosts=true`

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. Ran my springboot application with agent attached
2. I got errors below when application is bootstrapping

#### Logs
```
2020-02-05 14:37:13 [WARN ](c.n.p.p.i.f.GuardExceptionHandler  ) Exception occurred from interceptor
java.lang.NumberFormatException: For input string: "31568,31568,31568"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at com.navercorp.pinpoint.plugin.jdbc.postgresql.interceptor.PostgreSQLConnectionCreateInterceptor.after(PostgreSQLConnectionCreateInterceptor.java:65)
        at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:293)
        at org.postgresql.Driver.makeConnection(Driver.java:458)
        at org.postgresql.Driver.connect(Driver.java:260)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
        at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

#### Additional context
I'm using `loadBalanceHosts` parameter on jdbc string to use loadbalance mode. But I found that agent uses `jdbc:postgresql:loadbalance:` prefix to determine loadbanacing mode or not on `PostgreSqlJdbcUrlParser.java` in `postgresql-jdbc` module. I think mysql use loadbalance prefix like that, but in postgresql, I found it's not supporting prefix like that but have to use loadBalanceHosts parameter. Here is postgresql documentation.
https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by emeroad** [comment]
@tigerby
Thank you for reporting
Could you make a patch for the community?

Contributions are always welcome

**Comment by emeroad** [comment]
Resolved : https://github.com/naver/pinpoint/issues/6814
