### ISSUE TITLE
Received Goaway - seeing goaway error on agent

### ISSUE THREAD

**Issue by immusk** [naver/pinpoint#6490]
Hi Team,

seeing this error in logs and logs are filling up like anything with this error.
please help

2020-02-10 03:20:23 [WARN ](c.n.p.p.s.g.MetadataGrpcDataSender ) Error. request=apiId: 6676 apiInfo: "com.xx.xxx.xxx.xxxxxxx$$EnhancerBySpringCGLIB$$2c238f52.isExposeProxy()", cause=UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
max_idle
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
max_idle
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by immusk** [comment]
@koo-taejin can you please help here

**Comment by jaehong-kim** [comment]
@immusk 
The server has terminated the connection because the Max Connection Idle Time has been reached.
The default value is 360000ms.

1. Please check the settings.
~~~
collector.receiver.grpc.agent.connection.idle.timeout.millis=360000
~~~
2. Show me how often it happens.

**Comment by immusk** [comment]
@jaehong-kim I have almost doubled all the values in pinpoint-collector-grpc.properties
But still I am facing the same issue, can you please suggest what else can I do to overcome this issue.

`collector.receiver.grpc.agent.keepalive.time.millis=600000
collector.receiver.grpc.agent.keepalive.timeout.millis=120000
collector.receiver.grpc.agent.permit.keepalive.time.millis=360000
collector.receiver.grpc.agent.connection.idle.timeout.millis=720000
collector.receiver.grpc.agent.concurrent-calls.per-connection.max=2048
collector.receiver.grpc.agent.handshake.timeout.millis=240000
collector.receiver.grpc.agent.flow-control.window.size.init=2M
collector.receiver.grpc.agent.header.list.size.max=2K
collector.receiver.grpc.agent.inbound.message.size.max=8M
collector.receiver.grpc.agent.receive.buffer.size=128K

# Stat
# Server Option
collector.receiver.grpc.stat.keepalive.time.millis=600000
collector.receiver.grpc.stat.keepalive.timeout.millis=120000
collector.receiver.grpc.stat.permit.keepalive.time.millis=360000
collector.receiver.grpc.stat.connection.idle.timeout.millis=720000
collector.receiver.grpc.stat.concurrent-calls.per-connection.max=2048
collector.receiver.grpc.stat.handshake.timeout.millis=240000
collector.receiver.grpc.stat.flow-control.window.size.init=2M
collector.receiver.grpc.stat.header.list.size.max=2K
collector.receiver.grpc.stat.inbound.message.size.max=8M
collector.receiver.grpc.stat.receive.buffer.size=128K

# Span
# Server Option
collector.receiver.grpc.span.keepalive.time.millis=600000
collector.receiver.grpc.span.keepalive.timeout.millis=120000
collector.receiver.grpc.span.permit.keepalive.time.millis=360000
collector.receiver.grpc.span.connection.idle.timeout.millis=720000
collector.receiver.grpc.span.concurrent-calls.per-connection.max=2048
collector.receiver.grpc.span.handshake.timeout.millis=240000
collector.receiver.grpc.span.flow-control.window.size.init=2M
collector.receiver.grpc.span.header.list.size.max=2K
collector.receiver.grpc.span.inbound.message.size.max=8M
collector.receiver.grpc.span.receive.buffer.size=128K`

**Comment by immusk** [comment]
I am using the azure load balance and facing this issue on it, on using aws Load balancers I am not facing this issue.

**Comment by jaehong-kim** [comment]
@immusk 
It seems that the load balancer depends on how long it will stay connected.
Keepalive (ping-pong) time reduction seems to be one of the ways.
e.g.
~~~
collector.receiver.grpc.agent.keepalive.time.millis=1000
collector.receiver.grpc.agent.keepalive.timeout.millis=60000
~~~

**Comment by immusk** [comment]
@jaehong-kim 

Thanks 🙏  for the suggestions, after increasing the idle.timeout, I am not seeing the `Received Goaway`
But I am noticing this in logs.
a very huge and quick logs, I mean in 10minutes i am seeing around 24,000 messages for these in agent logs.
Can you please suggest here to over come this issue too 🙏 

`2020-02-12 03:57:40 [WARN ](c.n.p.p.r.g.GrpcCommandService     ) Failed to command stream, cause=UNAVAILABLE: Keepalive failed. The connection is likely gone
io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-02-12 03:57:40 [WARN ](c.n.p.p.s.g.PingStreamContext      ) Failed to ping stream, streamId=PingStream-2, cause=UNAVAILABLE: Keepalive failed. The connection is likely gone
io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by jaehong-kim** [comment]
@immusk 
Azure default TCP idle timeout time seems to be 4 minutes.(https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout)
Pinpoint default keep alive time is set too high.
~~~
profiler.transport.grpc.metadata.sender.keepalive.time.millis=300000
~~~

Please correct the keep-alive time setting.
~~~
profiler.transport.grpc.metadata.sender.keepalive.time.millis=30000
~~~

**Comment by immusk** [comment]
@jaehong-kim  @koo-taejin 

seeing these exceptions once in a while on all the agents.
`Caused by: java.io.IOException: Operation timed out`

2020-03-04 17:24:15 [WARN ](c.n.p.p.s.g.ResponseStreamObserver ) Failed to stream, name=StatStream-3, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 3 more


can you please help to fix this too

**Comment by jaehong-kim** [comment]
@immusk 
Please show the full log.
It looks like a timed out error, but I can't know the details.
~~~
Caused by: java.io.IOException: Operation timed out
~~~
