### ISSUE TITLE
While Tracing Kafka listening trace throwing -  java.lang.NullPointerException: callerApplicationName

### ISSUE THREAD

**Issue by dinesh4747** [naver/pinpoint#6512]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
V2.0.0-RC2

#### Describe your problem**
Unable to get the call stack for spring boot which listening from the Kafka topic and receiving messages from the topic and It was throwing below exceptions -

1. Failed to handle span=version: 1 transactionId { agentStartTime: 1582004417624 sequence: 5 } spanId: 3340841534782189573 parentSpanId: -1 startTime: 1582007056351 elapsed: 2 apiId: 331 serviceType: 8660 acceptEvent { rpc: "kafka://topic=pharos-error?partition=2&offset=313873" endPoint: "stable.ss-kafka-npe-xxxx:9092" remoteAddr: "stable.ss-kafka-npe-xxxxx:9092" }

2. java.lang.NullPointerException: callerApplicationName

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Launched '...' with agent
2. Tried tracing '...' (see agent log below)
3. Collector outputs trace log (see collector log below)
4. No trace shows up in the web UI (see web log below)

#### Logs

2020-02-18 06:24:16 [WARN ](c.n.p.c.h.g.GrpcSpanHandler        ) Failed to handle span=version: 1 transactionId { agentStartTime: 1582004417624 sequence: 5 } spanId: 3340841534782189573 parentSpanId: -1 startTime: 1582007056351 elapsed: 2 apiId: 331 serviceType: 8660 acceptEvent { rpc: "kafka://topic=pharos-error?partition=2&offset=313873" endPoint: "stable.ss-kafka-npe-dev.service.consul:9092" remoteAddr: "stable.ss-kafka-npe-dev.service.consul:9092" } annotation { key: 140 value { stringValue: "pharos-error" } } annotation { key: 141 value { intValue: 2 } } annotation { key: 142 value { longValue: 313873 } } spanEvent { depth: 1 endElapsed: 2 serviceType: 8661 apiId: 336 } spanEvent { sequence: 1 depth: 2 endElapsed: 1 serviceType: 5011 annotation { key: 9001 value { intValue: 776 } } apiId: 35 } spanEvent { sequence: 2 startElapsed: 1 endElapsed: 1 serviceType: 5071 apiId: 52 } spanEvent { sequence: 3 depth: 3 serviceType: 5011 apiId: 5 } spanEvent { sequence: 4 startElapsed: 1 serviceType: 5011 annotation { key: 9001 value { intValue: 18 } } apiId: 11 } spanEvent { sequence: 5 serviceType: 5011 annotation { key: 9001 value { intValue: 34 } } apiId: 11 } spanEvent { sequence: 6 serviceType: 8660 annotation { key: 140 value { stringValue: "pharos-druid-error" } } apiId: 329 nextEvent { messageEvent { nextSpanId: 7927484506219323612 endPoint: "stable.ss-kafka-npe-dev.service.consul:9092" destinationId: "stable.ss-kafka-npe-dev.service.consul:9092" } } } applicationServiceType: 1210
java.lang.NullPointerException: callerApplicationName
        at com.navercorp.pinpoint.collector.dao.hbase.HbaseMapStatisticsCallerDao.update(HbaseMapStatisticsCallerDao.java:91)
        at com.navercorp.pinpoint.collector.service.StatisticsService.updateCaller(StatisticsService.java:59)
        at com.navercorp.pinpoint.collector.service.TraceService.insertSpanStat(TraceService.java:128)
        at com.navercorp.pinpoint.collector.service.TraceService.insertSpan(TraceService.java:73)
        at com.navercorp.pinpoint.collector.handler.grpc.GrpcSpanHandler.handleSpan(GrpcSpanHandler.java:75)
        at com.navercorp.pinpoint.collector.handler.grpc.GrpcSpanHandler.handleSimple(GrpcSpanHandler.java:60)
        at com.navercorp.pinpoint.collector.receiver.SpanDispatchHandler.dispatchSendMessage(SpanDispatchHandler.java:56)
        at com.navercorp.pinpoint.collector.receiver.thrift.DelegateDispatchHandler.dispatchSendMessage(DelegateDispatchHandler.java:57)
        at com.navercorp.pinpoint.collector.receiver.grpc.service.SpanService.send(SpanService.java:112)
        at com.navercorp.pinpoint.collector.receiver.grpc.service.SpanService.access$300(SpanService.java:50)
        at com.navercorp.pinpoint.collector.receiver.grpc.service.SpanService$1.onNext(SpanService.java:72)
        at com.navercorp.pinpoint.collector.receiver.grpc.service.SpanService$1.onNext(SpanService.java:63)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248)
        at com.navercorp.pinpoint.grpc.server.StreamExecutorServerInterceptor$1$1.run(StreamExecutorServerInterceptor.java:79)
        at io.grpc.Context$1.run(Context.java:595)
        at com.navercorp.pinpoint.collector.monitor.MonitoredRunnableDecorator$InstrumentedRunnable.run(MonitoredRunnableDecorator.java:113)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by dinesh4747** [comment]
@jaehong-kim - Could you please confirm whether the above issue is pertains to the PR fix for NPE issue in Kafka - https://github.com/naver/pinpoint/pull/6493

**Comment by koo-taejin** [comment]
hi @dinesh4747 

Please tell me some additional information. 

* Kafka version to have used in Agent .
* Pinpoint version to have attached in Agent
* Pinpoint version to have used in Collector

thanks :)

**Comment by dinesh4747** [comment]
Hi @koo-taejin 

Thanks for your timely response, pls below the info for the same -

- Kafka version to have used in Agent  - we use **Confluent Kafka - V5.1.0** which is equivalent to **Apache Kafka V2.1.x** (Reference - https://docs.confluent.io/current/installation/versions-interoperability.html)
- Pinpoint version to have attached in Agent - V2.0.0-RC2
- Pinpoint version to have used in Collector - V2.0.0-RC2

Kindly let me know if you require any further information

**Comment by koo-taejin** [comment]
@dinesh4747 

I am looking into this issue.
If I find reason, then I will share it.

Thanks.

**Comment by koo-taejin** [comment]
@dinesh4747 

I have found it out reason.
This issue has resolved via #6499
So, If you use 2.0.0-RC4 version which will be released or master branch, then It will be OK. 

thanks :)

**Comment by dinesh4747** [comment]
Hi @koo-taejin 

Thanks for your timely response, I will use with master branch and get back to you on the findings

**Comment by dinesh4747** [comment]
Hi @koo-taejin 

Thanks for the direction and with the latest release 2-RC4 Kafka issue got fixed

Glad to get the extended support. Highly appreciated!!!

Regards
Dinesh

**Comment by koo-taejin** [comment]
@dinesh4747 

I'm glad to hear that your problem has been solved.

thanks :)
