### ISSUE TITLE
Page "transactionList" cannot open occasionally. And found error log "CorruptedSpanCallTreeNodeException: corrupted event."

### ISSUE THREAD

**Issue by joejinjin** [naver/pinpoint#6525]
com.navercorp.pinpoint.web.calltree.span.CorruptedSpanCallTreeNodeException: corrupted event ...... [[ too many message after here ]]
	at com.navercorp.pinpoint.web.calltree.span.SpanCallTree.add(SpanCallTree.java:179)
	at com.navercorp.pinpoint.web.calltree.span.SpanCallTree.add(SpanCallTree.java:173)
	at com.navercorp.pinpoint.web.calltree.span.SpanAligner.populateSpanEvent(SpanAligner.java:103)
	at com.navercorp.pinpoint.web.calltree.span.SpanAligner.populate(SpanAligner.java:89)
	at com.navercorp.pinpoint.web.calltree.span.SpanAligner.align(SpanAligner.java:70)
	at com.navercorp.pinpoint.web.service.SpanServiceImpl.order(SpanServiceImpl.java:432)
	at com.navercorp.pinpoint.web.service.SpanServiceImpl.selectSpan(SpanServiceImpl.java:105)
	at com.navercorp.pinpoint.web.controller.BusinessTransactionController.transactionInfo(BusinessTransactionController.java:95)
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.navercorp.pinpoint.web.servlet.NoCacheFilter.doFilter(NoCacheFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by joejinjin** [comment]
BTW I am using the master code, and version is 2.0.0 SNAPSHOT.
Thank you for information.

**Comment by jaehong-kim** [comment]
@joejinjin 
Maybe the packet is missing.
Check the Agent log.

https://github.com/naver/pinpoint/blob/0802795d8987b68ccf6c7e0ccb7c988b9c08a1c1/web/src/main/java/com/navercorp/pinpoint/web/calltree/span/SpanCallTree.java#L179

**Comment by joejinjin** [comment]
@jaehong-kim 
Thanks for replying. But the Agent log is very clean:
`2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: com/huya/sail/core/service/impl/SignedAnchorServiceImpl, registry size: 4
2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: com/huya/sail/core/service/impl/UpgradeTickDescServiceImpl, registry size: 3
2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: com/huya/sail/core/service/impl/WorldLangObjectServiceImpl, registry size: 2
2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: springfox/documentation/swagger2/web/Swagger2Controller, registry size: 1
2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: springfox/documentation/swagger/web/ApiResourceController, registry size: 0
2020-03-03 07:52:34 [INFO ](c.n.p.p.i.ASMEngine                ) appendToBootstrapClassPath:/data/services/pinpoint-agent/plugin/pinpoint-jdk-completable-future-plugin-2.0.0-SNAPSHOT.jar
2020-03-03 07:53:28 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@21a5fd96 HandshakeJob completed.`
I Have not got any error message to figure it out.

**Comment by joejinjin** [comment]
@jaehong-kim 
Thanks for replying. But the Agent log is very clean:
`2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: springfox/documentation/swagger2/web/Swagger2Controller, registry size: 1
2020-03-03 07:52:31 [INFO ](p.DefaultDynamicTransformerRegistry) removed dynamic transformer classLoader: org.springframework.boot.loader.LaunchedURLClassLoader@547c04c4, className: springfox/documentation/swagger/web/ApiResourceController, registry size: 0
2020-03-03 07:52:34 [INFO ](c.n.p.p.i.ASMEngine                ) appendToBootstrapClassPath:/data/services/pinpoint-agent/plugin/pinpoint-jdk-completable-future-plugin-2.0.0-SNAPSHOT.jar
2020-03-03 07:53:28 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@21a5fd96 HandshakeJob completed.`
I Have not got any error message to figure it out.
