### ISSUE TITLE
java.lang.IllegalStateException: Already connected

### ISSUE THREAD

**Issue by harbris** [naver/pinpoint#658]
안녕하세요 
이번에 저희 회사에서 오픈하려고 하는 서비스에 pinpoint를 사용하려고 하는데요
어플리케이션에 google api 연동하는 부분이 있는데 pinpoint를 사용하여 
톰캣을 구동 할때는 아래와 같은 에러가 발생합니다
그러나 pinpoint를 사용하지 않고 톰캣 구동시에는 에러가 발생하지 않습니다
혹시 api호출시 pinpoint쪽에서 문제가 있을 가능성이 있을까요? 
혹시 그런 부분이 있으면 알려주시면 감사하겠습니다

java.lang.IllegalStateException: Already connected
        at sun.net.www.protocol.http.HttpURLConnection.setRequestProperty(HttpURLConnection.java:3000)
        at com.navercorp.pinpoint.profiler.modifier.connector.jdkhttpconnector.interceptor.ConnectMethodInterceptor.before(ConnectMethodInterceptor.java:79)
        at com.navercorp.pinpoint.profiler.interceptor.DebugScopeDelegateSimpleInterceptor.before(DebugScopeDelegateSimpleInterceptor.java:59)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2965)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562)
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeUploadInitiation(MediaHttpUploader.java:519)
        at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:384)
        at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.sil.docswave.service.google.GoogleDriveApiServiceImpl.insertFileFromHtml(GoogleDriveApiServiceImpl.java:83)

**Comment by emeroad** [comment]
#281 이슈인듯합니다. 
현재 어떤 버전을 사용하고 있는지 알려주시고
https://github.com/naver/pinpoint/releases
여기서 1.0.5로 써보시겠어요.

**Comment by harbris** [comment]
답변 감사드립니다

현제 1.0.5 버전을 사용하고 있습니다

추천해주신 버전이 제가 사용하는 버전과 동일한 버전인가요?

**Comment by emeroad** [comment]
네. 1.0.5 입니다.
아무래도 pinpoint쪽 jdk connector의 캡쳐 로직에 생각지 못한 부분이 있는거 같네요.
사용하시는 jdk 버전도 알려주시겠어요.

**Comment by emeroad** [comment]
사용하신 google api lib 버전도 알려주세요.
관련 코드 
https://github.com/google/google-http-java-client/tree/master/google-http-client/src/main/java/com/google/api/client/http/javanet

https://github.com/google/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpRequest.java

https://github.com/google/google-http-java-client/blob/master/google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpResponse.java

**Comment by harbris** [comment]
답변 감사드립니다

jdk 버전은 1.8.0_05 입니다

구글 api는 아래와 같이 사용중입니다

<dependency>
	<groupId>com.google.apis</groupId>
	<artifactId>google-api-services-appsactivity</artifactId>
	<version>v1-rev12-1.20.0</version>
</dependency>
<dependency>
	<groupId>com.google.apis</groupId>
	<artifactId>google-api-services-drive</artifactId>
	<version>v2-rev167-1.20.0</version>
</dependency>
<dependency>
	<groupId>com.google.apis</groupId>
	<artifactId>google-api-services-gmail</artifactId>
	<version>v1-rev28-1.20.0</version>
</dependency>
<dependency>
	<groupId>com.google.apis</groupId>
	<artifactId>google-api-services-oauth2</artifactId>
	<version>v2-rev90-1.20.0</version>
</dependency>

**Comment by lioolli** [comment]
JDK 8이면 의심가는 부분은 한 군데 있고 비슷한 현상이 재현되고 있긴 합니다. 제가 재현에 성공한 시나리오는 HttpURLConnection을 가지고 연결 시도 도중 실패(예외가 발생)한 뒤에 같은 객체로 다시 연결을 시도하는 경우입니다. 이 부분에 대한 수정은 완료했습니다.

버전 정책 문제가 있어서 일단 제 저장소에 올려두었으니 이쪽에서 받아서 사용해 보시고 문제가 해결되는지 확인 부탁드립니다.

https://github.com/lioolli/pinpoint.git

여기서 1.0.x 브랜치 받아서 테스트 부탁드립니다.

**Comment by harbris** [comment]
답변감사드립니다 

알려주신 버전으로 설치 하니 문제가 발생하지 않습니다

감사합니다~~

**Comment by lioolli** [comment]
해결됐다니 다행이네요. 그런데 1.0.x는 1.0.5가 마지막이라 이 수정 사항은 1.1.x에만 적용될 예정이니 참고하시기 바랍니다.
