### ISSUE TITLE
UnknownHostException: {YOUR_RELEASE_ZOOKEEPER_ADDRESS}: Name or service not known

### ISSUE THREAD

**Issue by qizai123** [naver/pinpoint#6647]
Hope for help, i don't know what to do

Use tomcat to start the collector and get the following error:

```java
27-Mar-2020 12:47:22.597 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs y
et contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Sk
ipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-03-27T12:47:22.694 PinpointCollectorApplicationInitializer::ActiveProfile:release
2020-03-27 12:47:25 [WARN ](o.a.h.u.NativeCodeLoader           ) Unable to load native-hadoop library for your platform... using builtin-ja
va classes where applicable
2020-03-27 12:47:25 [WARN ](o.a.h.h.z.RecoverableZooKeeper     ) Unable to create ZooKeeper Connection
java.net.UnknownHostException: {YOUR_RELEASE_ZOOKEEPER_ADDRESS}: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
```

Base info:

```shell
HBase 1.2.6
pinpoint-collector-2.0.1.war
apache-tomcat-8.0.52.tar.gz
java version "1.8.0_221"

/etc/hosts   ## telnet zk port is ok
10.3.3.50       zookeeper1.mgt.tars.com 
10.3.3.51       zookeeper2.mgt.tars.com 
10.3.3.52       zookeeper3.mgt.tars.com
```

config info:

```xml
About Hbase
> about hbase-site.xml
<configuration>
 <property>
    <name>hbase.rootdir</name>
    <value>file:///data1/hbase/data</value>
 </property>
 <property>
    <name>hbase.cluster.distributed</name>
    <value>true</value>
  </property>
  <property>
        <name>hbase.zookeeper.quorum</name>
        <value>zookeeper1.mgt.tars.com,zookeeper2.mgt.tars.com,zookeeper3.mgt.tars.com</value>
    </property>
    <property>
        <name>zookeeper.session.timeout</name>
        <value>60000000</value>
    </property>
    <property>
      <name>hbase.regionserver.lease.period</name>
      <value>900000</value> <!-- 900 000, 15 minutes -->
    </property>
    <property>
      <name>hbase.rpc.timeout</name>
      <value>900000</value> <!-- 15 minutes -->
    </property>
</configuration>



About pinpoint-collector-2.0.1.war
> about pinpoint-collector.properties：
...
cluster.enable=true
cluster.zookeeper.address=zookeeper1.mgt.tars.com,zookeeper2.mgt.tars.com,zookeeper3.mgt.tars.com
cluster.zookeeper.sessiontimeout=30000
cluster.listen.ip=0.0.0.0
cluster.listen.port=9997
...

> about hbase.properties：
...
hbase.client.host=zookeeper1.mgt.tars.com,zookeeper2.mgt.tars.com,zookeeper3.mgt.tars.com
hbase.client.port=2181
...
```

**Comment by qizai123** [comment]
zookeeper version：environment:zookeeper.version=3.5.5-390fe37ea45dee01bf87dc1c042b5e3dcce88653

**Comment by koo-taejin** [comment]
hi @qizai123 

Please launch collector with jvm properties '-Dpinpoint.zookeeper.address=${YOUR_ZOOKEEPER_ADDRESS}'

You can do another way that you can set your zookeeper address in ${COLLECTOR_HOME}/resources/profiles/${YOUR_PROFILE}/pinpoint-collector-env.properties.

Please do it again in the way I posted.

thanks :)

**Comment by qizai123** [comment]
It works now, thank you very much.
Is this the configuration of the new version? What does this do?

**Comment by qizai123** [comment]
> 嗨@ qizai123
> 
> 请使用jvm属性'-Dpinpoint.zookeeper.address = $ {YOUR_ZOOKEEPER_ADDRESS}'启动收集器
> 
> 您可以通过另一种方式在$ {COLLECTOR_HOME} / resources / profiles / $ {YOUR_PROFILE} /pinpoint-collector-env.properties中设置动物园管理员地址。
> 
> 请按照我发布的方式再次进行。
> 
> 谢谢 ：）

It works now, thank you very much.
Is this the configuration of the new version? What does this do?

**Comment by koo-taejin** [comment]
@qizai123 

Pinpoint has applied the configuration in the form of profiles from v2.0.0.
You can check out detail descrption through below link.
(https://github.com/naver/pinpoint/blob/master/doc/installation.md#profiles)

thanks

**Comment by qizai123** [comment]
I solved this problem through Nginx's TCP / UDP proxy, but it very "low",But hope to help others, thank you for your generous help
about version: pinpoint 2.0.1
about nginx config


```shell
upstream collector_pool {
	server 10.3.2.41:8080  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:8080  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9991 {
	server 10.3.2.41:9991  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9991  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9992 {
	server 10.3.2.41:9992  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9992  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9993 {
	server 10.3.2.41:9993  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9993  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9994 {
	server 10.3.2.41:9994  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9994  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9995 {
	server 10.3.2.41:9995  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9995  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9996 {
	server 10.3.2.41:9996  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9996  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9997 {
	server 10.3.2.41:9997  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9997  max_fails=2 fail_timeout=3s;
}

server {
        listen 10.3.1.25:8080;
        proxy_pass collector_pool;
}
server {
        listen 10.3.1.25:9991;
        proxy_pass collector_pool_9991;
}
server {
        listen 10.3.1.25:9992;
        proxy_pass collector_pool_9992;
}
server {
        listen 10.3.1.25:9993;
        proxy_pass collector_pool_9993;
}
server {
        listen 10.3.1.25:9994;
        proxy_pass collector_pool_9994;
}
server {
        listen 10.3.1.25:9995 udp;
        proxy_pass collector_pool_9995;
}
server {
        listen 10.3.1.25:9996 udp;
        proxy_pass collector_pool_9996;
}
server {
        listen 10.3.1.25:9997;
        proxy_pass collector_pool_9997;
}

```
