### ISSUE TITLE
Regenerate deleted agent

### ISSUE THREAD

**Issue by snmsmanager** [naver/pinpoint#6661]
Dear All,

I hope you all stay safe.
We have lost our hbase node due to power outage issue and we have recreate new hbase node including fresh database. 
But it is not registered all agents and only few agents are visible in GUI. All agents are running properly and sending info to collector.

Is there any way to register agent without restarting the application ? 

Regards,
Sam

**Comment by koo-taejin** [comment]
hi @snmsmanager 

Basically, agent sends own agent info once a day. 
If agents keep to connect for more than a day, then it is expected that agents will be registered  again.

However, due to data loss, you will not be able to see the information that you want in some cases.
Please, will care to manage Hbase instance. 

thanks

**Comment by snmsmanager** [comment]
Hi Koo,
appriciated about the reply.
All agents are still running and using gRPC to transfer data. I've checked the and verfied port 9991/9992 and 9993 is open through network. But still not able to see some agents. Due to high load on agent installed server, we are not able to restart the service to bind agent again. 
Do we have any alternative workaround to register agent without resarting service or override existing 24 hours period ?

Regards,
Pradeep.

**Comment by koo-taejin** [comment]
Unfortunately, there is no way.
The agent is designed to resend own agentinfo data once a day, which re-registers the agent.

Even if it's shown again after a day, the METADATA is gone, so you can't see CalllStack  information normally.
I think the only way is  that you await  that agent owner restart their agent. 

ㅠㅠ

**Comment by snmsmanager** [comment]
Hi Koo,

Now I have docovered that all agent configured as gRPC are registed properly and issue is with only THRIFT. even I'm not able to telnet 9995 and 9996 but 9994 success. I have verfied 9994,005 and 9996 bound properly . But check network script also failed .

[root@hqsipmonapm02 ~]# lsof -i :9994
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    14081 root  489u  IPv6 606997      0t0  TCP *:palace-3 (LISTEN)
[root@hqsipmonapm02 ~]# lsof -i :9995
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    14081 root  491u  IPv6 606999      0t0  UDP *:palace-4 
[root@hqsipmonapm02 ~]# lsof -i :9996
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    14081 root  490u  IPv6 606998      0t0  UDP *:palace-5 

##############################
Transport Module set to THRIFT
java.net.SocketTimeoutException: Receive timed out
        at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:180)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
        at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
        at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
        at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPStat(NetworkAvailabilityChecker.java:154)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:96)
UDP-STAT:// 172.25.32.115
    => 172.25.32.115:9995 [FAIL]

java.net.SocketTimeoutException: Receive timed out
        at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
        at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:180)
        at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
        at com.navercorp.pinpoint.tools.network.UDPChecker.read(UDPChecker.java:91)
        at com.navercorp.pinpoint.tools.network.UDPChecker.check(UDPChecker.java:47)
        at com.navercorp.pinpoint.tools.network.AbstractNetworkChecker.check(AbstractNetworkChecker.java:58)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.checkUDPSpan(NetworkAvailabilityChecker.java:163)
        at com.navercorp.pinpoint.tools.NetworkAvailabilityChecker.main(NetworkAvailabilityChecker.java:102)
UDP-SPAN:// 172.25.32.115
    => 172.25.32.115:9996 [FAIL]
################################

Regards,
Pradeep.

**Comment by koo-taejin** [comment]
@snmsmanager 

Telnet is based on TCP.
That's why connecting telnet is impossible on using Datagream.

If networktest.sh has failed, please check to can access 9995 and 9996 Datagram port from outside. 

thanks

**Comment by snmsmanager** [comment]
Hi Koo,
Thanks for the great help. 
We have asked client to restart the sevice and able to register agent with METADATA. 
Would you please explain to me which is better THRIFT or GRPC using in large production environments . 

Regards,
Pradeep.

**Comment by koo-taejin** [comment]
@snmsmanager 

I can say that stability has been ensured because the Thrift base has been maintained for so long.
We are continuing test on gRpc base. But it's hard to say gRpc is as ensured as thrift.
However, I would say that the gRpc will be more stable than Thrift in the future because we will focus on gRpc connection. 

thanks :)

**Comment by snmsmanager** [comment]
Hi Koo, 

thanks for your extended support ...
