### ISSUE TITLE
Pinpoint Setup Fails On Tomcat-8

### ISSUE THREAD

**Issue by beetisushruth** [naver/pinpoint#6680]
#### What version of pinpoint are you using?
master/v2.0.1

#### Describe your problem**
I'm not able to start pinpoint on my tomcat, I've been stuck for 2 days. Logs say Failed to stream, name=SpanStream-1, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception. Please help me on how to get pinpoint up and running.
My system details:
Server version name:   Apache Tomcat/8.5.53
Server built:          Mar 11 2020 10:01:39 UTC
Server version number: 8.5.53.0
Name:               Linux
 OS Version:            3.10.0-957.10.1.el7.x86_64
 Architecture:          amd64
Java Home:             /usr/lib/java/jdk1.8.0_111/jre
JVM Version:           1.8.0_111-b14
JVM Vendor:            Oracle Corporation
CATALINA_BASE:         /home/developer/apache-tomcat-8.5.53
CATALINA_HOME:         /home/developer/apache-tomcat-8.5.53
Command line argument: -Djava.util.logging.config.file=/home/developer

#### What have you done?
1. I've followed the instructions here, https://naver.github.io/pinpoint/1.7.3/installation.html1 to setup pinpoint on tomcat-8 server.
2. I've downloaded the pinpoint-collector.war, pinpoint-web.war and agent jar from the latest release i.e 2.0.1
3. CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/developer/pinpoint/pinpoint-agent-2.0.1/pinpoint-bootstrap-2.0.1.jar"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.agentId=1"
CATALINA_OPTS="$CATALINA_OPTS -Dpinpoint.applicationName=sample"
included the above code in catalina.sh file in tomcat.
4.Deployed the collector war and web war in webapps folder, renames web war as ROOT.war, made some changes as per the documentation.
5. started the tomcat.

#### Logs
`2020-04-03 17:16:13 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) agent Lib:file:/home/developer/pinpoint/pinpoint-agent-2.0.1/lib/
2020-04-03 17:16:13 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) agent config:/home/developer/pinpoint/pinpoint-agent-2.0.1/pinpoint.config
2020-04-03 17:16:13 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent [com.navercorp.pinpoint.profiler.DefaultAgent] starting...
2020-04-03 17:16:17 [INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
2020-04-03 17:16:18 [WARN ](c.n.p.p.s.g.ResponseStreamObserver ) Failed to stream, name=SpanStream-1, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9993
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2020-04-03 17:16:18 [WARN ](c.n.p.p.r.g.GrpcCommandService     ) Failed to command stream, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9991
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

what might be the problem here?

**Comment by snmsmanager** [comment]
It seems your collector is not running and it is not listen GRPC ports ( 9991, 9992,9993).
**"io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9991"**

**Comment by beetisushruth** [comment]
Hi, according to the docs, collector uses default ports 9994, 9995, 9996. Right?

**Comment by RoySRose** [comment]
@beetisushruth 
From v2.0.0 9991,2,3 is the default port.

**Comment by beetisushruth** [comment]
Hi, from v2.0.0 default ports are changed, I tried the setup process using v1.8.5 now, I get the following error:
`[WARN ](.r.c.ConnectionFactory$ConnectEvent) try reconnect. connectAddress:DnsSocketAddressProvider{host='127.0.0.1', port=9994}`
Somehow it is not able to connect to 9994. How should I solve it?

**Comment by beetisushruth** [comment]
Can anyone give me a detailed instruction on how to setup collector in tomcat with pinpoint 2.0.1, 
These are the instructions given:
There are 3 configuration files available for Pinpoint Collector: pinpoint-collector.properties, pinpoint-grpc-collector.properties, and hbase.properties.

pinpoint-collector.properties - contains configurations for the collector. Check the following values with the agent’s configuration options :
collector.receiver.base.port (agent’s profiler.collector.tcp.port - default: 9994)
collector.receiver.stat.udp.port (agent’s profiler.collector.stat.port - default: 9995)
collector.receiver.span.udp.port (agent’s profiler.collector.span.port - default: 9996)
pinpoint-grpc-collector.properties - contains configurations for the grpc.
collector.receiver.grpc.agent.port (agent’s profiler.transport.grpc.agent.collector.port, profiler.transport.grpc.metadata.collector.port - default: 9991)
collector.receiver.grpc.stat.port (agent’s profiler.transport.grpc.stat.collector.port - default: 9992)
collector.receiver.grpc.stat.port  (agent’s profiler.transport.grpc.span.collector.port - default: 9993)
hbase.properties - contains configurations to connect to HBase.
hbase.client.host (default: localhost)
hbase.client.port (default: 2181)
These files are located under WEB-INF/classes/ inside the war file.

pinpoint-collector.properties file doesn't contain collector.receiver.grpc.agent.port, collector.receiver.grpc.stat.port, collector.receiver.grpc.span.port these configurations  should I add them manually?

Profiles
Add -Dkey=value to Java System Properties

WEB-INF/classes/profiles/$PROFILE
-Dspring.profiles.active=release or local
Default profile : release
Support external property
-Dpinpoint.zookeeper.address=$MY_ZOOKEEPER_ADDRESS -Dhbase.rpc.timeout=30000 …
Support external config
-Dpinpoint.web.config.location=$MY_EXTERNAL_CONFIG_PATH
Add custom profile
Create a custom profile in WEB-INF/classes/profiles/MyProfile
Add *-env.config & log4j.xml
Add -Dspring.profiles.active=MyProfile

Should I add -Dkey=value as CATALINA_OPTS in tomcat catalina.sh? Why am i creating a custom profile? Can anyone help me with this setup on tomcat 8, would be much grateful. Thanks.

**Comment by emeroad** [comment]
> Should I add -Dkey=value as CATALINA_OPTS in tomcat catalina.sh?

-Dpinpoint.zookeeper.address=127.0.0.1 <- Enter your zookeeper address.

> Why am i creating a custom profile? 

This is optional. Make it only when you need it.

**Comment by beetisushruth** [comment]
Thanks @emeroad will try it out. Where should I add collector.receiver.grpc.agent.port, collector.receiver.grpc.stat.port, collector.receiver.grpc.span.port  configurations?

**Comment by RoySRose** [comment]
@beetisushruth 
You don't have to add 
- collector.receiver.grpc.agent.port
- collector.receiver.grpc.stat.port
- collector.receiver.grpc.span.port configurations

These are already set in the config files.
Since the Connection has been refused, please check your network(firewall etc.), and your collector server if it's up and working

**Comment by beetisushruth** [comment]
@RoySRose I was able to start it. Problem was I used a single tomcat instance to start all the three (collector, web, agent). Thank you.
