### ISSUE TITLE
WebSphere exception

### ISSUE THREAD

**Issue by tytyty123** [naver/pinpoint#6696]
help, I' ve no idea...

2020-06-01 19:33:08 [INFO ](ebContainerHandleRequestInterceptor) Failed to servlet request event handle. 
java.lang.StringIndexOutOfBoundsException 
      at java.lang.String.substring(String.java:1150) 
      at com.navercorp.pinpoint.plugin.websphere.IRequestParameterExtractor.splitQuery(IRequestParameterExtractor.java:76) 
      at com.navercorp.pinpoint.plugin.websphere.IRequestParameterExtractor.extractParameter(IRequestParameterExtractor.java:46) 
      at com.navercorp.pinpoint.plugin.websphere.IRequestParameterExtractor.extractParameter(IRequestParameterExtractor.java:31) 
      at com.navercorp.pinpoint.plugin.websphere.MethodFilterExtractor.extractParameter(MethodFilterExtractor.java:42) 
      at com.navercorp.pinpoint.plugin.websphere.MethodFilterExtractor.extractParameter(MethodFilterExtractor.java:27) 
      at com.navercorp.pinpoint.bootstrap.plugin.request.util.HttpParameterRecorder.record(HttpParameterRecorder.java:40) 
      at com.navercorp.pinpoint.bootstrap.plugin.request.ServletRequestListenerInterceptorHelper.destroyed(ServletRequestListenerInterceptorHelper.java:159) 
      at com.navercorp.pinpoint.plugin.websphere.interceptor.WebContainerHandleRequestInterceptor.after(WebContainerHandleRequestInterceptor.java:94) 
      at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:49) 
      at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1876) 
      at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200) 
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463) 
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530) 
      at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316) 
      at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) 
      at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) 
      at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) 
      at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) 
      at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) 
      at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) 
      at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) 
      at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) 
      at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)

**Comment by emeroad** [comment]
Thanks for your reporting

https://github.com/naver/pinpoint/blob/master/plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/IRequestParameterExtractor.java#L75
```
private Map<String, String> splitQuery(String query) throws UnsupportedEncodingException {
        Map<String, String> query_pairs = new LinkedHashMap<String, String>();
        if (query != null) {
            String[] pairs = query.split("&");
            for (String pair : pairs) {
                int idx = pair.indexOf('=');
                // if (idx == -1) ~~~~  <---- The index check is missing.
                query_pairs.put(URLDecoder.decode(pair.substring(0, idx), "UTF-8"), URLDecoder.decode(pair.substring(idx + 1), "UTF-8"));
            }
        }
        return query_pairs;
    }
```

**Comment by tytyty123** [comment]
> Thanks for your reporting
> 
> https://github.com/naver/pinpoint/blob/master/plugins/websphere/src/main/java/com/navercorp/pinpoint/plugin/websphere/IRequestParameterExtractor.java#L75
> 
> ```
> private Map<String, String> splitQuery(String query) throws UnsupportedEncodingException {
>         Map<String, String> query_pairs = new LinkedHashMap<String, String>();
>         if (query != null) {
>             String[] pairs = query.split("&");
>             for (String pair : pairs) {
>                 int idx = pair.indexOf('=');
>                 // if (idx == -1) ~~~~  <---- The index check is missing.
>                 query_pairs.put(URLDecoder.decode(pair.substring(0, idx), "UTF-8"), URLDecoder.decode(pair.substring(idx + 1), "UTF-8"));
>             }
>         }
>         return query_pairs;
>     }
> ```

The version of pinpoint I used is 2.0.1.  Hasn't it been solved?
