### ISSUE TITLE
How to configure multiple collectors

### ISSUE THREAD

**Issue by qizai123** [naver/pinpoint#6730]
Hi, please ask, when I have multiple "pinpoint-collector", I hope to provide it to "pinpoint-agent" through Nginx middleware agent, but I get the error below

about version：pinpoint v2.0.1

Nginx configure:

```shell
upstream collector_pool {
        server 10.3.2.41:8080  max_fails=2 fail_timeout=3s;
        server 10.3.2.42:8080  max_fails=2 fail_timeout=3s;
}


server {
        listen 80;
        server_name collector.mgt.tarsapi.com;

        access_log  /var/log/nginx/collector.mgt.tarsapi.com.log  json;
        error_log  /var/log/nginx/collector.mgt.tarsapi.com.error  error;

        location / {
        proxy_set_header Host $http_host;
        proxy_pass http://collector_pool;
        }

}

# I have also configured [9991,9992,9993] port load balancing
```

Agent error info:

```shell
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```

Does the agent itself support multiple collector configuration methods without the help of Nginx middleware? Thank you in advance for your guidance

**Comment by koo-taejin** [comment]
hi @qizai123 

Pinpoint agent does not have function that agent sends message for multiple collector.
Even us use DNS  for it.

Additionally, we haven't tried nginx either.
I am not sure that nginx can seperate message, because we use stream of http2 through Grpc.

If you success this working, please post it here.
It will be to help for most of Pinpoint user.

thanks :)

**Comment by yjqg6666** [comment]
@qizai123 u could use Nginx as a LB. Collector is using TCP/UDP to receive data, not http. What you need is nginx stream module. You may reference http://nginx.org/en/docs/stream/ngx_stream_core_module.html and https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/.

**Comment by qizai123** [comment]
I solved this problem through Nginx's TCP / UDP proxy, But I suggest you use DNS to solve this problem, But hope to help others, thank you for your generous help @yjqg6666 @koo-taejin 
About version: pinpoint 2.0.1
About Nginx config

```
upstream collector_pool {
	server 10.3.2.41:8080  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:8080  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9991 {
	server 10.3.2.41:9991  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9991  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9992 {
	server 10.3.2.41:9992  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9992  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9993 {
	server 10.3.2.41:9993  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9993  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9994 {
	server 10.3.2.41:9994  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9994  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9995 {
	server 10.3.2.41:9995  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9995  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9996 {
	server 10.3.2.41:9996  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9996  max_fails=2 fail_timeout=3s;
}
upstream collector_pool_9997 {
	server 10.3.2.41:9997  max_fails=2 fail_timeout=3s;
	server 10.3.2.42:9997  max_fails=2 fail_timeout=3s;
}

server {
        listen 10.3.1.25:8080;
        proxy_pass collector_pool;
}
server {
        listen 10.3.1.25:9991;
        proxy_pass collector_pool_9991;
}
server {
        listen 10.3.1.25:9992;
        proxy_pass collector_pool_9992;
}
server {
        listen 10.3.1.25:9993;
        proxy_pass collector_pool_9993;
}
server {
        listen 10.3.1.25:9994;
        proxy_pass collector_pool_9994;
}
server {
        listen 10.3.1.25:9995 udp;
        proxy_pass collector_pool_9995;
}
server {
        listen 10.3.1.25:9996 udp;
        proxy_pass collector_pool_9996;
}
server {
        listen 10.3.1.25:9997;
        proxy_pass collector_pool_9997;
}
```
