### ISSUE TITLE
Agent startup fails if use oracle jdk11(ClassNotFoundException:JavaLangAccess/SharedSecrets)

### ISSUE THREAD

**Issue by messi-gao** [naver/pinpoint#6752]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
Pinpoint Agent 2.0.1.

#### Describe the bug
**Oracle JDK11.**
Springboot(2.2.6.RELEASE) **Webflux**.
Redisson(3.12.4)

#### What did you do to trigger the bug?
Server starts up.

#### Logs
If applicable, please attach agent/collector/web DEBUG log that includes the code execution that led to the bug. In case of agents, including the start-up log may be of great help.

> 2020-05-14 21:03:18 [WARN ](c.n.p.p.i.c.JavaLangAccessHelper   ) Failed to initialized JavaLangAccess Object
java.lang.ClassNotFoundException: jdk.internal.misc.SharedSecrets
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader.loadClass(Java9ClassLoader.java:116)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:1289)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.findSharedSecretsClass(JavaLangAccessHelper.java:109)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.initJavaLangAccessObject(JavaLangAccessHelper.java:66)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.access$000(JavaLangAccessHelper.java:31)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper$JavaLangAccessObjectHolder.<clinit>(JavaLangAccessHelper.java:135)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.getJavaLangAccessObject(JavaLangAccessHelper.java:50)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.shutdown.Java9ShutdownHookRegister.<clinit>(Java9ShutdownHookRegister.java:34)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.ShutdownHookRegisterProvider.createShutdownHookRegister(ShutdownHookRegisterProvider.java:108)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.ShutdownHookRegisterProvider.get(ShutdownHookRegisterProvider.java:78)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.registerStopHandler(DefaultAgent.java:174)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:134)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
2020-05-14 21:03:18 [WARN ](c.n.p.p.i.c.JavaLangAccessHelper   ) Failed to initialized registerShutdownHook MethodHandle
java.lang.ClassNotFoundException: jdk.internal.misc.JavaLangAccess
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at com.navercorp.pinpoint.bootstrap.java9.classloader.Java9ClassLoader.loadClass(Java9ClassLoader.java:116)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findClass(MethodHandles.java:1289)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.findJavaLangAccessClass(JavaLangAccessHelper.java:117)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.initRegisterShutdownHookMethodHandle(JavaLangAccessHelper.java:82)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.access$100(JavaLangAccessHelper.java:31)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper$RegisterShutdownHookMethodHandleHolder.<clinit>(JavaLangAccessHelper.java:139)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.instrument.classloading.JavaLangAccessHelper.getRegisterShutdownHookMethodHandle(JavaLangAccessHelper.java:54)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.shutdown.Java9ShutdownHookRegister.<clinit>(Java9ShutdownHookRegister.java:35)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.ShutdownHookRegisterProvider.createShutdownHookRegister(ShutdownHookRegisterProvider.java:108)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.context.provider.ShutdownHookRegisterProvider.get(ShutdownHookRegisterProvider.java:78)
	at pinpoint.agent/pinpoint.agent/com.navercorp.pinpoint.profiler.DefaultAgent.registerStopHandler(DefaultAgent.java:174)
	at com.navercorp.pinpoint.bootstrap.PinpointStarter.start(PinpointStarter.java:134)
	at com.navercorp.pinpoint.bootstrap.PinpointBootStrap.premain(PinpointBootStrap.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)

**Comment by emeroad** [comment]
@messi-gao 
Thanks for the report

I will check this issue

**Comment by messi-gao** [comment]
@emeroad Do you have some process about this issure?

**Comment by emeroad** [comment]
@messi-gao
Sorry. I haven't proceeded yet.

Could you make a sample project for me to reproduce?

**Comment by messi-gao** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.6.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>com.example</groupId>
    <artifactId>redisson_example</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>redisson_example</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.14</version>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.12.4</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-web</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.jasync-sql</groupId>
            <artifactId>jasync-r2dbc-mysql</artifactId>
            <version>1.0.17</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-r2dbc</artifactId>
            <version>1.0.0.RELEASE</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
`
@emeroad Use **JDK11** and create a maven project like above.

**Comment by messi-gao** [comment]
This bug only appears in **Oracle jdk**11,you should change to use OpenJDk/AdoptOpenJDK to avoid this bug.

From the log,we can see the classes such as `jdk.internal.misc.SharedSecrets`,`jdk.internal.misc.JavaLangAccess` cound not be found,it is because in **Oracle jdk**11 ,the path of `SharedSecrets`/ `JavaLangAccess ` and is different from OpenJDk/AdoptOpenJDK.

**Oracle jdk**11 `jdk.internal.access.SharedSecrets`:
![image](https://user-images.githubusercontent.com/24312100/81940220-f1a26a00-9629-11ea-9dcc-6adf0b10360f.png)

**AdoptOpenJDK**11 `jdk.internal.misc.SharedSecrets`:
![image](https://user-images.githubusercontent.com/24312100/81940651-6675a400-962a-11ea-8bdb-34d6d480a22e.png)

Before Pinpoint-agent v2.0.2, it could not load the  `jdk.internal.access.SharedSecrets` of **Oracle jdk**11,click [here ](https://github.com/naver/pinpoint/blob/v2.0.2/profiler-optional/profiler-optional-jdk9/src/main/java/com/navercorp/pinpoint/profiler/instrument/classloading/JavaLangAccessHelper.java#L34)to see the Implementation.

This bug will be fixed in next release.

All the above analysis is provided by @emeroad ,Thanks for your support .
