### ISSUE TITLE
Can't use quickstart app or use custom application based Spring

### ISSUE THREAD

**Issue by sruizdegopegui** [naver/pinpoint#6785]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [X] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
2.0.1

#### Describe your problem**
First of all, I am using kubernetes, I converted the official docker files to the yaml used by kubernetes.

The deployment process seems to have worked correctly, I can access the UI but it goes blank, I can access url / configuration.pinpoint and url / error, where I can see the attached image.

I access my application correctly via the web. But in pinpoint I have not been able to attach the agent, or make it capable of detecting the application.

[Pastebin with dockerfile and deployment file because bad format here](https://pastebin.com/nhJJD7Kb)

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Deploy PinPoint on kubernetes
2. Make custom image spring application
3. Tried attaching agent to custom application

### Screenshots
![pinpoint](https://user-images.githubusercontent.com/64840506/81690969-5e680980-945c-11ea-943b-d88152dbdf7a.png)

#### Logs
No errors on hbase log

Agent log
`sed -i '/profiler.transport.module=/ s/=.*/=GRPC/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.transport.module=/ s/=.*/=GRPC/' /pinpoint-agent/profiles/release/pinpoint-env.config
sed -i '/profiler.collector.ip=/ s/=.*/=pinpoint-collector/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.collector.tcp.port=/ s/=.*/=/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.collector.stat.port=/ s/=.*/=/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.collector.span.port=/ s/=.*/=/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.transport.grpc.collector.ip=/ s/=.*/=pinpoint-collector/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.transport.grpc.collector.ip=/ s/=.*/=pinpoint-collector/' /pinpoint-agent/profiles/release/pinpoint-env.config
sed -i '/profiler.transport.grpc.agent.collector.port=/ s/=.*/=9991/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.transport.grpc.metadata.collector.port=/ s/=.*/=9991/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.transport.grpc.stat.collector.port=/ s/=.*/=9992/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.transport.grpc.span.collector.port=/ s/=.*/=9993/' /pinpoint-agent/pinpoint.config
sed -i '/profiler.sampling.rate=/ s/=.*/=1/' /pinpoint-agent/profiles/release/pinpoint-env.config
sed -i '/level value=/ s/=.*/="INFO"\/>/g' /pinpoint-agent/profiles/release/log4j.xml
exec tail -f /dev/null`

Collector log
`
org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Tue May 12 13:15:01 UTC 2020, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68624: row 'ApplicationTr
aceIndex,,00000000000000' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=pinpoint-hbase-7bffbfd84f-smv82,4
3665,1589277589497, seqNum=0

2020-05-12 12:36:07 [WARN ](o.a.z.ClientCnxn                   ) Session 0x0 for server zoo1:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address zoo1:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
`

Web log
`2020-05-12 13:42:20 [WARN ](o.a.c.d.BasicDataSource            ) An internal object pool swallowed an Exception.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
`

and lot of...
`Tue May 12 13:44:20 UTC 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
`

#### Additional context
Add any other context about the problem here, such as affected library for agents, how your collector/web/hbase is set up if applicable.

**Comment by koo-taejin** [comment]
hi @sruizdegopegui 

If we look at the log you posted, Pinpoint collector and web seem to fail to connect Hbase and Zookeeper.
I think it will be ok if you solve the reason why they can not connect Hbase and Zookeeper. 

thanks

**Comment by sruizdegopegui** [comment]
Hi @koo-taejin 

I have modified the displays to try to know how to connect with each other, and now the errors are as follows

`collector log


2020-05-13 07:04:10 [WARN ](o.a.h.h.z.ZKUtil                   ) hconnection-0x42a2cbdb0x0, quorum=10.100.9.51:2181, baseZNode=/hbase Unable to get data of znode /hbase/meta
-region-server                                                                                                                                                               
org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:99)


2020-05-13 07:04:10 [ERROR](o.a.h.h.z.ZooKeeperWatcher         ) hconnection-0x42a2cbdb0x0, quorum=10.100.9.51:2181, baseZNode=/hbase Received unexpected KeeperException, re
-throwing exception                                                                                                                                                          
org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server                  
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:99)                                                               
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:51)                                                               
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)                                                                        
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.getData(RecoverableZooKeeper.java:354)                         

2020-05-13 07:04:10 [WARN ](c.n.p.c.h.ConnectionFactoryBean    ) Failed to warmup for Table:AgentEvent. message:Can't get the locations                                      
org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations                                                                                            
        at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:319) 
        
        
    
Web log

2020-05-13 07:08:30 [WARN ](o.a.h.h.s.o.a.z.ClientCnxn         ) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect           
java.net.ConnectException: Connection refused                                                                                                                                
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)                                                                                                          
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)                                                                                            
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)                                                 
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)                                                               
2020-05-13 07:08:31 [WARN ](o.a.h.h.s.o.a.z.ClientCnxn         ) Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect           
java.net.ConnectException: Connection refused                                                                                                                                
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)                                                                                                          
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)          
        
    
2020-05-13 07:08:49 [ERROR](o.a.h.h.z.ZooKeeperWatcher         ) hconnection-0x20cea4620x0, quorum=10.100.9.51:2181, baseZNode=/hbase Received unexpected KeeperException, re
-throwing exception                                                                                                                                                          
org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
     `

When deploying containers, should something be created in the volumes?

I have seen that mysql has several tables created, but how can I know if they are all necessary? in the documentation I have not known to find it

**Comment by koo-taejin** [comment]
@sruizdegopegui 

Log that you posted is not related with Mysql Table. 
If we look at it, It seems to fail to find location of the Hbase region where the AgentEvent "table is stored.

Please, dig in the Hbase further.

thanks :)

**Comment by sruizdegopegui** [comment]
Hi @koo-taejin


When i building collector deploy i added ip hbase to test it, but in log appears their hostname.

I have this error on collector log now...

`Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68521: row 'ApiMetaData,,00000000000000' on table 'hbase:meta' at region=hbase:meta,,1.1588230740
, hostname=pinpoint-hbase-7bffbfd84f-smv82,43665,1589277589497, seqNum=0                                                                                                     
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:169)                                                                      
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)                                          
        ... 3 more                                                                                                                                                           
Caused by: java.net.UnknownHostException: pinpoint-hbase-7bffbfd84f-smv82                                                      
`

No errors on web.

Hbase log now:

`
2020-05-14 08:20:48,788 WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: caught end of stream exception                                               
EndOfStreamException: Unable to read additional data from client sessionid 0x17208537293001a, likely client has closed socket                                                
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)                                                                                            
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)                                                                               
        at java.lang.Thread.run(Thread.java:745)       

2020-05-14 08:21:00,357 WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181] server.NIOServerCnxn: caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x17208537293001b, likely client has closed socket
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
        at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
        at java.lang.Thread.run(Thread.java:745)  
`
