### ISSUE TITLE
running collector & web 2.0.2 on tomcat 9

### ISSUE THREAD

**Issue by kevintruman** [naver/pinpoint#6786]
I use HBase standalone mode, then I deploy war file collector and web to Tomcat 9. When I check log in Tomcat, it appears like this repeatedly

`2020-05-12 23:40:32 [WARN ](o.a.h.h.z.RecoverableZooKeeper     ) Unable to create ZooKeeper Connection
java.net.UnknownHostException: {YOUR_RELEASE_ZOOKEEPER_ADDRESS}
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
        at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.checkZk(RecoverableZooKeeper.java:141)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:220)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:419)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:65)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:916)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:659)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:637)
...`

I only use the default configuration of pinpoint version 2.0.2 and I didn't change it. Is there something wrong with the way I installed it?
I open http://localhost:8080/pinpoint-web-2.0.2 only appears 404

**Comment by koo-taejin** [comment]
@kevintruman 
Please check this issue #6647 

thanks :)
