### ISSUE TITLE
Can'f find any doc or guide to hook docker application with pinpoint agent. 

### ISSUE THREAD

**Issue by Saptarshi510** [naver/pinpoint#6811]
hi , 
The tool is amazing but it very difficult to find few info like , how we can simply run a hello-world in java container and hook that container with pinpoint agent running in docker .
Simple doc or guide or an example will be really helpful .

Thank you in advance!

**Comment by vikasmsg** [comment]
RUN wget https://github.com/naver/pinpoint/releases/download/v2.0.1/pinpoint-agent-2.0.1.tar.gz
RUN tar -xvf pinpoint-agent-2.0.1.tar.gz; rm pinpoint-agent-2.0.1.tar.gz; mv pinpoint-agent-2.0.1/ pinpoint-agent/; rm pinpoint-agent/pinpoint.config; rm pinpoint-agent/profiles/release/pinpoint-env.config
RUN mv pinpoint-agent /
COPY pinpoint.config /pinpoint-agent/
COPY pinpoint-env.config /pinpoint-agent/profiles/release/
RUN chown -R root. /pinpoint-agent

**Comment by vikasmsg** [comment]
pass this in java_opts 

-javaagent:/pinpoint-agent/pinpoint-bootstrap.jar -Dpinpoint.applicationName=hello-world -Dpinpoint.agentId=hello-world

**Comment by Saptarshi510** [comment]
Hey Vikas, 

Thank you for your help buddy , but i still facing few issues , my pinpoint setup is running on top of docker , all the services are running well , even the "quickapp" also visible on pinpoint and i am able to see the request coming in. 
The problem i am facing now is while uploading the jar - pinpoint-flink-job-2.0.2.jar

```
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:545)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:419)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:80)
	at org.apache.flink.client.program.ClusterClient.getOptimizedPlan(ClusterClient.java:318)
	at org.apache.flink.runtime.webmonitor.handlers.JarActionHandler.getJobGraphAndClassLoader(JarActionHandler.java:72)

-----
Caused by: org.apache.flink.api.common.InvalidProgramException: The LocalStreamEnvironment cannot be used when submitting a program through a client, or running in a TestEnvironment context.
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.<init>(LocalStreamEnvironment.java:68)
	at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.<init>(LocalStreamEnvironment.java:58)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.createLocalEnvironment(StreamExecutionEnvironment.java:1626)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.createLocalEnvironment(StreamExecutionEnvironment.java:1612)
	at com.navercorp.pinpoint.flink.Bootstrap.createStreamExecutionEnvironment(Bootstrap.java:163)
	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.start(StatStreamingVer2Job.java:57)
	at com.navercorp.pinpoint.flink.StatStreamingVer2Job.main(StatStreamingVer2Job.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:528)
```
I have followed the steps according to doc. 

My sample Java application is running - 
My docker run command - 
docker run --name spring-boot -e JAVA_OPTS='-javaagent:/pinpoint-agent/pinpoint-bootstrap.jar -Dpinpoint.applicationName=spring-boot -Dpinpoint.agentId=spring-boot' -p 9014:8080 -t -d -it  spring-boot:1.0

My Dockerfile - pls correct me if i doing anything wrong.
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/spring-boot-web.jar
COPY . /var/www/java
COPY pinpoint-agent-2.0.2.tar.gz .
RUN tar -xvf pinpoint-agent-2.0.2.tar.gz; rm pinpoint-agent-2.0.2.tar.gz;
RUN mv pinpoint-agent-2.0.2/ pinpoint-agent/;
RUN rm pinpoint-agent/pinpoint.config; rm pinpoint-agent/profiles/release/pinpoint-env.config
COPY pinpoint.config /pinpoint-agent/
COPY pinpoint-env.config /pinpoint-agent/profiles/release/
RUN chown -R root. /pinpoint-agent
WORKDIR /opt/app
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]



Thank you !
