### ISSUE TITLE
Pinpoint Setup Fails on jar 

### ISSUE THREAD

**Issue by xingyaa** [naver/pinpoint#6932]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [x] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
master/v2.0.2

#### Describe your problem**
A clear and concise description of what is not working.

#### What have you done?
1,i have change agent configuration about collector ip

1, i run command as follows :
exec java -jar -Xms768m -Xmx768m -javaagent:/home/res/pinpoint-agent-2.0.2/pinpoint-bootstrap-2.0.2.jar -Dspring.profiles.active=dev -Dpinpoint.agentId=20200622 -Dpinpoint.applicationName=ERP jshERP2.0.jar 

>> my collecor  deployed on docker 
[root@localhost service]# netstat -tunlp | grep 9991
tcp6       0      0 :::9991                 :::*                    LISTEN      21726/docker-proxy  
udp6       0      0 :::9991                 :::*                                21738/docker-proxy  

>> just my agent deployed on another machine 
>> my firewall and seliux all down

#### Logs
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9991
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2020-06-22 14:49:46 [WARN ](c.n.p.p.s.g.ResponseStreamObserver ) Failed to stream, name=StatStream-142, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9992
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2020-06-22 14:49:49 [WARN ](c.n.p.p.s.g.ResponseStreamObserver ) Failed to stream, name=SpanStream-143, cause=UNAVAILABLE: io exception
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9993
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by yjqg6666** [comment]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9991
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9992
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9993

Your collector is not running or started correctly, no application listening on port 9991/9992/9993.

**Comment by xingyaa** [comment]
thanks for your reply , i have checked my port,its all open 

so i dont know what's the problem is ?

[root@localhost ~]# netstat -tunlp | grep 9991
tcp6       0      0 :::9991                 :::*                    LISTEN      21726/docker-proxy  
udp6       0      0 :::9991                 :::*                                21738/docker-proxy  
[root@localhost ~]# netstat -tunlp | grep 9992
tcp6       0      0 :::9992                 :::*                    LISTEN      21712/docker-proxy  
[root@localhost ~]# netstat -tunlp | grep 9993
tcp6       0      0 :::9993                 :::*                    LISTEN      21698/docker-proxy  
[root@localhost ~]# netstat -tunlp | grep 9994
tcp6       0      0 :::9994                 :::*                    LISTEN      21686/docker-proxy  
[root@localhost ~]# netstat -tunlp | grep 9995
tcp6       0      0 :::9995                 :::*                    LISTEN      21656/docker-proxy  
udp6       0      0 :::9995                 :::*                                21672/docker-proxy  
[root@localhost ~]# netstat -tunlp | grep 9996
tcp6       0      0 :::9996                 :::*                    LISTEN      21628/docker-proxy  
udp6       0      0 :::9996                 :::*                                21642/docker-proxy  
[root@localhost ~]# netstat -tunlp | grep 9997
tcp6       0      0 :::9997                 :::*                    LISTEN      21862/docker-proxy

**Comment by yjqg6666** [comment]
You are connecting to the collector using IPv4 while your collector is listening on IPv6 only. 
>Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9991
>Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9992
>Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9993

> tcp6 0 0 :::9997 :::* LISTEN 21862/docker-proxy
> tcp6 0 0 :::9996 :::* LISTEN 21628/docker-proxy
> tcp6 0 0 :::9995 :::* LISTEN 21656/docker-proxy

if you want to use IPv6, the host should be ::1.

**Comment by seocho2360** [comment]
would you please explain this sentence

""
You are connecting to the collector using IPv4 while your collector is listening on IPv6 only.

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9991
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9992
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9993

tcp6 0 0 :::9991 :::* LISTEN 21726/docker-proxy
tcp6 0 0 :::9992 :::* LISTEN 21712/docker-proxy
tcp6 0 0 :::9993 :::* LISTEN 21698/docker-proxy

if you want to use IPv6, the host should be ::1.
""
@yjqg6666

**Comment by seocho2360** [comment]
이 문장을 설명해 주 시겠어요

""
수집기가 IPv6에서만 수신하는 동안 IPv4를 사용하여 수집기에 연결합니다.

원인 : io.netty.channel.AbstractChannel $ AnnotatedConnectException : 연결 거부 : /127.0.0.1:9991
원인 : io.netty.channel.AbstractChannel $ AnnotatedConnectException : 연결 거부 : /127.0.0.1:9992
원인 : io.netty .channel.AbstractChannel $ AnnotatedConnectException : 연결 거부 : /127.0.0.1:9993

tcp6 0 0 ::: 9991 ::: * LISTEN 21726 / docker-proxy
tcp600 ::: 9992 ::: * LISTEN 21712 / docker-proxy
tcp600 ::: 9993 ::: * 21698 / docker- 듣기 대리

IPv6를 사용하려면 호스트가 :: 1이어야합니다.
""
@ yjqg6666

**Comment by yjqg6666** [comment]
Your agent is connecting to the collector using IPv4 while your collector is listening on IPv6 only. 

Either change the collector config or change config of the agent. They should be both IPv4 or IPv6.

**Comment by seocho2360** [comment]
Where are the collectors and agents configured?
Can you explain the path and setting method?

**Comment by yjqg6666** [comment]
http://naver.github.io/pinpoint/installation.html#configuration-2 and http://naver.github.io/pinpoint/installation.html#3-pinpoint-collector

Simply disable IPv6 may quickly solve your issue.

**Comment by yjqg6666** [comment]
@seocho2360 run your collectors with an additional java property: -Djava.net.preferIPv4Stack=true
