### ISSUE TITLE
NoClassDefFoundError exception during microservice startup

### ISSUE THREAD

**Issue by HanishRamc** [naver/pinpoint#6953]
#### Prerequisites
Please check the [FAQ](http://naver.github.io/pinpoint/faq.html), and search existing [issues](https://github.com/naver/pinpoint/issues) for similar questions before creating a new issue.**YOU MAY DELETE THIS PREREQUISITES SECTION.**

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v2.0.3 -pinpoint -agent

Problem
Received java.lang.ClassNotFoundException: org.apache.http.HttpHost exception during my spring boot service start .

#### What have you done?
Steps you have taken to trigger the problem, for example:
1. Enable  pinpoint using 
-javaagent:/opt/dev/tools/pinpoint-agent/pinpoint-bootstrap-2.0.3-SNAPSHOT.jar -Dpinpoint.agentId=service1 -Dpinpoint.applicationName=myapp
 
2. Tried to start micro service using org.springframework.boot.loader.JarLauncher
3. verify the logs and service availability 
4. In logs i could see the above said exception

#### Logs
Stack trace 
020-06-29 01:33:26 [ERROR](c.n.p.p.BaseClassFileTransformer   ) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:jar:file:/application/versions/2.4.1.RELEASE.04/service-2.4.1.RELEASE.04.jar!/lib/elasticsearch-rest-client-6.5.0.jar!/ cl:org.springframework.boot.loader.LaunchedURLClassLoader@27b71f50 ctxCl:org.springframework.boot.loader.LaunchedURLClassLoader@27b71f50 agentCl:ParallelClassLoader@1878246837{name='pinpoint.agent'} Cause:[Lorg/apache/http/HttpHost;
java.lang.NoClassDefFoundError: [Lorg/apache/http/HttpHost;
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at com.navercorp.pinpoint.profiler.instrument.AccessorAnalyzer.analyze(AccessorAnalyzer.java:33)
        at com.navercorp.pinpoint.profiler.instrument.ASMClass.addField(ASMClass.java:264)
        at com.navercorp.pinpoint.plugin.elasticsearch.ElasticsearchPlugin$ConnectorTransformCallback.doInTransform(ElasticsearchPlugin.java:113)
        at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:66)
        at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
        at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510)
        at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:697)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:640)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:609)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1484)
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1007)
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:168)

**Comment by emeroad** [comment]
It seems to be incompatible with `elasticsearch-rest-client-6.5.0.jar`. 
Disable this plugin.

**Comment by HanishRamc** [comment]
Thanks for you response .

I disabled elastic search and now getting other error "NoClassDefFoundError: ch/qos/logback/classic/spi/LoggingEvent" 
https://github.com/naver/pinpoint/issues/6954

pinpoint-agent config
###########################################################
# Elasticsearch
###########################################################
profiler.elasticsearch.enabled=false
profiler.elasticsearch.recordDsl=false
profiler.elasticsearch.recordESVersion=false

###########################################################
# ElasticsearchBBoss
###########################################################
profiler.elasticsearchbboss.enabled=false
profiler.elasticsearchbboss.recordResult=false
profiler.elasticsearchbboss.recordArgs=true
profiler.elasticsearchbboss.recordDsl=true
profiler.elasticsearchbboss.recordESVersion=true
profiler.elasticsearchbboss.recordResponseHandlerClass=false
profiler.elasticsearchbboss.maxDslSize=50000
