### ISSUE TITLE
java.lang.Exception: job fail : [Aggregation Stat Data]

### ISSUE THREAD

**Issue by luckykeith** [naver/pinpoint#6982]
v2.0.3 pinpoint-web logging error

I think something error in HealthCheckTaskletV2 class
    public HealthCheckTaskletV2() {
        this.jobNameList = new ArrayList<>(1);
        jobNameList.add("Aggregation Stat Data");
    }
because this construct method， this exception must be throwed

log:
2020-07-07 04:20:00 [ERROR](o.s.b.c.s.AbstractStep             ) Encountered an error executing step flinkCheckStep in job flinkCheckJob
java.lang.Exception: job fail : [Aggregation Stat Data]
        at com.navercorp.pinpoint.web.batch.flink.HealthCheckTaskletV2.execute(HealthCheckTaskletV2.java:92)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)

**Comment by minwoo-jung** [comment]
@luckykeith 
Please share full error log message. 
I can't see the root cause log message.

**Comment by luckykeith** [comment]
not a real issue
