### ISSUE TITLE
JDK6 compiler bug workarounds

### ISSUE THREAD

**Issue by emeroad** [naver/pinpoint#7050]
JDK6 compiler throws an error when adding log4j2 lib

Compiler version: 1.6.0_45
```
[INFO] Compiling 284 source files to C:\pin\pinpoint\profiler\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An exception has occurred in the compiler (1.6.0_45). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NullPointerException
	at com.sun.tools.javac.code.Symbol$MethodSymbol.params(Symbol.java:1196)
	at com.sun.tools.javac.jvm.ClassReader.attachParameterAnnotations(ClassReader.java:1111)
	at com.sun.tools.javac.jvm.ClassReader.readMemberAttr(ClassReader.java:871)
	at com.sun.tools.javac.jvm.ClassReader.readMemberAttrs(ClassReader.java:1027)
	at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:1490)
	at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:1586)
	at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:1658)
	at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:1845)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:1777)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
	at com.sun.tools.javac.jvm.ClassReader.completeOwners(ClassReader.java:1793)
	at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:1772)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.getSuperclass(Symbol.java:788)
	at com.sun.tools.javac.code.Types$18.visitClassType(Types.java:1610)
	at com.sun.tools.javac.code.Types$18.visitClassType(Types.java:1599)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:554)
	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:3260)
	at com.sun.tools.javac.code.Types.supertype(Types.java:1596)
	at com.sun.tools.javac.code.Types$14.visitClassType(Types.java:1295)
	at com.sun.tools.javac.code.Types$14.visitClassType(Types.java:1284)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:554)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:3203)
	at com.sun.tools.javac.code.Types.asSuper(Types.java:1281)
	at com.sun.tools.javac.code.Types$14.visitClassType(Types.java:1297)
	at com.sun.tools.javac.code.Types$14.visitClassType(Types.java:1284)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:554)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:3203)
	at com.sun.tools.javac.code.Types.asSuper(Types.java:1281)
	at com.sun.tools.javac.code.Types$5.visitClassType(Types.java:409)
	at com.sun.tools.javac.code.Types$5.visitClassType(Types.java:336)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:554)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:3203)
	at com.sun.tools.javac.code.Types.isSubtype(Types.java:332)
	at com.sun.tools.javac.code.Types.isSubtype(Types.java:316)
	at com.sun.tools.javac.code.Types$9.visitClassType(Types.java:937)
	at com.sun.tools.javac.code.Types$9.visitClassType(Types.java:880)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:554)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:3203)
	at com.sun.tools.javac.code.Types.isCastable(Types.java:871)
	at com.sun.tools.javac.comp.Check.checkCastable(Check.java:382)
	at com.sun.tools.javac.comp.Attr.visitTypeCast(Attr.java:1673)
	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1448)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:377)
	at com.sun.tools.javac.comp.Attr.visitAssign(Attr.java:1550)
	at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1342)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:384)
	at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1017)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1074)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:397)
	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:413)
	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:715)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:739)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:397)
	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:634)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:639)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:397)
	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:2697)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2628)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2564)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1045)
	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:768)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:730)
	at com.sun.tools.javac.main.Main.compile(Main.java:353)
	at com.sun.tools.javac.main.Main.compile(Main.java:279)
	at com.sun.tools.javac.main.Main.compile(Main.java:270)
	at com.sun.tools.javac.Main.compile(Main.java:69)
	at com.sun.tools.javac.Main.main(Main.java:54)
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

Reproduction Step
- Add log4j2 dependency to Profiler module
```
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.3</version>
            <scope>compile</scope>
        </dependency>
```
Related issue
- http://bugs.java.com/view_bug.do?bug_id=6889255
- https://github.com/cobertura/cobertura/issues/283

**Comment by emeroad** [comment]
Failed to compile ForwardingClientCall.
Replaced by a simpler class.
