### ISSUE TITLE
popinagent can not send info to collector

### ISSUE THREAD

**Issue by woaizhenli** [naver/pinpoint#7260]
2020-09-11 17:40:29 [INFO ](c.n.p.p.r.g.GrpcCommandDispatcher  ) close() started
2020-09-11 17:40:29 [INFO ](.p.r.g.GrpcActiveThreadCountService) close
2020-09-11 17:40:29 [INFO ](c.n.p.p.r.g.GrpcCommandDispatcher  ) close() completed
2020-09-11 17:40:30 [INFO ](c.n.p.p.s.g.AgentGrpcDataSender    ) newPingStream:PingStreamContext{PingStream-14}
2020-09-11 17:40:30 [INFO ](c.n.p.p.s.g.PingStreamContext      ) PingStream-14 onReady
2020-09-11 17:40:30 [INFO ](c.n.p.p.s.g.PingStreamContext      ) PingStream-14 success:
2020-09-11 17:40:30 [INFO ](c.n.p.p.r.g.GrpcCommandService     ) Attempt to connect to CommandServiceStream.
2020-09-11 17:40:30 [INFO ](c.n.p.p.r.g.GrpcCommandService     ) Connect to CommandServiceStream completed.
2020-09-11 17:40:47 [WARN ](c.n.p.p.s.g.ResponseStreamObserver ) Failed to stream, name=SpanStream-13, cause=UNAVAILABLE: Network closed for unknown reason
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-11 17:40:48 [INFO ](c.n.p.p.s.g.ResponseStreamObserver ) beforeStart:SpanStream-15
2020-09-11 17:40:48 [INFO ](c.n.p.p.s.g.ResponseStreamObserver ) onReadyHandler:SpanStream-15 eventNumber:0
2020-09-11 17:40:50 [WARN ](c.n.p.p.s.g.PingStreamContext      ) Failed to ping stream, streamId=PingStream-14, cause=UNAVAILABLE: Network closed for unknown reason

**Comment by yjqg6666** [comment]
You could try https://github.com/pinpoint-apm/pinpoint/issues/5931#issuecomment-1173479716 .
