### ISSUE TITLE
pinpoint2.0.3：For netty TCP application, do a monitoring plugin and report the following error，can anyone tell me how to solve it？thanks

### ISSUE THREAD

**Issue by caicha** [naver/pinpoint#7262]
2020-09-14 10:52:39 [ERROR](c.n.p.p.BaseClassFileTransformer   ) Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:file:/E:/workspace/baffle/rjm-baffle/target/classes/ cl:sun.misc.Launcher$AppClassLoader@18b4aac2 ctxCl:sun.misc.Launcher$AppClassLoader@18b4aac2 agentCl:ParallelClassLoader@468121027{name='pinpoint.agent'} Cause:Fail to invoke constructor: public com.navercorp.pinpoint.plugin.netty.interceptor.tcp.TCPDecoderInterceptor(com.navercorp.pinpoint.bootstrap.context.TraceContext,com.navercorp.pinpoint.bootstrap.context.MethodDescriptor), arguments: [com.navercorp.pinpoint.profiler.context.DefaultTraceContext@517bab91, {className=com.wx.route.TCPRequestDecoder, methodName=decode, parameterTypes=[io.netty.channel.ChannelHandlerContext, io.netty.buffer.ByteBuf, java.util.List], parameterVariableName=[ctx, in, out], parameterDescriptor=(io.netty.channel.ChannelHandlerContext ctx, io.netty.buffer.ByteBuf in, java.util.List out), apiDescriptor=com.wx.route.TCPRequestDecoder.decode(io.netty.channel.ChannelHandlerContext ctx, io.netty.buffer.ByteBuf in, java.util.List out), lineNumber=19, apiId=18, fullName=com.wx.route.TCPRequestDecoder.decode(io.netty.channel.ChannelHandlerContext ctx, io.netty.buffer.ByteBuf in, java.util.List out):19, type=0}]
com.navercorp.pinpoint.exception.PinpointException: Fail to invoke constructor: public com.navercorp.pinpoint.plugin.netty.interceptor.tcp.TCPDecoderInterceptor(com.navercorp.pinpoint.bootstrap.context.TraceContext,com.navercorp.pinpoint.bootstrap.context.MethodDescriptor), arguments: [com.navercorp.pinpoint.profiler.context.DefaultTraceContext@517bab91, {className=com.wx.route.TCPRequestDecoder, methodName=decode, parameterTypes=[io.netty.channel.ChannelHandlerContext, io.netty.buffer.ByteBuf, java.util.List], parameterVariableName=[ctx, in, out], parameterDescriptor=(io.netty.channel.ChannelHandlerContext ctx, io.netty.buffer.ByteBuf in, java.util.List out), apiDescriptor=com.wx.route.TCPRequestDecoder.decode(io.netty.channel.ChannelHandlerContext ctx, io.netty.buffer.ByteBuf in, java.util.List out), lineNumber=19, apiId=18, fullName=com.wx.route.TCPRequestDecoder.decode(io.netty.channel.ChannelHandlerContext ctx, io.netty.buffer.ByteBuf in, java.util.List out):19, type=0}]
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:107)
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:87)
	at com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.newInterceptor(AnnotatedInterceptorFactory.java:114)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.createInterceptor(ASMMethod.java:237)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.newInterceptor(ASMMethod.java:229)
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:297)
	at com.navercorp.pinpoint.plugin.netty.transformer.tcp.TCPDecoderTransformer.doInTransform(TCPDecoderTransformer.java:25)
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:66)
	at com.navercorp.pinpoint.profiler.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56)
	at com.navercorp.pinpoint.profiler.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:95)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.wx.route.TCPBaffleServer.createHandlers(TCPBaffleServer.java:26)
	at com.wx.route.AbstractBaffleServer$1.initChannel(AbstractBaffleServer.java:31)
	at com.wx.route.AbstractBaffleServer$1.initChannel(AbstractBaffleServer.java:28)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:590)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1355)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1090)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:640)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:456)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:378)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:428)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:105)
	... 41 more
Caused by: java.lang.NullPointerException
	at com.navercorp.pinpoint.plugin.netty.interceptor.tcp.TCPDecoderInterceptor.<init>(TCPDecoderInterceptor.java:40)
	... 46 more
2020-09-14 10:52:43 [INFO ](c.n.p.p.s.g.PingStreamContext      ) PingStream-2 success:

**Comment by caicha** [comment]
![image](https://user-images.githubusercontent.com/16550895/93039233-8e792080-f679-11ea-8ec8-5c7537810229.png)
