### ISSUE TITLE
weave error

### ISSUE THREAD

**Issue by Rwangyang** [naver/pinpoint#7279]
In pinpoint 2.x version, the jdk5 class(majorVersion =48) is used in the monitored system. When the weave method is used, the following error is reported, but there is no problem with jdk6+ or higher.  In pinpoint1.7X version, this problem did not appear, this is an upgrade bug??

java.lang.IllegalArgumentException: Class versions V1_5 or less must use F_NEW frames.
	at org.objectweb.asm.MethodWriter.visitFrame(MethodWriter.java:779)
	at org.objectweb.asm.tree.FrameNode.accept(FrameNode.java:134)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:465)
	at com.navercorp.pinpoint.profiler.instrument.ASMClassNodeAdapter.toByteArray(ASMClassNodeAdapter.java:574)
	at com.navercorp.pinpoint.profiler.instrument.ASMClass.toBytecode(ASMClass.java:800)

**Comment by jaehong-kim** [comment]
@Rwangyang 
It seems to be an error caused by the ASM library.
Check out [ASM](https://asm.ow2.io/versions.html).
