### ISSUE TITLE
quickstart에서 Collector, Web, testapp 실행시 에러...

### ISSUE THREAD

**Issue by yangbongsoo** [naver/pinpoint#786]
안녕하세요 제가 pinpoint 동영상을 보고 그대로 따라하면서 우분투 서버에 quickstart를 돌리려고 하는데요. 

설치 및 collector실행, web실행까지는 잘됐습니다. 문제는 testapp을 실행하면서부터 testapp이 되면 collector쪽에서 버벅거리고 다시 restart해주면 web쪽에서 버벅거리는 현상들이 발생하다 최종적으로는 

collector쪽 에러 
![collector](https://cloud.githubusercontent.com/assets/7060510/8966226/2f0a129a-366b-11e5-9789-9df2ec7b2787.PNG)

07-30 03:17:11 [WARN ](o.a.z.ClientCnxn                   :1102) Session 0x14edaf5340e0008 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
07-30 03:17:11 [INFO ](o.a.z.ClientCnxn                   :975) Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)

web쪽 에러 
![web](https://cloud.githubusercontent.com/assets/7060510/8966230/3743d234-366b-11e5-9416-bac1dbe4b200.PNG)

java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739            )
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocket            NIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
03:19:41 INFO (o.a.z.ClientCnxn                   :975) Opening socket connectio            n to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SAS            L (unknown error)
03:19:41 WARN (o.a.z.ClientCnxn                   :1102) Session 0x14edaf5340e00            0c for server null, unexpected error, closing socket connection and attempting r            econnect

testapp.sh에서는 180초 넘어가서 No such process 됐습니다.

제 서버는 AWS EC2 Ubuntu14.04 메모리 1G 최하버전인데 이것때문에 버벅거리고 죽어버리는 문제가 계속되는걸까요??

**Comment by yangbongsoo** [comment]
아... 역시 서버의 스펙차이였습니다!!! 4G 메모리에 네트워크 퍼포먼스 High 으로 업그레이드하니까 
엄청 빠르네요 ㅎㅎ

생각해보니 서버 뻑난것도 제가 testApp에서 /consumeCpu 이거 눌러서 그런것 같습니다

**Comment by minwoo-jung** [comment]
네 해결되었다니 다행이네요.^^
